### ISSUE TITLE
"(FunctionClauseError) no function clause matching in anonymous fn/2 in EthereumJSONRPC.Geth.extract_transactions_params" when using  traceBlock

### ISSUE THREAD

**Issue by JABirchall** [blockscout/blockscout#10006]
### Description

It is documented that Blockscout supports debug_tradeBlock for geth varient nodes. Added in this PR https://github.com/blockscout/blockscout/pull/9072

I enabled this and blockscout throws errors about function not existing in `extract_transactions_params`

Full tracelog

```json
{

    "time":"2024-05-02T00:08:14.004Z",
    "severity":"error",
    "message":"Task #PID<0.7650.0> started from Indexer.Fetcher.InternalTransaction terminating\n** (FunctionClauseError) no function clause matching in anonymous fn/2 in EthereumJSONRPC.Geth.extract_transactions_params/3\n (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/geth.ex:123: anonymous fn(%{\"result\" => %{\"from\" => \"0xe28f2e59a43e575f8422a746ca1bdbd8f737d3c2\", \"gas\" => \"0x5208\", \"gasUsed\" => \"0x5208\", \"input\" => \"0x\", \"to\" => \"0x32e45b441773cbdcad3660fa00c20eca068ddde4\", \"type\" => \"CALL\", \"value\" => \"0x36ebdd48429bc000\"}}, {[], 0, 0}) in EthereumJSONRPC.Geth.extract_transactions_params/3\n (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/geth.ex:115: anonymous fn/3 in EthereumJSONRPC.Geth.to_transactions_params/2\n (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/geth.ex:113: EthereumJSONRPC.Geth.to_transactions_params/2\n (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/geth.ex:76: EthereumJSONRPC.Geth.fetch_block_internal_transactions/2\n (indexer 6.5.0) lib/indexer/fetcher/internal_transaction.ex:113: Indexer.Fetcher.InternalTransaction.run/2\n (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\nFunction: &Indexer.BufferedTask.log_run/1\n Args: [%{batch: [1922237, 1922236, 1922235, 1922234, 1922233, 1922232, 1922231, 1922230, 1922229, 1922228], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://host.docker.internal:8545/\", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: \"http://host.docker.internal:8545/\", debug_traceTransaction: \"http://host.docker.internal:8545/\", debug_traceBlockByNumber: \"http://host.docker.internal:8545/\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]",
    "metadata":{
        "count":10,
        "error":{
            "initial_call":null,
            "reason":"** (FunctionClauseError) no function clause matching in anonymous fn/2 in EthereumJSONRPC.Geth.extract_transactions_params/3\n (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/geth.ex:123: anonymous fn(%{\"result\" => %{\"from\" => \"0xe28f2e59a43e575f8422a746ca1bdbd8f737d3c2\", \"gas\" => \"0x5208\", \"gasUsed\" => \"0x5208\", \"input\" => \"0x\", \"to\" => \"0x32e45b441773cbdcad3660fa00c20eca068ddde4\", \"type\" => \"CALL\", \"value\" => \"0x36ebdd48429bc000\"}}, {[], 0, 0}) in EthereumJSONRPC.Geth.extract_transactions_params/3\n (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/geth.ex:115: anonymous fn/3 in EthereumJSONRPC.Geth.to_transactions_params/2\n (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/geth.ex:113: EthereumJSONRPC.Geth.to_transactions_params/2\n (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/geth.ex:76: EthereumJSONRPC.Geth.fetch_block_internal_transactions/2\n (indexer 6.5.0) lib/indexer/fetcher/internal_transaction.ex:113: Indexer.Fetcher.InternalTransaction.run/2\n (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n"
        },
        "fetcher":"internal_transaction"
    }

}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Link to the page

https://explorer.hypra.network/

### Steps to reproduce

Enable `ETHEREUM_JSONRPC_GETH_TRACE_BY_BLOCK` in blockscout envs

### Backend version

v6.5.0

### Frontend version

v1.29

### Elixir & Erlang/OTP versions

default

### Operating system

Linux

**Comment by vbaranov** [comment]
@JABirchall your node doesn't return `txHash` in the response of `debug_traceBlockByNumber` method. Are you using fork of Geth? Vanilla Geth does return this prop in the response.

**Comment by JABirchall** [comment]
> @JABirchall your node doesn't return `txHash` in the response of `debug_traceBlockByNumber` method. Are you using fork of Geth? Vanilla Geth does return this prop in the response.

Yes, Gimlu helped me debug last night, turns out, for the first 5 years traceBlock was in geth, it never returned txHash and only recently was it added to traceBlock and my geth nodes dont have this patch in. Ill add it later today and test.

**Comment by JABirchall** [comment]
This is now resolved by patching in txHash into the tracer results.
