### ISSUE TITLE
Handle static array while encode contract call

### ISSUE THREAD

**Issue by sl1depengwyn** [blockscout/blockscout#10011]
https://github.com/blockscout/blockscout/blob/master/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex#L28

```elixir
binding() #=> [args: [[1], [2], [3]], types: {:array, {:array, {:int, 256}}, 3}]

2024-05-02T19:32:16.576 [error] #PID<0.30508.2> running BlockScoutWeb.Endpoint (connection #PID<0.30507.2>, stream id 1) terminated
Server: 127.0.0.1:4000 (http)
Request: POST /api/v2/smart-contracts/0xad1df93A0b970948ADAdA62b0be145b8aC261736/query-read-method?is_custom_abi=false
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for {:array, {:array, {:int, 256}}, 3} of type Tuple
        (elixir 1.14.5) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.14.5) lib/enum.ex:166: Enumerable.reduce/3
        (stdlib 4.3.1.3) lists.erl:1442: :lists.foreach_1/2
        (elixir 1.14.5) lib/stream.ex:1371: Stream.do_zip_enum/4
        (elixir 1.14.5) lib/enum.ex:3983: Enum.zip_reduce/3
        (elixir 1.14.5) lib/enum.ex:3837: Enum.zip/1
        (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/encoder.ex:35: EthereumJSONRPC.Encoder.parse_args/2
        (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/encoder.ex:16: EthereumJSONRPC.Encoder.encode_function_call/2
        (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/contract.ex:52: anonymous fn/2 in EthereumJSONRPC.Contract.execute_contract_functions/4
        (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (ethereum_jsonrpc 6.5.0) lib/ethereum_jsonrpc/contract.ex:43: EthereumJSONRPC.Contract.execute_contract_functions/4
        (explorer 6.5.0) lib/explorer/smart_contract/reader.ex:191: Explorer.SmartContract.Reader.query_contracts/5
        (explorer 6.5.0) lib/explorer/smart_contract/reader.ex:156: Explorer.SmartContract.Reader.query_contract_inner/7
        (explorer 6.5.0) lib/explorer/smart_contract/reader.ex:98: Explorer.SmartContract.Reader.query_verified_contract_inner/6
        (explorer 6.5.0) lib/explorer/smart_contract/reader.ex:628: Explorer.SmartContract.Reader.query_contract_and_link_outputs/8
        (explorer 6.5.0) lib/explorer/smart_contract/reader.ex:586: Explorer.SmartContract.Reader.query_function_with_custom_abi_inner/7
        (explorer 6.5.0) lib/explorer/smart_contract/reader.ex:416: Explorer.SmartContract.Reader.query_function_with_names/7
        (block_scout_web 6.5.0) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:173: BlockScoutWeb.API.V2.SmartContractController.query_read_method/2
        (block_scout_web 6.5.0) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.action/2
```

**Comment by k1rill-fedoseev** [comment]
Also doesn't work for tuples, likely related to the same issue
<img width="1415" alt="image" src="https://github.com/blockscout/blockscout/assets/29590423/9761fff6-7e40-4ce3-b161-de0e87455ef1">
