### ISSUE TITLE
** (RuntimeError)  Pubsub not configured! - when using realtime indexer

### ISSUE THREAD

**Issue by JABirchall** [blockscout/blockscout#10023]
### Description

I had to resync my network due to curropted database when upgrading. But after resyncing and switching to realtime indexer, it crashes the backend with the following error.

```
2024-05-04T14:23:38.548 [error] GenServer #PID<0.5516.0> terminating
** (RuntimeError) Pubsub not configured!

Subscriptions require a configured pubsub module.

    (absinthe 1.7.6) lib/absinthe/phase/subscription/subscribe_self.ex:108: Absinthe.Phase.Subscription.SubscribeSelf.ensure_pubsub!/1
    (absinthe 1.7.6) lib/absinthe/phase/subscription/subscribe_self.ex:20: Absinthe.Phase.Subscription.SubscribeSelf.do_subscription/3
    (absinthe 1.7.6) lib/absinthe/pipeline.ex:408: Absinthe.Pipeline.run_phase/3
    (absinthe_phoenix 2.0.3) lib/absinthe/phoenix/channel.ex:130: Absinthe.Phoenix.Channel.run/4
    (absinthe_phoenix 2.0.3) lib/absinthe/phoenix/channel.ex:98: Absinthe.Phoenix.Channel.run_doc/4
    (absinthe_phoenix 2.0.3) lib/absinthe/phoenix/channel.ex:64: Absinthe.Phoenix.Channel.handle_in/3
    (phoenix 1.5.14) lib/phoenix/channel/server.ex:315: Phoenix.Channel.Server.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
Last message: %Phoenix.Socket.Message{topic: "__absinthe__:control", event: "doc", payload: %{"query" => "subscription {tokenTransfers(tokenContractAddressHash: \"0xcBFbd38167519F4DCcfF1dbd48304a4FC8d4De32\") { amount, toAddressHash, transactionHash, fromAddressHash }}"}, ref: "2", join_ref: "1"}
State: %Phoenix.Socket{assigns: %{__absinthe_gc_interval__: nil, __absinthe_pipeline__: nil, __absinthe_schema__: BlockScoutWeb.GraphQL.Schema, absinthe: %{gc_interval: nil, opts: [context: %{pubsub: BlockScoutWeb.Endpoint}], pipeline: {Absinthe.Phoenix.Channel, :default_pipeline}, schema: BlockScoutWeb.GraphQL.Schema}}, channel: Absinthe.Phoenix.Channel, channel_pid: #PID<0.5516.0>, endpoint: BlockScoutWeb.Endpoint, handler: BlockScoutWeb.UserSocket, id: nil, joined: true, join_ref: "1", private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: BlockScoutWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "__absinthe__:control", transport: :websocket, transport_pid: #PID<0.5379.0>}
```

I dont see any configuration for pubsub and disabling realtime indexer lets the explorer load, but kinda need it indexing new blocks.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Link to the page

https://explorer.hypra.network/

### Steps to reproduce

 `DISABLE_REALTIME_INDEXER=false`

### Backend version

6.5.0

### Frontend version

1.29.2

### Elixir & Erlang/OTP versions

default

### Operating system

Linux

**Comment by JABirchall** [comment]
Secondary issue, after the initial indexing, the catchup indexer is not catching back up with the chain. As it constantly thinks its caught up and no new blocks.

```
2024-05-07T16:17:42.218 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2024-05-07T16:17:42.218 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
2024-05-07T16:18:07.221 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2024-05-07T16:18:07.221 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
2024-05-07T16:18:30.660 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
2024-05-07T16:18:32.224 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2024-05-07T16:18:32.224 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
2024-05-07T16:18:57.226 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2024-05-07T16:18:57.226 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
```

The current head is: 2,893,763
The explorer thinks the head is 2,824,510

**Comment by JABirchall** [comment]
Things i've tried that hasnt fixed the issue

- Rebuild the image
- basically put env back to default
- updated packages + docker
- rebooted the server

None of these changed the crashing.

**Comment by GimluCom** [comment]
In case anyone encounter this issue, try to unset the `ETHEREUM_JSONRPC_WS_URL` ENV. If the error disappears then the issue is likely with your RPC node.

Make sure the WS-RPC server is enabled and that it is listening for all incoming WS connections.
With geth you need: `--ws.addr=0.0.0.0`
