### ISSUE TITLE
Getting Error: protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s.

### ISSUE THREAD

**Issue by yohanelly95** [blockscout/blockscout#10047]
### Description

Getting this error on the `backend` service when running `docker-compose -f geth.yml up -d`.
```
Starting dependencies..
Starting repos..
** (EXIT from #PID<0.132.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Cldr.Unit.Range, DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
        (elixir 1.14.5) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.14.5) lib/enum.ex:166: Enumerable.reduce/3
        (elixir 1.14.5) lib/enum.ex:4307: Enum.reverse/1
        (elixir 1.14.5) lib/keyword.ex:202: Keyword.new/2
        lib/explorer/repo/config_helper.ex:61: Explorer.Repo.ConfigHelper.extract_parameters/1
        lib/explorer/repo/config_helper.ex:26: Explorer.Repo.ConfigHelper.get_db_config/1
        lib/explorer/repo.ex:20: Explorer.Repo.init/2
        (ecto 3.11.2) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1
```

Running it as docker containers not sure what is causing this. I have tried it locally on my mac and it seems to work. But not on ubuntu VM. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

GETH

### Type of the chain

L2

### Link to the page

http://34.176.139.12/

### Steps to reproduce

Just running `docker-compose -f geth.yml up -d` 

branch: `production-optimism`. Updated the envs/common-backend with appropriate values for our op-stack chain.

### Backend version

production-optimism

### Frontend version

production-optimism

### Elixir & Erlang/OTP versions

Elixir 1.14.5 (compiled with Erlang/OTP 25)

### Operating system

Linux

### Additional information

![Screenshot 2024-05-10 at 2 53 52 PM](https://github.com/blockscout/blockscout/assets/33081891/e391908c-ac5e-45dc-8445-2955a640f26b)

**Comment by yohanelly95** [comment]
hey @vbaranov any insights what could be going wrong here? 

db url is: `postgresql://postgres:***@db:5432/blockscout`. I have tried connecting to this db and it connects fine. Not sure whats going wrong here. Error only on the `backend` service

**Comment by yohanelly95** [comment]
Thanks! 

I am seeing these errors now 
```
{"time":"2024-05-10T09:54:33.231Z","severity":"error","message":"GenServer Explorer.Counters.LastOutputRootSizeCounter terminating\n** (Postgrex.Error) ERROR 42P01 (undefined_table) relation \"op_output_roots\" does not exist\n\n    query: SELECT o0.\"l2_block_number\" FROM \"op_output_roots\" AS o0 ORDER BY o0.\"l2_output_index\" DESC LIMIT 2\n    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6\n    (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4\n    (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\n    (explorer 6.5.0) lib/explorer/counters/last_output_root_size_counter.ex:75: Explorer.Counters.LastOutputRootSizeCounter.consolidate/0\n    (explorer 6.5.0) lib/explorer/counters/last_output_root_size_counter.ex:37: Explorer.Counters.LastOutputRootSizeCounter.handle_continue/2\n    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4\n    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7\nLast message: {:continue, :ok}\nState: %{consolidate?: true}","metadata":{"error":{"initial_call":null,"reason":"** (Postgrex.Error) ERROR 42P01 (undefined_table) relation \"op_output_roots\" does not exist\n\n    query: SELECT o0.\"l2_block_number\" FROM \"op_output_roots\" AS o0 ORDER BY o0.\"l2_output_index\" DESC LIMIT 2\n    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6\n    (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4\n    (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\n    (explorer 6.5.0) lib/explorer/counters/last_output_root_size_counter.ex:75: Explorer.Counters.LastOutputRootSizeCounter.consolidate/0\n    (explorer 6.5.0) lib/explorer/counters/last_output_root_size_counter.ex:37: Explorer.Counters.LastOutputRootSizeCounter.handle_continue/2\n    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4\n    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7\n"}}}
```

```
{"time":"2024-05-10T09:54:33.625Z","severity":"error","message":"Task #PID<0.7711.0> started from Indexer.Fetcher.InternalTransaction terminating\n** (RuntimeError) could not lookup Ecto repo Explorer.Repo because it was not started or it does not exist\n    (ecto 3.11.2) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1\n    (ecto 3.11.2) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2\n    (explorer 6.5.0) lib/explorer/repo.ex:2: Explorer.Repo.all/2\n    (indexer 6.5.0) lib/indexer/fetcher/internal_transaction.ex:99: Indexer.Fetcher.InternalTransaction.run/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nFunction: &Indexer.BufferedTask.log_run/1\n    Args: [%{batch: [46583, 46582, 46581, 46577, 46580, 46579, 46585, 46584, 46521, 46519], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://35.246.50.60:8545\", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: \"http://35.246.50.60:8545\", debug_traceTransaction: \"http://35.246.50.60:8545\", debug_traceBlockByNumber: \"http://35.246.50.60:8545\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]","metadata":{"error":{"initial_call":null,"reason":"** (RuntimeError) could not lookup Ecto repo Explorer.Repo because it was not started or it does not exist\n    (ecto 3.11.2) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1\n    (ecto 3.11.2) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2\n    (explorer 6.5.0) lib/explorer/repo.ex:2: Explorer.Repo.all/2\n    (indexer 6.5.0) lib/indexer/fetcher/internal_transaction.ex:99: Indexer.Fetcher.InternalTransaction.run/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"},"fetcher":"internal_transaction"}}
```
and then finally
```
{"time":"2024-05-10T09:54:33.713Z","severity":"info","message":"Postgrex.Protocol (#PID<0.4400.0>) missed message: {:EXIT, #PID<0.4555.0>, :shutdown}","metadata":{}}
```
all on the `backend` service @vbaranov

**Comment by yohanelly95** [comment]
> > branch: production-optimism. Updated the envs/common-backend with appropriate values for our op-stack chain.
> 
> `production-optimism` branch is obsolete. You should use master branch with 2 additions:
> 
> * set `CHAIN_TYPE=optimism`
> * use docker image for optimism: `blockscout/blockscout-optimism:latest`

I see! I'll switch to the master branch and just run `docker pull blockscout/blockscout-optimism:latest` and then run this container ?

**Comment by yohanelly95** [comment]
> > branch: production-optimism. Updated the envs/common-backend with appropriate values for our op-stack chain.
> 
> `production-optimism` branch is obsolete. You should use master branch with 2 additions:
> 
> * set `CHAIN_TYPE=optimism`
> * use docker image for optimism: `blockscout/blockscout-optimism:latest`

@vbaranov this is done:
```
{"time":"2024-05-10T10:40:25.026Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-05-10T10:40:25.161Z","severity":"info","message":"Start handling L1 block range 9741697..9741698. Target range: 9737109..9784175.","metadata":{"fetcher":"optimism_deposits"}}
{"time":"2024-05-10T10:40:25.161Z","severity":"info","message":"Finish handling L1 block range 9741697..9741698. Found 0 TransactionDeposited event(s). Target range: 9737109..9784175. Progress: 9.75%","metadata":{"fetcher":"optimism_deposits"}}
{"time":"2024-05-10T10:40:25.392Z","severity":"info","message":"Start handling L1 block range 9741699..9741700. Target range: 9737109..9784175.","metadata":{"fetcher":"optimism_deposits"}}
{"time":"2024-05-10T10:40:25.392Z","severity":"info","message":"Finish handling L1 block range 9741699..9741700. Found 0 TransactionDeposited event(s). Target range: 9737109..9784175. Progress: 9.76%","metadata":{"fetcher":"optimism_deposits"}}
{"time":"2024-05-10T10:40:25.437Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":30344,"last_block_number":30245,"missing_block_count":100,"shrunk":false}}
{"time":"2024-05-10T10:40:25.437Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-05-10T10:40:25.776Z","severity":"info","message":"Start handling L1 block range 9741701..9741702. Target range: 9737109..9784175.","metadata":{"fetcher":"optimism_deposits"}}
```


seeing this on the `backend` service so it seems to be running. But http://34.176.139.12/ still shows no data. What am I missing? Which service is not working here I am not sure. Locally when I run it it shows data.

![Screenshot 2024-05-10 at 4 18 46 PM](https://github.com/blockscout/blockscout/assets/33081891/b5639838-b1d1-4b16-9cee-199f06739660)

**Comment by yohanelly95** [comment]
Figured it out!! Thanks @vbaranov

**Comment by yohanelly95** [comment]
Figured it out!! Thanks @vbaranov

**Comment by phpmac** [comment]
> Figured it out!! Thanks Figured it out! ! Thanks @vbaranov

How to solve, I can't update the data now
