### ISSUE TITLE
Unable to fetch block info from Reth execution client

### ISSUE THREAD

**Issue by barnabasbusa** [blockscout/blockscout#10186]
### Description

If [reth](https://github.com/paradigmxyz/reth) is being used as an execution endpoint then blockscout fails:

```sh
ERROR! Config provider Config.Reader failed with:
** (Code.LoadError) could not load /app/apps/explorer/config/prod/reth.exs. Reason: enoent
    (elixir 1.14.5) lib/code.ex:1826: Code.find_file!/2
    (elixir 1.14.5) lib/code.ex:1252: Code.require_file/2
    config/runtime/prod.exs:86: (file)
    (elixir 1.14.5) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4
    (elixir 1.14.5) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
    (elixir 1.14.5) src/elixir_compiler.erl:39: :elixir_compiler.eval_or_compile/3
    (elixir 1.14.5) src/elixir_lexical.erl:15: :elixir_lexical.run/3
    (elixir 1.14.5) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Code.LoadError',file=><<"/app/apps/explorer/config/prod/reth.exs">>,message=><<"could not load /app/apps/explorer/config/prod/reth.exs. Reason: enoent">>,reason=>enoent},[{'Elixir.Code','find_file!',2,[{file,"lib/code.ex"},{line,1826}]},{'Elixir.Code',require_file,2,[{file,"lib/code.ex"},{line,1252}]},{elixir_compiler_0,'__FILE__',1,[{file,"config/runtime/prod.exs"},{line,86}]},{elixir_compiler,dispatch,4,[{file,"src/elixir_compiler.erl"},{line,66}]},{elixir_compiler,compile,3,[{file,"src/elixir_compiler.erl"},{line,51}]},{elixir_compiler,eval_or_compile,3,[{file,"src/elixir_compiler.erl"},{line,39}]},{elixir_lexical,run,3,[{file,"src/elixir_lexical.erl"},{line,15}]},{elixir_compiler,quoted,3,[{file,"src/elixir_compiler.erl"},{line,17}]}]}}
init terminating in do_boot ({,[{Elixir.Code,find_file!,2,[{_},{_}]},{Elixir.Code,require_file,2,[{_},{_}]},{elixir_compiler_0,__FILE__,1,[{_},{_}]},{elixir_compiler,dispatch,4,[{_},{_}]},{elixir_compiler,compile,3,[{_},{_}]},{elixir_compiler,eval_or_compile,3,[{_},{_}]},{elixir_lexical,run,3,[{_},{_}]},{elixir_compiler,quoted,3,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done
```

### Type of the installation

Docker

### Type of the JSON RPC archive node

Reth

### Type of the chain

L1

### Steps to reproduce

kurtosis config:

```yaml
  participants:
    - el_type: reth
  additional_services:
    - blockscout
 ```

`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file config.yaml`

### Backend version

v6.0.0

### Elixir & Erlang/OTP versions

n/a

**Comment by sl1depengwyn** [comment]
Reth is currently not supported yet, but you can try to set `erigon` `ETHEREUM_JSONRPC_VARIANT`

**Comment by barnabasbusa** [comment]
I'm aware erigon and geth is working. But I would like to use reth.

**Comment by sl1depengwyn** [comment]
I understant try to set `ETHEREUM_JSONRPC_VARIANT=erigon` to use reth
