### ISSUE TITLE
Bad performance of API v2 address internal transactions endpoint

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#10202]
Slow API v2 endpoint:
https://optimism.blockscout.com/api/v2/addresses/0x5eB2c4a34A82a329C3E5D9F97F78Dc5446C3A9FB/internal-transactions

Fast similar API v1 endpoint:
https://optimism.blockscout.com/api?module=account&action=txlistinternal&address=0x5eB2c4a34A82a329C3E5D9F97F78Dc5446C3A9FB&page=1&offset=50

**Comment by InoMurko** [comment]
```
iex(blockscout@blockscout-74fdc7b898-s5thc)41> a
%Explorer.Chain.Hash{
  byte_count: 20,
  bytes: <<145, 13, 196, 32, 244, 161, 186, 82, 73, 192, 211, 234, 182, 247,
    246, 206, 174, 106, 75, 19>>
}
iex(blockscout@blockscout-74fdc7b898-s5thc)42> opt2
[
  necessity_by_association: %{
    [created_contract_address: :names] => :optional,
    [created_contract_address: :smart_contract] => :optional,
    [from_address: :names] => :optional,
    [from_address: :smart_contract] => :optional,
    [to_address: :names] => :optional,
    [to_address: :smart_contract] => :optional
  },
  paging_options: %Explorer.PagingOptions{
    key: nil,
    page_size: 1,
    page_number: 1,
    is_pending_tx: false,
    is_index_in_asc_order: false,
    asc_order: false,
    batch_key: nil
  },
  api?: true
]
iex(blockscout@blockscout-74fdc7b898-s5thc)43> Chain.address_to_internal_transactions(a, opt2)

12:13:07.898 [debug] QUERY ERROR db=60006.6ms idle=724.9ms
SELECT s0."call_type", s0."created_contract_code", s0."error", s0."gas", s0."gas_used", s0."index", s0."init", s0."input", s0."output", s0."trace_address", s0."type", s0."value", s0."block_number", s0."transaction_index", s0."block_index", s0."inserted_at", s0."updated_at", s0."created_contract_address_hash", s0."from_address_hash", s0."to_address_hash", s0."transaction_hash", s0."block_hash" FROM (SELECT ss0."call_type" AS "call_type", ss0."created_contract_code" AS "created_contract_code", ss0."error" AS "error", ss0."gas" AS "gas", ss0."gas_used" AS "gas_used", ss0."index" AS "index", ss0."init" AS "init", ss0."input" AS "input", ss0."output" AS "output", ss0."trace_address" AS "trace_address", ss0."type" AS "type", ss0."value" AS "value", ss0."block_number" AS "block_number", ss0."transaction_index" AS "transaction_index", ss0."block_index" AS "block_index", ss0."inserted_at" AS "inserted_at", ss0."updated_at" AS "updated_at", ss0."created_contract_address_hash" AS "created_contract_address_hash", ss0."from_address_hash" AS "from_address_hash", ss0."to_address_hash" AS "to_address_hash", ss0."transaction_hash" AS "transaction_hash", ss0."block_hash" AS "block_hash" FROM (SELECT ssi0."call_type" AS "call_type", ssi0."created_contract_code" AS "created_contract_code", ssi0."error" AS "error", ssi0."gas" AS "gas", ssi0."gas_used" AS "gas_used", ssi0."index" AS "index", ssi0."init" AS "init", ssi0."input" AS "input", ssi0."output" AS "output", ssi0."trace_address" AS "trace_address", ssi0."type" AS "type", ssi0."value" AS "value", ssi0."block_number" AS "block_number", ssi0."transaction_index" AS "transaction_index", ssi0."block_index" AS "block_index", ssi0."inserted_at" AS "inserted_at", ssi0."updated_at" AS "updated_at", ssi0."created_contract_address_hash" AS "created_contract_address_hash", ssi0."from_address_hash" AS "from_address_hash", ssi0."to_address_hash" AS "to_address_hash", ssi0."transaction_hash" AS "transaction_hash", ssi0."block_hash" AS "block_hash" FROM "internal_transactions" AS ssi0 LEFT OUTER JOIN "pending_block_operations" AS ssp1 ON ssp1."block_hash" = ssi0."block_hash" WHERE (ssp1."block_hash" IS NULL) AND (ssi0."to_address_hash" = $1) AND (((ssi0."type" = $2) AND (ssi0."index" > 0)) OR (ssi0."type" != $3)) ORDER BY ssi0."block_number" DESC, ssi0."transaction_index" DESC, ssi0."index" DESC LIMIT $4) AS ss0 UNION (SELECT ss0."call_type", ss0."created_contract_code", ss0."error", ss0."gas", ss0."gas_used", ss0."index", ss0."init", ss0."input", ss0."output", ss0."trace_address", ss0."type", ss0."value", ss0."block_number", ss0."transaction_index", ss0."block_index", ss0."inserted_at", ss0."updated_at", ss0."created_contract_address_hash", ss0."from_address_hash", ss0."to_address_hash", ss0."transaction_hash", ss0."block_hash" FROM (SELECT ssi0."call_type" AS "call_type", ssi0."created_contract_code" AS "created_contract_code", ssi0."error" AS "error", ssi0."gas" AS "gas", ssi0."gas_used" AS "gas_used", ssi0."index" AS "index", ssi0."init" AS "init", ssi0."input" AS "input", ssi0."output" AS "output", ssi0."trace_address" AS "trace_address", ssi0."type" AS "type", ssi0."value" AS "value", ssi0."block_number" AS "block_number", ssi0."transaction_index" AS "transaction_index", ssi0."block_index" AS "block_index", ssi0."inserted_at" AS "inserted_at", ssi0."updated_at" AS "updated_at", ssi0."created_contract_address_hash" AS "created_contract_address_hash", ssi0."from_address_hash" AS "from_address_hash", ssi0."to_address_hash" AS "to_address_hash", ssi0."transaction_hash" AS "transaction_hash", ssi0."block_hash" AS "block_hash" FROM "internal_transactions" AS ssi0 LEFT OUTER JOIN "pending_block_operations" AS ssp1 ON ssp1."block_hash" = ssi0."block_hash" WHERE (ssp1."block_hash" IS NULL) AND (ssi0."from_address_hash" = $5) AND (((ssi0."type" = $6) AND (ssi0."index" > 0)) OR (ssi0."type" != $7)) ORDER BY ssi0."block_number" DESC, ssi0."transaction_index" DESC, ssi0."index" DESC LIMIT $8) AS ss0) UNION (SELECT ss0."call_type", ss0."created_contract_code", ss0."error", ss0."gas", ss0."gas_used", ss0."index", ss0."init", ss0."input", ss0."output", ss0."trace_address", ss0."type", ss0."value", ss0."block_number", ss0."transaction_index", ss0."block_index", ss0."inserted_at", ss0."updated_at", ss0."created_contract_address_hash", ss0."from_address_hash", ss0."to_address_hash", ss0."transaction_hash", ss0."block_hash" FROM (SELECT ssi0."call_type" AS "call_type", ssi0."created_contract_code" AS "created_contract_code", ssi0."error" AS "error", ssi0."gas" AS "gas", ssi0."gas_used" AS "gas_used", ssi0."index" AS "index", ssi0."init" AS "init", ssi0."input" AS "input", ssi0."output" AS "output", ssi0."trace_address" AS "trace_address", ssi0."type" AS "type", ssi0."value" AS "value", ssi0."block_number" AS "block_number", ssi0."transaction_index" AS "transaction_index", ssi0."block_index" AS "block_index", ssi0."inserted_at" AS "inserted_at", ssi0."updated_at" AS "updated_at", ssi0."created_contract_address_hash" AS "created_contract_address_hash", ssi0."from_address_hash" AS "from_address_hash", ssi0."to_address_hash" AS "to_address_hash", ssi0."transaction_hash" AS "transaction_hash", ssi0."block_hash" AS "block_hash" FROM "internal_transactions" AS ssi0 LEFT OUTER JOIN "pending_block_operations" AS ssp1 ON ssp1."block_hash" = ssi0."block_hash" WHERE (ssp1."block_hash" IS NULL) AND (ssi0."created_contract_address_hash" = $9) AND (((ssi0."type" = $10) AND (ssi0."index" > 0)) OR (ssi0."type" != $11)) ORDER BY ssi0."block_number" DESC, ssi0."transaction_index" DESC, ssi0."index" DESC LIMIT $12) AS ss0)) AS s0 WHERE (((s0."type" = $13) AND (s0."index" > 0)) OR (s0."type" != $14)) ORDER BY s0."block_number" DESC, s0."transaction_index" DESC, s0."index" DESC LIMIT $15 [%Explorer.Chain.Hash{byte_count: 20, bytes: <<145, 13, 196, 32, 244, 161, 186, 82, 73, 192, 211, 234, 182, 247, 246, 206, 174, 106, 75, 19>>}, :call, :call, 1, %Explorer.Chain.Hash{byte_count: 20, bytes: <<145, 13, 196, 32, 244, 161, 186, 82, 73, 192, 211, 234, 182, 247, 246, 206, 174, 106, 75, 19>>}, :call, :call, 1, %Explorer.Chain.Hash{byte_count: 20, bytes: <<145, 13, 196, 32, 244, 161, 186, 82, 73, 192, 211, 234, 182, 247, 246, 206, 174, 106, 75, 19>>}, :call, :call, 1, :call, :call, 1]
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

I have noticed the same, I think  https://hal.explorer.caldera.xyz/address/0x910Dc420f4a1Ba5249c0d3EAb6F7F6ceaE6A4B13?tab=internal_txns

on `db.m5d.xlarge`.
