### ISSUE TITLE
[error] GenServer Indexer.Block.Catchup.MissingRangesCollector terminating

### ISSUE THREAD

**Issue by fewensa** [blockscout/blockscout#10214]
### Description

```
2024-06-08T10:48:08.972 [error] GenServer Indexer.Block.Catchup.MissingRangesCollector terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_uncles/1
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/block.ex:620: EthereumJSONRPC.Block.elixir_to_uncles(%{"difficulty" => 0, "extraData" => "0x", "gasLimit" => 20000000, "gasUsed" => 0, "hash" => "0x57d9f062a5fc498ecf59ac9a71636b4c21374d3a09d6962732b39a534228716e", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x4ef9c61704e17b67e3aee801421d42f31510dbae", "mixHash" => "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce" => "0x0000000000000000", "number" => 2865958, "parentHash" => "0x61d384de2e55d603c9a40510a8995d917f25105c238e408987016d11d9464b5e", "receiptsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => 514, "stateRoot" => "0x56b9018debd325b95a6cd1592fd6c6a1d2db486b92cd8377fc4c72b427ef0265", "timestamp" => ~U[2024-06-08 10:47:48Z], "totalDifficulty" => 0, "transactions" => [], "transactionsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"})
    (elixir 1.14.5) lib/enum.ex:4249: Enum.flat_map_list/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/blocks.ex:49: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:576: EthereumJSONRPC.fetch_blocks_by_params/3
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:346: EthereumJSONRPC.fetch_block_number_by_tag/2
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:196: Indexer.Block.Catchup.MissingRangesCollector.fetch_max_block_number/0
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:119: Indexer.Block.Catchup.MissingRangesCollector.get_initial_min_max/0
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:48: Indexer.Block.Catchup.MissingRangesCollector.default_init/0
Last message: {:continue, :ok}
State: %{max_fetched_block_number: nil, min_fetched_block_number: nil}
2024-06-08T10:48:10.859 fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_uncles/1
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/block.ex:620: EthereumJSONRPC.Block.elixir_to_uncles(%{"difficulty" => 0, "extraData" => "0x", "gasLimit" => 20000000, "gasUsed" => 0, "hash" => "0x57d9f062a5fc498ecf59ac9a71636b4c21374d3a09d6962732b39a534228716e", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x4ef9c61704e17b67e3aee801421d42f31510dbae", "mixHash" => "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce" => "0x0000000000000000", "number" => 2865958, "parentHash" => "0x61d384de2e55d603c9a40510a8995d917f25105c238e408987016d11d9464b5e", "receiptsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => 514, "stateRoot" => "0x56b9018debd325b95a6cd1592fd6c6a1d2db486b92cd8377fc4c72b427ef0265", "timestamp" => ~U[2024-06-08 10:47:48Z], "totalDifficulty" => 0, "transactions" => [], "transactionsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"})
    (elixir 1.14.5) lib/enum.ex:4249: Enum.flat_map_list/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/blocks.ex:49: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:576: EthereumJSONRPC.fetch_blocks_by_params/3
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:346: EthereumJSONRPC.fetch_block_number_by_tag/2
    (indexer 6.6.0) lib/indexer/block/realtime/fetcher.ex:132: Indexer.Block.Realtime.Fetcher.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
Last message: :poll_latest_block_number
State: %Indexer.Block.Realtime.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "https://darwinia-hrpc.vercel.app", fallback_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: "https://darwinia-hrpc.vercel.app"], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Ganache], receipts_batch_size: 250, receipts_concurrency: 10}, subscription: nil, previous_number: nil, timer: #Reference<0.3793721946.1026555906.239722>}
2024-06-08T10:48:10.901 [error] GenServer Indexer.Block.Catchup.MissingRangesCollector terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_uncles/1
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/block.ex:620: EthereumJSONRPC.Block.elixir_to_uncles(%{"difficulty" => 0, "extraData" => "0x", "gasLimit" => 20000000, "gasUsed" => 0, "hash" => "0x57d9f062a5fc498ecf59ac9a71636b4c21374d3a09d6962732b39a534228716e", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x4ef9c61704e17b67e3aee801421d42f31510dbae", "mixHash" => "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce" => "0x0000000000000000", "number" => 2865958, "parentHash" => "0x61d384de2e55d603c9a40510a8995d917f25105c238e408987016d11d9464b5e", "receiptsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => 514, "stateRoot" => "0x56b9018debd325b95a6cd1592fd6c6a1d2db486b92cd8377fc4c72b427ef0265", "timestamp" => ~U[2024-06-08 10:47:48Z], "totalDifficulty" => 0, "transactions" => [], "transactionsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"})
    (elixir 1.14.5) lib/enum.ex:4249: Enum.flat_map_list/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/blocks.ex:49: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:576: EthereumJSONRPC.fetch_blocks_by_params/3
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:346: EthereumJSONRPC.fetch_block_number_by_tag/2
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:196: Indexer.Block.Catchup.MissingRangesCollector.fetch_max_block_number/0
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:119: Indexer.Block.Catchup.MissingRangesCollector.get_initial_min_max/0
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:48: Indexer.Block.Catchup.MissingRangesCollector.default_init/0
Last message: {:continue, :ok}
State: %{max_fetched_block_number: nil, min_fetched_block_number: nil}
2024-06-08T10:48:12.253 [error] GenServer Indexer.Block.Catchup.MissingRangesCollector terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_uncles/1
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/block.ex:620: EthereumJSONRPC.Block.elixir_to_uncles(%{"difficulty" => 0, "extraData" => "0x", "gasLimit" => 20000000, "gasUsed" => 0, "hash" => "0x57d9f062a5fc498ecf59ac9a71636b4c21374d3a09d6962732b39a534228716e", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x4ef9c61704e17b67e3aee801421d42f31510dbae", "mixHash" => "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce" => "0x0000000000000000", "number" => 2865958, "parentHash" => "0x61d384de2e55d603c9a40510a8995d917f25105c238e408987016d11d9464b5e", "receiptsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => 514, "stateRoot" => "0x56b9018debd325b95a6cd1592fd6c6a1d2db486b92cd8377fc4c72b427ef0265", "timestamp" => ~U[2024-06-08 10:47:48Z], "totalDifficulty" => 0, "transactions" => [], "transactionsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"})
    (elixir 1.14.5) lib/enum.ex:4249: Enum.flat_map_list/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/blocks.ex:49: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:576: EthereumJSONRPC.fetch_blocks_by_params/3
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:346: EthereumJSONRPC.fetch_block_number_by_tag/2
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:196: Indexer.Block.Catchup.MissingRangesCollector.fetch_max_block_number/0
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:119: Indexer.Block.Catchup.MissingRangesCollector.get_initial_min_max/0
    (indexer 6.6.0) lib/indexer/block/catchup/missing_ranges_collector.ex:48: Indexer.Block.Catchup.MissingRangesCollector.default_init/0
Last message: {:continue, :ok}
State: %{max_fetched_block_number: nil, min_fetched_block_number: nil}
2024-06-08T10:48:12.973 fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_uncles/1
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/block.ex:620: EthereumJSONRPC.Block.elixir_to_uncles(%{"difficulty" => 0, "extraData" => "0x", "gasLimit" => 20000000, "gasUsed" => 0, "hash" => "0x57d9f062a5fc498ecf59ac9a71636b4c21374d3a09d6962732b39a534228716e", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x4ef9c61704e17b67e3aee801421d42f31510dbae", "mixHash" => "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce" => "0x0000000000000000", "number" => 2865958, "parentHash" => "0x61d384de2e55d603c9a40510a8995d917f25105c238e408987016d11d9464b5e", "receiptsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => 514, "stateRoot" => "0x56b9018debd325b95a6cd1592fd6c6a1d2db486b92cd8377fc4c72b427ef0265", "timestamp" => ~U[2024-06-08 10:47:48Z], "totalDifficulty" => 0, "transactions" => [], "transactionsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"})
    (elixir 1.14.5) lib/enum.ex:4249: Enum.flat_map_list/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/blocks.ex:49: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:576: EthereumJSONRPC.fetch_blocks_by_params/3
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc.ex:346: EthereumJSONRPC.fetch_block_number_by_tag/2
    (indexer 6.6.0) lib/indexer/block/realtime/fetcher.ex:132: Indexer.Block.Realtime.Fetcher.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
Last message: :poll_latest_block_number
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Darwinia

### Type of the chain

L1

### Backend version

https://hub.docker.com/layers/blockscout/blockscout/latest/images/sha256-8b36df83794704f666dae707052e3920b46aa2ca4da60167d51492721ae3135b?context=explore

### Elixir & Erlang/OTP versions

X

**Comment by Qwerty5Uiop** [comment]
Hi @fewensa! Blockscout expects the field `uncles` in `eth_getBlockByNumber` response. This error appears if there is no such field
