### ISSUE TITLE
Unknown token transfer format

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout#10228]
### Description

```
{"time":"2024-06-11T04:35:03.074Z","severity":"error","message":"Unknown token transfer format: %{address_hash: \"0xba8cd99c30da11a22f4d8ef3e763ac4cc3d1e3f5\", block_hash: \"0x5f105962ff2988aebbc99da341b5de89637b242c59cda0fd4b710bb21102e354\", block_number: 1719317, data: \"0x0000000000000000000000004beb61a8ff4b983aae688938bd068ef4178199cb000000000000000000000000000000000000000000000000001c6bf526340000\", first_topic: \"0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c\", fourth_topic: nil, index: 21, second_topic: nil, third_topic: nil, transaction_hash: \"0x9a25d0b08f405234f4bbf77c4bc13aa00f4589d5c2fae4fa6cec99f053cb5ee2\"}** (MatchError) no match of right hand side value: \"\"\n    (ex_abi 0.7.2) lib/abi/type_decoder.ex:365: ABI.TypeDecoder.decode_uint/2\n    (ex_abi 0.7.2) lib/abi/type_decoder.ex:190: anonymous fn/3 in ABI.TypeDecoder.do_decode_raw/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (ex_abi 0.7.2) lib/abi/type_decoder.ex:185: ABI.TypeDecoder.do_decode_raw/2\n    (ex_abi 0.7.2) lib/abi/type_decoder.ex:179: ABI.TypeDecoder.decode_raw/2\n    (indexer 6.5.0) lib/indexer/transform/token_transfers.ex:286: Indexer.Transform.TokenTransfers.parse_params/1\n    (indexer 6.5.0) lib/indexer/transform/token_transfers.ex:164: Indexer.Transform.TokenTransfers.do_parse/3\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n","metadata":{"fetcher":"block_catchup","first_block_number":1719317,"last_block_number":1719316}}
```

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

geth

### Type of the chain

l2

### Backend version

v6.6.0

### Frontend version

v1.11.1

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

Linux

**Comment by vbaranov** [comment]
@InoMurko this warning means, that Blockscout detected this transaction as a token transfer. However, the event structure doesn't correspond to any known token standards. Currently known standards in Blockscout are ERC-20, ERC-721, ERC-1155, ERC-404.

**Comment by InoMurko** [comment]
Ah, makes sense. Maybe it should be a warning then and not an error? Just a thought. Thanks!

**Comment by vbaranov** [comment]
Thanks for suggestion. We would like to still keep it as error for better visibility in case of some bug in supported token formats processing.
