### ISSUE TITLE
ETH Sepolia: token metadata update error

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#10230]
```
{"time":"2024-06-11T07:58:12.399Z","severity":"error","message":"Task #PID<0.14207.1> started from Indexer.Fetcher.TokenUpdater terminating\n** (FunctionClauseError) no function clause matching in anonymous fn/1 in Indexer.Fetcher.TokenUpdater.update_metadata/1\n    (indexer 6.6.0) lib/indexer/fetcher/token_updater.ex:81: anonymous fn(%{name: \"MY YT CHANNEL\"}) in Indexer.Fetcher.TokenUpdater.update_metadata/1\n    (elixir 1.14.5) lib/enum.ex:975: Enum.\"-each/2-lists^foreach/1-0-\"/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nFunction: &Indexer.BufferedTask.log_run/1\n    Args: [%{batch: [%Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: nil, symbol: nil, total_supply: Decimal.new(\"2\"), decimals: nil, type: \"ERC-1155\", cataloged: true, holder_count: 1, skip_metadata: nil, total_supply_updated_at_block: 6070331, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<123, 70, 23, 123, 113, 134, 102, 2, 54, 173, 36, 15, 65, 59, 50, 16, 91, 32, 96, 75>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2024-03-21 07:52:02.607046Z], updated_at: ~U[2024-06-09 07:54:33.231345Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"AccessToken\", symbol: \"accesstoken\", total_supply: nil, decimals: nil, type: \"ERC-721\", cataloged: true, holder_count: 1, skip_metadata: nil, total_supply_updated_at_block: nil, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<68, 241, 238, 232, 88, 158, 169, 220, 247, 162, 179, 172, 62, 18, 61, 227, 79, 102, 187, 144>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2023-09-01 10:21:48.066415Z], updated_at: ~U[2024-06-09 07:54:33.442257Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"Token\", symbol: \"Symbol\", total_supply: Decimal.new(\"10000000000000000000000\"), decimals: Decimal.new(\"6\"), type: \"ERC-20\", cataloged: true, holder_count: 1, skip_metadata: nil, total_supply_updated_at_block: 6070331, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<220, 214, 224, 105, 38, 96, 32, 42, 207, 179, 196, 139, 132, 120, 156, 229, 131, 17, 18, 199>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2024-03-07 06:30:39.314012Z], updated_at: ~U[2024-06-09 07:54:33.704058Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"reward Token 1\", symbol: \"r1Token\", total_supply: Decimal.new(\"100000000000000000000000000\"), decimals: Decimal.new(\"18\"), type: \"ERC-20\", cataloged: true, holder_count: 1, skip_metadata: nil, total_supply_updated_at_block: 6070331, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<221, 254, 86, 226, 163, 83, 212, 182, 249, 122, 100, 246, 77, 116, 186, 215, 149, 92, 221, 51>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2023-09-13 10:22:04.411576Z], updated_at: ~U[2024-06-09 07:54:33.964308Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"CardGame\", symbol: \"CGM\", total_supply: nil, decimals: nil, type: \"ERC-721\", cataloged: true, holder_count: 1, skip_metadata: nil, total_supply_updated_at_block: nil, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<6, 242, 36, 138, 234, 26, 226, 16, 35, 218, 254, 142, 196, 136, 88, 139, 26, 56, 80, 149>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2023-09-01 10:21:36.317471Z], updated_at: ~U[2024-06-09 07:54:34.252413Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"Artwork Contract\", symbol: \"ART\", total_supply: nil, decimals: nil, type: \"ERC-721\", cataloged: true, holder_count: 1, skip_metadata: nil, total_supply_updated_at_block: nil, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<43, 228, 33, 22, 182, 107, 13, 229, 101, 127, 207, 22, 39, 194, 131, 42, 130, 22, 157, 186>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2023-10-03 10:22:24.966321Z], updated_at: ~U[2024-06-09 07:54:34.992457Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"USDC\", symbol: \"USDC\", total_supply: Decimal.new(\"10000000000000000000000000\"), decimals: Decimal.new(\"18\"), type: \"ERC-20\", cataloged: true, holder_count: 2, skip_metadata: nil, total_supply_updated_at_block: 6070331, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<11, 34, 179, 195, 4, 116, 246, 34, 221, 155, 141, 102, 47, 185, 156, 242, 78, 147, 87, 40>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2024-02-23 18:55:20.923325Z], updated_at: ~U[2024-06-09 07:54:35.255558Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"My Collection\", symbol: nil, total_supply: nil, decimals: nil, type: \"ERC-1155\", cataloged: true, holder_count: 6, skip_metadata: nil, total_supply_updated_at_block: nil, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<39, 249, 120, 240, 179, 87, 49, 240, 163, 250, 186, 71, 75, 247, 152, 55, 213, 135, 234, 77>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2024-05-14 07:40:51.981159Z], updated_at: ~U[2024-06-09 07:54:35.520154Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"USDT\", symbol: \"USDT\", total_supply: Decimal.new(\"1000000001500000000000\"), decimals: Decimal.new(\"6\"), type: \"ERC-20\", cataloged: true, holder_count: 14, skip_metadata: nil, total_supply_updated_at_block: 6070331, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<139, 80, 110, 115, 89, 236, 211, 124, 67, 224, 134, 48, 180, 100, 207, 137, 98, 199, 89, 234>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2023-08-28 22:35:22.749813Z], updated_at: ~U[2024-06-09 07:54:35.782797Z]}, %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, \"tokens\">, name: \"ice token\", symbol: \"ice\", total_supply: Decimal.new(\"10000000000000000\"), decimals: Decimal.new(\"10\"), type: \"ERC-20\", cataloged: true, holder_count: 1, skip_metadata: nil, total_supply_updated_at_block: 6070331, fiat_value: nil, circulating_market_cap: nil, icon_url: nil, is_verified_via_admin_panel: false, volume_24h: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<71, 102, 208, 85, 176, 139, 112, 120, 109, 195, 25, 193, 114, 61, 250, 13, 191, 113, 100, 199>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2024-05-12 07:53:50.641027Z], updated_at: ~U[2024-06-09 07:54:36.044126Z]}], cal (truncated)","metadata":{"error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in anonymous fn/1 in Indexer.Fetcher.TokenUpdater.update_metadata/1\n    (indexer 6.6.0) lib/indexer/fetcher/token_updater.ex:81: anonymous fn(%{name: \"MY YT CHANNEL\"}) in Indexer.Fetcher.TokenUpdater.update_metadata/1\n    (elixir 1.14.5) lib/enum.ex:975: Enum.\"-each/2-lists^foreach/1-0-\"/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"},"fetcher":"token_updater"}}
```

**Comment by vbaranov** [comment]
Fixed by https://github.com/blockscout/blockscout/pull/10231
