### ISSUE TITLE
Get address transactions, return 500, "no case clause matching" when process revert transaction

### ISSUE THREAD

**Issue by xiang-xx** [blockscout/blockscout#10251]
### Logs:

```json
{"duration":21180264,"endpoint":"/api/v2/addresses/0x768f24d2cdaE1849867f4E58eD38f66b2E71C6a8/transactions?","method":"GET","request_id":"b60da3c85104536486344d8a1904d14f","status":"500","unit":"microsecond"}}
```

```json

{
    "time": "2024-06-16T11:56:35.232Z",
    "severity": "error",
    "message": "#PID<0.24419.0> running BlockScoutWeb.Endpoint (connection #PID<0.24418.0>, stream id 1) terminated\nServer: scan-testnet-api.bevm.io:80 (http)\nRequest: GET /api/v2/addresses/0x768f24d2cdaE1849867f4E58eD38f66b2E71C6a8/transactions\n** (exit) an exception was raised:\n ** (CaseClauseError) no case clause matching: {:ok, [%{block_number: 1474765, call_type: \"call\", error: \"execution reverted\", from_address_hash: \"0x3add51910a1f133630f741c57740e4cd75399ef9\", gas: 2953056, index: 0, input: \"0xa83627de\", to_address_hash: \"0x768f24d2cdae1849867f4e58ed38f66b2e71c6a8\", trace_address: [], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}, %{block_number: 1474765, call_type: \"staticcall\", error: nil, from_address_hash: \"0x768f24d2cdae1849867f4e58ed38f66b2e71c6a8\", gas: 2919839, gas_used: 48755, index: 1, input: \"0x18160ddd\", output: \"0x0000000000000000000000000000000000000000000000000000000000000000\", to_address_hash: \"0xbb9baf42deb3d77b01a68de5173c5570332326c1\", trace_address: [0], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}, %{block_number: 1474765, call_type: \"staticcall\", error: nil, from_address_hash: \"0x768f24d2cdae1849867f4e58ed38f66b2e71c6a8\", gas: 2907874, gas_used: 52150, index: 2, input: \"0x981b24d000000000000000000000000000000000000000000000000000000000666a367f\", output: \"0x0000000000000000000000000000000000000000000000000000000000000000\", to_address_hash: \"0xcd66d1c65eeae421b6b40e4db0e6a2ade385f776\", trace_address: [1], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}, %{block_number: 1474765, call_type: \"delegatecall\", from_address_hash: \"0xcd66d1c65eeae421b6b40e4db0e6a2ade385f776\", gas: 2862678, gas_used: 45890, index: 3, input: \"0x7259b019000000000000000000000000000000000000000000000000000000000000001b0000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000666a367f\", output: \"0x0000000000000000000000000000000000000000000000000000000000000000\", to_address_hash: \"0x494da9cb94856f873b79a8fae05fa2ad2fd7911c\", trace_address: [1, 0], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}, %{block_number: 1474765, call_type: \"staticcall\", error: nil, from_address_hash: \"0x768f24d2cdae1849867f4e58ed38f66b2e71c6a8\", gas: 2907249, gas_used: 46523, index: 4, input: \"0x18160ddd\", output: \"0x0000000000000000000000000000000000000000000000000000000000000000\", to_address_hash: \"0xbb9baf42deb3d77b01a68de5173c5570332326c1\", trace_address: [2], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}]}\n (explorer 6.7.0) lib/explorer/chain.ex:4806: Explorer.Chain.fetch_first_trace/2\n (explorer 6.7.0) lib/explorer/chain.ex:2995: Explorer.Chain.fetch_tx_revert_reason/1\n (block_scout_web 6.7.0) lib/block_scout_web/views/transaction_view.ex:354: BlockScoutWeb.TransactionView.transaction_revert_reason/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:508: BlockScoutWeb.API.V2.TransactionView.revert_reason/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:403: BlockScoutWeb.API.V2.TransactionView.prepare_transaction/6\n (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:72: BlockScoutWeb.API.V2.TransactionView.render/2\n (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3",
    "metadata": {
        "error": {
            "initial_call": null,
            "reason": "** (CaseClauseError) no case clause matching: {:ok, [%{block_number: 1474765, call_type: \"call\", error: \"execution reverted\", from_address_hash: \"0x3add51910a1f133630f741c57740e4cd75399ef9\", gas: 2953056, index: 0, input: \"0xa83627de\", to_address_hash: \"0x768f24d2cdae1849867f4e58ed38f66b2e71c6a8\", trace_address: [], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}, %{block_number: 1474765, call_type: \"staticcall\", error: nil, from_address_hash: \"0x768f24d2cdae1849867f4e58ed38f66b2e71c6a8\", gas: 2919839, gas_used: 48755, index: 1, input: \"0x18160ddd\", output: \"0x0000000000000000000000000000000000000000000000000000000000000000\", to_address_hash: \"0xbb9baf42deb3d77b01a68de5173c5570332326c1\", trace_address: [0], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}, %{block_number: 1474765, call_type: \"staticcall\", error: nil, from_address_hash: \"0x768f24d2cdae1849867f4e58ed38f66b2e71c6a8\", gas: 2907874, gas_used: 52150, index: 2, input: \"0x981b24d000000000000000000000000000000000000000000000000000000000666a367f\", output: \"0x0000000000000000000000000000000000000000000000000000000000000000\", to_address_hash: \"0xcd66d1c65eeae421b6b40e4db0e6a2ade385f776\", trace_address: [1], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}, %{block_number: 1474765, call_type: \"delegatecall\", from_address_hash: \"0xcd66d1c65eeae421b6b40e4db0e6a2ade385f776\", gas: 2862678, gas_used: 45890, index: 3, input: \"0x7259b019000000000000000000000000000000000000000000000000000000000000001b0000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000666a367f\", output: \"0x0000000000000000000000000000000000000000000000000000000000000000\", to_address_hash: \"0x494da9cb94856f873b79a8fae05fa2ad2fd7911c\", trace_address: [1, 0], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}, %{block_number: 1474765, call_type: \"staticcall\", error: nil, from_address_hash: \"0x768f24d2cdae1849867f4e58ed38f66b2e71c6a8\", gas: 2907249, gas_used: 46523, index: 4, input: \"0x18160ddd\", output: \"0x0000000000000000000000000000000000000000000000000000000000000000\", to_address_hash: \"0xbb9baf42deb3d77b01a68de5173c5570332326c1\", trace_address: [2], transaction_hash: \"0x3c31b309e7987a82e3a186de83611a2c346593301ef21b4fb3cb38c421835a2c\", transaction_index: 5, type: \"call\", value: 0}]}\n (explorer 6.7.0) lib/explorer/chain.ex:4806: Explorer.Chain.fetch_first_trace/2\n (explorer 6.7.0) lib/explorer/chain.ex:2995: Explorer.Chain.fetch_tx_revert_reason/1\n (block_scout_web 6.7.0) lib/block_scout_web/views/transaction_view.ex:354: BlockScoutWeb.TransactionView.transaction_revert_reason/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:508: BlockScoutWeb.API.V2.TransactionView.revert_reason/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:403: BlockScoutWeb.API.V2.TransactionView.prepare_transaction/6\n (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:72: BlockScoutWeb.API.V2.TransactionView.render/2\n (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3\n"
        }
    }
}
```

>  Explorer.Chain.fetch_first_trace/2\n (explorer 6.7.0) lib/explorer/chain.ex:2995: Explorer.Chain.fetch_tx_revert_reason/1\n (block_scout_web 6.7.0) lib/block_scout_web/views/transaction_view.ex:354: BlockScoutWeb.TransactionView.transaction_revert_reason/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:508: BlockScoutWeb.API.V2.TransactionView.revert_reason/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:403: BlockScoutWeb.API.V2.TransactionView.prepare_transaction/6\n (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:72: BlockScoutWeb.API.V2.TransactionView.render/2\n (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3

revert reason
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32603,
        "message": "VM Exception while processing transaction: revert",
        "data": "0x4e487b710000000000000000000000000000000000000000000000000000000000000012"
    },
    "id": 1
}
```

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://scan-testnet.bevm.io/address/0x768f24d2cdaE1849867f4E58eD38f66b2E71C6a8

### Backend version

v6.6.0-beta

### Elixir & Erlang/OTP versions

/

### Operating system

linux

**Comment by vbaranov** [comment]
@xiang-xx we're rolling out 6.7.0. Would you please check if the issue persist with release candidate: docker image `blockscout/blockscout:6.7.0-alpha.3`?

**Comment by xiang-xx** [comment]
> @xiang-xx we're rolling out 6.7.0. Would you please check if the issue persist with release candidate: docker image `blockscout/blockscout:6.7.0-alpha.3`?

Thanks for you reply. I found that this error also occurred in the v6.7.0-alpha.6 version.

**Comment by vbaranov** [comment]
@xiang-xx the issue is similar to https://github.com/blockscout/blockscout/issues/10276. Please take a look to my comment there https://github.com/blockscout/blockscout/issues/10276#issuecomment-2176568061.
