### ISSUE TITLE
GET /api/v2/addresses/*/transactions: CaseClauseError no case clause matching

### ISSUE THREAD

**Issue by pustovalov** [blockscout/blockscout#10276]
### Description

Hi,

```
Request: GET /api/v2/addresses/0x123272C227C73432d19814771da11dFBF3D0509C/transactions
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: 
    {:ok, 
    [
        %{
        block_number: 121438645,
        call_type: "call",
        error: "Revert(Reverted)",
        from_address_hash: "0x123272c227c73432d19814771da11dfbf3d0509c",
        gas: 1_000_000,
        index: 0,
        input: "0x3951475f00000000000000000000000020f8aefb5697b77e0bb835a8518be70775cda1b003e503e8000000084595161401484a0000000000000000000000000002c6f9b1000000000000000000000000b12bfca5a55806aaf64e99521918a4bf0fc40802000000000000000000000000c42c30ac6cc15fac9bd938618bcaa1a1fae8501d",
        to_address_hash: "0x2d782c300b8ee5dd92b95218037cbe41bbc49d78",
        trace_address: [],
        transaction_hash: "0x1d1a4f2d901f3e4ac5e1f5b1d414b85f325b917fa9a855dc6eff02d65cdd1394",
        transaction_index: 1,
        type: "call",
        value: 0
        },
        %{
        block_number: 121438645,
        call_type: "staticcall",
        error: nil,
        from_address_hash: "0x2d782c300b8ee5dd92b95218037cbe41bbc49d78",
        gas: 977_512,
        gas_used: 7_934,
        index: 1,
        input: "0x0902f1ac",
        output: "0x00000000000000000000000000000000000000000000000000000018cfe4b9dd00000000000000000000000000000000000000004a05f8cc80f978f2d448691d000000000000000000000000000000000000000000000000000000006671830f",
        to_address_hash: "0x20f8aefb5697b77e0bb835a8518be70775cda1b0",
        trace_address: [0],
        transaction_hash: "0x1d1a4f2d901f3e4ac5e1f5b1d414b85f325b917fa9a855dc6eff02d65cdd1394",
        transaction_index: 1,
        type: "call",
        value: 0
        }
    ]
    }
        (explorer 6.7.0) lib/explorer/chain.ex:4806: Explorer.Chain.fetch_first_trace/2
        (explorer 6.7.0) lib/explorer/chain.ex:2995: Explorer.Chain.fetch_tx_revert_reason/1
        (block_scout_web 6.7.0) lib/block_scout_web/views/transaction_view.ex:354: BlockScoutWeb.TransactionView.transaction_revert_reason/2
        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:511: BlockScoutWeb.API.V2.TransactionView.revert_reason/2
        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:403: BlockScoutWeb.API.V2.TransactionView.prepare_transaction/6
        (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/transaction_view.ex:72: BlockScoutWeb.API.V2.TransactionView.render/2
        (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
        (block_scout_web 6.7.0) lib/block_scout_web/controllers/api/v2/address_controller.ex:1: BlockScoutWeb.API.V2.AddressController.action/2
        (block_scout_web 6.7.0) lib/block_scout_web/controllers/api/v2/address_controller.ex:1: BlockScoutWeb.API.V2.AddressController.phoenix_controller_pipeline/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 6.7.0) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web 6.7.0) /Users/pavel/dev/aurora/aurora-blockscout/deps/plug/lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web 6.7.0) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
        (block_scout_web 6.7.0) /Users/pavel/dev/aurora/aurora-blockscout/deps/spandex_phoenix/lib/spandex_phoenix.ex:151: BlockScoutWeb.Endpoint.call/2
        (phoenix 1.5.14) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
```

```
{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "id": 1,
    "params": [
        "0x1d1a4f2d901f3e4ac5e1f5b1d414b85f325b917fa9a855dc6eff02d65cdd1394",
        {
          "timeout": "5s",
          "tracer": "callTracer",
          "tracerConfig": {
            "onlyTopCall": true
          }
        }
    ]
}

{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "calls": [
            {
                "from": "0x2d782c300b8ee5dd92b95218037cbe41bbc49d78",
                "gas": "0xeea68",
                "gasUsed": "0x1efe",
                "input": "0x0902f1ac",
                "output": "0x00000000000000000000000000000000000000000000000000000018cfe4b9dd00000000000000000000000000000000000000004a05f8cc80f978f2d448691d000000000000000000000000000000000000000000000000000000006671830f",
                "to": "0x20f8aefb5697b77e0bb835a8518be70775cda1b0",
                "type": "STATICCALL"
            }
        ],
        "error": "Revert(Reverted)",
        "from": "0x123272c227c73432d19814771da11dfbf3d0509c",
        "gas": "0xf4240",
        "gasUsed": "0x0",
        "input": "0x3951475f00000000000000000000000020f8aefb5697b77e0bb835a8518be70775cda1b003e503e8000000084595161401484a0000000000000000000000000002c6f9b1000000000000000000000000b12bfca5a55806aaf64e99521918a4bf0fc40802000000000000000000000000c42c30ac6cc15fac9bd938618bcaa1a1fae8501d",
        "output": "0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000020537761707065725632204558434553534956455f494e5055545f414d4f554e54",
        "to": "0x2d782c300b8ee5dd92b95218037cbe41bbc49d78",
        "type": "CALL"
    }
}
```

With v6.5.0 all works fine

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

v6.5.0
https://explorer.mainnet.aurora.dev/address/0x123272C227C73432d19814771da11dFBF3D0509C

### Backend version

[v6.7.0](https://github.com/blockscout/blockscout/commit/ed5e3e36c06aa266c9544771d9cb9b8564179527) 

### Frontend version

v1.31.1

### Elixir & Erlang/OTP versions

Elixir 1.14.5-otp-25

**Comment by vbaranov** [comment]
@pustovalov Geth JSON RPC client supports requesting top trace via `onlyTopCall: true` tracer config.

6.7.0 uses this option to fetch first trace:

https://github.com/blockscout/blockscout/blob/aa7f9703dc93348483e939422f9d9df99b4211a7/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex#L217

Does the JSON RPC node, which you use, support this config option as well? If not, is it feasible to add it there?

**Comment by pustovalov** [comment]
@vbaranov Thx, I'll explore the feasibility of adding `onlyTopCall` option
