### ISSUE TITLE
Exception in Indexer.Block.Fetcher.Receipts:  "type": "mined"

### ISSUE THREAD

**Issue by SurfingNerd** [blockscout/blockscout#10375]
### Description

Indexer runs continous into an exeception.
Digging the source code gives me a clue:

The field "type" was removed in Pull Request: https://github.com/blockscout/blockscout/pull/9007/files#diff-bef83897a0670c5e28f476b33f6ef8b2a52b56a23234623370e4eebfa0cac601L175

```
  defp entry_to_elixir({key, _} = entry)
       when key in ~w(address blockHash data removed topics transactionHash timestamp),
       do: entry
```

Maybe a solution for improved backward and forward compatibility of blockscout would be to ignore fields that are not interesting for blockscout ?

For now, i will try to change the Node Software to not return ` "type": "mined" `

```
(FunctionClauseError) no function clause matching in anonymous fn/2 in Indexer.Block.Fetcher.Receipts.fetch/2
    (indexer 6.7.1) anonymous fn({:exit, 
    {:function_clause, 
      [{EthereumJSONRPC.Log, :entry_to_elixir, 
        [{\"type\", \"mined\"}], 
        [file: 'lib/ethereum_jsonrpc/log.ex', line: 165]}, {Enum, :\"-map/2-fun-0-\", 3, [file: 'lib/enum.ex', line: 1662]}, 
        {:maps, :fold_1, 3, [file: 'maps.erl', line: 410]}, {Enum, :map, 2, [file: 'lib/enum.ex', line: 2480]}, 
        {Enum, :into, 3, [file: 'lib/enum.ex', line: 1552]}, {Enum, :\"-map/2-lists^map/1-0-\", 2, [file: 'lib/enum.ex', line: 1658]}, 
        {EthereumJSONRPC.Receipt, :entry_to_elixir, 1, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 385]},
        {EthereumJSONRPC.Receipt, :entry_reducer, 2, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 328]}]}}, 
        {:ok, %{logs: [], receipts: []}}) in Indexer.Block.Fetcher.Receipts.fetch/2
    (elixir 1.14.5) lib/task/supervised.ex:370: Task.Supervised.stream_deliver/7<
    (elixir 1.14.5) lib/enum.ex:2514: Enum.reduce_while/3#
    (indexer 6.7.1) lib/indexer/block/fetcher/receipts.ex:22: Indexer.Block.Fetcher.Receipts.fetch/2#
    (indexer 6.7.1) lib/indexer/block/fetcher.ex:150: Indexer.Block.Fetcher.fetch_and_import_range/3
    (stdlib 3.17) timer.erl:166: :timer.tc/1
    (indexer 6.7.1) lib/indexer/block/catchup/fetcher.ex:169: Indexer.Block.Catchup.Fetcher.fetch_and_import_missing_range/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","first_block_number":1316,"last_block_number":1307}}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenEthereum fork diamond-node 

### Type of the chain

L1

### Link to the page

https://github.com/SurfingNerd/honey-badger-testing/tree/11abae1cc42ae43ec2429472ca05b85d20c92a11/blockscout/alpha3/docker-compose

### Steps to reproduce

reproducable with this docker compose setup:
https://github.com/SurfingNerd/honey-badger-testing/tree/11abae1cc42ae43ec2429472ca05b85d20c92a11/blockscout/alpha3/docker-compose

config file: dmd-alpha3.yml

its a docker compose
blockscout docker image used: sha256:db0649d5edf1acdce554e40ab9603d23d429980e32d4579aea2c8564b2f17243

### Backend version

v6.7.1-beta ? docker image sha256:db0649d5edf1acdce554e40ab9603d23d429980e32d4579aea2c8564b2f17243

### Frontend version

not relevant

### Elixir & Erlang/OTP versions

? used version drom Docker image

### Operating system

Linux

**Comment by vbaranov** [comment]
Please try with the latest version of the backend.
