### ISSUE TITLE
Constraint error when attempting to insert struc proxy_implementations_proxy_address_hash_index

### ISSUE THREAD

**Issue by klemenfn** [blockscout/blockscout#10398]
### Description

Seen this today in error.log

```
2024-07-08T18:36:37.048 [error] Task #PID<0.333363.0> started from #PID<0.333315.0> terminating
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * "proxy_implementations_pkey" (unique_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `unique_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset defined the following constraints:

    * "proxy_implementations_proxy_address_hash_index" (unique_constraint)

    (ecto 3.11.2) lib/ecto/repo/schema.ex:815: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto 3.11.2) lib/ecto/repo/schema.ex:799: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto 3.11.2) lib/ecto/repo/schema.ex:780: Ecto.Repo.Schema.apply/4
    (ecto 3.11.2) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (explorer 6.7.2) lib/explorer/chain/smart_contract/proxy/models/implementation.ex:290: Explorer.Chain.SmartContract.Proxy.Models.Implementation.save_implementation_data/4
    (explorer 6.7.2) lib/explorer/chain/smart_contract/proxy/models/implementation.ex:175: anonymous fn/3 in Explorer.Chain.SmartContract.Proxy.Models.Implementation.get_implementation/2
    (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<2.51050308/0 in Explorer.Chain.SmartContract.Proxy.Models.Implementation.get_implementation/2>
    Args: []
```

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Steps to reproduce

Unknown, randomly saw in error log.

### Backend version

v6.7.2

### Elixir & Erlang/OTP versions

Elixir 1.16.3, Erlang/OTP 26

### Operating system

Ubuntu 22.04

**Comment by InoMurko** [comment]
can confirm!
```
{"time":"2024-08-03T08:51:24.366Z","severity":"error","message":"Task #PID<0.103493.0> started from #PID<0.103488.0> terminating\n** (Ecto.ConstraintError) constraint error when attempting to insert struct:\n\n    * \"proxy_implementations_pkey\" (unique_constraint)\n\nIf you would like to stop this constraint violation from raising an\nexception and instead add it as an error to your changeset, please\ncall `unique_constraint/3` on your changeset with the constraint\n`:name` as an option.\n\nThe changeset defined the following constraints:\n\n    * \"proxy_implementations_proxy_address_hash_index\" (unique_constraint)\n\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:815: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3\n    (elixir 1.16.3) lib/enum.ex:1700: Enum.\"-map/2-lists^map/1-1-\"/2\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:799: Ecto.Repo.Schema.constraints_to_errors/3\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:780: Ecto.Repo.Schema.apply/4\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4\n    (explorer 6.7.2) lib/explorer/chain/smart_contract/proxy/models/implementation.ex:290: Explorer.Chain.SmartContract.Proxy.Models.Implementation.save_implementation_data/4\n    (explorer 6.7.2) lib/explorer/chain/smart_contract/proxy/models/implementation.ex:175: anonymous fn/3 in Explorer.Chain.SmartContract.Proxy.Models.Implementation.get_implementation/2\n    (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: #Function<2.15234331/0 in Explorer.Chain.SmartContract.Proxy.Models.Implementation.get_implementation/2>\n    Args: []","metadata":{"error":{"initial_call":null,"reason":"** (Ecto.ConstraintError) constraint error when attempting to insert struct:\n\n    * \"proxy_implementations_pkey\" (unique_constraint)\n\nIf you would like to stop this constraint violation from raising an\nexception and instead add it as an error to your changeset, please\ncall `unique_constraint/3` on your changeset with the constraint\n`:name` as an option.\n\nThe changeset defined the following constraints:\n\n    * \"proxy_implementations_proxy_address_hash_index\" (unique_constraint)\n\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:815: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3\n    (elixir 1.16.3) lib/enum.ex:1700: Enum.\"-map/2-lists^map/1-1-\"/2\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:799: Ecto.Repo.Schema.constraints_to_errors/3\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:780: Ecto.Repo.Schema.apply/4\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4\n    (explorer 6.7.2) lib/explorer/chain/smart_contract/proxy/models/implementation.ex:290: Explorer.Chain.SmartContract.Proxy.Models.Implementation.save_implementation_data/4\n    (explorer 6.7.2) lib/explorer/chain/smart_contract/proxy/models/implementation.ex:175: anonymous fn/3 in Explorer.Chain.SmartContract.Proxy.Models.Implementation.get_implementation/2\n    (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\n"}}}
```

Arbitrum Nitro.

**Comment by vbaranov** [comment]
@klemenfn @InoMurko could you please post the result of `\d proxy_implementations` from the main explorer DB?

**Comment by klemenfn** [comment]
After upgrading to latest release I have not seen this yet. Leaving the output here anyway

```
                       Table "public.proxy_implementations"
       Column       |            Type             | Collation | Nullable | Default 
--------------------+-----------------------------+-----------+----------+---------
 proxy_address_hash | bytea                       |           | not null | 
 address_hashes     | bytea[]                     |           | not null | 
 names              | character varying(255)[]    |           | not null | 
 inserted_at        | timestamp without time zone |           | not null | 
 updated_at         | timestamp without time zone |           | not null | 
 proxy_type         | proxy_type                  |           |          | 
Indexes:
    "proxy_implementations_pkey" PRIMARY KEY, btree (proxy_address_hash)
    "proxy_implementations_proxy_type_index" btree (proxy_type)
```

**Comment by InoMurko** [comment]
```
{"time":"2024-08-07T09:21:35.637Z","severity":"error","message":"Ranch protocol #PID<0.204926124.0> of listener BlockScoutWeb.Endpoint.HTTP (connection #PID<0.205691953.0>, stream id 1) terminated\nan exception was raised:\n    ** (Ecto.ConstraintError) constraint error when attempting to insert struct:\n\n    * \"proxy_implementations_pkey\" (unique_constraint)\n\nIf you would like to stop this constraint violation from raising an\nexception and instead add it as an error to your changeset, please\ncall `unique_constraint/3` on your changeset with the constraint\n`:name` as an option.\n\nThe changeset defined the following constraints:\n\n    * \"proxy_implementations_proxy_address_hash_index\" (unique_constraint)\n\n        (ecto 3.11.2) lib/ecto/repo/schema.ex:815: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3\n        (elixir 1.16.3) lib/enum.ex:1700: Enum.\"-map/2-lists^map/1-1-\"/2\n        (ecto 3.11.2) lib/ecto/repo/schema.ex:799: Ecto.Repo.Schema.constraints_to_errors/3\n        (ecto 3.11.2) lib/ecto/repo/schema.ex:780: Ecto.Repo.Schema.apply/4\n        (ecto 3.11.2) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4\n        (explorer 6.7.2) lib/explorer/chain/smart_contract/proxy/models/implementation.ex:290: Explorer.Chain.SmartContract.Proxy.Models.Implementation.save_implementation_data/4\n        (explorer 6.7.2) lib/explorer/chain/smart_contract/proxy/models/implementation.ex:175: anonymous fn/3 in Explorer.Chain.SmartContract.Proxy.Models.Implementation.get_implementation/2\n        (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2","metadata":{"error":{"initial_call":null,"reason":"%Ecto.ConstraintError{type: :unique, constraint: \"proxy_implementations_pkey\", message: \"constraint error when attempting to insert struct:\\n\\n    * \\\"proxy_implementations_pkey\\\" (unique_constraint)\\n\\nIf you would like to stop this constraint violation from raising an\\nexception and instead add it as an error to your changeset, please\\ncall `unique_constraint/3` on your changeset with the constraint\\n`:name` as an option.\\n\\nThe changeset defined the following constraints:\\n\\n    * \\\"proxy_implementations_proxy_address_hash_index\\\" (unique_constraint)\\n\"}"}}}
```

```
psql (15.7, server 13.12)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

blockscout_plume_testnet_bfe682d3_4382_4a5c_9221_0b75397e0d75=> \d proxy_implementations
                       Table "public.proxy_implementations"
       Column       |            Type             | Collation | Nullable | Default
--------------------+-----------------------------+-----------+----------+---------
 proxy_address_hash | bytea                       |           | not null |
 address_hashes     | bytea[]                     |           | not null |
 names              | character varying(255)[]    |           | not null |
 inserted_at        | timestamp without time zone |           | not null |
 updated_at         | timestamp without time zone |           | not null |
 proxy_type         | proxy_type                  |           |          |
Indexes:
    "proxy_implementations_pkey" PRIMARY KEY, btree (proxy_address_hash)
    "proxy_implementations_proxy_type_index" btree (proxy_type)
```

This explorer is the latest 6.7.2

**Comment by vbaranov** [comment]
@InoMurko could I ask you to try with [6.8.0](https://github.com/blockscout/blockscout/releases/tag/v6.8.0-beta)?

**Comment by InoMurko** [comment]
> ConstraintError

This rollup is not active anymore. But I haven't seen this error with other rollups with similar setup and using the latest blockscout, imo it seems it's fixed.

**Comment by vbaranov** [comment]
Thanks for feedback. I am closing the issue.
