### ISSUE TITLE
key :gas_used not found in: nil

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#10453]
Base Mainnet:
```
{"time":"2024-07-19T09:54:54.577Z","severity":"error","message":"#PID<0.2861718.0> running BlockScoutWeb.Endpoint (connection #PID<0.2851785.0>, stream id 6) terminated\nServer: base.blockscout.com:80 (http)\nRequest: GET /api/v2/stats\n** (exit) an exception was raised:\n    ** (KeyError) key :gas_used not found in: nil\n\nIf you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map\n        (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:90: anonymous fn/2 in BlockScoutWeb.API.V2.StatsController.network_utilization_percentage/0\n        (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n        (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:89: BlockScoutWeb.API.V2.StatsController.network_utilization_percentage/0\n        (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:80: BlockScoutWeb.API.V2.StatsController.stats/2\n        (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:1: BlockScoutWeb.API.V2.StatsController.action/2\n        (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:1: BlockScoutWeb.API.V2.StatsController.phoenix_controller_pipeline/2\n        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n        (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2","metadata":{"error":{"initial_call":null,"reason":"** (KeyError) key :gas_used not found in: nil\n\nIf you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map\n    (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:90: anonymous fn/2 in BlockScoutWeb.API.V2.StatsController.network_utilization_percentage/0\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:89: BlockScoutWeb.API.V2.StatsController.network_utilization_percentage/0\n    (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:80: BlockScoutWeb.API.V2.StatsController.stats/2\n    (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:1: BlockScoutWeb.API.V2.StatsController.action/2\n    (block_scout_web 6.7.2) lib/block_scout_web/controllers/api/v2/stats_controller.ex:1: BlockScoutWeb.API.V2.StatsController.phoenix_controller_pipeline/2\n    (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n    (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n"}}}
```

**Comment by sl1depengwyn** [comment]
Should be fixed with https://github.com/blockscout/blockscout/pull/10647
