### ISSUE TITLE
Error Log Internal Transaction batch

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#10459]
### Description

optimism based. i got error on indexing 

logs : 
```
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{metadata: [fetcher: :internal_transaction], callback_module: Indexer.Fetcher.InternalTransaction, batch: [7495040, 7495044, 7497099, 7497101, 7497100, 7498821, 7498822, 7497095, 7497093, 7497129], callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "https://onlylayer.org/", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: "https://onlylayer.org/", debug_traceTransaction: "https://onlylayer.org/", debug_traceBlockByNumber: "https://onlylayer.org/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth]}]
2024-07-20T04:59:19.243 fetcher=internal_transaction count=10 [error] Task #PID<0.19917.0> started from Indexer.Fetcher.InternalTransaction terminating
** (BadMapError) expected a map, got: {"calls", [%{"from" => "0x4200000000000000000000000000000000000015", "gas" => "0xe9a0d", "gasUsed" => "0x4a28", "input" => "0x015d8eb9000000000000000000000000000000000000000000000000000000000060c85d00000000000000000000000000000000000000000000000000000000669b364c00000000000000000000000000000000000000000000000000000000000db91c0a5a2b925fc7ce0ff26d36217da435f24c72c1b02f7131d149b44b825cf1cdb500000000000000000000000000000000000000000000000000000000000000030000000000000000000000003335b12ff0adf80cc0793561956e4d0b9d161508000000000000000000000000000000000000000000000000000000000000083400000000000000000000000000000000000000000000000000000000000f4240", "to" => "0xc0d3c0d3c0d3c0d3c0d3c0d3c0d3c0d3c0d30015", "type" => "DELEGATECALL", "value" => "0x0"}]}
    (ethereum_jsonrpc 6.7.2) lib/ethereum_jsonrpc/geth.ex:337: anonymous fn/4 in EthereumJSONRPC.Geth.debug_trace_transaction_response_to_internal_transactions_params/2
    (elixir 1.16.3) lib/enum.ex:1708: anonymous fn/3 in Enum.map/2
    (elixir 1.16.3) lib/enum.ex:4396: anonymous fn/3 in Enum.map/2
    (elixir 1.16.3) lib/stream.ex:1816: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir 1.16.3) lib/stream.ex:1159: anonymous fn/3 in Stream.with_index/2
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/stream.ex:1828: Enumerable.Stream.do_each/4
    (elixir 1.16.3) lib/enum.ex:4396: Enum.map/2
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L2

### Link to the page

https://onlyscan.info

### Backend version

v6.1.2

### Frontend version

latest

### Elixir & Erlang/OTP versions

-

### Operating system

Linux

**Comment by Qwerty5Uiop** [comment]
Hi @avenbreaks! Could you please show the values of `ETHEREUM_JSONRPC_GETH_TRACE_BY_BLOCK` and `INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE` env variables?

**Comment by avenbreaks** [comment]
> Hi @avenbreaks! Could you please show the values of `ETHEREUM_JSONRPC_GETH_TRACE_BY_BLOCK` and `INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE` env variables?

solve sir, now im not see tx on page txs-batches, output-root, dispute-game, and bridge tx

**Comment by vbaranov** [comment]
Please follow [Optimism setup docs](https://docs.blockscout.com/setup/deployment/rollup-deployment#optimism-env-notes) and the [full list of env variables](https://docs.blockscout.com/setup/env-variables/backend-envs-chain-specific#optimism-rollup-management) for OP stack. I am closing the issue. PLease let us know, if you still experience the issue configuration Blockscout for OP-stack.
