### ISSUE TITLE
Backend error: "Could not insert all of chunk into Elixir.Explorer.Chain.Log using options"

### ISSUE THREAD

**Issue by revett** [blockscout/blockscout#10476]
### Description

We are getting a lot of the following errors, and would like so help in understanding how to fix them. This is happening locally, and in our ECS cluster in AWS.

### Errors

```
Could not insert all of chunk into Elixir.Explorer.Chain.Log using options because of error. 
```

```
(Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table "logs" violates foreign key constraint "logs_block_hash_fkey"

table: logs
constraint: logs_block_hash_fkey

Key (block_hash)=(\\xd62e85dc47d616d86a92d44f534ddfa914ecf17051de09a84fcd76d765307e67) is not present in table "blocks".
```

### Raw Logs

```
{"time":"2024-07-24T10:29:37.795Z","severity":"error","message":"** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table \"logs\" violates foreign key constraint \"logs_block_hash_fkey\"\n\n table: logs\n constraint: logs_block_hash_fkey\n\nKey (block_hash)=(\\xd62e85dc47d616d86a92d44f534ddfa914ecf17051de09a84fcd76d765307e67) is not present in table \"blocks\".\n (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:925: Ecto.Adapters.SQL.insert_all/9\n (ecto 3.11.2) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7\n (explorer 6.7.2) lib/explorer/repo.ex:47: anonymous fn/5 in Explorer.Repo.safe_insert_all/3\n (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n (explorer 6.7.2) lib/explorer/chain/import.ex:304: Explorer.Chain.Import.insert_changes_list/3\n (explorer 6.7.2) lib/explorer/chain/import/runner/logs.ex:71: Explorer.Chain.Import.Runner.Logs.insert/3\n (stdlib 5.2.3) timer.erl:270: :timer.tc/2\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","last_block_number":790918,"first_block_number":790927}}
{"time":"2024-07-24T10:29:37.785Z","severity":"error","message":"Could not insert all of chunk into Elixir.Explorer.Chain.Log using options because of error.\n\nChunk Size: 1\nChunk:\n\n[%{data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 101, 108, 111, 110, 46, 110, 101, 111, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, index: 0, inserted_at: ~U[2024-07-24 10:29:37.655590Z], updated_at: ~U[2024-07-24 10:29:37.655590Z], address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<241, 128, 19, 109, 220, 158, 79, 140, 155, 90, 159, 229, 158, 43, 31, 7, 38, 92, 93, 77>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<137, 97, 11, 179, 225, 48, 158, 87, 48, 192, 116, 247, 196, 64, 49, 202, 111, 9, 59, 247, 100, 174, 204, 173, 199, 230, 168, 61, 233, 137, 89, 18>>}, block_number: 776488, transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<113, 1, 81, 229, 101, 164, 112, 145, 206, 162, 15, 17, 130, 4, 155, 187, 131, 181, 14, 5, 62, 192, 131, 113, 195, 77, 32, 121, 4, 247, 155, 148>>}, first_topic: %Explorer.Chain.Hash{byte_count: 32, bytes: <<83, 148, 107, 249, 132, 7, 47, 88, 136, 252, 178, 215, 210, 176, 88, 124, 142, 254, 185, 24, 125, 149, 143, 33, 128, 151, 17, 207, 0, 180, 180, 165>>}, second_topic: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3>>}, third_topic: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 79, 183, 205, 28, 248, 207, 238, 107, 148, 64, 245, 204, 221, 44, 180, 63, 115, 213, 170, 163>>}}]\n\nOptions:\n\n[conflict_target: [:transaction_hash, :index, :block_hash], on_conflict: #Ecto.Query<from l0 in Explorer.Chain.Log, where: fragment(\n \"(EXCLUDED.address_hash, EXCLUDED.data, EXCLUDED.first_topic, EXCLUDED.second_topic, EXCLUDED.third_topic, EXCLUDED.fourth_topic) IS DISTINCT FROM (?, ?, ?, ?, ?, ?)\",\n l0.address_hash,\n l0.data,\n l0.first_topic,\n l0.second_topic,\n l0.third_topic,\n l0.fourth_topic\n), update: [\n set: [\n address_hash: fragment(\"EXCLUDED.address_hash\"),\n data: fragment(\"EXCLUDED.data\"),\n first_topic: fragment(\"EXCLUDED.first_topic\"),\n second_topic: fragment(\"EXCLUDED.second_topic\"),\n third_topic: fragment(\"EXCLUDED.third_topic\"),\n fourth_topic: fragment(\"EXCLUDED.fourth_topic\"),\n inserted_at: fragment(\"LEAST(?, EXCLUDED.inserted_at)\", l0.inserted_at),\n updated_at: fragment(\"GREATEST(?, EXCLUDED.updated_at)\", l0.updated_at)\n ]\n]>, returning: true, timeout: 60000, timestamps: %{inserted_at: ~U[2024-07-24 10:29:37.655590Z], updated_at: ~U[2024-07-24 10:29:37.655590Z]}]\n\nException:\n\n** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table \"logs\" violates foreign key constraint \"logs_block_hash_fkey\"\n\n table: logs\n constraint: logs_block_hash_fkey\n\nKey (block_hash)=(\\x89610bb3e1309e5730c074f7c44031ca6f093bf764aeccadc7e6a83de9895912) is not present in table \"blocks\".\n (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:925: Ecto.Adapters.SQL.insert_all/9\n (ecto 3.11.2) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7\n (explorer 6.7.2) lib/explorer/repo.ex:47: anonymous fn/5 in Explorer.Repo.safe_insert_all/3\n (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n (explorer 6.7.2) lib/explorer/chain/import.ex:304: Explorer.Chain.Import.insert_changes_list/3\n (explorer 6.7.2) lib/explorer/chain/import/runner/logs.ex:71: Explorer.Chain.Import.Runner.Logs.insert/3\n (stdlib 5.2.3) timer.erl:270: :timer.tc/2\n","metadata":{"fetcher":"block_catchup","last_block_number":776479,"import_id":86491379,"transaction_id":86491811,"first_block_number":776488}}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Link to the page

n/a — Not running frontend.

### Backend version

6.7.2

### Frontend version

n/a — Not running frontend.

### Elixir & Erlang/OTP versions

Running via Docker.

### Operating system

Linux via ECS on AWS.

### Additional information

Related issues from the past:

- https://github.com/blockscout/blockscout/issues/620
- https://github.com/blockscout/blockscout/issues/1415
- https://github.com/blockscout/blockscout/issues/4852
- https://github.com/blockscout/blockscout/issues/9268

**Comment by sl1depengwyn** [comment]
Could you please specify which chain do you index and which client specifically do you use? Isn't it a geth fork actually by any chance?

**Comment by ixje** [comment]
@sl1depengwyn , allow me to join the conversation in as I work together with @revett.

The chain is called NeoX ([this page](https://docs.banelabs.org/development/development-environment-information) has the ChainId, RPC/WS info etc). 

> Isn't it a geth fork actually by any chance?

Yes the node is a Geth fork. fwiw; the previously linked page page says
> Compatible to Geth v1.13.11.

Unfortunately they do not have a public node available yet. I've worked with the authors in different projects, so I can easily get in contact if there's something specific you'd like to know.

**Comment by revett** [comment]
Thanks for the details @ixje 👍 

@sl1depengwyn some more details:

This is the RPC endpoint: `https://neoxt4seed1.ngd.network`, and the client version is as follows:

```bash
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' https://neoxt4seed1.ngd.network:8545
```

```json
{
    "jsonrpc": "2.0",
    "id": 67,
    "result": "Geth/nodes/node1/v0.2.1-unstable-e6932462-20240717/linux-amd64/go1.21.5"
}
```

**Comment by revett** [comment]
@sl1depengwyn - Is anyone else from the team available?

**Comment by CoNETProject** [comment]
I face to same issue
Chain information: hard fork from ethereum POS
GETH + Prysm

https://scan.conet.network/

this is the logs:
```
backend           | 2024-09-30T06:37:17.005621405Z {"time":"2024-09-30T06:37:16.997Z","severity":"error","message":"Could not insert all of chunk into Elixir.Explorer.Chain.TokenTransfer using options because of error.\n\nChunk Size: 500\nChunk:\n\n[%{amount: Decimal.new(\"1\"), inserted_at: ~U[2024-09-30 06:33:14.413623Z], updated_at: ~U[2024-09-30 06:33:14.413623Z], block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<157, 224, 50, 179, 160, 88, 208, 192, 166, 130, 178, 203, 217, 24, 13, 14, 74, 34, 62, 252, 249, 71, 230, 21, 106, 158, 237, 175, 0, 63, 35, 54>>}, block_number: 290255, transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<8, 5, 0, 222, 181, 29, 150, 48, 40, 34, 9, 58, 125, 5, 181, 117, 70, 9, 170, 73, 191, 45, 57, 1, 41, 77, 203, 146, 235, 133, 105, 219>>}, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<39, 30, 115, 125, 109, 95, 237, 73, 155, 158, 105, 254, 103, 145, 203, 165, 22, 135, 16, 158>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, token_type: \"ERC-1155\", token_ids: [Decimal.new(\"1\")], log_index: 2784, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<146, 160, 51, 160, 47, 169, 33, 105, 4, 107, 145, 35, 33, 149, 208, 232, 43, 128, 23, 171>>}}, %{amount: Decimal.new(\"1\"), inserted_at: ~U[2024-09-30 06:33:14.413623Z], updated_at: ~U[2024-09-30 06:33:14.413623Z], block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<157, 224, 50, 179, 160, 88, 208, 192, 166, 130, 178, 203, 217, 24, 13, 14, 74, 34, 62, 252, 249, 71, 230, 21, 106, 158, 237, 175, 0, 63, 35, 54>>}, block_number: 290255,

........hide 584KB(There was a problem saving your comment. Your comment is too long (maximum is 65536 characters))

Options:\n\n[conflict_target: [:transaction_hash, :log_index, :block_hash], on_conflict: #Ecto.Query<from t0 in Explorer.Chain.TokenTransfer, where: fragment(\n  \"(EXCLUDED.amount, EXCLUDED.from_address_hash, EXCLUDED.to_address_hash, EXCLUDED.token_contract_address_hash, EXCLUDED.token_ids, EXCLUDED.token_type, EXCLUDED.block_consensus) IS DISTINCT FROM (?, ?, ?, ?, ?, ?, ?)\",\n  t0.amount,\n  t0.from_address_hash,\n  t0.to_address_hash,\n  t0.token_contract_address_hash,\n  t0.token_ids,\n  t0.token_type,\n  t0.block_consensus\n), update: [\n  set: [\n    amount: fragment(\"EXCLUDED.amount\"),\n    from_address_hash: fragment(\"EXCLUDED.from_address_hash\"),\n    to_address_hash: fragment(\"EXCLUDED.to_address_hash\"),\n    token_contract2024-09-30T06:37:17.623996678Z _address_hash: fragment(\"EXCLUDED.token_contract_address_hash\"),\n    token_ids: fragment(\"EXCLUDED.token_ids\"),\n    token_type: fragment(\"EXCLUDED.token_type\"),\n    block_consensus: fragment(\"EXCLUDED.block_consensus\"),\n    inserted_at: fragment(\"LEAST(?, EXCLUDED.inserted_at)\", t0.inserted_at),\n    updated_at: fragment(\"GREATEST(?, EXCLUDED.updated_at)\", t0.updated_at)\n  ]\n]>, returning: true, timeout: 60000, timestamps: %{inserted_at: ~U[2024-09-30 06:33:16.858894Z], updated_at: ~U[2024-09-30 06:33:16.858894Z]}]\n\nException:\n\n** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:925: Ecto.Adapters.SQL.insert_all/9\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7\n    (explorer 6.8.1) lib/explorer/repo.ex:47: anonymous fn/5 in Explorer.Repo.safe_insert_all/3\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.8.1) lib/explorer/chain/import.ex:304: Explorer.Chain.Import.insert_changes_list/3\n    (explorer 6.8.1) lib/explorer/chain/import/runner/token_transfers.ex:77: Explorer.Chain.Import.Runner.TokenTransfers.insert/3\n    (stdlib 5.2.3) timer.erl:270: :timer.tc/2\n","metadata":{"fetcher":"block_catchup","last_block_number":290364,"import_id":99848,"transaction_id":99976,"first_block_number":290373}}
```

**Comment by nikitosing** [comment]
@CoNETProject @revett is it still actual report?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
