### ISSUE TITLE
Optimism Bedrock blockscout 1.9.0 transaction batch 

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout#11101]
### Description

Starting a fresh Bedrock 1.8.0 rollup with blockscout 6.9.0

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://github.com/blockscout/blockscout

### Steps to reproduce

```
{"time":"2024-11-01T13:50:39.941Z","severity":"info","message":"Start handling L1 block range 17350038..17350041. Target range: 17350038..17350201.","metadata":{"fetcher":"optimism_transaction_batches"}}
{"time":"2024-11-01T13:50:39.980Z","severity":"error","message":"GenServer Indexer.Fetcher.Optimism.TransactionBatch terminating\n** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.do_elixir_to_params/1\n    (ethereum_jsonrpc 6.9.0) lib/ethereum_jsonrpc/transaction.ex:310: EthereumJSONRPC.Transaction.do_elixir_to_params(%{:ignore => :ignore, \"blockHash\" => \"0xdfd6ce85098d884000d80f53f75892be0097a3256503298c597dde4ffb2d6efa\", \"blockNumber\" => 17350039, \"block_timestamp\" => ~U[2024-11-01 13:39:26Z], \"chainId\" => 84532, \"from\" => \"0xe07ab6195a1b4639839b4dbe489549ddc49bcc07\", \"gas\" => 6601714, \"gasPrice\" => 1001411, \"hash\" => \"0xe38fc43b887251a3895b37511323cec6f2111853d452abc3a2c3d08903b67ad7\", \"input\" => \"0x6101c06040523480156200001257600080fd5b5060405162005f7438038062005f74833981016040819052620000359162000187565b620000436001607e62000248565b60ff168811156200006757604051633beff19960e11b815260040160405180910390fd5b878710620000885760405163e62ccf3960e01b815260040160405180910390fd5b620000a7856001600160401b03166200014e60201b62000c891760201c565b6001600160401b0316620000cf876001600160401b03166200014e60201b62000c891760201c565b6001600160401b03161115620000f85760405163235dfb2b60e21b815260040160405180910390fd5b63ffffffff9099166101205260809790975260a09590955260c0939093526001600160401b039182166101a0521660e0526001600160a01b0390811661010052908116610140521661016052610180526200027a565b90565b80516001600160401b03811681146200016957600080fd5b919050565b6001600160a01b03811681146200018457600080fd5b50565b6000806000806000806000806000806101408b8d031215620001a857600080fd5b8a5163ffffffff81168114620001bd57600080fd5b809a505060208b0151985060408b0151975060608b01519650620001e460808c0162000151565b9550620001f460a08c0162000151565b945060c08b015162000206816200016e565b60e08c015190945062000219816200016e565b6101008c01519093506200022d816200016e565b809250506101208b015190509295989b9194979a5092959850565b600060ff821660ff8416808210156200027157634e487b7160e01b600052601160045260246000fd5b90039392505050565b60805160a05160c05160e05161010051610120516101405161016051610180516101a051615b82620003f2600039600081816106bb01528181611e9001528181611f4e0152611f78015260008181610a1e01526137960152600081816106130152818161178a01526124b00152600081816105270152818161194c01528181612349015281816128b20152613c5601526000818161088d0152818161246f01526138250152600081816104b40152818161310a015261345f015260008181610a7101528181610f6001528181611e2a01528181611ebb01528181611fb001528181612abe0152612b00015260008181610aa401528181611c7301528181611d9901528181611f1901528181612f5d0152818161365e01528181613d4d01528181614473015281816145a1015281816146a20152614777015260008181610b4b01528181611d3c01528181612bce01528181612c5401528181612e530152612f7e015260008181610786015261301c0152615b826000f3fe6080604052600436106102f25760003560e01c806370872aa51161018f578063c6f0308c116100e1578063ec5e63081161008a578063fa24f74311610064578063fa24f74314610b18578063fa315aa914610b3c578063fe2bbeb214610b6f57600080fd5b8063ec5e630814610a95578063eff0f59214610ac8578063f8f43ff614610af857600080fd5b8063d6ae3cd5116100bb578063d6ae3cd514610a0f578063d8cc1a3c14610a42578063dabd396d14610a6257600080fd5b8063c6f0308c14610937578063cf09e0d0146109c1578063d5d44d80146109e257600080fd5b80638d450a9511610143578063bcef3b551161011d578063bcef3b55146108b7578063bd8da956146108f7578063c395e1ca1461091757600080fd5b80638d450a9514610777578063a445ece6146107aa578063bbdc02db1461087657600080fd5b80638129fc1c116101745780638129fc1c1461071a5780638980e0cc146107225780638b85902b1461073757600080fd5b806370872aa5146106f25780637b0f0adc1461070757600080fd5b80633fc8cef3116102485780635c0cba33116101fc5780636361506d116101d65780636361506d1461066c5780636b6716c0146106ac5780636f034409146106df57600080fd5b80635c0cba3314610604578063609d33341461063757806360e274641461064c57600080fd5b806354fd4d501161022d57806354fd4d501461055e57806357da950e146105b45780635a5fa2d9146105e457600080fd5b80633fc8cef314610518578063472777c61461054b57600080fd5b80632810e1d6116102aa57806337b1b2291161028457806337b1b229146104655780633a768463146104a55780633e3ac912146104d857600080fd5b80632810e1d6146103de5780632ad69aeb146103f357806330dbe5701461041357600080fd5b806319effeb4116102db57806319effeb414610339578063200d2ed21461038457806325fc2ace146103bf57600080fd5b806301935130146102f757806303c2924d14610319575b600080fd5b34801561030357600080fd5b5061031761031236600461532d565b610b9f565b005b34801561032557600080fd5b50610317610334366004615388565b610ec0565b34801561034557600080fd5b506000546103669068010000000000000000900467ffffffffffffffff1681565b60405167ffffffffffffffff90911681526020015b60405180910390f35b34801561039057600080fd5b506000546103b290700100000000000000000000000000000000900460ff1681565b60405161037b91906153d9565b3480156103cb57600080fd5b506008545b60405190815260200161037b565b3480156103ea57600080fd5b506103b2611566565b3480156103ff57600080fd5b506103d061040e366004615388\" <> ..., \"maxFeePerGas\" => 1002824, \"maxPriorityFeePerGas\" => 1000000, \"nonce\" => 36, \"r\" => 38248157724718431937780270765756072423121902523610719538168188411170050621754, \"s\" => 35832967733730107118771614047414123382452128216048613478162200287028860524989, \"transactionIndex\" => 13, \"type\" => 2, \"v\" => 1, \"value\" => 0})\n    (ethereum_jsonrpc 6.9.0) lib/ethereum_jsonrpc/transaction.ex:306: EthereumJSONRPC.Transaction.elixir_to_params/1\n    (elixir 1.17.3) lib/enum.ex:1703: Enum.\"-map/2-lists^map/1-1-\"/2\n    (elixir 1.17.3) lib/enum.ex:1703: Enum.\"-map/2-lists^map/1-1-\"/2\n    (ethereum_jsonrpc 6.9.0) lib/ethereum_jsonrpc/blocks.ex:54: EthereumJSONRPC.Blocks.from_responses/2\n    (ethereum_jsonrpc 6.9.0) lib/ethereum_jsonrpc.ex:697: EthereumJSONRPC.fetch_blocks_by_params/3\n    (indexer 6.9.0) lib/indexer/fetcher/optimism/transaction_batch.ex:440: Indexer.Fetcher.Optimism.TransactionBatch.get_transaction_batches/8\n    (indexer 6.9.0) lib/indexer/fetcher/optimism/transaction_batch.ex:259: anonymous fn/12 in Indexer.Fetcher.Optimism.TransactionBatch.handle_info/2\nLast message: :continue\nState: %{chunk_size: 4, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://l1-proxy:8080\", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]]], end_block: 17350201, start_block: 17350038, block_check_interval: 1000, json_rpc_named_arguments_l2: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://rollup-proxy-service:8545\", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: \"http://rollup-proxy-service:8545\", debug_traceTransaction: \"http://rollup-proxy-service:8545\", debug_traceBlockByNumber: \"http://rollup-proxy-service:8545\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], genesis_block_l2: 0, eip4844_blobs_api_url: \"\", celestia_blobs_api_url: \"\", batch_inbox: \"0x9dfe2e327f1d8774bdb381f2203f4cd9e9de71c8\", batch_submitter: \"0xce5ec53aa2f0ec2fd88e70c57668427aa3189635\", incomplete_channels: %{}}","metadata":{"error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.do_elixir_to_params/1\n    (ethereum_jsonrpc 6.9.0) lib/ethereum_jsonrpc/transaction.ex:310: EthereumJSONRPC.Transaction.do_elixir_to_params(%{:ignore => :ignore, \"blockHash\" => \"0xdfd6ce85098d884000d80f53f75892be0097a3256503298c597dde4ffb2d6efa\", \"blockNumber\" => 17350039, \"block_timestamp\" => ~U[2024-11-01 13:39:26Z], \"chainId\" => 84532, \"from\" => \"0xe07ab6195a1b4639839b4dbe489549ddc49bcc07\", \"gas\" => 6601714, \"gasPrice\" => 1001411, \"hash\" => \"0xe38fc43b887251a3895b37511323cec6f2111853d452abc3a2c3d08903b67ad7\", \"input\" => \"0x6101c06040523480156200001257600080fd5b5060405162005f7438038062005f74833981016040819052620000359162000187565b620000436001607e62000248565b60ff168811156200006757604051633beff19960e11b815260040160405180910390fd5b878710620000885760405163e62ccf3960e01b815260040160405180910390fd5b620000a7856001600160401b03166200014e60201b62000c891760201c565b6001600160401b0316620000cf876001600160401b03166200014e60201b62000c891760201c565b6001600160401b03161115620000f85760405163235dfb2b60e21b815260040160405180910390fd5b63ffffffff9099166101205260809790975260a09590955260c0939093526001600160401b039182166101a0521660e0526001600160a01b0390811661010052908116610140521661016052610180526200027a565b90565b80516001600160401b03811681146200016957600080fd5b919050565b6001600160a01b03811681146200018457600080fd5b50565b6000806000806000806000806000806101408b8d031215620001a857600080fd5b8a5163ffffffff81168114620001bd57600080fd5b809a505060208b0151985060408b0151975060608b01519650620001e460808c0162000151565b9550620001f460a08c0162000151565b945060c08b015162000206816200016e565b60e08c015190945062000219816200016e565b6101008c01519093506200022d816200016e565b809250506101208b015190509295989b9194979a5092959850565b600060ff821660ff8416808210156200027157634e487b7160e01b600052601160045260246000fd5b90039392505050565b60805160a05160c05160e05161010051610120516101405161016051610180516101a051615b82620003f2600039600081816106bb01528181611e9001528181611f4e0152611f78015260008181610a1e01526137960152600081816106130152818161178a01526124b00152600081816105270152818161194c01528181612349015281816128b20152613c5601526000818161088d0152818161246f01526138250152600081816104b40152818161310a015261345f015260008181610a7101528181610f6001528181611e2a01528181611ebb01528181611fb001528181612abe0152612b00015260008181610aa401528181611c7301528181611d9901528181611f1901528181612f5d0152818161365e01528181613d4d01528181614473015281816145a1015281816146a20152614777015260008181610b4b01528181611d3c01528181612bce01528181612c5401528181612e530152612f7e015260008181610786015261301c0152615b826000f3fe6080604052600436106102f25760003560e01c806370872aa51161018f578063c6f0308c116100e1578063ec5e63081161008a578063fa24f74311610064578063fa24f74314610b18578063fa315aa914610b3c578063fe2bbeb214610b6f57600080fd5b8063ec5e630814610a95578063eff0f59214610ac8578063f8f43ff614610af857600080fd5b8063d6ae3cd5116100bb578063d6ae3cd514610a0f578063d8cc1a3c14610a42578063dabd396d14610a6257600080fd5b8063c6f0308c14610937578063cf09e0d0146109c1578063d5d44d80146109e257600080fd5b80638d450a9511610143578063bcef3b551161011d578063bcef3b55146108b7578063bd8da956146108f7578063c395e1ca1461091757600080fd5b80638d450a9514610777578063a445ece6146107aa578063bbdc02db1461087657600080fd5b80638129fc1c116101745780638129fc1c1461071a5780638980e0cc146107225780638b85902b1461073757600080fd5b806370872aa5146106f25780637b0f0adc1461070757600080fd5b80633fc8cef3116102485780635c0cba33116101fc5780636361506d116101d65780636361506d1461066c5780636b6716c0146106ac5780636f034409146106df57600080fd5b80635c0cba3314610604578063609d33341461063757806360e274641461064c57600080fd5b806354fd4d501161022d57806354fd4d501461055e57806357da950e146105b45780635a5fa2d9146105e457600080fd5b80633fc8cef314610518578063472777c61461054b57600080fd5b80632810e1d6116102aa57806337b1b2291161028457806337b1b229146104655780633a768463146104a55780633e3ac912146104d857600080fd5b80632810e1d6146103de5780632ad69aeb146103f357806330dbe5701461041357600080fd5b806319effeb4116102db57806319effeb414610339578063200d2ed21461038457806325fc2ace146103bf57600080fd5b806301935130146102f757806303c2924d14610319575b600080fd5b34801561030357600080fd5b5061031761031236600461532d565b610b9f565b005b34801561032557600080fd5b50610317610334366004615388565b610ec0565b34801561034557600080fd5b506000546103669068010000000000000000900467ffffffffffffffff1681565b60405167ffffffffffffffff90911681526020015b60405180910390f35b34801561039057600080fd5b506000546103b290700100000000000000000000000000000000900460ff1681565b60405161037b91906153d9565b3480156103cb57600080fd5b506008545b60405190815260200161037b565b3480156103ea57600080fd5b506103b2611566565b3480156103ff57600080fd5b506103d061040e366004615388\" <> ..., \"maxFeePerGas\" => 1002824, \"maxPriorityFeePerGas\" => 1000000, \"nonce\" => 36, \"r\" => 38248157724718431937780270765756072423121902523610719538168188411170050621754, \"s\" => 35832967733730107118771614047414123382452128216048613478162200287028860524989, \"transactionIndex\" => 13, \"type\" => 2, \"v\" => 1, \"value\" => 0})\n    (ethereum_jsonrpc 6.9.0) lib/ethereum_jsonrpc/transaction.ex:306: EthereumJSONRPC.Transaction.elixir_to_params/1\n    (elixir 1.17.3) lib/enum.ex:1703: Enum.\"-map/2-lists^map/1-1-\"/2\n    (elixir 1.17.3) lib/enum.ex:1703: Enum.\"-map/2-lists^map/1-1-\"/2\n    (ethereum_jsonrpc 6.9.0) lib/ethereum_jsonrpc/blocks.ex:54: EthereumJSONRPC.Blocks.from_responses/2\n    (ethereum_jsonrpc 6.9.0) lib/ethereum_jsonrpc.ex:697: EthereumJSONRPC.fetch_blocks_by_params/3\n    (indexer 6.9.0) lib/indexer/fetcher/optimism/transaction_batch.ex:440: Indexer.Fetcher.Optimism.TransactionBatch.get_transaction_batches/8\n    (indexer 6.9.0) lib/indexer/fetcher/optimism/transaction_batch.ex:259: anonymous fn/12 in Indexer.Fetcher.Optimism.TransactionBatch.handle_info/2\n"},"fetcher":"optimism_transaction_batches"}}
{"time":"2024-11-01T13:50:40.809Z","severity":"info","message":"tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 05 Sep 2024 18:47:42 GMT.","metadata":{}}
```

### Backend version

v6.9.0

### Frontend version

1.35

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Linux

### Additional information

asdf

**Comment by varasev** [comment]
Hi, This issue duplicated the following one: https://github.com/blockscout/blockscout/issues/11086 - that will be fixed by https://github.com/blockscout/blockscout/pull/11073
