### ISSUE TITLE
Postgrex expected an integer in -2147483648..2147483647, got 9223372036854775807

### ISSUE THREAD

**Issue by klemenfn** [blockscout/blockscout#11120]
### Description

Occasionally we see this in error.log. Unfortunately the stack trace does not show exactly what triggers it but it seems some database field is a signed 32bit number while code tries to use signed 64bit max. I tried to turn on debug ecto logs but a restart doesn't seem to pick it up (recompile needed?).

`2024-11-02T18:00:13.949 application=api request_id=GAQ4n10gguerrh8AAcgh [error] Error while calling RPC action"** (Plug.Conn.WrapperError) ** (DBConnection.EncodeError) Postgrex expected an integer in -2147483648..2147483647, got 9223372036854775807. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.\n    (postgrex 0.19.1) lib/postgrex/type_module.ex:1084: Postgrex.DefaultTypes.encode_params/3\n    (postgrex 0.19.1) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3\n    (db_connection 2.7.0) lib/db_connection.ex:1449: DBConnection.encode/5\n    (db_connection 2.7.0) lib/db_connection.ex:1549: DBConnection.run_prepare_execute/5\n    (db_connection 2.7.0) lib/db_connection.ex:1653: DBConnection.run/6\n    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5\n    (db_connection 2.7.0) lib/db_connection.ex:764: DBConnection.prepare_execute/4\n    (ecto_sql 3.11.3) lib/ecto/adapters/postgres/connection.ex:101: Ecto.Adapters.Postgres.Connection.prepare_execute/5\n"`

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Backend version

v6.8.1-beta

### Elixir & Erlang/OTP versions

Elixir 1.16, Erlang 1.26

### Operating system

Ubuntu 22.04

**Comment by vivienbcr** [comment]
I also get this error from fresh blockscout install (backend 7.0.2 postgres 17) on Sepolia network and Erigon node

```
{"time":"2025-03-14T13:38:24.684Z","severity":"error","message":"** (DBConnection.EncodeError) Postgrex expected an integer in -2147483648..2147483647, got 1741816862113. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.\n    (postgrex 0.20.0) lib/postgrex/type_module.ex:1084: Postgrex.DefaultTypes.encode_params/3\n    (postgrex 0.20.0) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3\n    (db_connection 2.7.0) lib/db_connection.ex:1449: DBConnection.encode/5\n    (db_connection 2.7.0) lib/db_connection.ex:1549: DBConnection.run_prepare_execute/5\n    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5\n    (db_connection 2.7.0) lib/db_connection.ex:764: DBConnection.prepare_execute/4\n    (postgrex 0.20.0) lib/postgrex.ex:296: Postgrex.query/4\n    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:547: Ecto.Adapters.SQL.query!/4\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","last_block_number":7889669,"first_block_number":7889675}}
{"time":"2025-03-14T13:38:24.733Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 10","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2025-03-14T13:38:25.046Z","severity":"error","message":"Could not insert all of chunk into Elixir.Explorer.Chain.SignedAuthorization using options because of error.\n\nChunk Size: 2\nChunk:\n\n[%{index: 0, address: %Explorer.Chain.Hash{byte_count: 20, bytes: <<68, 195, 146, 37, 150, 129, 239, 226, 118, 43, 63, 86, 65, 254, 82, 79, 135, 11, 139, 73>>}, v: 1, s: Decimal.new(\"42233679031289711307549493995865574424864498337354451203004091722286715852592\"), r: Decimal.new(\"42609484869408557841012568769065034835909151671848623386487818316749075941139\"), authority: %Explorer.Chain.Hash{byte_count: 20, bytes: <<172, 92, 128, 70, 0, 168, 15, 191, 198, 4, 95, 241, 105, 244, 83, 22, 144, 70, 181, 67>>}, nonce: 1741817076801, inserted_at: ~U[2025-03-14 13:38:24.265778Z], updated_at: ~U[2025-03-14 13:38:24.265778Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<103, 51, 182, 112, 168, 222, 59, 7, 147, 58, 160, 209, 163, 120, 149, 91, 117, 78, 181, 92, 49, 206, 216, 12, 117, 151, 77, 62, 63, 77, 81, 79>>}, chain_id: 11155111}, %{index: 0, address: %Explorer.Chain.Hash{byte_count: 20, bytes: <<68, 195, 146, 37, 150, 129, 239, 226, 118, 43, 63, 86, 65, 254, 82, 79, 135, 11, 139, 73>>}, v: 1, s: Decimal.new(\"50203824092681129652918789893157063214518872756301933648741143174699427195566\"), r: Decimal.new(\"93833927639803149125485689405297138457693780767725133269691990197293664648091\"), authority: %Explorer.Chain.Hash{byte_count: 20, bytes: <<230, 173, 48, 199, 139, 88, 110, 36, 4, 136, 201, 163, 238, 69, 38, 4, 38, 143, 192, 68>>}, nonce: 1741816969236, inserted_at: ~U[2025-03-14 13:38:24.265778Z], updated_at: ~U[2025-03-14 13:38:24.265778Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<239, 137, 23, 207, 155, 221, 235, 240, 159, 176, 89, 116, 227, 59, 110, 101, 94, 107, 91, 118, 75, 56, 83, 232, 28, 12, 121, 14, 133, 78, 102, 33>>}, chain_id: 11155111}]\n\nOptions:\n\n[on_conflict: #Ecto.Query<from s0 in Explorer.Chain.SignedAuthorization, where: fragment(\n  \"(EXCLUDED.chain_id, EXCLUDED.address, EXCLUDED.nonce, EXCLUDED.r, EXCLUDED.s, EXCLUDED.v, EXCLUDED.authority) IS DISTINCT FROM (?, ?, ?, ?, ?, ?, ?)\",\n  s0.chain_id,\n  s0.address,\n  s0.nonce,\n  s0.r,\n  s0.s,\n  s0.v,\n  s0.authority\n), update: [\n  set: [\n    chain_id: fragment(\"EXCLUDED.chain_id\"),\n    address: fragment(\"EXCLUDED.address\"),\n    nonce: fragment(\"EXCLUDED.nonce\"),\n    r: fragment(\"EXCLUDED.r\"),\n    s: fragment(\"EXCLUDED.s\"),\n    v: fragment(\"EXCLUDED.v\"),\n    authority: fragment(\"EXCLUDED.authority\"),\n    inserted_at: fragment(\"LEAST(?, EXCLUDED.inserted_at)\", s0.inserted_at),\n    updated_at: fragment(\"GREATEST(?, EXCLUDED.updated_at)\", s0.updated_at)\n  ]\n]>, conflict_target: [:transaction_hash, :index], returning: true, timeout: 60000, timestamps: %{inserted_at: ~U[2025-03-14 13:38:24.265778Z], updated_at: ~U[2025-03-14 13:38:24.265778Z]}]\n\nException:\n\n** (DBConnection.EncodeError) Postgrex expected an integer in -2147483648..2147483647, got 1741817076801. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.\n    (postgrex 0.20.0) lib/postgrex/type_module.ex:1084: Postgrex.DefaultTypes.encode_params/3\n    (postgrex 0.20.0) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3\n    (db_connection 2.7.0) lib/db_connection.ex:1449: DBConnection.encode/5\n    (db_connection 2.7.0) lib/db_connection.ex:1549: DBConnection.run_prepare_execute/5\n    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5\n    (db_connection 2.7.0) lib/db_connection.ex:764: DBConnection.prepare_execute/4\n    (postgrex 0.20.0) lib/postgrex.ex:296: Postgrex.query/4\n    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:547: Ecto.Adapters.SQL.query!/4\n","metadata":{"transaction_id":56640263}}
{"time":"2025-03-14T13:38:25.167Z","severity":"warn","message":"Set refetch_needed for partially imported block because of error: [7889682, 7889683, 7889684, 7889685, 7889686, 7889687, 7889688, 7889689, 7889690, 7889691]","metadata":{"fetcher":"block_catchup","last_block_number":7889682,"first_block_number":7889691}}
```
