### ISSUE TITLE
INDEXER_DISABLE_BEACON_BLOB_FETCHER=true causes backend service to terminate

### ISSUE THREAD

**Issue by yohanelly95** [blockscout/blockscout#11272]
### Description

When I add these changes to the blockscout.env I get an error and backend service is terminated. 
```
INDEXER_BEACON_RPC_URL=http://IP:PORT
INDEXER_DISABLE_BEACON_BLOB_FETCHER=false
INDEXER_BEACON_BLOB_FETCHER_SLOT_DURATION=12
INDEXER_BEACON_BLOB_FETCHER_REFERENCE_SLOT=120
INDEXER_BEACON_BLOB_FETCHER_REFERENCE_TIMESTAMP=1732691945
INDEXER_BEACON_BLOB_FETCHER_START_BLOCK=200
INDEXER_BEACON_BLOB_FETCHER_END_BLOCK=100
```
Note: This is a new chain that runs on kurtosis. So its an eth2.0 chain. 

The error I get is: 

```
{"time":"2024-11-27T07:55:56.675Z","severity":"error","message":"Task #PID<0.5825.0> started from Indexer.Fetcher.Beacon.Blob terminating\n** (Postgrex.Error) ERROR 42P01 (undefined_table) relation \"beacon_blobs_transactions\" does not exist\n\n    query: SELECT DISTINCT ON (t1.\"block_timestamp\") t1.\"block_timestamp\" FROM (SELECT sb0.\"hash\" AS \"transaction_hash\", unnest(blob_versioned_hashes) AS \"blob_hash\" FROM \"beacon_blobs_transactions\" AS sb0) AS s0 INNER JOIN \"transactions\" AS t1 ON s0.\"transaction_hash\" = t1.\"hash\" LEFT OUTER JOIN \"beacon_blobs\" AS b2 ON b2.\"hash\" = s0.\"blob_hash\" WHERE (t1.\"type\" = 3) AND (b2.\"hash\" IS NULL) AND (t1.\"block_number\" >= $1) AND (t1.\"block_number\" <= $2)\n    (db_connection 2.7.0) lib/db_connection.ex:1509: DBConnection.prepare_declare!/4\n    (db_connection 2.7.0) lib/db_connection.ex:1249: anonymous fn/4 in DBConnection.reduce/3\n    (elixir 1.17.3) lib/stream.ex:1675: anonymous fn/5 in Stream.resource/3\n    (elixir 1.17.3) lib/stream.ex:1891: Enumerable.Stream.do_each/4\n    (elixir 1.17.3) lib/stream.ex:943: Stream.do_transform/5\n    (elixir 1.17.3) lib/stream.ex:1891: Enumerable.Stream.do_each/4\n    (elixir 1.17.3) lib/enum.ex:4423: Enum.reduce/3\n    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4\nFunction: #Function<1.82347618/0 in Indexer.BufferedTask.do_initial_stream/1>\n    Args: []","metadata":{"error":{"initial_call":null,"reason":"** (Postgrex.Error) ERROR 42P01 (undefined_table) relation \"beacon_blobs_transactions\" does not exist\n\n    query: SELECT DISTINCT ON (t1.\"block_timestamp\") t1.\"block_timestamp\" FROM (SELECT sb0.\"hash\" AS \"transaction_hash\", unnest(blob_versioned_hashes) AS \"blob_hash\" FROM \"beacon_blobs_transactions\" AS sb0) AS s0 INNER JOIN \"transactions\" AS t1 ON s0.\"transaction_hash\" = t1.\"hash\" LEFT OUTER JOIN \"beacon_blobs\" AS b2 ON b2.\"hash\" = s0.\"blob_hash\" WHERE (t1.\"type\" = 3) AND (b2.\"hash\" IS NULL) AND (t1.\"block_number\" >= $1) AND (t1.\"block_number\" <= $2)\n    (db_connection 2.7.0) lib/db_connection.ex:1509: DBConnection.prepare_declare!/4\n    (db_connection 2.7.0) lib/db_connection.ex:1249: anonymous fn/4 in DBConnection.reduce/3\n    (elixir 1.17.3) lib/stream.ex:1675: anonymous fn/5 in Stream.resource/3\n    (elixir 1.17.3) lib/stream.ex:1891: Enumerable.Stream.do_each/4\n    (elixir 1.17.3) lib/stream.ex:943: Stream.do_transform/5\n    (elixir 1.17.3) lib/stream.ex:1891: Enumerable.Stream.do_each/4\n    (elixir 1.17.3) lib/enum.ex:4423: Enum.reduce/3\n    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4\n"},"fetcher":"beacon_blob"}}
{"time":"2024-11-27T07:55:56.678Z","severity":"info","message":"Application indexer exited: shutdown","metadata":{}}
Kernel pid terminated (application_controller) ("{application_terminated,indexer,shutdown}")

Crash dump is being written to: erl_crash.dump...done
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

http://34.143.128.61/

### Steps to reproduce

Update the blockscout.env with the Blob related paramaters and run `docker compose -f geth.yml up -d`

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

Elixir 1.14.5 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by vbaranov** [comment]
@yohanelly95 was your issue resolved after switching to blockscout-ethereum docker image?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
