### ISSUE TITLE
Syncing arbitrum batches

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout#11356]
### Description

```
{"time":"2024-12-06T11:38:12.261Z","severity":"error","message":"Could not insert all of chunk into Elixir.Explorer.Chain.Arbitrum.DaMultiPurposeRecord using options because of error.\n\nChunk Size: 10\nChunk:\n\n[%{data: %{timeout: ~U[2024-03-28 20:04:55Z], bls_signature: \"0x0b072d6d0b29bd0e09a60cf10a5dbc7fcf7a55ebf24fb808143668f9252bdfa6d2010f2616fbc432277048d8e6892ca30242f23282534a23d300aa81a471e596a697147ecbd9e932ceedfe385da4898b092ed48e8614a84700b43f62fe534e44\", data_hash: \"0x08b9b7306d3ac990cb36405260d288b64efb05adfbf0a9f98c39a6d1e33e267b\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9397, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<8, 185, 183, 48, 109, 58, 201, 144, 203, 54, 64, 82, 96, 210, 136, 182, 78, 251, 5, 173, 251, 240, 169, 249, 140, 57, 166, 209, 227, 62, 38, 123>>}}, %{data: %{timeout: ~U[2024-03-28 20:16:23Z], bls_signature: \"0x179df32c38bcf22d42dcbf86e0e31547a9265f711e404404b41d5bdfecebf20f0524a50322dbddd50e08d72115b9b5e7054117a0cc00c9daf49488081518bd31c88076fe3bfc6dbd434393219a9d1a1c2ee179e640f0aa1fb6f9008a99726e10\", data_hash: \"0x2869f5067e86443cbcf64d8034bce6115866afe7a0295e2b664195e61080f916\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9399, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<40, 105, 245, 6, 126, 134, 68, 60, 188, 246, 77, 128, 52, 188, 230, 17, 88, 102, 175, 231, 160, 41, 94, 43, 102, 65, 149, 230, 16, 128, 249, 22>>}}, %{data: %{timeout: ~U[2024-03-28 20:20:17Z], bls_signature: \"0x041ab6315232b831c6df76fca80ab95b9b87a71abfeceb75db27827e06f4af6301168004e0b798b7ef1d9135abd2bb3709f00d533ec8f73c3e2b262ae6109d4a997f08a1506c2be8c84cfabc3ed8f65cd00c018d499aa3f86ae22fa5404a0bed\", data_hash: \"0x4233e60e1891e56f3cfec51693d29f0f2dc6642528e86a4d6bc1ed60602ca92a\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9400, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<66, 51, 230, 14, 24, 145, 229, 111, 60, 254, 197, 22, 147, 210, 159, 15, 45, 198, 100, 37, 40, 232, 106, 77, 107, 193, 237, 96, 96, 44, 169, 42>>}}, %{data: %{timeout: ~U[2024-03-28 20:11:42Z], bls_signature: \"0x0c6f56f117e70cb9c385f4568bbf7bc1f9774055adcdda908d9964cbbfef6417a2905c95d545fe486dbb38e9e61963d013c1bca4e4f3b36df501d4a1e6e0f8c89547db9c9e35532b4698604bfb8803043306c14f4d04b095438f5b7fa3cb343c\", data_hash: \"0x50fa78bb8078ddebd2d2d8cafa651fd7628326255c0f5e75d425c39b7f445c8c\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9398, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<80, 250, 120, 187, 128, 120, 221, 235, 210, 210, 216, 202, 250, 101, 31, 215, 98, 131, 38, 37, 92, 15, 94, 117, 212, 37, 195, 155, 127, 68, 92, 140>>}}, %{data: %{timeout: ~U[2024-03-28 20:24:16Z], bls_signature: \"0x11a4287517e93fc84051f0e0b4f4edb8daf2193affe1a3c30b086dc718fbc80888a2222ee203a90decffab7d8f1bf25702424477cdfa9a8c208830e5c692ea461ae9e0bc99a76b561b476d446d43234d831a910c139be0fce7fc7af5a6f8a675\", data_hash: \"0x60c3c64fb64daf7581981cd7778435739ec443e9881a02c41c5397a976966259\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9402, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<96, 195, 198, 79, 182, 77, 175, 117, 129, 152, 28, 215, 119, 132, 53, 115, 158, 196, 67, 233, 136, 26, 2, 196, 28, 83, 151, 169, 118, 150, 98, 89>>}}, %{data: %{timeout: ~U[2024-03-28 19:51:58Z], bls_signature: \"0x05a0806541fad87dda549bbb8ebfb788e5da9d48d492e0fba34843c468d66983d66563686fa2d745a8c063d56180f4e0126ce14e6e4d0838803e172293d3da33bc73d741cc0b71cfcfb6327ee4781faf462783a0f76e423104a6fdfdd8bfed3b\", data_hash: \"0x8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9394, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<130, 119, 179, 112, 140, 232, 205, 20, 239, 140, 232, 164, 32, 38, 179, 100, 158, 246, 8, 79, 76, 21, 28, 108, 177, 125, 120, 210, 4, 111, 172, 5>>}}, %{data: %{timeout: ~U[2024-03-28 19:54:14Z], bls_signature: \"0x11cce397efcb54f5f2624fa7b0f940ce3144d170f4d4c8bf6b0fb1e0695c64bedeee2854658d279aa7bc5fc6ec8476b716805837c5f97b8d5ebc09a4b5ff3df42812787801f3bfc853ae90981cabaea332f0e1199bba4f0eaa416c0f87298b4c\", data_hash: \"0x8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9396, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<130, 119, 179, 112, 140, 232, 205, 20, 239, 140, 232, 164, 32, 38, 179, 100, 158, 246, 8, 79, 76, 21, 28, 108, 177, 125, 120, 210, 4, 111, 172, 5>>}}, %{data: %{timeout: ~U[2024-03-28 20:21:03Z], bls_signature: \"0x0ae2e3356617696ca7cba97b8b5e77ebe3e191707072acccd96479a17ad6ddd025b79420d64b9cac04db5143c39356cc1379aaf6a2d51d956d1ba2c8a0b1991df1b70dca788fc9f83c7370380a24f78a92f49a526db0ce0af43130d5ffe2ac16\", data_hash: \"0x8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9401, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<130, 119, 179, 112, 140, 232, 205, 20, 239, 140, 232, 164, 32, 38, 179, 100, 158, 246, 8, 79, 76, 21, 28, 108, 177, 125, 120, 210, 4, 111, 172, 5>>}}, %{data: %{timeout: ~U[2024-03-28 20:25:26Z], bls_signature: \"0x0b0b8bc6b37a80907935ebc77599f1786655f7c98693be8dbee0060c9d8441fbecfc2e81f5567c1cd9b7c8f5b01394180c363a2f4375b372ca40d4eb24e3a5c600d1bb55bdd76ea283a2f08567c504bbc9ed12901c4d294802938443f7c7d600\", data_hash: \"0xe4cecb1e3583088c5f166a06a00aa0df0dc9013290ff8e2b50502f0f3855ec9e\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9403, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<228, 206, 203, 30, 53, 131, 8, 140, 95, 22, 106, 6, 160, 10, 160, 223, 13, 201, 1, 50, 144, 255, 142, 43, 80, 80, 47, 15, 56, 85, 236, 158>>}}, %{data: %{timeout: ~U[2024-03-28 19:53:03Z], bls_signature: \"0x17ed41153eff08ee831615577346a30c2a68c798fc281dea799e8f331c7f629d1b8361d9b773bead94a0ef22fd38418215815b446da2f880f1519bcbb3160198b2a5a979114636b1394340ff32243d768309e221c9118e8aec7ff5d91898173f\", data_hash: \"0xf94742cbe1814fd6a5a3bcb28f70e7801b5f74b76bebcf8abac190c09b23d672\", keyset_hash: \"0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c\", signers_mask: 1}, data_type: 0, inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z], batch_number: 9395, data_key: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 71, 66, 203, 225, 129, 79, 214, 165, 163, 188, 178, 143, 112, 231, 128, 27, 95, 116, 183, 107, 235, 207, 138, 186, 193, 144, 192, 155, 35, 214, 114>>}}]\n\nOptions:\n\n[returning: true, timeout: 60000, timestamps: %{inserted_at: ~U[2024-12-06 11:38:12.176296Z], updated_at: ~U[2024-12-06 11:38:12.176296Z]}, conflict_target: :data_key, on_conflict: #Ecto.Query<from d0 in Explorer.Chain.Arbitrum.DaMultiPurposeRecord, where: fragment(\n  \"(EXCLUDED.data_type, EXCLUDED.data, EXCLUDED.batch_number) IS DISTINCT FROM (?, ?, ?)\",\n  d0.data_type,\n  d0.data,\n  d0.batch_number\n), update: [\n  set: [\n    data_type: fragment(\"EXCLUDED.data_type\"),\n    data: fragment(\"EXCLUDED.data\"),\n    batch_number: fragment(\"EXCLUDED.batch_number\"),\n    inserted_at: fragment(\"LEAST(?, EXCLUDED.inserted_at)\", d0.inserted_at),\n    updated_at: fragment(\"GREATEST(?, EXCLUDED.updated_at)\", d0.updated_at)\n  ]\n]>]\n\nException:\n\n** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time\n\n    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:925: Ecto.Adapters.SQL.insert_all/9\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7\n    (explorer 6.8.1) lib/explorer/repo.ex:47: anonymous fn/5 in Explorer.Repo.safe_insert_all/3\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.8.1) lib/explorer/chain/import.ex:304: Explorer.Chain.Import.insert_changes_list/3\n    (explorer 6.8.1) lib/explorer/chain/import/runner/arbitrum/da_multi_purpose_records.ex:70: Explorer.Chain.Import.Runner.Arbitrum.DaMultiPurposeRecords.insert/3\n    (stdlib 5.2.3) timer.erl:270: :timer.tc/2\n","metadata":{"fetcher":"arbitrum_batches_tracker","import_id":2251,"transaction_id":2379}}
{"time":"2024-12-06T11:38:12.262Z","severity":"error","message":"GenServer Indexer.Fetcher.Arbitrum.TrackingBatchesStatuses terminating\n** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time\n\n    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:925: Ecto.Adapters.SQL.insert_all/9\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7\n    (explorer 6.8.1) lib/explorer/repo.ex:47: anonymous fn/5 in Explorer.Repo.safe_insert_all/3\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.8.1) lib/explorer/chain/import.ex:304: Explorer.Chain.Import.insert_changes_list/3\n    (explorer 6.8.1) lib/explorer/chain/import/runner/arbitrum/da_multi_purpose_records.ex:70: Explorer.Chain.Import.Runner.Arbitrum.DaMultiPurposeRecords.insert/3\n    (stdlib 5.2.3) timer.erl:270: :timer.tc/2\nLast message: :check_new_batches\nState: %{data: %{historical_batches_end_block: 1642761, historical_confirmations_end_block: nil, historical_confirmations_start_block: nil, historical_executions_end_block: 1646167, missing_batches_end_batch: 9393, new_batches_start_block: 22868027, new_confirmations_start_block: 22859879, new_executions_start_block: 22835239}, config: %{rollup_rpc: %{chunk_size: 20, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://replica:8545\", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: \"http://replica:8545\", debug_traceTransaction: \"http://replica:8545\", debug_traceBlockByNumber: \"http://replica:8545\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth]}, recheck_interval: 20000, l1_rpc: %{chunk_size: 20, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://l1-proxy:8080\", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]]], track_finalization: true, finalized_confirmations: true, logs_block_range: 10000}, l1_rollup_address: \"0x2EeDc7b995267aa1060587Ff2585690C204E7e5c\", l1_start_block: 1640371, l1_outbox_address: \"0x4d8679db1058b0f8cae84485f6b760a858ceca10\", l1_sequencer_inbox_address: \"0xf0d96b3a783f04620d5cbbf2829e70cee396403f\", lowest_batch: 1, l1_rollup_init_block: 1640371, messages_to_blocks_shift: 0, confirmation_batches_depth: nil, new_batches_limit: 10, missing_batches_range: 10000, node_interface_address: \"0x00000000000000000000000000000000000000C8\"}}","metadata":{"error":{"initial_call":null,"reason":"** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time\n\n    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:925: Ecto.Adapters.SQL.insert_all/9\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7\n    (explorer 6.8.1) lib/explorer/repo.ex:47: anonymous fn/5 in Explorer.Repo.safe_insert_all/3\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.8.1) lib/explorer/chain/import.ex:304: Explorer.Chain.Import.insert_changes_list/3\n    (explorer 6.8.1) lib/explorer/chain/import/runner/arbitrum/da_multi_purpose_records.ex:70: Explorer.Chain.Import.Runner.Arbitrum.DaMultiPurposeRecords.insert/3\n    (stdlib 5.2.3) timer.erl:270: :timer.tc/2\n"},"fetcher":"arbitrum_batches_tracker"}}
```

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Geth

### Type of the chain

L3 - Nitro 3.2.1 (Anytrust) 
Parent chain: Arbitrum Sepolia

### Link to the page

https://rari-testnet.calderaexplorer.xyz/

### Steps to reproduce

Syncing Rari Testnet

### Backend version

6.8.1

### Frontend version

1.35

### Elixir & Erlang/OTP versions

Elixir

**Comment by akolotov** [comment]
The issue arises from incorrect handling of cases where a block of batches is being imported into the database, and the same `AnyTrust` data blob is used for different batches. Since the data hash serves as the key for the import operation, the process fails when the table `arbitrum_da_multi_purpose` is updated with multiple records having the same key.

A temporary workaround could be to reduce the `INDEXER_ARBITRUM_NEW_BATCHES_LIMIT` to `1`.

**Comment by InoMurko** [comment]
> The issue arises from incorrect handling of cases where a block of batches is being imported into the database, and the same `AnyTrust` data blob is used for different batches. Since the data hash serves as the key for the import operation, the process fails when the table `arbitrum_da_multi_purpose` is updated with multiple records having the same key.
> 
> A temporary workaround could be to reduce the `INDEXER_ARBITRUM_NEW_BATCHES_LIMIT` to `1`.

Okay, I can try that!

**Comment by akolotov** [comment]
For the record:

Here is decoded data from the initial log. It represents DA information which was trying to be imported to the DB:
```json
[
  {
    "data": {
      "timeout": "2024-03-28T20:04:55Z",
      "bls_signature": "0x0b072d6d0b29bd0e09a60cf10a5dbc7fcf7a55ebf24fb808143668f9252bdfa6d2010f2616fbc432277048d8e6892ca30242f23282534a23d300aa81a471e596a697147ecbd9e932ceedfe385da4898b092ed48e8614a84700b43f62fe534e44",
      "data_hash": "0x08b9b7306d3ac990cb36405260d288b64efb05adfbf0a9f98c39a6d1e33e267b",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9397,
    "data_key": {
      "byte_count": 32,
      "bytes": "08b9b7306d3ac990cb36405260d288b64efb05adfbf0a9f98c39a6d1e33e267b"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T20:16:23Z",
      "bls_signature": "0x179df32c38bcf22d42dcbf86e0e31547a9265f711e404404b41d5bdfecebf20f0524a50322dbddd50e08d72115b9b5e7054117a0cc00c9daf49488081518bd31c88076fe3bfc6dbd434393219a9d1a1c2ee179e640f0aa1fb6f9008a99726e10",
      "data_hash": "0x2869f5067e86443cbcf64d8034bce6115866afe7a0295e2b664195e61080f916",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9399,
    "data_key": {
      "byte_count": 32,
      "bytes": "2869f5067e86443cbcf64d8034bce6115866afe7a0295e2b664195e61080f916"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T20:20:17Z",
      "bls_signature": "0x041ab6315232b831c6df76fca80ab95b9b87a71abfeceb75db27827e06f4af6301168004e0b798b7ef1d9135abd2bb3709f00d533ec8f73c3e2b262ae6109d4a997f08a1506c2be8c84cfabc3ed8f65cd00c018d499aa3f86ae22fa5404a0bed",
      "data_hash": "0x4233e60e1891e56f3cfec51693d29f0f2dc6642528e86a4d6bc1ed60602ca92a",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9400,
    "data_key": {
      "byte_count": 32,
      "bytes": "4233e60e1891e56f3cfec51693d29f0f2dc6642528e86a4d6bc1ed60602ca92a"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T20:11:42Z",
      "bls_signature": "0x0c6f56f117e70cb9c385f4568bbf7bc1f9774055adcdda908d9964cbbfef6417a2905c95d545fe486dbb38e9e61963d013c1bca4e4f3b36df501d4a1e6e0f8c89547db9c9e35532b4698604bfb8803043306c14f4d04b095438f5b7fa3cb343c",
      "data_hash": "0x50fa78bb8078ddebd2d2d8cafa651fd7628326255c0f5e75d425c39b7f445c8c",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9398,
    "data_key": {
      "byte_count": 32,
      "bytes": "50fa78bb8078ddebd2d2d8cafa651fd7628326255c0f5e75d425c39b7f445c8c"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T20:24:16Z",
      "bls_signature": "0x11a4287517e93fc84051f0e0b4f4edb8daf2193affe1a3c30b086dc718fbc80888a2222ee203a90decffab7d8f1bf25702424477cdfa9a8c208830e5c692ea461ae9e0bc99a76b561b476d446d43234d831a910c139be0fce7fc7af5a6f8a675",
      "data_hash": "0x60c3c64fb64daf7581981cd7778435739ec443e9881a02c41c5397a976966259",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9402,
    "data_key": {
      "byte_count": 32,
      "bytes": "60c3c64fb64daf7581981cd7778435739ec443e9881a02c41c5397a976966259"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T19:51:58Z",
      "bls_signature": "0x05a0806541fad87dda549bbb8ebfb788e5da9d48d492e0fba34843c468d66983d66563686fa2d745a8c063d56180f4e0126ce14e6e4d0838803e172293d3da33bc73d741cc0b71cfcfb6327ee4781faf462783a0f76e423104a6fdfdd8bfed3b",
      "data_hash": "0x8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9394,
    "data_key": {
      "byte_count": 32,
      "bytes": "8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T19:54:14Z",
      "bls_signature": "0x11cce397efcb54f5f2624fa7b0f940ce3144d170f4d4c8bf6b0fb1e0695c64bedeee2854658d279aa7bc5fc6ec8476b716805837c5f97b8d5ebc09a4b5ff3df42812787801f3bfc853ae90981cabaea332f0e1199bba4f0eaa416c0f87298b4c",
      "data_hash": "0x8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9396,
    "data_key": {
      "byte_count": 32,
      "bytes": "8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T20:21:03Z",
      "bls_signature": "0x0ae2e3356617696ca7cba97b8b5e77ebe3e191707072acccd96479a17ad6ddd025b79420d64b9cac04db5143c39356cc1379aaf6a2d51d956d1ba2c8a0b1991df1b70dca788fc9f83c7370380a24f78a92f49a526db0ce0af43130d5ffe2ac16",
      "data_hash": "0x8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9401,
    "data_key": {
      "byte_count": 32,
      "bytes": "8277b3708ce8cd14ef8ce8a42026b3649ef6084f4c151c6cb17d78d2046fac05"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T20:25:26Z",
      "bls_signature": "0x0b0b8bc6b37a80907935ebc77599f1786655f7c98693be8dbee0060c9d8441fbecfc2e81f5567c1cd9b7c8f5b01394180c363a2f4375b372ca40d4eb24e3a5c600d1bb55bdd76ea283a2f08567c504bbc9ed12901c4d294802938443f7c7d600",
      "data_hash": "0xe4cecb1e3583088c5f166a06a00aa0df0dc9013290ff8e2b50502f0f3855ec9e",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9403,
    "data_key": {
      "byte_count": 32,
      "bytes": "e4cecb1e3583088c5f166a06a00aa0df0dc9013290ff8e2b50502f0f3855ec9e"
    }
  },
  {
    "data": {
      "timeout": "2024-03-28T19:53:03Z",
      "bls_signature": "0x17ed41153eff08ee831615577346a30c2a68c798fc281dea799e8f331c7f629d1b8361d9b773bead94a0ef22fd38418215815b446da2f880f1519bcbb3160198b2a5a979114636b1394340ff32243d768309e221c9118e8aec7ff5d91898173f",
      "data_hash": "0xf94742cbe1814fd6a5a3bcb28f70e7801b5f74b76bebcf8abac190c09b23d672",
      "keyset_hash": "0x414e0847074cf03f4ad8e1b4214af48bfb92a9277beaa6e178107a3d0b317b7c",
      "signers_mask": 1
    },
    "data_type": 0,
    "inserted_at": "2024-12-06T11:38:12.176296Z",
    "updated_at": "2024-12-06T11:38:12.176296Z",
    "batch_number": 9395,
    "data_key": {
      "byte_count": 32,
      "bytes": "f94742cbe1814fd6a5a3bcb28f70e7801b5f74b76bebcf8abac190c09b23d672"
    }
  }
]
```

**Comment by akolotov** [comment]
For the record:

Here is the list of transactions submitting batches of Rari Testnet to Arbitrum Sepolia:
- [batch 9394](https://arbitrum-sepolia.blockscout.com/tx/0xbf1365764ed26a3521c8b46320b446ba9e92b84d35d2c392363567d582a5afd6)
- [batch 9395](https://arbitrum-sepolia.blockscout.com/tx/0xfc47705d2f59ecc57e23b24d0b89712abb358bf0a52150f8fbd53188b04a8c77)
- [batch 9396](https://arbitrum-sepolia.blockscout.com/tx/0x650d45eeb86058b281adb4ed17e94960f3df6e621a0dcc388d5022282d953167)
- [batch 9397](https://arbitrum-sepolia.blockscout.com/tx/0x6e70fc1898c03b699b60c845ad0ba4633250fb4c991ebc7c5df0755f181f2f37)
- [batch 9398](https://arbitrum-sepolia.blockscout.com/tx/0xe5808531932622525c14a75b71aca6ec26fb37520c1281aaaf5ea0a7f4a1dd7e)
- [batch 9399](https://arbitrum-sepolia.blockscout.com/tx/0xd17f7f37a55c933ebda406e45bc38254bc02ea33169c81e24361691b4fea5bc0)
- [batch 9400](https://arbitrum-sepolia.blockscout.com/tx/0xc5282421fdc27076c763cc487794452195b5f66f7153f5fd57e94ae358b39881)
- [batch 9401](https://arbitrum-sepolia.blockscout.com/tx/0x818d8501e4f11176274dd37124688209edb1ccb5a19b6fb770e18895c16f5aa4)
