### ISSUE TITLE
can't process eip-7702 tx

### ISSUE THREAD

**Issue by islishude** [blockscout/blockscout#11538]
### Description

geth version

master

log

```
{"time":"2024-12-24T15:12:19.588Z","severity":"error","message":"** (ArgumentError) argument error\n    (ex_secp256k1 0.7.3) ExSecp256k1.Impl.recover(<<174, 172, 217, 137, 9, 35, 0, 26, 144, 120, 218, 24, 108, 143, 77, 103, 82, 90, 134, 49, 109, 116, 144, 132, 157, 215, 135, 98, 184, 98, 89, 167>>, <<248, 212, 163, 41, 199, 207, 3, 107, 214, 68, 237, 105, 4, 220, 234, 7, 117, 113, 181, 207, 31, 119, 41, 37, 118, 202, 161, 238, 101, 82, 245, 228>>, <<119, 145, 151, 200, 140, 135, 107, 114, 206, 34, 63, 77, 100, 69, 221, 172, 20, 101, 169, 139, 221, 205, 60, 190, 221, 30, 162, 238, 20, 226, 34, 178>>, nil)\n    (indexer 6.10.0) lib/indexer/transform/signed_authorizations.ex:67: Indexer.Transform.SignedAuthorizations.ec_recover/4\n    (indexer 6.10.0) lib/indexer/transform/signed_authorizations.ex:37: anonymous fn/2 in Indexer.Transform.SignedAuthorizations.parse/1\n    (elixir 1.17.3) lib/enum.ex:1703: Enum.\"-map/2-lists^map/1-1-\"/2\n    (elixir 1.17.3) lib/enum.ex:4353: Enum.flat_map_list/2\n    (indexer 6.10.0) lib/indexer/block/fetcher.ex:250: Indexer.Block.Fetcher.fetch_and_import_range/3\n    (stdlib 6.1) timer.erl:590: :timer.tc/2\n    (indexer 6.10.0) lib/indexer/block/catchup/fetcher.ex:173: Indexer.Block.Catchup.Fetcher.fetch_and_import_missing_range/2\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","last_block_number":1088,"first_block_number":1097}}
```

tx

```
{
  accessList: [],
  authorizationList: [{
      address: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      chainId: "0x539",
      nonce: "0x3",
      r: "0xf8d4a329c7cf036bd644ed6904dcea077571b5cf1f77292576caa1ee6552f5e4",
      s: "0x779197c88c876b72ce223f4d6445ddac1465a98bddcd3cbedd1ea2ee14e222b2",
      yParity: "0x1"
  }],
  blockHash: "0xee5b5c1a70f693b75cbcc3ed6e5f26c251076e580fbc4cc7b0bd351f3f1a7d32",
  blockNumber: 1091,
  chainId: "0x539",
  from: "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
  gas: 1000000,
  gasPrice: 9,
  hash: "0x66b0c883eb536fd5f334938eaa28ed746cc6d0abb79921f939224f60fc431440",
  input: "0x",
  maxFeePerGas: 23,
  maxPriorityFeePerGas: 2,
  nonce: 2,
  r: "0x9b6ba0199b44f4f2d54e6619ee32a7110b07f2d339fbf7d111ec11603dfbc058",
  s: "0x17c3570bdd6f92d99db4d7f911a8a1cb9855ed309e48376dc7967456a554a65d",
  to: "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
  transactionIndex: 0,
  type: "0x4",
  v: "0x0",
  value: 1,
  yParity: "0x0"
}
```

chain config

```
 {
        arrowGlacierBlock: 0,
        berlinBlock: 0,
        byzantiumBlock: 0,
        cancunTime: 0,
        chainId: 1337,
        constantinopleBlock: 0,
        depositContractAddress: "0x0000000000000000000000000000000000000000",
        eip150Block: 0,
        eip155Block: 0,
        eip158Block: 0,
        grayGlacierBlock: 0,
        homesteadBlock: 0,
        istanbulBlock: 0,
        londonBlock: 0,
        muirGlacierBlock: 0,
        petersburgBlock: 0,
        pragueTime: 0,
        shanghaiTime: 0,
        terminalTotalDifficulty: 0
      },
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

localhost

### Backend version

blockscout/blockscout:master

### Frontend version

main

### Elixir & Erlang/OTP versions

blockscout/blockscout:master

### Operating system

macOS

**Comment by islishude** [comment]
https://github.com/blockscout/blockscout/blob/master/apps/indexer/lib/indexer/transform/signed_authorizations.ex#L54-L55

I think it should use `signed_authorization.yParity` instead `signed_authorization.v`

**Comment by AllFi** [comment]
Hello, @islishude!

Thank you for highlighting this issue! This field was indeed renamed in [this commit](https://github.com/ethereum/go-ethereum/commit/73a4ecf675f6714e1fdf49904ce9426841de2e02). We'll update our codebase to reflect this change.
