### ISSUE TITLE
Can not parse block timestamp of quorum Raft private chain,invalid Unix time 1600178177994719000.

### ISSUE THREAD

**Issue by passionofvc** [blockscout/blockscout#3294]
*Describe my issue here.*
blockscount not work in private quorum raft chain, can not parse
timestamp under Raft, due to Raft holding block timestamp in nanoseconds, instead of seconds.
1600178177994719000 is the parse time, is there an option to workaround like export BLOCK_TRANSFORMER=raft?

```
> eth.getBlock(1)
{
  difficulty: 131072,
  extraData: "0x0000000000000000000000000000000000000000000000000000000000000000f84431b8412c330acf61bca831ece098e1cbdd0767af3741811cec906caacecf0c5e9a0d3a3bbbfb0208cc8e08d4a52cff240dfd4c0af1864005861b9913f83262acf59cf901",
  gasLimit: 3757178881,
  gasUsed: 471462,
  hash: "0x64787a34625f15cb2e09a736f60ecfe5c666e2de89e41c5bb6da2a250051c612",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 1,
  parentHash: "0xce82ff1a4245d8cad7c3cf55f9197e6764c8127b54f6cb8226f9163deb2d8e6d",
  receiptsRoot: "0xf462e1dd16d7426ad39cdccb2e4eee5ad8bf6ba092ddb30cc5b22fa9521c07f9",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 2688,
  stateRoot: "0x97bde64379559efc67aac5165bd842fe1c764036ca8d2428c15e88388fb0e4ed",
  timestamp: 1600178177994719000,
  totalDifficulty: 131072,
  transactions: ["0x2a70a6ce89123c0ff52160e85ef5355ecd70760820396c013a66e32642fdbfb0"],
  transactionsRoot: "0xab072b4ff28f8e323a837ea0fcf4a092c35a50c88db91225d0b32b1a65f64003",
  uncles: []
}
```
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):

```
$ elixir --version
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.0-dev (67cbd59) (compiled with Erlang/OTP 22)

```
* Operating System:
mac os
* Blockscout Version/branch: 
master, run from docker 

### Steps to reproduce
run a quorum private raft 7 nodes example.

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*
$ run https://github.com/ConsenSys/quorum-examples/tree/master/examples/7nodes in Raft consensus
$ git clone https://github.com/poanetwork/blockscout.git
$ cd docker
$ make migrate
$ make start

### Expected behaviour
can parse block timestamp and show blockinfo

### Actual behaviour
```
Retrying.
2020-09-15T14:46:50.202 application=indexer fetcher=block_catchup first_block_number=9 last_block_number=1 missing_block_count=9 shrunk=false [info] Index had to catch up.
2020-09-15T14:46:50.202 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
2020-09-15T14:46:50.912 application=explorer [warn] Failed to fetch genesis data. Chain spec path is not set.
2020-09-15T14:46:52.728 application=indexer fetcher=block_catchup first_block_number=9 last_block_number=1 [error] ** (ArgumentError) invalid Unix time 1600178177994719000
    (elixir 1.10.3) lib/calendar/datetime.ex:179: DateTime.from_unix!/3
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/block.ex:502: EthereumJSONRPC.Block.entry_to_elixir/1
    (elixir 1.10.3) lib/enum.ex:1320: anonymous fn/4 in Enum.into/3
    (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
    (elixir 1.10.3) lib/enum.ex:2127: Enum.into/4
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3

```

**Comment by LvLs9** [comment]
@passionofvc did you found solution?

**Comment by billaure-crystaleum** [comment]
Might be an old thread, and something else could had been the cause of this issue.

However, OP noted the versions and detected a mismatch for the required depends:
change Erlang/OTP 22 for Erlang/OTP 24
change Elixir 1.11.0-dev for Elixir 1.13.4

use ASDF for a more efficient version control for installation of depends

Hope this helps!
