### ISSUE TITLE
Application start error when use DISABLE_INDEXER

### ISSUE THREAD

**Issue by unqjohnny** [blockscout/blockscout#3849]
when i set:  ```export DISABLE_INDEXER=true```

got this error:

```
2021-04-23T19:29:58.607 application=que [info] [Que] Booting Server Supervisor for Workers
2021-04-23T19:29:59.761 [info] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {%KeyError{key: :password, message: nil, term: [types: nil, types: Postgrex.DefaultTypes, username: "zara", sync_connect: true, hostname: "172.18.4.254", database: "explorer3?ssl=false", migration_timestamps: [type: :utc_datetime_usec], url: "postgresql://postgres:123456@172.18.4.254:5432/explorer3?ssl=false", pool_size: 50, timeout: 80000]}, [{Keyword, :fetch!, 2, [file: 'lib/keyword.ex', line: 420]}, {Postgrex.Protocol, :auth_md5, 4, [file: 'lib/postgrex/protocol.ex', line: 722]}, {Postgrex.Protocol, :handshake, 2, [file: 'lib/postgrex/protocol.ex', line: 579]}, {Postgrex.Notifications, :connect, 2, [file: 'lib/postgrex/notifications.ex', line: 225]}, {Postgrex.Notifications, :init, 1, [file: 'lib/postgrex/notificat** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {%KeyError{key: :password, message: nil, term: [types: nil, types: Postgrex.DefaultTypes, username: "zara", sync_connect: true, hostname: "172.18.4.254", database: "explorer3?ssl=false", migration_timestamps: [type: :utc_datetime_usec], url: "postgresql://postgres:123456@172.18.4.254:5432/explorer3?ssl=false", pool_size: 50, timeout: 80000]}, [{Keyword, :fetch!, 2, [file: 'lib/keyword.ex', line: 420]}, {Postgrex.Protocol, :auth_md5, 4, [file: 'lib/postgrex/protocol.ex', line: 722]}, {Postgrex.Protocol, :handshake, 2, [file: 'lib/postgrex/protocol.ex', line: 579]}, {Postgrex.Notifications, :connect, 2, [file: 'lib/postgrex/notifications.ex', line: 225]}, {Postgrex.Notifications, :init, 1, [file: 'lib/postgrex/notifications.ex',ions.ex', line: 207]}, {Connection, :init_it, 6, [file: 'lib/connection.ex', line: 424]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
            (explorer 0.0.1) lib/explorer/chain/events/listener.ex:22: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
 line: 207]}, {Connection, :init_it, 6, [file: 'lib/connection.ex', line: 424]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
            (explorer 0.0.1) lib/explorer/chain/events/listener.ex:22: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by rogerganga** [comment]
I am getting the same error as well. Any solutions on this?

**Comment by cdivitotawela** [comment]
I also want to enable indexer in one instance and disable in all other instances with the expectation to reduce the concurrency issues. When I set `DISABLE_INDEXER=true` I also get same error.

**Comment by cdivitotawela** [comment]
> I also want to enable indexer in one instance and disable in all other instances with the expectation to reduce the concurrency issues. When I set `DISABLE_INDEXER=true` I also get same error.

I experience this in version 3.7.0-beta

**Comment by adean-consensys** [comment]
I think I have an idea what’s going on, but I don’t know enough about Elixir to troubleshoot because its error handling messages are awfully terse.  I don’t think it’s parsing the **DATABASE_URL** env var correctly, so it’s not able to populate things like username, password, etc. to the Postgrex connection constructor.  If it’s set in a ConfigMap like so:

```
PGHOST: "your-server-12345-rds.amazonaws.com"
PGPORT: "5432"
PGDATABASE: blockscout
PGUSER: postgres
```

and obviously the password as a Secret named **PGPASSWORD**, you get a different error message:

```
│ ** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener                  │
│     ** (EXIT) an exception was raised:                                                                                                                                                     │
│         ** (MatchError) no match of right hand side value: {:error, :badarg}                                                                                                               │
│             (explorer 0.0.1) lib/explorer/chain/events/listener.ex:22: Explorer.Chain.Events.Listener.init/1                                                                               │
│             (stdlib 3.14.1) gen_server.erl:417: :gen_server.init_it/2                                                                                                                      │
│             (stdlib 3.14.1) gen_server.erl:385: :gen_server.init_it/6                                                                                                                      │
│             (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3                                                                                                                  │
│ 2021-06-30T15:40:35.967 [info] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener     │
│     ** (EXIT) an exception was raised:                                                                                                                                                     │
│         ** (MatchError) no match of right hand side value: {:error, :badarg}                                                                                                               │
│             (explorer 0.0.1) lib/explorer/chain/events/listener.ex:22: Explorer.Chain.Events.Listener.init/1                                                                               │
│             (stdlib 3.14.1) gen_server.erl:417: :gen_server.init_it/2                                                                                                                      │
│             (stdlib 3.14.1) gen_server.erl:385: :gen_server.init_it/6                                                                                                                      │
│             (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3      
```

Omitting something like **PGHOST** gives you an expected result


```
│ 2021-06-30T16:41:04.039 application=db_connection [error] Postgrex.Protocol (#PID<0.547.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection  │
│ refused - :econnrefused
```

Similarly if omitting **PGDATABASE**

```
│ 2021-06-30T16:42:26.334 [error] GenServer #PID<0.558.0> terminating                                                                                                                        │
│ ** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may s │
│ et :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details                                                                    │
│     (elixir 1.11.4) lib/keyword.ex:420: Keyword.fetch!/2                                                                                                                                   │
│     (postgrex 0.15.8) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1                                                                                                             │
│     (db_connection 2.3.1) lib/db_connection/connection.ex:82: DBConnection.Connection.connect/2                                                                                            │
│     (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5                                                                                                                   │
│     (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3   
```

**Comment by zalam003** [comment]
@vbaranov I have tried couple of settings.  I see the [same issue](https://github.com/blockscout/blockscout/issues/3849#issue-866027038) when setting `DISABLE_INDEXER=true` and `DISABLE_WEBAPP=false`.

On the indexer, I would like to do the reverse: `DISABLE_INDEXER=false` and `DISABLE_WEBAPP=true`.  It is also exiting with an error.  Here I am not exposing the web port.  It is a work around to get the indexer to work.

**Comment by zalam003** [comment]
@vbaranov Issue resolved by added following to environment variables:
```
PGHOST="your-server-12345-rds.amazonaws.com"
PGPORT=5432
PGDATABASE=your_db_name
PGUSER=your_db_sername
PGPASSWORD=your_db_password
```
