### ISSUE TITLE
Error building Node.js dependencies

### ISSUE THREAD

**Issue by fiexer** [blockscout/blockscout#3913]
*Describe your issue here.*

### Environment

* Erlang/OPT 23.2.1 
* Elixi 1.11.2
* Postgres
* Node.js v14.16.1
* Ubuntu 18.04
* Blockscout version: latest (master)
* Hosting Azure

### Steps to reproduce

*When I try to build BlockScout, I encounter several errors.
*All software needed installed `cd blockscout`

```
export DATABASE_URL= OK
export SECRET_KEY_BASE= OK
```
If you have deployed previously, remove static assets from the previous build (witch I have)
`mix phx.digest.clean`

Following error:
```
maarten@EVM:~/blockscout$ sudo mix phx.digest.clean
==> ethereum_jsonrpc
The output path "priv/static" does not exist
==> explorer
The output path "priv/static" does not exist
==> indexer
The output path "priv/static" does not exist
==> block_scout_web
The output path "priv/static" does not exist
```

Let's ignore this for now and set all environment variables:
```
export NETWORK=Plasm Network
export SUBNETWORK=Dusty
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:9933
export ETHEREUM_JSONRPC_TRACE_URL=http://localhost:9933
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:9944
```

Install Mix dependencies, compile them and compile the application:
`mix do deps.get, local.rebar --force, deps.compile, compile`

All good:
`Compiling NIF crate :exkeccak (native/exkeccak)...
    Finished release [optimized] target(s) in 0.05s`

Check DB connection:
`maarten@EVM:~/blockscout$ pg_isready
/var/run/postgresql:5432 - accepting connections`

Create DB (successfully):
`mix do ecto.drop, ecto.create, ecto.migrate`

Building:
```
cd apps/block_scout_web/assets
sudo npm install
```

Error:
````
gyp verb build dir attempting to create "build" dir: /home/maarten/blockscout/apps/block_scout_web/assets/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/maarten/blockscout/apps/block_scout_web/assets/node_modules/node-sass/build'
gyp ERR! System Linux 5.4.0-1046-azure
gyp ERR! command "/usr/bin/node" "/home/maarten/blockscout/apps/block_scout_web/assets/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/maarten/blockscout/apps/block_scout_web/assets/node_modules/node-sass
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optimize-css-assets-webpack-plugin@5.0.4 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@5.0.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Also using `sudo su`
and build as root

Thanks for the help!

Kind regards
Maarten

**Comment by fiexer** [comment]
Found the solution by running:
`sudo npm install -g --unsafe-perm=true --allow-root`

**Comment by fiexer** [comment]
The moment I do mix phx.server

I'll receive this error:
```
2021-05-05T20:07:20.654 [warn] The on_load function for module libsecp256k1 returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/maarten/blockscout/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so: cannot open shared object file: No such file or directory\''}}
```

and this
```
2021-05-05T20:07:26.317 fetcher=block_catchup [error] Task #PID<0.2950.0> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating
** (MatchError) no match of right hand side value: {:error, :econnrefused}
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:76: Indexer.Block.Catchup.Fetcher.task/1
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:7545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Ganache], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}]
2021-05-05T20:07:26.318 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({{:badmatch, {:error, :econnrefused}}, [{Indexer.Block.Catchup.Fetcher, :task, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 76]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}). Restarting
```

**Comment by KunioHaha** [comment]
i hava the same problem,

**Comment by vbaranov** [comment]
libsecp256k1 issue should be resolved. The application was upgraded to be compatible with the latest version of Elixir 1.12.x.

**Comment by fiexer** [comment]
> libsecp256k1 issue should be resolved. The application was upgraded to be compatible with the latest version of Elixir 1.12.x.

Hi @vbaranov, would be great if you could contact me regarding an EVM explorer.
We are more than happy to offer you a grant for this. Telegram: [https://t.me/fiexer](https://t.me/fiexer)
