### ISSUE TITLE
Could not compile dependency :ex_keccak

### ISSUE THREAD

**Issue by AleksMVP** [blockscout/blockscout#4062]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions 
```
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.11.2 (compiled with Erlang/OTP 23)
```
* Operating System:
```
Ubuntu 20.04 LTS
```
* Blockscout Version/branch: 
```
git clone https://github.com/poanetwork/blockscout;
I think latest?
```

### Steps to reproduce
```
# Dependencies
wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
sudo dpkg -i erlang-solutions_2.0_all.deb
sudo apt-get update
sudo apt-get install -y esl-erlang=1:23*

sudo apt-get update
sudo apt-get install -y elixir

sudo apt update
sudo apt install -y postgresql postgresql-contrib

sudo apt-get install -y npm

sudo apt-get install -y automake

sudo apt-get install -y libtool

sudo apt-get install -y libgmp3-dev

sudo apt-get install -y inotify-tools

# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
curl https://sh.rustup.rs -sSf | sh -s -- -y

git clone https://github.com/poanetwork/blockscout;
cd blockscout;
echo "
# blockscout/start.sh

export HOME=/home/aleks
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
export ETHEREUM_JSONRPC_VARIANT=geth
export COIN=ETH
export DATABASE_URL=postgresql://dbusername:dbuserpassword@localhost:5432/blockscout
" > start.sh

mix do deps.get, local.rebar --force, deps.compile, compile -y;
```

### Expected behaviour

* Build success 

### Actual behaviour
```
Compiling NIF crate :exkeccak (native/exkeccak)...
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (ErlangError) Erlang error: :enoent
    (elixir 1.11.2) lib/system.ex:815: System.cmd("cargo", ["rustc", "--release"], [cd: "/home/aleks/blockscout/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/aleks/blockscout/_build/dev/rustler_crates/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
```

**Comment by vbaranov** [comment]
@AleksMVP  Nowadays Rust is required for building `ex_keccak` dependency https://docs.blockscout.com/for-developers/information-and-settings/requirements.
