### ISSUE TITLE
Can't compile ex_keccak

### ISSUE THREAD

**Issue by sami3232** [blockscout/blockscout#4250]
I have done all the install but when I try to compile ex _keccak, compilation failes

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):

Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]
Elixir 1.12.0 (compiled with Erlang/OTP 24)

* Operating System: Ubuntu 20.04 LTS
* Blockscout Version/branch: https://github.com/poanetwork/blockscout; I'm on branch "master" 
* Libtool: 2.4.6-14
* Libgmp3-dev: 2:6.2.0+dfsg-4
* Inotify-tools: 3.14-8
* Rustc: 1.52.1
* Postgre : 12.7-0ubuntu0.20.04.1

### Steps to reproduce
```
sudo apt-get update
wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
sudo dpkg -i erlang-solutions_2.0_all.deb
sudo apt-get update
sudo apt-get install -y esl-erlang=1:23*

sudo apt-get update
sudo apt-get install -y elixir
sudo apt-get update
sudo apt-get install -y elixir

sudo apt update
sudo apt install -y postgresql postgresql-contrib

sudo apt-get install -y npm

sudo apt-get install -y automake

# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
curl https://sh.rustup.rs -sSf | sh -s -- -y

echo "
# blockscout/start.sh

export HOME=/home/ubuntu
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
export ETHEREUM_JSONRPC_VARIANT=geth
export COIN=ETH
export DATABASE_URL=postgresql://dbusername:dbuserpassword@localhost:5432/blockscout
" > start.sh
```

Parsetool was missing on erlang so I used this command to fix it:
```
sudo apt install build-essential erlang-dev erlang-dev erlang-parsetools
```

The error appeared after this command:
```
mix do deps.get, local.rebar --force, deps.compile, compile -y;

```

### Expected behaviour

Install Succes

### Actual behaviour
```
*Compiling NIF crate :exkeccak (native/exkeccak)...
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (ErlangError) Erlang error: :enoent
    (elixir 1.12.0) lib/system.ex:1041: System.cmd("cargo", ["rustc", "--release"], [cd: "/home/ubuntu/blockscout/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/ubuntu/blockscout/_build/dev/rustler_crates/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.12.0) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.0) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.0) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.0) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2*
```
*Help please*
I have already done the installation twice with the same error. I know, this problem has already been "resolved". However, as you can see, I have installed rust and nothing has changed. Do you have any idea how to solve this problem?

**Comment by piersandro** [comment]
> Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]
> Elixir 1.12.0 (compiled with Erlang/OTP 24)

Erlang OTP 24 is not compatible with rust.
Plase downgrade to Erlang to OTP 23 and Elixir to version 1.10/1.11.

**Comment by sami3232** [comment]
I changed my version of both Elixir and Erlang with asdf.

elixir -v :
```
Erlang/OTP 23 [erts-11.2.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.11.3 (compiled with Erlang/OTP 21)
```

The issue remains the same:
```
Compiling NIF crate :exkeccak (native/exkeccak)...
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (ErlangError) Erlang error: :enoent
    (elixir 1.12.0) lib/system.ex:1041: System.cmd("cargo", ["rustc", "--release"], [cd: "/home/ubuntu/blockscout/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/ubuntu/blockscout/_build/dev/rustler_crates/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.12.0) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.0) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.0) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.0) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
```

**Comment by sami3232** [comment]
I restarted the install. I changed the way I installed elixir. the command I used for elixir was :
```
sudo apt-get install -y --allow-downgrades elixir=1.11.1-1
```
My version of both Erlang and Elixir :
```
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.11.1 (compiled with Erlang/OTP 23)
```
Rust is still there.

After  this command :
```
mix do deps.get, local.rebar --force, deps.compile, compile -y;


Compiling NIF crate :exkeccak (native/exkeccak)...
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (ErlangError) Erlang error: :enoent
    (elixir 1.11.1) lib/system.ex:815: System.cmd("cargo", ["rustc", "--release"], [cd: "/home/ubuntu/blockscout/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/ubuntu/blockscout/_build/dev/rustler_crates/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.11.1) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.11.1) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.1) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.1) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.1) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
```
The issue remains the same.

Is there a command to remove all the changes made by mix ?

**Comment by vbaranov** [comment]
> Is there a command to remove all the changes made by mix ?

`mix clean --deps`
https://hexdocs.pm/mix/Mix.Tasks.Clean.html

**Comment by sami3232** [comment]
The problem was the " permissions " on the blockscout folder. In `sudo` I had this problem but without it, I didn't have the permissions. I put myself in owner and the command was executed.
I guess this issue can be closed.

Thank you for all your answers!

**Comment by jennerwein** [comment]
I have exactly the same problem, although I use the right versions of both Erlang and Elixir. I don't understand the solution of sami232

**Comment by sami3232** [comment]
Well, once I installed the correct versions of Erlang and Elixir and got exactly the same errors I looked for something else.

I have a "bad" habit. I always run everything in `sudo`. If you use this command with sudo, you'll get the error with ex_keccak. 
I put myself as the owner of the whole folder.
Use this command:
```

**Comment by jennerwein** [comment]
Thanks a lot. Now it works
