### ISSUE TITLE
FunctionClauseError: Function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1 with variant Besu

### ISSUE THREAD

**Issue by helderjnpinto** [blockscout/blockscout#4311]
*Describe your issue here.*
Give an error when found revertReason with  no function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1
in variant Besu

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
 Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
 Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Operating System: ubuntu 20
* Blockscout Version/branch: develop

### Steps to reproduce
Just connect to besu node

### Expected behaviour
No fetch error 
### Actual behaviour
Error in variante besu will try fetch parity function 

`
Args: [%{batch: [1806779, 1806739, 2082736, 2082737, 1933740, 1806655, 1806656, 1806659, 1806654, 1934255], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://172.20.1.90:8545/", method_to_url: [eth_getBalance: "http://172.20.1.90:8545/", trace_block: "http://172.20.1.90:8545/", trace_replayTransaction: "http://172.20.1.90:8545/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Besu], metadata: [fetcher: :internal_transaction]}]
2021-06-23T18:32:31.891 fetcher=internal_transaction count=10 [error] Task #PID<0.1592.0> started from Indexer.Fetcher.InternalTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Parity.Trace.entry_to_elixir({"revertReason", "0x"})
    (elixir 1.11.3) lib/enum.ex:1335: anonymous fn/4 in Enum.into/3
    (stdlib 3.13.2) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.3) lib/enum.ex:2209: Enum.into/4
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/besu.ex:114: EthereumJSONRPC.Besu.trace_replay_block_transactions_responses_to_internal_transactions_params/2
    (indexer 0.1.0) lib/indexer/fetcher/internal_transaction.ex:109: Indexer.Fetcher.InternalTransaction.run/2
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [2082650, 2082646, 1806647, 1806643, 1933575, 2078042, 1809877, 1809874, 1807976, 1806771], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://172.20.1.90:8545/", method_to_url: [eth_getBalance: "http://172.20.1.90:8545/", trace_block: "http://172.20.1.90:8545/", trace_replayTransaction: "http://172.20.1.90:8545/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Besu], metadata: [fetcher: :internal_transaction]}]
2021-06-23T18:32:32.164 fetcher=internal_transaction count=10 [error] Task #PID<0.1591.0> started from Indexer.Fetcher.InternalTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Parity.Trace.entry_to_elixir({"revertReason", "0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000017496e76616c696420646973747269627574696f6e206964000000000000000000"})
    (elixir 1.11.3) lib/enum.ex:1335: anonymous fn/4 in Enum.into/3
    (stdlib 3.13.2) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.3) lib/enum.ex:2209: Enum.into/4
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/besu.ex:114: EthereumJSONRPC.Besu.trace_replay_block_transactions_responses_to_internal_transactions_params/2
    (indexer 0.1.0) lib/indexer/fetcher/internal_transaction.ex:109: Indexer.Fetcher.InternalTransaction.run/2
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [1817384, 2080142, 1823090, 1933725, 2077979, 1809599, 1806801, 1806809, 2078062, 2082648], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://172.20.1.90:8545/", method_to_url: [eth_getBalance: "http://172.20.1.90:8545/", trace_block: "http://172.20.1.90:8545/", trace_replayTransaction: "http://172.20.1.90:8545/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Besu], metadata: [fetcher: :internal_transaction]}]
2021-06-23T18:32:32.552 fetcher=internal_transaction count=10 [error] Task #PID<0.1594.0> started from Indexer.Fetcher.InternalTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Parity.Trace.entry_to_elixir({"revertReason", "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001b496e73756666696369656e7420756e7374616b6520616d6f756e740000000000"})
    (elixir 1.11.3) lib/enum.ex:1335: anonymous fn/4 in Enum.into/3
    (stdlib 3.13.2) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.3) lib/enum.ex:2209: Enum.into/4
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/besu.ex:114: EthereumJSONRPC.Besu.trace_replay_block_transactions_responses_to_internal_transactions_params/2
    (indexer 0.1.0) lib/indexer/fetcher/internal_transaction.ex:109: Indexer.Fetcher.InternalTransaction.run/2
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [1934179, 1806640, 2077976, 2077974, 1806666, 2082519, 1934197, 1934164, 1806941, 1806943], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://172.20.1.90:8545/", method_to_url: [eth_getBalance: "http://172.20.1.90:8545/", trace_block: "http://172.20.1.90:8545/", trace_replayTransaction: "http://172.20.1.90:8545/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Besu], metadata: [fetcher: :internal_transaction]}]
`

**Comment by helderjnpinto** [comment]
Hello @vbaranov  all good ? 
How can stop this log of error temporarily until it's fixed?

**Comment by helderjnpinto** [comment]
Just put some related docs: https://besu.hyperledger.org/en/stable/Reference/API-Methods/#trace_transaction

**Comment by helderjnpinto** [comment]
i changed to this temporarelly... it's ok ?

![image](https://user-images.githubusercontent.com/12281088/134667708-bdc4767c-3991-4cec-80b8-109672ea532e.png)

**Comment by DosPuppet** [comment]
Hello, same problem here (besu), and the amount of error log with this error is insane (and impacting server performances...). Tried to modify, but the new last version of blockscout has a different trace.ex, and i can't remove this trace call...

**Comment by damianlluch** [comment]
> i changed to this temporarelly... it's ok ?
> 
> ![image](https://user-images.githubusercontent.com/12281088/134667708-bdc4767c-3991-4cec-80b8-109672ea532e.png)

I think I have the same problem, where did you copy that code from?

**Comment by mfolnovic** [comment]
Just wanted to say this is still happening.

**Comment by mfolnovic** [comment]
This was fixed in latest version with https://github.com/blockscout/blockscout/pull/5303.
