### ISSUE TITLE
The browser returns a duplicate error

### ISSUE THREAD

**Issue by hashpaypie** [blockscout/blockscout#4333]
Branch
git branch
* master

System version
CentOS 7.6

steps
cd expl/blockscout/docker
nohup make start &

The same error is repeated after startup，Finally causes the program to run crashed

Args: [981913, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://127.0.0.1:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2021-07-02T08:42:14.028 [error] Task #PID<0.11534.1> started from Indexer.Block.Realtime.Fetcher terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 127ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

 1. Tracking down slow queries and making sure they are running fast enough
 2. Increasing the pool_size (albeit it increases resource consumption)
 3. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

   (db_connection 2.3.1) lib/db_connection.ex:852: DBConnection.transaction/3
   (ecto 3.5.5) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4
   (stdlib 3.14.1) timer.erl:197: :timer.tc/3
   (explorer 0.0.1) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
   (explorer 0.0.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
   (explorer 0.0.1) lib/explorer/chain/import.ex:330: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
   (elixir 1.11.4) lib/enum.ex:3776: Enumerable.List.reduce/3
   (elixir 1.11.4) lib/enum.ex:2243: Enum.reduce_while/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3

Args: [982092, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://127.0.0.1:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2021-07-02T08:42:14.036 application=indexer fetcher=replaced_transaction [error] failed to update replaced transactions for transactions: %DBConnection.ConnectionError{message: "connection not available and request was dropped from queue after 103ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Tracking down slow queries and making sure they are running fast enough\n  2. Increasing the pool_size (albeit it increases resource consumption)\n  3. Allowing requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n", reason: :queue_timeout, severity: :error}
2021-07-02T08:42:14.123 [error] Task #PID<0.8434.1> started from Indexer.Block.Realtime.Fetcher terminating
** (stop) exited in: GenServer.call(#PID<0.658.0>, {:lock, "block_numbers", #Reference<0.2476929089.1211891718.128969>}, 5000)
** (EXIT) time out
(elixir 1.11.4) lib/gen_server.ex:1027: GenServer.call/3
(con_cache 0.14.0) lib/con_cache/lock.ex:22: ConCache.Lock.exec/4
(indexer 0.1.0) lib/indexer/block/fetcher.ex:188: Indexer.Block.Fetcher.fetch_and_import_range/2
(indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:284: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
(indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
(indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:267: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
(elixir 1.11.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

2021-07-02T08:42:15.210 application=db_connection [info] Postgrex.Protocol (#PID<0.557.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.13745.1> exited
2021-07-02T08:42:15.210 application=db_connection [info] Postgrex.Protocol (#PID<0.593.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.13373.1> exited
2021-07-02T08:42:15.213 application=db_connection [info] Postgrex.Protocol (#PID<0.559.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.13700.1> exited
2021-07-02T08:42:15.213 application=db_connection [info] Postgrex.Protocol (#PID<0.555.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.13399.1> exited
2021-07-02T08:42:15.211 application=db_connection [info] Postgrex.Protocol (#PID<0.590.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.12204.1> exited
{"Kernel pid terminated",application_controller,"{application_terminated,block_scout_web,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,block_scout_web,shutdown})

Crash dump is being written to: erl_crash.dump...done
make: *** [start] Error 1

**Comment by vbaranov** [comment]
@hashpaypie what do you use for the archive node? It is required for running Blockscout. Did you set up env variables before running the application? Could you share the list if so (please hide sensitive information there)?

**Comment by vbaranov** [comment]
Closed due to no user feedback
