### ISSUE TITLE
unknown_key "effectiveGasPrice"

### ISSUE THREAD

**Issue by SaulMoonves** [blockscout/blockscout#4335]
I followed instructions for installing and starting Blockscout but my output is filled with errors.

### Environment

Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.11.2 (compiled with Erlang/OTP 23)
Ubuntu 20.04.2 LTS
Git branch: master, commit: 59e4e1d707e09068c8ca1cf8fd897d8c00f16b71
Geth: 1.10.4-stable-aa637fd3 running archive with debug and txpool turned on, not fully synced though
Network: Ethereum
Subnetwork: Core
Coin: DAI

### Steps to reproduce

Followed install instructions from website, then ran `mix phx.server`

### Expected behaviour

Server should start with no errors.

### Actual behaviour

Log filled with:

```
2021-07-02T15:26:00.341 [error] Task #PID<0.1212.0> started from #PID<0.1209.0> terminating
** (ArgumentError) Could not convert receipt to elixir

Receipt:
  %{"blockHash" => "0xe9d4b14f5da592ed71106e7133538430213fb387e6d0f03c07d2869299f3a33a", "blockNumber" => "0x3b3183", "contractAddress" => nil, "cumulativeGasUsed" => "0x5208", "effectiveGasPrice" => "0x4e3b29200", "from" => "0xea674fdde714fd979de3edf0f56aa9716b898ec8", "gas" => 50000, "gasUsed" => "0x5208", "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "root" => "0x70de4068f845e7e1d942fa35b5c4ea57d6982c27eabc36bf21078e8649960c68", "to" => "0xd89732c8779fc4a287a3b04ee1525066cf03c59a", "transactionHash" => "0xe10ce1a74bd86d2839abb4b27e7dcee0979a93d75865425143a5ccfa9749b593", "transactionIndex" => "0x0", "type" => "0x0"}

Errors:
  {:unknown_key, %{key: "effectiveGasPrice", value: "0x4e3b29200"}}

    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.ok!/2
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.62918258/1 in Indexer.Block.Fetcher.Receipts.fetch/2>, [[%{block_hash: "0xe9d4b14f5da592ed71106e7133538430213fb387e6d0f03c07d2869299f3a33a", block_number: 3879299, from_address_hash: "0xea674fdde714fd979de3edf0f56aa9716b898ec8", gas: 50000, gas_price: 21000000000, hash: "0xe10ce1a74bd86d2839abb4b27e7dcee0979a93d75865425143a5ccfa9749b593", index: 0, input: "0x", nonce: 2079334, r: 47677698855571468023821433207453323443896317683510451428295409027441168789182, s: 46640621931721806794464559577936679905075810990345407603197987204466407224218, to_address_hash: "0xd89732c8779fc4a287a3b04ee1525066cf03c59a", transaction_index: 0, v: 37, value: 99624483384746134}, %{block_hash: "0xe9d4b14f5da592ed71106e7133538430213fb387e6d0f03c07d2869299f3a33a", block_number: 3879299, from_address_hash: "0xea674fdde714fd979de3edf0f56aa9716b898ec8", gas: 50000, gas_price: 21000000000, hash: "0x697184c8a7259cd23dcb573f838dd396363c3681a29b658d2e3d882394c9500f", index: 1, input: "0x", nonce: 2079335, r: 89208269728759388342395369492758834034308448335857533349189176426289806379174, s: 43145794021057713542310950176443869995044869887880947286974050147623121739633, to_address_hash: "0x0bca1e71e038a06af7159c0d4fa0f02e58ec118b", transaction_index: 1, v: 38, value: 103142338400040776}]]]
2021-07-02T15:26:00.351 [error] Task #PID<0.1204.0> started from #PID<0.1199.0> terminating
```

**Comment by DosPuppet** [comment]
Same here. Can't find any solution to this...

**Comment by DosPuppet** [comment]
Same, but client is besu, and consensus is clique. everything runs smooth until a transaction passes then this specific block is not added, transaction not seen and logs explode with this error...
```
Errors:
  {:unknown_key, %{key: "effectiveGasPrice", value: "0x0"}}

    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.ok!/2
    (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.13257.1>, {%ArgumentError{message: "Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0x9973a4759a528b9b652d0f4a700818ef4897f7da8b30b63f5f68128f103424a4\", \"blockNumber\" => \"0x33\", \"contractAddress\" => nil, \"cumulativeGasUsed\" => \"0x5208\", \"effectiveGasPrice\" => \"0x0\", \"from\" => \"0x2baf30f02598bdfee543d1cdaf3f358d66029129\", \"gas\" => 21000, \"gasUsed\" => \"0x5208\", \"logs\" => [], \"logsBloom\" => \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\", \"status\" => \"0x1\", \"to\" => \"0xb820edaf7842984ecf9dbd8b6244265cb074a408\", \"transactionHash\" => \"0xd7fc32ff0e1f3aec8775a34218ef24cccb80c635e93b64471d6a452d9c78ffea\", \"transactionIndex\" => \"0x0\"}\n\nErrors:\n  {:unknown_key, %{key: \"effectiveGasPrice\", value: \"0x0\"}}\n"}, [{EthereumJSONRPC.Receipt, :ok!, 2, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 236]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1399]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 138]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
State: %Indexer.Block.Catchup.Sequence{bound_queue: %Indexer.BoundQueue{maximum_size: nil, queue: {[], []}, size: 0}, current: nil, step: -10}
2021-07-06T14:45:10.375 [error] Task #PID<0.13273.1> started from #PID<0.13270.1> terminating
** (ArgumentError) Could not convert receipt to elixir

Receipt:
  %{"blockHash" => "0x9973a4759a528b9b652d0f4a700818ef4897f7da8b30b63f5f68128f103424a4", "blockNumber" => "0x33", "contractAddress" => nil, "cumulativeGasUsed" => "0x5208", "effectiveGasPrice" => "0x0", "from" => "0x2baf30f02598bdfee543d1cdaf3f358d66029129", "gas" => 21000, "gasUsed" => "0x5208", "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status" => "0x1", "to" => "0xb820edaf7842984ecf9dbd8b6244265cb074a408", "transactionHash" => "0xd7fc32ff0e1f3aec8775a34218ef24cccb80c635e93b64471d6a452d9c78ffea", "transactionIndex" => "0x0"}
```

**Comment by stasionok** [comment]
last geth from ubuntu PPA:  1.10.4
Same issue when start from docker.

**Comment by thanachaiTP** [comment]
I tested with docker ethereum/client-go:v1.10.1 and blockscout-3.7.0 fixed unknown_key "effectiveGasPrice" issue.
