### ISSUE TITLE
Address transactions query request timeout

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4340]
Address transactions query request timeout is not handled and performance of the query should be improved:

<img width="932" alt="Screenshot 2021-07-05 at 13 17 26" src="https://user-images.githubusercontent.com/4341812/124456429-591dfa80-dd93-11eb-9191-a496976488f2.png">

```
Request: GET /address/0x523B6539Ff08d72A6C8Bb598Af95bF50c1EA839C/transactions?type=JSON
** (exit) an exception was raised:
    ** (RuntimeError) Query fetching address transactions timed out.
        (explorer 0.0.1) lib/explorer/chain.ex:530: anonymous fn/1 in Explorer.Chain.wait_for_address_transactions/1
        (elixir 1.11.4) lib/enum.ex:3433: Enum.flat_map_list/2
        (explorer 0.0.1) lib/explorer/chain.ex:382: Explorer.Chain.transactions_with_rewards_results/3
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_transaction_controller.ex:47: BlockScoutWeb.AddressTransactionController.index/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_transaction_controller.ex:1: BlockScoutWeb.AddressTransactionController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_transaction_controller.ex:1: BlockScoutWeb.AddressTransactionController.phoenix_controller_pipeline/2
        (phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.6) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
```

**Comment by cen1** [comment]
I noticed a slight improvement of this issue by increasing the postgres work_mem after seeing that the query was doing sorts on disk in explain analyze. In my case the size of tmp file was around 8MB so I increased to 20MB `set work_mem = "20MB";`
