### ISSUE TITLE
issues with ganache type websocket connection on private chain 

### ISSUE THREAD

**Issue by moda20** [blockscout/blockscout#4372]
I am having  an issue with the websocket connection with ganache when running blockscout. 
the error is the following : 
```
2021-07-11T16:54:23.701785444Z 2021-07-11T16:54:23.698 fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating
2021-07-11T16:54:23.701875445Z ** (stop) exited in: GenServer.call(Indexer.Block.Realtime.WebSocket, {:subscribe, "newHeads", []}, 5000)
2021-07-11T16:54:23.701884185Z     ** (EXIT) time out
2021-07-11T16:54:23.701888473Z     (elixir 1.11.4) lib/gen_server.ex:1027: GenServer.call/3
2021-07-11T16:54:23.701892755Z     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:150: Indexer.Block.Realtime.Fetcher.subscribe_to_new_heads/2
2021-07-11T16:54:23.701897240Z     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:73: Indexer.Block.Realtime.Fetcher.handle_continue/2
2021-07-11T16:54:23.701901561Z     (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
2021-07-11T16:54:23.701905794Z     (stdlib 3.14.1) gen_server.erl:431: :gen_server.loop/7
2021-07-11T16:54:23.701909920Z     (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-07-11T16:54:23.701914303Z Last message: {:continue, {:init, [transport: EthereumJSONRPC.WebSocket, transport_options: %EthereumJSONRPC.WebSocket{url: "ws://ganache_node:8545", web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %EthereumJSONRPC.WebSocket.WebSocketClient.Options{event: nil, params: nil, web_socket: Indexer.Block.Realtime.WebSocket}}]}}
2021-07-11T16:54:23.701939754Z State: %Indexer.Block.Realtime.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://ganache_node:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Ganache], receipts_batch_size: 250, receipts_concurrency: 10}, max_number_seen: nil, previous_number: nil, subscription: nil, timer: nil}
```

I also found out that what causes the timeouts is blockscout itself as, apparently, it overwhelms the node with requests and subscription requests after WS timeouts causing the node to stop sending transactions and mini them. 

is this a known issue ? how can i fix it ?

the error seems to be a timeout on connections. 

### Environment

* Operating System: linux ubuntu 20
* Blockscout Version/branch: master

### Expected behaviour

Connects to websocket and fills the necessary information on the explorer page.

### Actual behaviour

having an error and not showing blocks or transactions on the explorer page

**Comment by vbaranov** [comment]
You can simply unset `ETHEREUM_JSONRPC_WS_URL`. It is optional.
