### ISSUE TITLE
Seeing baseFeePerGas (London fork) specific elixir errors on master

### ISSUE THREAD

**Issue by sidhujag** [blockscout/blockscout#4461]
```
2021-07-29T22:02:09.942 application=indexer fetcher=block_catchup first_block_number=67 last_block_number=58 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"baseFeePerGas", "0x867e9"})
    (elixir 1.11.4) lib/enum.ex:1335: anonymous fn/4 in Enum.into/3
    (stdlib 3.14.1) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.4) lib/enum.ex:2209: Enum.into/4
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
```

I am seeing this error specifically around baseFeePerGas which was put in as part of London.
### Environment

Master
Linux Alpine

### Steps to reproduce

Launch against London fork enabled chain

**Comment by vbaranov** [comment]
Fixed in https://github.com/blockscout/blockscout/pull/4486
