### ISSUE TITLE
cardinality_violation: ON CONFLICT DO UPDATE command cannot affect row a second time

### ISSUE THREAD

**Issue by jlochman** [blockscout/blockscout#4474]
Blockscout is unable to sync some blocks of our blockchain. As a blockchain solution, we are using Hyperledger Besu. This error is very sporadical - I cannot say for which blocks error happens and which blocks are processed without any problem.

Looking at the stack trace, some duplicate rows are inserted into DB in a single DB transaction.

```
2021-08-02T14:30:31.746 application=explorer fetcher=block_catchup first_block_number=780759 last_block_number=780750 import_id=113162 transaction_id=106949 [error] Could not insert all of chunk into Elixir.Explorer.Chain.Address.CoinBalance using options because of error.
Chunk Size: 23
Chunk:
[%{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<22, 175, 168, 237, 153, 18, 192, 180, 77, 27, 191, 132, 1, 225, 234, 20, 219, 6, 224, 163>>}, block_number: 780750, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<22, 175, 168, 237, 153, 18, 192, 180, 77, 27, 191, 132, 1, 225, 234, 20, 219, 6, 224, 163>>}, block_number: 780753, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<22, 175, 168, 237, 153, 18, 192, 180, 77, 27, 191, 132, 1, 225, 234, 20, 219, 6, 224, 163>>}, block_number: 780754, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<22, 175, 168, 237, 153, 18, 192, 180, 77, 27, 191, 132, 1, 225, 234, 20, 219, 6, 224, 163>>}, block_number: 780758, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<124, 113, 34, 219, 146, 250, 172, 186, 56, 77, 20, 216, 162, 98, 1, 209, 115, 5, 18, 59>>}, block_number: 780751, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<124, 113, 34, 219, 146, 250, 172, 186, 56, 77, 20, 216, 162, 98, 1, 209, 115, 5, 18, 59>>}, block_number: 780755, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<124, 113, 34, 219, 146, 250, 172, 186, 56, 77, 20, 216, 162, 98, 1, 209, 115, 5, 18, 59>>}, block_number: 780759, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<174, 209, 84, 66, 53, 144, 115, 174, 28, 232, 154, 130, 70, 6, 176, 75, 51, 19, 250, 21>>}, block_number: 780753, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<174, 209, 84, 66, 53, 144, 115, 174, 28, 232, 154, 130, 70, 6, 176, 75, 51, 19, 250, 21>>}, block_number: 780753, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<182, 219, 200, 71, 47, 112, 194, 217, 173, 34, 103, 232, 235, 193, 19, 87, 53, 227, 89, 189>>}, block_number: 780752, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<182, 219, 200, 71, 47, 112, 194, 217, 173, 34, 103, 232, 235, 193, 19, 87, 53, 227, 89, 189>>}, block_number: 780756, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780750, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780751, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780752, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780753, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780754, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780755, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780756, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780757, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780758, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<189, 1, 60, 244, 63, 180, 1, 79, 37, 231, 75, 151, 190, 91, 233, 17, 231, 64, 236, 113>>}, block_number: 780759, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<242, 214, 47, 215, 66, 232, 209, 61, 144, 91, 79, 238, 236, 15, 19, 22, 22, 55, 24, 78>>}, block_number: 780753, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<242, 214, 47, 215, 66, 232, 209, 61, 144, 91, 79, 238, 236, 15, 19, 22, 22, 55, 24, 78>>}, block_number: 780757, inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}]
Options:
[conflict_target: [:address_hash, :block_number], on_conflict: #Ecto.Query<from c0 in Explorer.Chain.Address.CoinBalance, where: fragment("EXCLUDED.value IS NOT NULL") and (is_nil(c0.value_fetched_at) or fragment("EXCLUDED.value_fetched_at > ?", c0.value_fetched_at)), update: [set: [value: fragment("CASE WHEN EXCLUDED.value IS NOT NULL AND (? IS NULL OR EXCLUDED.value_fetched_at > ?) THEN\n       EXCLUDED.value\n     ELSE\n       ?\nEND\n", c0.value_fetched_at, c0.value_fetched_at, c0.value), value_fetched_at: fragment("CASE WHEN EXCLUDED.value IS NOT NULL AND (? IS NULL OR EXCLUDED.value_fetched_at > ?) THEN\n       EXCLUDED.value_fetched_at\n     ELSE\n       ?\nEND\n", c0.value_fetched_at, c0.value_fetched_at, c0.value_fetched_at), inserted_at: fragment("LEAST(EXCLUDED.inserted_at, ?)", c0.inserted_at), updated_at: fragment("GREATEST(EXCLUDED.updated_at, ?)", c0.updated_at)]]>, timeout: 60000, timestamps: %{inserted_at: ~U[2021-08-02 14:30:31.726323Z], updated_at: ~U[2021-08-02 14:30:31.726323Z]}]
Exception:
** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time
    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:660: Ecto.Adapters.SQL.insert_all/8
    (ecto 3.5.5) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6
    (explorer 0.0.1) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:299: Explorer.Chain.Import.insert_changes_list/3
    (explorer 0.0.1) lib/explorer/chain/import/runner/address/coin_balances.ex:78: Explorer.Chain.Import.Runner.Address.CoinBalances.insert/3
    (ecto 3.5.5) lib/ecto/multi.ex:646: Ecto.Multi.apply_operation/5
2021-08-02T14:30:31.750 application=indexer fetcher=block_catchup first_block_number=780759 last_block_number=780750 [error] ** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time
    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:660: Ecto.Adapters.SQL.insert_all/8
    (ecto 3.5.5) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6
    (explorer 0.0.1) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:299: Explorer.Chain.Import.insert_changes_list/3
    (explorer 0.0.1) lib/explorer/chain/import/runner/address/coin_balances.ex:78: Explorer.Chain.Import.Runner.Address.CoinBalances.insert/3
    (ecto 3.5.5) lib/ecto/multi.ex:646: Ecto.Multi.apply_operation/5
Retrying.
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.11.4 (compiled with Erlang/OTP 21)
* Operating System: Ubuntu 18.04.5 LTS
* Blockscout Version/branch: 3.7.2. (commit bc737bd7ad6ee5741c83452d3f5f13a0d8b032e0)
* Hyperledger Besu: besu-21.1.6-SNAPSHOT
* http://explorer.mainnet.xixoio.com:4004/

### Steps to reproduce

This is next to impossible to define. I'd need to define an instance of Besu, all of the executed transactions...

### Expected behaviour

Blockscout should sync blockchain without any problem.

### Actual behaviour

Sync is stuck at some blocks.

**Comment by vbaranov** [comment]
Please check with the latest version of Blockscout. If the issue is still reproducible, please open a new issue.
