### ISSUE TITLE
Contract verification: expected at most one result but got 6 in query

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4716]
```
2021-10-03T18:49:44.681 [error] Task #PID<0.4551.32> started from #PID<0.4493.32> terminating
** (Ecto.MultipleResultsError) expected at most one result but got 6 in query:

from t0 in Explorer.Chain.Transaction,
  left_join: a1 in Explorer.Chain.Address,
  on: t0.created_contract_address_hash == a1.hash,
  where: t0.created_contract_address_hash == ^"0x525127C1F5670cc102B26905DcCF8245C05c164f",
  select: %{init: t0.input, created_contract_code: a1.contract_code}

    (ecto 3.7.1) lib/ecto/repo/queryable.ex:149: Ecto.Repo.Queryable.one/3
    (explorer 0.0.1) lib/explorer/chain.ex:3899: Explorer.Chain.smart_contract_creation_tx_bytecode/1
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/verifier.ex:109: Explorer.SmartContract.Solidity.Verifier.compare_bytecodes/6
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/verifier.ex:49: anonymous fn/4 in Explorer.SmartContract.Solidity.Verifier.evaluate_authenticity/2
    (elixir 1.12.2) lib/enum.ex:4280: Enumerable.List.reduce/3
    (elixir 1.12.2) lib/enum.ex:2431: Enum.reduce_while/3
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/publisher.ex:30: Explorer.SmartContract.Solidity.Publisher.publish/3
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/publisher_worker.ex:13: Explorer.SmartContract.Solidity.PublisherWorker.perform/1
Function: #Function<3.131974459/0 in Que.Job.perform/1>
    Args: []
```

**Comment by royki** [comment]
Hi @vbaranov,
We are facing similar issue - and smart contract is not verifying and the `Verify & publish` button always showing `Loading`
`[Que] Failed Job # 7 with Explorer.SmartContract.PublisherWorker`
![image](https://user-images.githubusercontent.com/1545990/146387093-589ee96c-3280-4484-a407-957f93bc41e9.png)

```sql
from t0 in Explorer.Chain.Transaction,
blockscout_1  |   where: t0.created_contract_address_hash == ^"0x17623C6dF0E9Cb06Bf64364588eBB057b0ea43C6",
blockscout_1  |   select: t0.input
blockscout_1  | 
blockscout_1  |     (ecto 3.5.5) lib/ecto/repo/queryable.ex:152: Ecto.Repo.Queryable.one/3
blockscout_1  |     (explorer 0.0.1) lib/explorer/chain.ex:3588: Explorer.Chain.smart_contract_creation_tx_bytecode/1
blockscout_1  |     (explorer 0.0.1) lib/explorer/smart_contract/verifier.ex:109: Explorer.SmartContract.Verifier.compare_bytecodes/6
blockscout_1  |     (explorer 0.0.1) lib/explorer/smart_contract/verifier.ex:49: anonymous fn/4 in Explorer.SmartContract.Verifier.evaluate_authenticity/2
blockscout_1  |     (elixir 1.11.4) lib/enum.ex:3776: Enumerable.List.reduce/3
blockscout_1  |     (elixir 1.11.4) lib/enum.ex:2243: Enum.reduce_while/3
blockscout_1  |     (explorer 0.0.1) lib/explorer/smart_contract/publisher.ex:30: Explorer.SmartContract.Publisher.publish/3
blockscout_1  |     (explorer 0.0.1) lib/explorer/smart_contract/publisher_worker.ex:13: Explorer.SmartContract.PublisherWorker.perform/1
blockscout_1  | Function: #Function<3.79678554/0 in Que.Job.perform/1>
blockscout_1  |     Args: []
blockscout_1  | 2021-12-16T13:16:46.902 application=que [info] [Que] Failed Job # 7 with Explorer.SmartContract.PublisherWorker
blockscout_1  | 2021-12-16T13:16:47.580 application=plug request_id=FsE-oqMOpXHYtnsALs7F [info] GET /
blockscout_1  | 2021-12-16T13:16:47.585 application=plug request_id=FsE-oqMOpXHYtnsALs7F [info] Sent 200 in 5ms
blockscout_1  | 2021-12-16T13:16:48.324 application=plug request_id=FsE-os9l7cpmBZMAQldh [info] POST /api
blockscout_1  | 2021-12-16T13:16:48.325 application=plug request_id=FsE-os9l7cpmBZMAQldh [info] Sent 200 in 245µs
blockscout_1  | 2021-12-16T13:16:48.600 application=plug request_id=FsE-ot_ZivZvrh0AQlfh [info] GET /address/0xBCC3f0c116CB7e98aD4fd981058Dd047756574f2/token-balances
blockscout_1  | 2021-12-16T13:16:48.603 application=plug request_id=FsE-ot_ZivZvrh0AQlfh [info] Sent 200 in 2ms
blockscout_1  | 2021-12-16T13:16:51.023 application=phoenix [info] CONNECTED TO BlockScoutWeb.UserSocket in 499µs
blockscout_1  |   Transport: :websocket
blockscout_1  |   Serializer: Phoenix.Socket.V2.JSONSerializer
```

**Comment by fenQY** [comment]
I had the same problem
