### ISSUE TITLE
Error in calling contract method with bytes[] input data

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4863]
https://blockscout.com/lukso/l14/address/0x148393cd92333A9d3E016B61aFEea19D461B2546/read-contract

`getData` method with input data: `0xeafec4d89fa9619884b6b89135626455000000000000000000000000abe425d6`

<img width="758" alt="Screenshot 2021-11-05 at 00 46 44" src="https://user-images.githubusercontent.com/4341812/140491961-51f2d0ff-bdff-46ee-b954-798ca6fd6eac.png">

**Comment by vbaranov** [comment]
@nikitosing

<img width="879" alt="Screenshot 2021-12-29 at 14 22 39" src="https://user-images.githubusercontent.com/4341812/147657303-7502bd36-02a0-4ec3-8c3f-0687f354723e.png">

```
Request: GET /smart-contracts?hash=0x148393cd92333a9d3e016b61afeea19d461b2546&type=regular&action=read
** (exit) an exception was raised:
    ** (BadMapError) expected a map, got: nil
        (elixir 1.12.2) lib/map.ex:464: Map.get(nil, :method_id, nil)
        (explorer 0.0.1) lib/explorer/smart_contract/reader.ex:302: anonymous fn/1 in Explorer.SmartContract.Reader.get_abi_with_method_id/1
        (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
        (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
        (explorer 0.0.1) lib/explorer/smart_contract/reader.ex:231: Explorer.SmartContract.Reader.read_only_functions/1
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:38: BlockScoutWeb.SmartContractController.index/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
```

**Comment by vbaranov** [comment]
The issue was resolved and patch deployed to Lukso L14 instance.
