### ISSUE TITLE
Explorer.Chain.fetch_omni_bridged_tokens_metadata: ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4932]
```
** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

from i0 in Explorer.Chain.InternalTransaction,
  join: t1 in assoc(i0, :transaction),
  where: i0.created_contract_address_hash == ^%Explorer.Chain.Hash{byte_count: 20, bytes: <<92, 113, 137, 55, 178, 215, 68, 38, 36, 178, 196, 93, 180, 85, 47, 40, 170, 142, 21, 190>>},
  where: t1.status == ^1

    (ecto 3.7.1) lib/ecto/repo/queryable.ex:149: Ecto.Repo.Queryable.one/3
    (explorer 0.0.1) lib/explorer/chain.ex:4913: anonymous fn/1 in Explorer.Chain.fetch_omni_bridged_tokens_metadata/1
    (elixir 1.12.2) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (explorer 0.0.1) lib/explorer/chain.ex:4902: Explorer.Chain.fetch_omni_bridged_tokens_metadata/1
    (indexer 0.1.0) lib/indexer/set_omni_bridged_metadata_for_tokens.ex:50: Indexer.SetOmniBridgedMetadataForTokens.fetch_omni_bridged_tokens_metadata/1
    (indexer 0.1.0) lib/indexer/set_omni_bridged_metadata_for_tokens.ex:37: Indexer.SetOmniBridgedMetadataForTokens.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
Last message: :reveal_unprocessed_tokens
State: %{interval: 1200000}
```

**Comment by vbaranov** [comment]
Resolved by updating Nethermind archive node to v1.12.3
