### ISSUE TITLE
Exceptions thrown when running with GoQuorum  {:unknown_key, %{key: "isPrivacyMarkerTransaction", value: false}}

### ISSUE THREAD

**Issue by joshuafernandes** [blockscout/blockscout#4995]
*Describe your issue here.*

Running Blockscout with GoQuorum appears to throw the below error and additionally not pull in tx data.

```2021-12-09T02:40:49.032 [error] Task #PID<0.2471.0> started from #PID<0.2468.0> terminating
** (ArgumentError) Could not convert receipt to elixir

Receipt:
  %{"blockHash" => "0x64c2ecacd70c962e56bc53146243fe7bf1c9ce26dbaef5e9cdeef9260a2fcc1a", "blockNumber" => "0x18", "contractAddress" => "0x845e817a37eff8c66bf344e677fe590b815f5b70", "cumulativeGasUsed" => "0x24a09", "from" => "0xc6ef791a4a4a594550b6fef3f84eb1a7da7a582a", "gas" => 150050, "gasUsed" => "0x24a09", "isPrivacyMarkerTransaction" => false, "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status" => "0x1", "to" => nil, "transactionHash" => "0xa54f72ded2878a355ca9e33e5f8ac3680905bee78def7bd5a3292f11948d1800", "transactionIndex" => "0x0"}

Errors:
  {:unknown_key, %{key: "isPrivacyMarkerTransaction", value: false}}

    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.ok!/2
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.124558711/1 in Indexer.Block.Fetcher.Receipts.fetch/2>, [[%{block_hash: "0x64c2ecacd70c962e56bc53146243fe7bf1c9ce26dbaef5e9cdeef9260a2fcc1a", block_number: 24, from_address_hash: "0xc6ef791a4a4a594550b6fef3f84eb1a7da7a582a", gas: 150050, gas_price: 0, hash: "0xa54f72ded2878a355ca9e33e5f8ac3680905bee78def7bd5a3292f11948d1800", index: 0, input: "0x60806040523480156100115760006000fd5b50604051610173380380610173833981810160405260208110156100355760006000fd5b81019080805190602001909291905050505b8060006000508190909055505b5061005a565b61010a806100696000396000f3fe608060405234801560105760006000fd5b506004361060405760003560e01c80632a1afcd914604657806360fe47b11460625780636d4ce63c14608e576040565b60006000fd5b604c60aa565b6040518082815260200191505060405180910390f35b608c6004803603602081101560775760006000fd5b810190808035906020019092919050505060b3565b005b609460c3565b6040518082815260200191505060405180910390f35b60006000505481565b8060006000508190909055505b50565b6000600060005054905060d1565b9056fea2646970667358221220ce3d5ba3b8342783b15340319795a6f6f6949230edf734ceb649f63aa646190764736f6c63430007060033000000000000000000000000000000000000000000000000000000000000002f", nonce: 0, r: 42226902986165597709670224709902404430850545176011800228385198121287816970455, s: 4244835235057198668342741649788679031235843481711455264564154223226409178217, to_address_hash: nil, transaction_index: 0, v: 2710, value: 0}, %{block_hash: "0x00e910332770fa0e92a4c5e837f99f6fad0435a1a664484b619097734208c99f", block_number: 25, from_address_hash: "0xf0e2db6c8dc6c681bb5d6ad121a107f300e9b2b5", gas: 150050, gas_price: 0, hash: "0x2054237d237f110a66b949685144189cfc30c8ad4f961b6c3e6e7730bd895ff3", index: 0, input: "0x60fe47b1000000000000000000000000000000000000000000000000000000000000007b", nonce: 0, r: 97796527851762583500372338503727110443983934516265183606689518122106203946242, s: 28957927624000430651150535346513837125112458475259998055022436957001573112212, to_address_hash: "0x845e817a37eff8c66bf344e677fe590b815f5b70", transaction_index: 0, v: 2710, value: 0}]]]
2021-12-09T02:40:49.035 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({%ArgumentError{message: "Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0x64c2ecacd70c962e56bc53146243fe7bf1c9ce26dbaef5e9cdeef9260a2fcc1a\", \"blockNumber\" => \"0x18\", \"contractAddress\" => \"0x845e817a37eff8c66bf344e677fe590b815f5b70\", \"cumulativeGasUsed\" => \"0x24a09\", \"from\" => \"0xc6ef791a4a4a594550b6fef3f84eb1a7da7a582a\", \"gas\" => 150050, \"gasUsed\" => \"0x24a09\", \"isPrivacyMarkerTransaction\" => false, \"logs\" => [], \"logsBloom\" => \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\", \"status\" => \"0x1\", \"to\" => nil, \"transactionHash\" => \"0xa54f72ded2878a355ca9e33e5f8ac3680905bee78def7bd5a3292f11948d1800\", \"transactionIndex\" => \"0x0\"}\n\nErrors:\n  {:unknown_key, %{key: \"isPrivacyMarkerTransaction\", value: false}}\n"}, [{EthereumJSONRPC.Receipt, :ok!, 2, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 236]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1582]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 138]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}). Restarting
```

![image](https://user-images.githubusercontent.com/3722503/145330994-2f0e2b0d-8747-4c12-843e-dcfbc469e85e.png)

### Environment

* Operating System: Ubuntu via docker compose
* Blockscout Version/branch: v4.0.0-beta

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

1. Run the [quorum-dev-quickstart](https://docs.goquorum.consensys.net/en/stable/Tutorials/Quorum-Dev-Quickstart/Using-the-Quickstart/) v 0.0.47 and higher
`npx quorum-dev-quickstart`

Select options: goQuroum and `y` for privacy and blockscout, `n`  for the rest

2. When the network starts up give it a couple of mins for blockscout to come live on `localhost:26000`
3. Run a transaction like so:
```
cd smart_contracts
npm i
node scripts/public_tx.js
```
The tx will go through and the result is the above

### Expected behaviour

Expected behaviour is that blockscout accepts the parameter and shows the block and transaction in the UI

### Actual behaviour
Errors are thrown and blocks and txs for that block aren't populated

**Comment by vbaranov** [comment]
GoQuorum is not supported by default. You can add all specific extra fields in the transaction receipt response something like this:
```
  # GoQuorum specific transaction receipt fields
  defp entry_to_elixir({key, _}) when key in ~w(isPrivacyMarkerTransaction) do
    :ignore
  end
```

and you can place it, for instance after:
https://github.com/blockscout/blockscout/blob/88f5ac6d733afb363773f68166a06e252296ff37/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex#L302-L305

**Comment by kth-tw** [comment]
Is #5302 fix this issue ?

**Comment by vbaranov** [comment]
@kth-tw yes, it should.
