### ISSUE TITLE
[error] ** (MatchError) no match of right hand side value

### ISSUE THREAD

**Issue by anshengme** [blockscout/blockscout#5028]
I deployed a private ETH genesis node locally, blockscout will have the following errors when running

```
Retrying.
2021-12-22T03:36:02.930 application=indexer fetcher=block_catchup first_block_number=87 last_block_number=78 [error] ** (MatchError) no match of right hand side value: <<216, 131, 1, 10, 13, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 49, 55, 46, 50, 133, 108, 105, 110, 117, 120>>
    (indexer 0.1.0) lib/indexer/transform/blocks.ex:78: Indexer.Transform.Blocks.recover_pub_key/2
    (indexer 0.1.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:132: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:205: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

The blockscout run command is as follows

```bash
cd blockscout/docker/

COIN=ETH \
ETHEREUM_JSONRPC_VARIANT=geth \
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545 \
ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546 \
make start
```

please help me.

**Comment by vbaranov** [comment]
You should also set `BLOCK_TRANSFORMER=clique` if you're using Clique proof-of-authority consensus protocol

**Comment by anshengme** [comment]
Hi @vbaranov , thanks for the reply, I tried it and it still doesn't work.

Start the blockscout command

```
COIN=ETH \
ETHEREUM_JSONRPC_VARIANT=geth \
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545 \
ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546 \
BLOCK_TRANSFORMER=clique \
make start
```

This is the configuration of the genesis node

```bash
$ cat /data/genesis.json
{
   "config":{
      "chainId":9,
      "homesteadBlock":0,
      "eip150Block":0,
      "eip155Block":0,
      "eip158Block":0,
      "byzantiumBlock":0,
      "constantinopleBlock":0,
      "petersburgBlock":0,
      "istanbulBlock":0
   },
   "alloc":{},
   "coinbase":"0x0000000000000000000000000000000000000000",
   "difficulty":"0x20000",
   "extraData":"",
   "gasLimit":"0x2fefd8",
   "nonce":"0x0000000000000042",
   "mixhash":"0x0000000000000000000000000000000000000000000000000000000000000000",
   "parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000",
   "timestamp":"0x00"
}
```

The following are the startup parameters

```bash
$ cat /data/node3/run.sh
geth --snapshot=false --nousb \
     --identity "node3" \
     --networkid 9 \
     --datadir /data/node3/data \
     --cache 2048 \
     --allow-insecure-unlock \
     --http \
     --http.addr 0.0.0.0 \
     --http.api admin,debug,web3,eth,txpool,personal,ethash,miner,net \
     --ws \
     --ws.addr 0.0.0.0 \
     --ws.api admin,debug,web3,eth,txpool,personal,ethash,miner,net \
     --ws.origins "*" \
     --http.corsdomain "*" >> /data/node3.log 2>&1
```

**Comment by vbaranov** [comment]
@anshengme please try replacing 
```
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545 \
ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546 \
```

with

```
ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545 \
ETHEREUM_JSONRPC_WS_URL=ws://host.docker.internal:8546 \
```

**Comment by vbaranov** [comment]
I am closing this due to no response. Please open again, if the last comment didn't help.

**Comment by whoo** [comment]
Hi,
I've got the same issue with fresh docker install.
```
    environment:
      -  ETHEREUM_JSONRPC_VARIANT=geth
      -  BLOCK_TRANSFORMER=clique
      -  ETHEREUM_JSONRPC_HTTP_URL=http://172.21.20.22:8545/
      -  DATABASE_URL=postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      -  ECTO_USE_SSL="false"
```
Network connection working >> many trace in tcpdump.

```
blockscout    | 2022-03-26T23:47:07.466 application=indexer fetcher=block_catchup first_block_number=5160 last_block_number=5151 [error] ** (MatchError) no match of right hand side value: <<216, 131, 1, 10, 16, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 49, 55, 46, 52, 133, 108, 105, 110, 117, 120>>
blockscout    |     (indexer 0.1.0) lib/indexer/transform/blocks.ex:78: Indexer.Transform.Blocks.recover_pub_key/2
blockscout    |     (indexer 0.1.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout    |     (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
blockscout    |     (indexer 0.1.0) lib/indexer/block/fetcher.ex:132: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout    |     (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:205: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout    |     (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
blockscout    |     (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
blockscout    |     (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by vbaranov** [comment]
@whoo could you share a command to run Geth node and genesis.json in order to reproduce the issue?

**Comment by whoo** [comment]
geth init --datadir /mine/genesis.json
```
{
   "config": {
      "chainId": 3333,
      "homesteadBlock": 0,
      "eip155Block": 0,
      "eip158Block": 0,
      "eip150Block": 0,
      "byzantiumBlock": 0
   },
   "difficulty": "1000",
   "gasLimit": "20000000",
   "alloc": {}
}
```
# after creating personnal.account

/go/bin/geth --datadir /mine --networkid 3333 --http.api=personal,eth,net,web3,txpool --allow-insecure-unlock --http.corsdomain * -http -http.addr 0.0.0.0 -http.vhosts * --mine --miner.threads 1
