### ISSUE TITLE
Contract read page: no function clause matching in Base.encode16/2

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#5062]
```
Request: GET /smart-contracts?hash=0x3b3887242f423c472044246bc06b55e4dc632aae&type=regular&action=read
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Base.encode16/2
        (elixir 1.12.2) lib/base.ex:271: Base.encode16(nil, [case: :lower])
        (explorer 0.0.1) lib/explorer/smart_contract/reader.ex:305: anonymous fn/1 in Explorer.SmartContract.Reader.get_abi_with_method_id/1
        (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
        (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
        (explorer 0.0.1) lib/explorer/smart_contract/reader.ex:231: Explorer.SmartContract.Reader.read_only_functions/1
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:38: BlockScoutWeb.SmartContractController.index/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
```

**Comment by vbaranov** [comment]
Resolved
