### ISSUE TITLE
Improve Logging During Contract Verification

### ISSUE THREAD

**Issue by jtbeckman** [blockscout/blockscout#5095]
Please improve logging during contract verification.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): `1.12.3-otp-24` and `24.1`, respectively
* Operating System: We use Docker images built from ./docker/Dockerfile, so bitwalker/alpine-elixir-phoenix:1.12. This runs on a host that runs an Amazon Linux 2 golden image.
* Blockscout Version/branch: v4.0.0-beta

### Steps to reproduce

When a user verifies a contract via (`/address/0x.../verify-via-flattened-code/new`), the logging doesn't provide much feedback to diagnose any issues or to confirm that contract was verified. Given the logs below, I am to believe that the contract was verified successfully, but the UI does not reflect that.

```
2022-01-04T20:41:21.920 application=plug request_id=c0e3320e5fa586bbf4264060ac91c00c [info] POST /verify_smart_contract/contract_verifications
2022-01-04T20:41:21.929 application=que [info] [Que] Spawning Server for worker: Explorer.SmartContract.Solidity.PublisherWorker
2022-01-04T20:41:21.929 application=que [info] [Que] Queued new Job for Explorer.SmartContract.Solidity.PublisherWorker
2022-01-04T20:41:21.930 application=que [info] [Que] Starting Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker
warning: Supervisor.start_child/2 with a list of args is deprecated, please use DynamicSupervisor instead
  (elixir 1.12.2) lib/supervisor.ex:826: Supervisor.start_child/2
  (que 0.10.1) lib/que/server_supervisor.ex:48: Que.ServerSupervisor.add/2
  (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:55: BlockScoutWeb.AddressContractVerificationController.create/2
  (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.action/2
  (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.phoenix_controller_pipeline/2
  (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2

...

2022-01-04T20:42:37.463 application=que [info] [Que] Completed Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker
```

### Expected behaviour

More logs detailing that a contract verification was successful or not. 

### Actual behaviour

Logs stating that a worker completed its job, but no indication if it failed or not. In another instance of the contract failing I was able to find the following logs, which is helpful, but I did not always find them when verification failed.

```
2022-01-04T19:03:54.715 application=explorer [warn] There was an error compiling a provided contract: {:error, [%{"component" => "general", "errorCode" => "1878", "formattedMessage" => "Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing \"SPDX-License-Identifier: <SPDX-License>\" to each source file. Use \"SPDX-License-Identifier: UNLICENSED\" for non-open-source code. Please see https://spdx.org for more information.\n--> New.sol\n\n", "message" => "SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing \"SPDX-License-Identifier: <SPDX-License>\" to each source file. Use \"SPDX-License-Identifier: UNLICENSED\" for non-open-source code. Please see https://spdx.org for more information.", "severity" => "warning", "sourceLocation" => %{"end" => -1, "file" => "New.sol", "start" => -1}, "type" => "Warning"}, %{"component" => "general", "errorCode" => "3420", "formattedMessage" => "Warning: Source file does not specify required compiler version! Consider adding \"pragma solidity ^0.8.11;\"\n--> New.sol\n\n", "message" => "Source file does not specify required compiler version! Consider adding \"pragma solidity ^0.8.11;\"", "severity" => "warning", "sourceLocation" => %{"end" => -1, "file" => "New.sol", "start" => -1}, "type" => "Warning"}]}
```

**Comment by wighawag** [comment]
I have the same issue, created a post on the forum : https://forum.poa.network/t/debugging-smart-contract-verification-on-local-blockscout/9472 and posted a message on discord

If there could be some flag to have more verbose logging for smart contract verification it would be great.

I am also open to get pointer on the best way to add elixir code to get that more verbose output.

**Comment by wighawag** [comment]
> Hi @wighawag, what flag did you use, I searched your message on discord but it not found

I am actually asking for flag to use too :)
