### ISSUE TITLE
Market chart is empty, transactions per day is 0 always.

### ISSUE THREAD

**Issue by nikolay-nikolaev** [blockscout/blockscout#5165]
Market history is completely empty. You can see it here: https://ektascan.io/

Coin is https://www.coingecko.com/en/coins/ekta

Config on test https://ektascan.io is:
    -e 'NETWORK=EKTA Chain' \
    -e 'SUBNETWORK=EktaScan' \
    -e 'CHAIN_ID=1994' \
    -e 'COIN=EKTA' \
    -e 'SHOW_PRICE_CHART=true' \
    -e 'SHOW_TXS_CHART=true' \
    -e 'DISABLE_EXCHANGE_RATES=false' \
    -e 'BLOCKSCOUT_HOST=ektascan.io' \
    -e 'BLOCKSCOUT_PROTOCOL=https' \
    -e 'BLOCK_TRANSFORMER=clique' \

Also periodically we have next error in the logs:

```
2022-02-07T07:32:58.831 [error] GenServer #PID<0.6867.36> terminating
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Explorer.ExchangeRates.Token{available_supply: #Decimal<11157603.18>, btc_value: #Decimal<0.00003154021524631576409395545092>, id: "ekta-2", last_updated: ~U[2022-02-07 07:31:04.945Z], market_cap_usd: #Decimal<15631360>, name: "Ekta", symbol: "EKTA", total_supply: #Decimal<2.205E+8>, usd_value: #Decimal<1.35>, volume_24h_usd: #Decimal<77370>} of type Explorer.ExchangeRates.Token (a struct), Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:

    @derive Jason.Encoder
    defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
    Protocol.derive(Jason.Encoder, NameOfTheStruct)
. This protocol is implemented for the following type(s): BlockScoutWeb.API.EthRPC.View, Explorer.Chain.Hash, Explorer.Chain.DecompiledSmartContract, Explorer.Chain.Transaction.History.TransactionStats, Explorer.Chain.BridgedToken, Explorer.Chain.Transaction, Explorer.Chain.Address, Explorer.Chain.Data, Explorer.Chain.Token, Cldr.LanguageTag, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Integer, DateTime, List, Decimal, NaiveDateTime, Time, Any, Jason.Fragment, Jason.OrderedObject, Atom, Map, BitString, Date, Float
    (jason 1.3.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
    (phoenix 1.5.13) lib/phoenix/socket/serializers/v2_json_serializer.ex:95: Phoenix.Socket.V2.JSONSerializer.encode!/1
    (phoenix 1.5.13) lib/phoenix/channel/server.ex:240: Phoenix.Channel.Server.push/6
    (block_scout_web 0.0.1) lib/block_scout_web/channels/exchange_rate_channel.ex:14: BlockScoutWeb.ExchangeRateChannel.handle_out/3
    (phoenix 1.5.13) lib/phoenix/channel/server.ex:327: Phoenix.Channel.Server.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:236: :proc_lib.wake_up/3
Last message: %Phoenix.Socket.Broadcast{event: "new_rate", payload: %{exchange_rate: %Explorer.ExchangeRates.Token{available_supply: #Decimal<11157603.18>, btc_value: #Decimal<0.00003154021524631576409395545092>, id: "ekta-2", last_updated: ~U[2022-02-07 07:31:04.945Z], market_cap_usd: #Decimal<15631360>, name: "Ekta", symbol: "EKTA", total_supply: #Decimal<2.205E+8>, usd_value: #Decimal<1.35>, volume_24h_usd: #Decimal<77370>}, market_history_data: []}, topic: "exchange_rate:new_rate"}
State: %Phoenix.Socket{assigns: %{locale: "en"}, channel: BlockScoutWeb.ExchangeRateChannel, channel_pid: #PID<0.6867.36>, endpoint: BlockScoutWeb.Endpoint, handler: BlockScoutWeb.UserSocket, id: nil, join_ref: "756", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: BlockScoutWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "exchange_rate:new_rate", transport: :websocket, transport_pid: #PID<0.6846.36>}
```

**Comment by vbaranov** [comment]
@nikolay-nikolaev did you try setting explicit Coingecko ID of the coin with `COINGECKO_COIN_ID`?

**Comment by nikolay-nikolaev** [comment]
@vbaranov yes, I set parameter
-e 'COINGECKO_COIN_ID=ekta-2' \
And chart is empty anyway.

**Comment by vbaranov** [comment]
@nikolay-nikolaev  Sorry, I was wrong. Blockscout uses Cryptocompare API for the price history fetching. And EKTA token is not listed there https://min-api.cryptocompare.com/data/histoday?fsym=EKTA&limit=10&tsym=USD

**Comment by nikolay-nikolaev** [comment]
@vbaranov thanks for the info!
