### ISSUE TITLE
An incorrect namespace prevents a test from failing

### ISSUE THREAD

**Issue by amonsosanz** [blockscout/blockscout#5275]
The namespace that defines [this test](https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs#L1) looks incorrect. I think it should be `BlockScoutWeb.Tokens.SmartContractViewTest` instead of `BlockScoutWeb.SmartContractViewTest`.

I found this issue because I get a compilation error when I run the tests locally:
```
== Compilation error in file test/block_scout_web/views/tokens/smart_contract_view_test.exs ==
** (CompileError) test/block_scout_web/views/tokens/smart_contract_view_test.exs:1: cannot define module BlockScoutWeb.SmartContractViewTest because it is currently being defined in test/block_scout_web/views/smart_contract_view_test.exs:1
    (elixir 1.13.0) lib/kernel/parallel_compiler.ex:455: Kernel.ParallelCompiler.require_file/2
    (elixir 1.13.0) lib/kernel/parallel_compiler.ex:348: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```

I can't tell why this compilation error does not break the execution of the tests on the GitHub workflow, though I found a warning is logged. If you check the [logs](https://github.com/blockscout/blockscout/suites/5546585345/logs) from this run on master you will see this warning:
```
2022-03-07T09:51:14.1552400Z warning: redefining module BlockScoutWeb.SmartContractViewTest (current version defined in memory)
2022-03-07T09:51:14.1553645Z   test/block_scout_web/views/tokens/smart_contract_view_test.exs:1
```

Well, the thing is that I locally fixed the issue with the namespace to be able to run the tests and discovered that [this test](https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/test/block_scout_web/views/smart_contract_view_test.exs) does not pass:
```
[CI/Blockscout Web Tests]   |   1) test values_with_type/1 complex data type case (BlockScoutWeb.SmartContractViewTest)
[CI/Blockscout Web Tests]   |      test/block_scout_web/views/smart_contract_view_test.exs:9
[CI/Blockscout Web Tests]   |      Assertion with == failed
[CI/Blockscout Web Tests]   |      code:  assert SmartContractView.values_with_type(value, type, names, 0) == "<div style=\"padding-left: 20px\"><span style=\"color: black\">struct AsyncCallTest.Receipt</span> (tuple[bytes32,uint256,bool,tuple[address,bytes32[],bytes][]]) : <div style=\"padding-left: 20px\"><span style=\"color: black\">txHash</span> (bytes32) : 0x9cd14677f9aa5569b3bbb351fcd67d1115aa563ae1624276d3d4e67fb3d6f926</div><div style=\"padding-left: 20px\"><span style=\"color: black\">blockNumber</span> (uint256) : 23183417</div><div style=\"padding-left: 20px\"><span style=\"color: black\">status</span> (bool) : true</div><div style=\"padding-left: 20px\"><span style=\"color: black\">logs</span> (tuple[address,bytes32[],bytes][]) : [(\n<div style=\"padding-left: 20px\"><span style=\"color: black\">from</span> (address) : 0xa4764045851f17aa60b6c8e8b62072bea9538521</div><div style=\"padding-left: 20px\"><span style=\"color: black\">topics</span> (bytes32[]) : [0x0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d4121396885, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53]</div><div style=\"padding-left: 20px\"><span style=\"color: black\">data</span> (bytes) : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div style=\"padding-left: 20px\"><span style=\"color: black\">from</span> (address) : 0xa4764045851f17aa60b6c8e8b62072bea9538521</div><div style=\"padding-left: 20px\"><span style=\"color: black\">topics</span> (bytes32[]) : [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef, 0x0000000000000000000000000000000000000000000000000000000000000000, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53]</div><div style=\"padding-left: 20px\"><span style=\"color: black\">data</span> (bytes) : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div style=\"padding-left: 20px\"><span style=\"color: black\">from</span> (address) : 0xa68bd659a9167f3d3c01ba9776a1208dae8f003b</div><div style=\"padding-left: 20px\"><span style=\"color: black\">topics</span> (bytes32[]) : [0x2f9a6098d4503a127779ba975f5f6b04f842362b1809f346989e9abc0b4dedb6, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53, 0x00050000249bfc2f3cc8d68f6b6bf7230ea0a8ed853de731000000000000024f]</div><div style=\"padding-left: 20px\"><span style=\"color: black\">data</span> (bytes) : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div style=\"padding-left: 20px\"><span style=\"color: black\">from</span> (address) : 0xfe446bef1dbf7afe24e81e05bc8b271c1ba9a560</div><div style=\"padding-left: 20px\"><span style=\"color: black\">topics</span> (bytes32[]) : [0x27333edb8bdcd40a0ae944fb121b5e2d62ea782683946654a0f5e607a908d578, 0x0000000000000000000000002a5fc52d8a563b2f181c6a527d422e1592c9ecfa, 0x000000000000000000000000a68bd659a9167f3d3c01ba9776a1208dae8f003b, 0x00050000249bfc2f3cc8d68f6b6bf7230ea0a8ed853de731000000000000024f]</div><div style=\"padding-left: 20px\"><span style=\"color: black\">data</span> (bytes) : 0x0000000000000000000000000000000000000000000000000000000000000001</div>)]</div></div>"
[CI/Blockscout Web Tests]   |      left:  "<div class=\"pl-3\"><i><span style=\"color: black\">struct AsyncCallTest.Receipt</span> (tuple[bytes32,uint256,bool,tuple[address,bytes32[],bytes][]])</i> : <div class=\"pl-3\"><i><span style=\"color: black\">txHash</span> (bytes32)</i> : 0x9cd14677f9aa5569b3bbb351fcd67d1115aa563ae1624276d3d4e67fb3d6f926</div><div class=\"pl-3\"><i><span style=\"color: black\">blockNumber</span> (uint256)</i> : 23183417</div><div class=\"pl-3\"><i><span style=\"color: black\">status</span> (bool)</i> : true</div><div class=\"pl-3\"><i><span style=\"color: black\">logs</span> (tuple[address,bytes32[],bytes][])</i> : [(\n<div class=\"pl-3\"><i><span style=\"color: black\">from</span> (address)</i> : 0xa4764045851f17aa60b6c8e8b62072bea9538521</div><div class=\"pl-3\"><i><span style=\"color: black\">topics</span> (bytes32[])</i> : [0x0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d4121396885, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53]</div><div class=\"pl-3\"><i><span style=\"color: black\">data</span> (bytes)</i> : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div class=\"pl-3\"><i><span style=\"color: black\">from</span> (address)</i> : 0xa4764045851f17aa60b6c8e8b62072bea9538521</div><div class=\"pl-3\"><i><span style=\"color: black\">topics</span> (bytes32[])</i> : [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef, 0x0000000000000000000000000000000000000000000000000000000000000000, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53]</div><div class=\"pl-3\"><i><span style=\"color: black\">data</span> (bytes)</i> : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div class=\"pl-3\"><i><span style=\"color: black\">from</span> (address)</i> : 0xa68bd659a9167f3d3c01ba9776a1208dae8f003b</div><div class=\"pl-3\"><i><span style=\"color: black\">topics</span> (bytes32[])</i> : [0x2f9a6098d4503a127779ba975f5f6b04f842362b1809f346989e9abc0b4dedb6, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53, 0x00050000249bfc2f3cc8d68f6b6bf7230ea0a8ed853de731000000000000024f]</div><div class=\"pl-3\"><i><span style=\"color: black\">data</span> (bytes)</i> : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div class=\"pl-3\"><i><span style=\"color: black\">from</span> (address)</i> : 0xfe446bef1dbf7afe24e81e05bc8b271c1ba9a560</div><div class=\"pl-3\"><i><span style=\"color: black\">topics</span> (bytes32[])</i> : [0x27333edb8bdcd40a0ae944fb121b5e2d62ea782683946654a0f5e607a908d578, 0x0000000000000000000000002a5fc52d8a563b2f181c6a527d422e1592c9ecfa, 0x000000000000000000000000a68bd659a9167f3d3c01ba9776a1208dae8f003b, 0x00050000249bfc2f3cc8d68f6b6bf7230ea0a8ed853de731000000000000024f]</div><div class=\"pl-3\"><i><span style=\"color: black\">data</span> (bytes)</i> : 0x0000000000000000000000000000000000000000000000000000000000000001</div>)]</div></div>"
[CI/Blockscout Web Tests]   |      right: "<div style=\"padding-left: 20px\"><span style=\"color: black\">struct AsyncCallTest.Receipt</span> (tuple[bytes32,uint256,bool,tuple[address,bytes32[],bytes][]]) : <div style=\"padding-left: 20px\"><span style=\"color: black\">txHash</span> (bytes32) : 0x9cd14677f9aa5569b3bbb351fcd67d1115aa563ae1624276d3d4e67fb3d6f926</div><div style=\"padding-left: 20px\"><span style=\"color: black\">blockNumber</span> (uint256) : 23183417</div><div style=\"padding-left: 20px\"><span style=\"color: black\">status</span> (bool) : true</div><div style=\"padding-left: 20px\"><span style=\"color: black\">logs</span> (tuple[address,bytes32[],bytes][]) : [(\n<div style=\"padding-left: 20px\"><span style=\"color: black\">from</span> (address) : 0xa4764045851f17aa60b6c8e8b62072bea9538521</div><div style=\"padding-left: 20px\"><span style=\"color: black\">topics</span> (bytes32[]) : [0x0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d4121396885, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53]</div><div style=\"padding-left: 20px\"><span style=\"color: black\">data</span> (bytes) : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div style=\"padding-left: 20px\"><span style=\"color: black\">from</span> (address) : 0xa4764045851f17aa60b6c8e8b62072bea9538521</div><div style=\"padding-left: 20px\"><span style=\"color: black\">topics</span> (bytes32[]) : [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef, 0x0000000000000000000000000000000000000000000000000000000000000000, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53]</div><div style=\"padding-left: 20px\"><span style=\"color: black\">data</span> (bytes) : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div style=\"padding-left: 20px\"><span style=\"color: black\">from</span> (address) : 0xa68bd659a9167f3d3c01ba9776a1208dae8f003b</div><div style=\"padding-left: 20px\"><span style=\"color: black\">topics</span> (bytes32[]) : [0x2f9a6098d4503a127779ba975f5f6b04f842362b1809f346989e9abc0b4dedb6, 0x000000000000000000000000bf3d6f830ce263cae987193982192cd990442b53, 0x00050000249bfc2f3cc8d68f6b6bf7230ea0a8ed853de731000000000000024f]</div><div style=\"padding-left: 20px\"><span style=\"color: black\">data</span> (bytes) : 0x000000000000000000000000000000000000000000000000aab260d4f14e0000</div>),\n(<div style=\"padding-left: 20px\"><span style=\"color: black\">from</span> (address) : 0xfe446bef1dbf7afe24e81e05bc8b271c1ba9a560</div><div style=\"padding-left: 20px\"><span style=\"color: black\">topics</span> (bytes32[]) : [0x27333edb8bdcd40a0ae944fb121b5e2d62ea782683946654a0f5e607a908d578, 0x0000000000000000000000002a5fc52d8a563b2f181c6a527d422e1592c9ecfa, 0x000000000000000000000000a68bd659a9167f3d3c01ba9776a1208dae8f003b, 0x00050000249bfc2f3cc8d68f6b6bf7230ea0a8ed853de731000000000000024f]</div><div style=\"padding-left: 20px\"><span style=\"color: black\">data</span> (bytes) : 0x0000000000000000000000000000000000000000000000000000000000000001</div>)]</div></div>"
[CI/Blockscout Web Tests]   |      stacktrace:
[CI/Blockscout Web Tests]   |        test/block_scout_web/views/smart_contract_view_test.exs:61: (test)
```

My assumption is that the HTML of that view was changed at some point and since the test was not executed because of the overridden namespace, it became obsolete.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]. Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Operating System: Ubuntu 20.04.3 LTS
* Blockscout Version/branch: master

**Comment by vbaranov** [comment]
@amonsosanz nice catch, thank you! A am fixing that.
