### ISSUE TITLE
Documentation to run tests seems outdated

### ISSUE THREAD

**Issue by SebastienGllmt** [blockscout/blockscout#5335]
*Describe your issue here.*

The test documentation seems to be out of date so I am not sure how to run tests (notably, for graphql changes)

**EDIT:** I think I figured it out. The documentation is missing that you need to set `MIX_ENV` to `test`

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):  Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Operating System: WSL2
* Blockscout Version/branch:  master / b05c5c6ed2398cf21decc15a715b17f20d5aa428

### Steps to reproduce

The [current testing documentation](https://docs.blockscout.com/for-developers/testing) says to run `mix coveralls.html --umbrella`

However, this fails because it seems coveralls was [previously removed](https://github.com/blockscout/blockscout/pull/3761)

### Expected behaviour

Tests run successfully

### Actual behaviour

```
** (Mix) The task "coveralls.html" could not be found
```

### Additional note

I tried to instead run `mix test --no-start --exclude no_parity` and I got

```
==> ethereum_jsonrpc
** (UndefinedFunctionError) function Mox.defmock/2 is undefined (module Mox is not available)
    Mox.defmock(EthereumJSONRPC.Mox, [for: EthereumJSONRPC.Transport])
    test/test_helper.exs:9: (file)
    (elixir 1.12.3) lib/code.ex:1261: Code.require_file/2
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
```

Not really sure what this error wants from me

If I instead try and run the tests purely from the `block_scout_web` app, I instead get

```
** (MatchError) no match of right hand side value: {:error, {:wallaby, {'no such file or directory', 'wallaby.app'}}}
    test/test_helper.exs:9: (file)
    (elixir 1.12.3) lib/code.ex:1261: Code.require_file/2
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.12.3) lib/mix/tasks/test.ex:500: Mix.Tasks.Test.do_run/3
```

but I installed PhantomJS as described in the docs (edit: it seems PhantomJS was removed as a dependency from blockscout, but the docs still mention it) so I'm not sure how to get around this error. My best guess is that the test featurecase isn't being run, but disabling the wallaby check then just fails on ex_machina

**Comment by SebastienGllmt** [comment]
Okay, so far I've found that you have to do the following:

1. sudo -u postgres dropdb explorer_test
2. sudo -u postgres createdb explorer_test
3. sudo -u postgres createuser blockscout_test
4. sudo -u postgres psql
5. \password blockscout_test
6. grant all privileges on database explorer_test to blockscout_test ;
7. Set the env variables as follows (note: db name/username/password match what you set in the previous step)
```sh
export MIX_ENV=test
export PGUSER=blockscout_test
export PGPASSWORD=blockscouttestpassword
export ETHEREUM_JSONRPC_CASE=EthereumJSONRPC.Case.Parity.Mox
export ETHEREUM_JSONRPC_WEB_SOCKET_CASE=EthereumJSONRPC.WebSocket.Case.Mox
export CHAIN_ID=77
export ADMIN_PANEL_ENABLED=true
```
8. Install chromedriver. You can reference the script at `./bin/install_chrome_headless.sh` for how to do it, but note that the **chromedriver version much match your chrome version** (notably, open chrome and find the first 3 parts of your version number such as x.x.xxxx)
9. mix test --no-start --exclude no_parity (you can also run a specific test using `mix cmd --app block_scout_web mix test test/block_scout_web/schema/query/address_test.exs`)

This seems to get me pretty far, however I run into this error on a lot of tests

```
     ** (Ecto.ConstraintError) constraint error when attempting to insert struct:

         * one_consensus_block_at_height (unique_constraint)

     If you would like to stop this constraint violation from raising an
     exception and instead add it as an error to your changeset, please
     call `unique_constraint/3` on your changeset with the constraint
     `:name` as an option.

     The changeset has not defined any constraint.
```

**Comment by SebastienGllmt** [comment]
Closing in favor of https://github.com/blockscout/docs/issues/48 as I didn't realize these were separate repos
