### ISSUE TITLE
verify contract failed

### ISSUE THREAD

**Issue by zjb0807** [blockscout/blockscout#5463]
```
2022-04-14T15:26:50.571 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
2022-04-14T15:26:54.906 [error] Task #PID<0.17549.8> started from #PID<0.2291.8> terminating
** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

from t0 in Explorer.Chain.Transaction,
  left_join: a1 in Explorer.Chain.Address,
  on: t0.created_contract_address_hash == a1.hash,
  where: t0.created_contract_address_hash == ^"0x0000000000000000000100000000000000000080",
  where: t0.status == ^1,
  select: %{init: t0.input, created_contract_code: a1.contract_code}

    (ecto 3.7.1) lib/ecto/repo/queryable.ex:149: Ecto.Repo.Queryable.one/3
    (explorer 0.0.1) lib/explorer/chain.ex:3836: Explorer.Chain.smart_contract_creation_tx_bytecode/1
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/verifier.ex:200: Explorer.SmartContract.Solidity.Verifier.compare_bytecodes/6
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/verifier.ex:82: anonymous fn/6 in Explorer.SmartContract.Solidity.Verifier.verify/3
    (elixir 1.12.3) lib/enum.ex:4286: Enumerable.List.reduce/3
    (elixir 1.12.3) lib/enum.ex:2431: Enum.reduce_while/3
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/publisher.ex:49: Explorer.SmartContract.Solidity.Publisher.publish_with_standard_json_input/2
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/publisher_worker.ex:39: Explorer.SmartContract.Solidity.PublisherWorker.perform/1
Function: #Function<3.131974459/0 in Que.Job.perform/1>
    Args: []
2022-04-14T15:26:54.908 application=que [info] [Que] Failed Job # 16 with Explorer.SmartContract.Solidity.PublisherWorker
2022-04-14T15:27:05.528 application=indexer fetcher=block_catchup first_block_number=300894 last_block_number=291458 missing_block_count=0 shrunk=false [info] Index already caught up.
2022-04-14T15:27:05.528 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
```

**Comment by vbaranov** [comment]
@zjb0807 is it from latest commit of master branch?

**Comment by zjb0807** [comment]
This commit: https://github.com/AcalaNetwork/blockscout/commit/ce99db3956b64f7db569677fbc3da4302398fd93

**Comment by zjb0807** [comment]
There is a problem with the data source
