### ISSUE TITLE
FunctionClauseError no function clause matching in EthereumJSONRPC.Geth.Tracer.finalize/1 when indexing internal txs of some txs of CLV parachain

### ISSUE THREAD

**Issue by YakovL** [blockscout/blockscout#5477]
I'm trying to adapt Blockscout for CLV parachain. Since they don't support js-based tracing, I've removed js tracer, i.e.

* in `apps/ethereum_jsonprc/lib/ethereum_jsonprc/geth.ex` in `debug_trace_transaction_request` removed the `tracer: @tracer` bit
* commented out the lines 87-89 (starting with `@tracer_path`)
* (I'm not sure if there's a more convenient way to switch to the "hardcoded tracer" instead of js one)

also, since they seem to have a non-standart response format, I've replaced `"structLogs"` with `"stepLogs"` in both `geth.ex` and `geth/tracer.ex` (3 occurences in total) to fix corresponding errors.

Now during indexing internal txs they are successfully extracted for some txs (like `0x720a134eea5d77257df5e511154904b48302d2bfc1e759d7ef8f1fb292ec6c4d`) and give errors for others (like `0x1b44cf5d4a9896219f50f61541fb3f21ac0ad65cb522991062bf74b18582f953`).

The error is the following (the stack is shown since I've added `Exception.format(:error, error, __STACKTRACE__) |> Logger.error()` at `apps/indexer/lib/indexer/fetcher/internal_transaction.ex:121`):

```
2022-04-18T18:21:45.029 application=indexer fetcher=internal_transaction count=10 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Geth.Tracer.finalize/1
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/geth/tracer.ex:297: EthereumJSONRPC.Geth.Tracer.finalize(%{calls: [[[], %{"callType" => "call", "from" => nil, "gas" => 0, "gasUsed" => 0, "input" => "0x", "output" => "0x", "to" => "0x4498a1859f0c2429d69069d1d46825b2b9fbe764", "traceAddress" => [0, 5], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000e043da6168ae2e0"}, [%{"callType" => "call", "from" => "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3", "gas" => 2300, "gasUsed" => 95, "input" => "0x", "output" => "0x", "to" => "0x7144835cda7698c7767e3ef144da98e5e218af33", "traceAddress" => [0, 4, 0], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000e043da6168ae2e0"}, []], %{"callType" => "call", "from" => nil, "gas" => 397268, "gasUsed" => 11830, "input" => "0x2e1a7d4d0000000000000000000000000000000000000000000000000e043da6168a0000", "output" => "0x", "to" => "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3", "traceAddress" => [0, 4], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000000000000000000"}, [], %{"callType" => "call", "from" => nil, "gas" => 405610, "gasUsed" => 6669, "input" => "0xa9059cbb0000000000000000000000004498a1859f0c2429d69069d1d46825b2b9fbe764000000000000000000000000000000000000000000000000000000024e280000", "output" => "0x", "to" => "0xb995fff52a9472f752b57deca5bef73c8654a012", "traceAddress" => [0, 3], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000000000000000000"}, [%{"callType" => "staticcall", "from" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "gas" => 505008, "gasUsed" => 1263, "input" => "0x70a0823100000000000000000000000064b38c173c74a40e7809a9ca538fa94700000000", "output" => "0x0000000000000000000000000000000000000000000000000e043da617250000", "to" => "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3", "traceAddress" => [0, 2, 0], "type" => "call", "value" => "0x0"}, [], %{"callType" => "staticcall", "from" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "gas" => 502158, "gasUsed" => 1283, "input" => "0x70a0823100000000000000000000000064b38c173c74a40e7809a9ca538fa94700000000", "output" => "0x000000000000000000000000000000000000000000000000000000024e28dbec", "to" => "0xb995fff52a9472f752b57deca5bef73c8654a012", "traceAddress" => [0, 2, 1], "type" => "call", "value" => "0x0"}, [], %{"callType" => "staticcall", "from" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "gas" => 497612, "gasUsed" => 1038, "input" => "0x017e7e58", "output" => "0x0000000000000000000000000000000000000000000000000000000000000000", "to" => "0xbba0fae33618e20f029f41758dc05a7dc0d37690", "traceAddress" => [0, 2, 2], "type" => "call", "value" => "0x0"}, [], %{"callType" => "call", "from" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "gas" => 487756, "gasUsed" => 26072, "input" => "0xa9059cbb0000000000000000000000007144835cda7698c7767e3ef144da98e5e218af330000000000000000000000000000000000000000000000000e043da6168ae2e0", "output" => "0x", "to" => "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3", "traceAddress" => [0, 2, 3], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000000000000000000"}, [], %{"callType" => "call", "from" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "gas" => 460478, "gasUsed" => 25869, "input" => "0xa9059cbb0000000000000000000000007144835cda7698c7767e3ef144da98e5e218af33000000000000000000000000000000000000000000000000000000024e28dbeb", "output" => "0x", "to" => "0xb995fff52a9472f752b57deca5bef73c8654a012", "traceAddress" => [0, 2, 4], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000000000000000000"}, [], %{"callType" => "staticcall", "from" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "gas" => 433233, "gasUsed" => 1263, "input" => "0x70a0823100000000000000000000000064b38c173c74a40e000000000000000000000000", "output" => "0x0000000000000000000000000000000000000000000000000000000000000000", "to" => "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3", "traceAddress" => [0, 2, 5], "type" => "call", "value" => "0x0"}, [], %{"callType" => "staticcall", "from" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "gas" => 430385, "gasUsed" => 1283, "input" => "0x70a0823100000000000000000000000064b38c173c74a40e000000000000000000000000", "output" => "0x0000000000000000000000000000000000000000000000000000000000000000", "to" => "0xb995fff52a9472f752b57deca5bef73c8654a012", "traceAddress" => [0, 2, 6], "type" => "call", "value" => "0x0"}, []], %{"callType" => "call", "from" => nil, "gas" => 519045, "gasUsed" => 113371, "input" => "0x89afcb440000000000000000000000007144835cda7698c7767e3ef144da98e5e218af33", "output" => "0x0000000000000000000000000000000000000000000000000e043da6168ae2e0000000000000000000000000000000000000000000000000000000024e28dbeb", "to" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "traceAddress" => [0, 2], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000000000000000000"}, [], %{"callType" => "call", "from" => nil, "gas" => 548350, "gasUsed" => 28136, "input" => "0x23b872dd0000000000000000000000004498a1859f0c2429d69069d1d46825b2b9fbe76400000000000000000000000064b38c173c74a40e7809a9ca538fa94728f791f4000000000000000000000000000000000000000000000000000000005af3107a", "output" => "0x0000000000000000000000000000000000000000000000000000000000000001", "to" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "traceAddress" => [0, 1], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000000000000000000"}, [], %{"callType" => "staticcall", "from" => nil, "gas" => 572248, "gasUsed" => 22216, "input" => "0x69f5c1c4d67e92c2da2d1c1c342cfd423aed750e61c3641bf5bf5f2f77b5bc4e000000000000000000000000000000000000000000000000000000000000001b631f65fa28e98d04bb1d595cd6c9e984a693df791450555d0ef435c941085f4d301f109cd85a4f7a55eb4c64354cfbb77443a44800ed117f4d831c409f610000", "output" => "0x0000000000000000000000000000000000000000000000000000000000001b63", "to" => "0x0000000000000000000000000000000000000001", "traceAddress" => [0, 0], "type" => "call", "value" => "0x0"}], []], depth: 2, stack: [%{"callType" => "call", "from" => nil, "gas" => 598718, "gasUsed" => 214972, "input" => "0xd505accf0000000000000000000000004498a1859f0c2429d69069d1d46825b2b9fbe7640000000000000000000000007144835cda7698c7767e3ef144da98e5e218af3300000000000000000000000000000000000000000000000000005af3107a3c1800000000000000000000000000000000000000000000000000000000625703a7000000000000000000000000000000000000000000000000000000000000001b631f65fa28e98d04bb1d595cd6c9e984a693df791450555d0ef435c941085f4d301f109cd85a4f7a55eb4c64354cfbb77443a44800ed117f4d831c409f616300", "output" => "0x", "outputLength" => 0, "outputOffset" => 634, "to" => "0x64b38c173c74a40e7809a9ca538fa94728f791f4", "traceAddress" => [0], "type" => "call", "value" => "0x0000000000000000000000000000000000000000000000000000000000000000"}, %{"callType" => "call", "from" => "0x4498a1859f0c2429d69069d1d46825b2b9fbe764", "gas" => 611105, "gasUsed" => 1484, "input" => "0xded9382a000000000000000000000000b995fff52a9472f752b57deca5bef73c8654a01200000000000000000000000000000000000000000000000000005af3107a3c18000000000000000000000000000000000000000000000000000000024b35746b0000000000000000000000000000000000000000000000000df24cb3566e08240000000000000000000000004498a1859f0c2429d69069d1d46825b2b9fbe76400000000000000000000000000000000000000000000000000000000625703a70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001b631f65fa28e98d04bb1d595cd6c9e984a693df791450555d0ef435c941085f4d301f109cd85a4f7a55eb4c64354cfbb77443a44800ed117f4d831c409f616343", "output" => "0x", "to" => "0x7144835cda7698c7767e3ef144da98e5e218af33", "traceAddress" => [], "type" => "call", "value" => "0x0"}], trace_address: [6, 0]})
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/geth.ex:119: anonymous fn/4 in EthereumJSONRPC.Geth.debug_trace_transaction_responses_ (truncated)
2022-04-18T18:21:45.029 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :finalize, kind: nil, module: EthereumJSONRPC.Geth.Tracer}
```

If you take a closer look, you can see that the argument of `finalize`, which is expected to be `%{stack: [top], calls: [calls]` actually has more than one element in both `.stack` and `.calls` (note that this particular error is probably not for the tx for which I've provided example hash above). Below (*) you can find an example of what the result of `reduced_logs = Enum.reduce(logs, ctx, &step/2)` may look like. Previously, I've tried to add a `[]` wrapper to `reduced_logs.calls` (in "ok" cases it had one more), and it seemed to "fix" a part of the error, but `reduced_logs.stack` has also more than one element and adding a wrapper is obviously not an option. **Is `reduced_logs.depth` expected to be `1`? Are the last elements ("bottom of the stack"?) what should be a correct output?**

Now, since `logs` (inside tracer.`replay`) is something that comes from the CLV node (well, it's a result of some processing by BS too) and I can't see much structural difference between `logs` in "successful" cases and when the error occurs, I'm not sure **how to debug this further and how to determine whether** this is an error in BS processing of logs or some sort of "corrupted date" from the CLV node.

Can you help me debug this further? Or may be explain the algorithm of tracer.ex and implications behind it so that I can verify some constraints? For now, I'm a bit "blind" when debugging this as I don't even have "a source of truth" and don't know whether this is a problem of BS or CLV; and how to fix it on "my" side (BS) anyway.

### Environment

* Elixir & Erlang/OTP versions:
  * Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
  * Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Operating System: Ubuntu 20.04.3 LTS
* Blockscout Version/branch: tweaked master (from commit ce99db395)

### Steps to reproduce

Main env variables to set:

* `ETHEREUM_JSONRPC_VARIANT=geth`
* `ETHEREUM_JSONRPC_HTTP_URL=https://api-para.clover.finance`
* (`COIN=CLV`)

I'm running outside Docker for dev purposes; I've described the minimal code modifications above.

### Expected behaviour

Indexing should finish normally.

### Actual behaviour

Indexing of txs finishes, but the interface tells "Indexing Tokens - We're indexing this chain right now. Some of the counts may be inaccurate.". The output of `mix phx.server` contains the errors that I've mentioned. There's also a number of errors of another type though (formatted a bit for your convenience):

```
2022-04-18T18:21:56.829 application=indexer fetcher=internal_transaction count=10 error_count=10 [error]
 failed to fetch internal transactions for blocks: [%{
  code: -32603, data: %{block_number: 396394, transaction_hash: "0x41ce2cb2b4fb3fcb82c7ac2c0f9f76837a5f9c1d0f041451b446b433a2bd3e8e", transaction_index: 0},
  message: "Runtime block call failed: FailedToDecodeReturnValue { function: \"current_block\", error: Error { cause: Some(Error { cause: Some(Error { cause: None, desc: \"Could not decode `TransactionV2`, variant doesn't exist\" }),
   desc: \"Could not decode `Block::transactions`\" }), desc: \"Could not decode `Option::Some(T)`\" } }"}]
```

(*) an example of what the result of `Enum.reduce(logs, ctx, &step/2)` may look like:

```
%{
  calls: [[], [], [], []],
  depth: 4,
  stack: [
    %{
      "callType" => "staticcall",
      "from" => nil,
      "gas" => 432013,
      "gasUsed" => 21661,
      "input" => "0xefc4cfa" <> ...,
      "output" => "0x",
      "outputLength" => 64,
      "outputOffset" => 4346,
      "to" => "0x0000000000000000000000000000000000000001",
      "traceAddress" => [0, 0, 0],
      "type" => "call",
      "value" => "0x0"
    },
    %{
      "callType" => "staticcall",
      "from" => nil,
      "gas" => 438139,
      "gasUsed" => 1726,
      "input" => "0xefc4c" <> ...,
      "output" => "0x",
      "outputLength" => 64,
      "outputOffset" => 4026,
      "to" => "0x0000000000000000000000000000000000000001",
      "traceAddress" => [0, 0],
      "type" => "call",
      "value" => "0x0"
    },
    %{
      "callType" => "staticcall",
      "from" => nil
      "gas" => 445060,
      "gasUsed" => 2521,
      "input" => "0xefc4" <> ...,
      "output" => "0x",
      "outputLength" => 64,
      "outputOffset" => 3706,
      "to" => "0x0000000000000000000000000000000000000001",
      "traceAddress" => [0],
      "type" => "call",
      "value" => "0x0"
    },
    %{
      "callType" => "call",
      "from" => "0x9a66644084108a1bc23a9ccd50d6d63e53098db6",
      "gas" => 460960,
      "gasUsed" => 11500,
      "input" => "0xba2c" <> ...,
      "output" => "0x",
      "to" => "0x841ce48f9446c8e281d3f1444cb859b4a6d0738c",
      "traceAddress" => [],
      "type" => "call",
      "value" => "0x0"
    }
  ],
  trace_address: [0, 0, 0, 0]
}
```

in non-problematic cases, it looks like:

```
%{
  calls: [[]],
  depth: 1,
  stack: [
    %{
      "callType" => "call",
      "error" => "execution reverted",
      "from" => "0xbfa2f68bf9ad60dc3cfb1cef04730eb7fa251424",
      "gas" => 457336,
      "gasUsed" => 2464,
      "input" => "0xba2cb2" <> ...,
      "output" => "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001e547269676765722074696d65206973206e6f7420696e6372656173696e670000",
      "to" => "0x841ce48f9446c8e281d3f1444cb859b4a6d0738c",
      "traceAddress" => [],
      "type" => "call",
      "value" => "0x0"
    }
  ],
  trace_address: [0]
}
```

**Comment by YakovL** [comment]
PS Here's a more interesting example of `Enum.reduce(logs, ctx, &step/2)` result that's "invalid" (converted into JSON):

```
  {
    "calls": [
      [
        [],
        {
          "callType": "call",
          "from": null,
          "gas": 0,
          "gasUsed": 0,
          "input": "0x",
          "output": "0x",
          "to": "0x4498a1859f0c2429d69069d1d46825b2b9fbe764",
          "traceAddress": [0, 5],
          "type": "call",
          "value": "0x0000000000000000000000000000000000000000000000000e043da6168ae2e0"
        },
        [
          {
            "callType": "call",
            "from": "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3",
            "gas": 2300,
            "gasUsed": 95,
            "input": "0x",
            "output": "0x",
            "to": "0x7144835cda7698c7767e3ef144da98e5e218af33",
            "traceAddress": [0, 4, 0],
            "type": "call",
            "value": "0x0000000000000000000000000000000000000000000000000e043da6168ae2e0"
          },
          []
        ],
        {
          "callType": "call",
          "from": null,
          "gas": 397268,
          "gasUsed": 11830,
          "input": "0x2e1a7d4d0000000000000000000000000000000000000000000000000e043da6168a0000",
          "output": "0x",
          "to": "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3",
          "traceAddress": [0, 4],
          "type": "call",
          "value": "0x0000000000000000000000000000000000000000000000000000000000000000"
        },
        [],
        {
          "callType": "call",
          "from": null,
          "gas": 405610,
          "gasUsed": 6669,
          "input": "0xa9059cbb0000000000000000000000004498a1859f0c2429d69069d1d46825b2b9fbe764000000000000000000000000000000000000000000000000000000024e280000",
          "output": "0x",
          "to": "0xb995fff52a9472f752b57deca5bef73c8654a012",
          "traceAddress": [0, 3],
          "type": "call",
          "value": "0x0000000000000000000000000000000000000000000000000000000000000000"
        },
        [
          {
            "callType": "staticcall",
            "from": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
            "gas": 505008,
            "gasUsed": 1263,
            "input": "0x70a0823100000000000000000000000064b38c173c74a40e7809a9ca538fa94700000000",
            "output": "0x0000000000000000000000000000000000000000000000000e043da617250000",
            "to": "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3",
            "traceAddress": [0, 2, 0],
            "type": "call",
            "value": "0x0"
          },
          [],
          {
            "callType": "staticcall",
            "from": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
            "gas": 502158,
            "gasUsed": 1283,
            "input": "0x70a0823100000000000000000000000064b38c173c74a40e7809a9ca538fa94700000000",
            "output": "0x000000000000000000000000000000000000000000000000000000024e28dbec",
            "to": "0xb995fff52a9472f752b57deca5bef73c8654a012",
            "traceAddress": [0, 2, 1],
            "type": "call",
            "value": "0x0"
          },
          [],
          {
            "callType": "staticcall",
            "from": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
            "gas": 497612,
            "gasUsed": 1038,
            "input": "0x017e7e58",
            "output": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "to": "0xbba0fae33618e20f029f41758dc05a7dc0d37690",
            "traceAddress": [0, 2, 2],
            "type": "call",
            "value": "0x0"
          },
          [],
          {
            "callType": "call",
            "from": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
            "gas": 487756,
            "gasUsed": 26072,
            "input": "0xa9059cbb0000000000000000000000007144835cda7698c7767e3ef144da98e5e218af330000000000000000000000000000000000000000000000000e043da6168ae2e0",
            "output": "0x",
            "to": "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3",
            "traceAddress": [0, 2, 3],
            "type": "call",
            "value": "0x0000000000000000000000000000000000000000000000000000000000000000"
          },
          [],
          {
            "callType": "call",
            "from": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
            "gas": 460478,
            "gasUsed": 25869,
            "input": "0xa9059cbb0000000000000000000000007144835cda7698c7767e3ef144da98e5e218af33000000000000000000000000000000000000000000000000000000024e28dbeb",
            "output": "0x",
            "to": "0xb995fff52a9472f752b57deca5bef73c8654a012",
            "traceAddress": [0, 2, 4],
            "type": "call",
            "value": "0x0000000000000000000000000000000000000000000000000000000000000000"
          },
          [],
          {
            "callType": "staticcall",
            "from": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
            "gas": 433233,
            "gasUsed": 1263,
            "input": "0x70a0823100000000000000000000000064b38c173c74a40e000000000000000000000000",
            "output": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "to": "0x6d6ad95425fcf315c39fa6f3226471d4f16f27b3",
            "traceAddress": [0, 2, 5],
            "type": "call",
            "value": "0x0"
          },
          [],
          {
            "callType": "staticcall",
            "from": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
            "gas": 430385,
            "gasUsed": 1283,
            "input": "0x70a0823100000000000000000000000064b38c173c74a40e000000000000000000000000",
            "output": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "to": "0xb995fff52a9472f752b57deca5bef73c8654a012",
            "traceAddress": [0, 2, 6],
            "type": "call",
            "value": "0x0"
          },
          []
        ],
        {
          "callType": "call",
          "from": null,
          "gas": 519045,
          "gasUsed": 113371,
          "input": "0x89afcb440000000000000000000000007144835cda7698c7767e3ef144da98e5e218af33",
          "output": "0x0000000000000000000000000000000000000000000000000e043da6168ae2e0000000000000000000000000000000000000000000000000000000024e28dbeb",
          "to": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
          "traceAddress": [0, 2],
          "type": "call",
          "value": "0x0000000000000000000000000000000000000000000000000000000000000000"
        },
        [],
        {
          "callType": "call",
          "from": null,
          "gas": 548350,
          "gasUsed": 28136,
          "input": "0x23b872dd0000000000000000000000004498a1859f0c2429d69069d1d46825b2b9fbe76400000000000000000000000064b38c173c74a40e7809a9ca538fa94728f791f4000000000000000000000000000000000000000000000000000000005af3107a",
          "output": "0x0000000000000000000000000000000000000000000000000000000000000001",
          "to": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
          "traceAddress": [0, 1],
          "type": "call",
          "value": "0x0000000000000000000000000000000000000000000000000000000000000000"
        },
        [],
        {
          "callType": "staticcall",
          "from": null,
          "gas": 572248,
          "gasUsed": 22216,
          "input": "0x69f5c1c4d67e92c2da2d1c1c342cfd423aed750e61c3641bf5bf5f2f77b5bc4e000000000000000000000000000000000000000000000000000000000000001b631f65fa28e98d04bb1d595cd6c9e984a693df791450555d0ef435c941085f4d301f109cd85a4f7a55eb4c64354cfbb77443a44800ed117f4d831c409f610000",
          "output": "0x0000000000000000000000000000000000000000000000000000000000001b63",
          "to": "0x0000000000000000000000000000000000000001",
          "traceAddress": [0, 0],
          "type": "call",
          "value": "0x0"
        }
      ],
      []
    ],
    "depth": 2,
    "stack": [
      {
        "callType": "call",
        "from": null,
        "gas": 598718,
        "gasUsed": 214972,
        "input": "0xd505accf0000000000000000000000004498a1859f0c2429d69069d1d46825b2b9fbe7640000000000000000000000007144835cda7698c7767e3ef144da98e5e218af3300000000000000000000000000000000000000000000000000005af3107a3c1800000000000000000000000000000000000000000000000000000000625703a7000000000000000000000000000000000000000000000000000000000000001b631f65fa28e98d04bb1d595cd6c9e984a693df791450555d0ef435c941085f4d301f109cd85a4f7a55eb4c64354cfbb77443a44800ed117f4d831c409f616300",
        "output": "0x",
        "outputLength": 0,
        "outputOffset": 634,
        "to": "0x64b38c173c74a40e7809a9ca538fa94728f791f4",
        "traceAddress": [0],
        "type": "call",
        "value": "0x0000000000000000000000000000000000000000000000000000000000000000"
      },
      {
        "callType": "call",
        "from": "0x4498a1859f0c2429d69069d1d46825b2b9fbe764",
        "gas": 611105,
        "gasUsed": 1484,
        "input": "0xded9382a000000000000000000000000b995fff52a9472f752b57deca5bef73c8654a01200000000000000000000000000000000000000000000000000005af3107a3c18000000000000000000000000000000000000000000000000000000024b35746b0000000000000000000000000000000000000000000000000df24cb3566e08240000000000000000000000004498a1859f0c2429d69069d1d46825b2b9fbe76400000000000000000000000000000000000000000000000000000000625703a70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001b631f65fa28e98d04bb1d595cd6c9e984a693df791450555d0ef435c941085f4d301f109cd85a4f7a55eb4c64354cfbb77443a44800ed117f4d831c409f616343",
        "output": "0x",
        "to": "0x7144835cda7698c7767e3ef144da98e5e218af33",
        "traceAddress": [],
        "type": "call",
        "value": "0x0"
      }
    ],
    "trace_address": [6, 0]
  }
```

It looks like tracing of calls stopped before reaching the stack bottom (I presume): the last call has `"traceAddress": [0, 0]` – I'm not sure, but may be it should go down to `[]` or at least `[0]` (should it?).

Judging by `from`, https://clvscan.com/address/0x4498a1859f0c2429d69069d1d46825b2b9fbe764 and `to`, this should be the stack of one of these txs:

* 0x6a441186974b4374d98d9ab2701965e358c618546818437bf0c1cacc76f5144d
* 0x1b44cf5d4a9896219f50f61541fb3f21ac0ad65cb522991062bf74b18582f953
* 0x3abf1c5109f2672d88e51cfed8902c27e725aca78b09fe91c9980574281ec44e

and judging by input it's exactly for [0x1b44cf5d4a9896219f50f61541fb3f21ac0ad65cb522991062bf74b18582f953](https://clvscan.com/tx/0x3abf1c5109f2672d88e51cfed8902c27e725aca78b09fe91c9980574281ec44e).

**Comment by goodsoft** [comment]
![image](https://user-images.githubusercontent.com/2828228/164056030-dd32d10f-8500-4a0f-95a3-0e26948e3973.png)

(sorry)

**Comment by vbaranov** [comment]
@YakovL `callTracer` is now a default option for fetching of internal transactions. While js tracer is currently optional. Please try pull updates from master branch. I am clsoing this issue for now. Let me know, if the issue still present.
