### ISSUE TITLE
Smart-contracts interaction, balanceOf method: no function clause matching in Integer.parse/2

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#5518]
```
Request: GET /smart-contracts/0x93d0c9a35c43f6BC999416A06aaDF21E68B29EBA?function_name=balanceOf&method_id=00fdd58e&args%5B%5D=0x343aa9b908bf6ef8d0e954221789881750c9c3ce&args%5B%5D=873
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Integer.parse/2
        (elixir 1.13.1) lib/integer.ex:275: Integer.parse(nil, 10)
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:110: BlockScoutWeb.SmartContractController.show/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
```

**Comment by nikitosing** [comment]
@vbaranov 
cannot reproduce the issue
![image](https://user-images.githubusercontent.com/32202610/165919444-15f37d4c-8967-48c3-b7ee-e48213f08b9f.png)This is requested url: `https://blockscout.com/xdai/mainnet/smart-contracts/0x93d0c9a35c43f6BC999416A06aaDF21E68B29EBA?function_name=balanceOf&method_id=00fdd58e&type=regular&args_count=2&arg_1=873&arg_0=0x343aa9b908bf6ef8d0e954221789881750c9c3ce` (now args format is different unlike attached log)

**Comment by vbaranov** [comment]
This is from a fresh today's log. Ok, I will continue to monitor for this error.

**Comment by vbaranov** [comment]
@nikitosing this error repeats again:
```
2022-05-04T16:51:19.402 [error] #PID<0.3533.68> running BlockScoutWeb.Endpoint (connection #PID<0.3507.68>, stream id 1) terminated
Server: ...
Request: GET /smart-contracts/0x93d0c9a35c43f6BC999416A06aaDF21E68B29EBA?function_name=balanceOf&method_id=00fdd58e&args%5B%5D=0x5360f5437cc9be8770c1b2b282cc5a222226ad26&args%5B%5D=873
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Integer.parse/2
        (elixir 1.13.1) lib/integer.ex:275: Integer.parse(nil, 10)
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:110: BlockScoutWeb.SmartContractController.show/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
2022-05-04T16:51:19.773 [error] #PID<0.3525.68> running BlockScoutWeb.Endpoint (connection #PID<0.3571.68>, stream id 1) terminated
Server: ...
Request: GET /smart-contracts/0x93d0c9a35c43f6BC999416A06aaDF21E68B29EBA?function_name=balanceOf&method_id=00fdd58e&args%5B%5D=0x5360f5437cc9be8770c1b2b282cc5a222226ad26&args%5B%5D=873
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Integer.parse/2
        (elixir 1.13.1) lib/integer.ex:275: Integer.parse(nil, 10)
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:110: BlockScoutWeb.SmartContractController.show/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
2022-05-04T16:51:20.167 [error] #PID<0.4029.68> running BlockScoutWeb.Endpoint (connection #PID<0.3920.68>, stream id 1) terminated
Server: ...
Request: GET /smart-contracts/0x93d0c9a35c43f6BC999416A06aaDF21E68B29EBA?function_name=balanceOf&method_id=00fdd58e&args%5B%5D=0x5360f5437cc9be8770c1b2b282cc5a222226ad26&args%5B%5D=873
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Integer.parse/2
        (elixir 1.13.1) lib/integer.ex:275: Integer.parse(nil, 10)
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:110: BlockScoutWeb.SmartContractController.show/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
```

Let's handle it.

**Comment by nikitosing** [comment]
@vbaranov Is the issue still actual?

**Comment by vbaranov** [comment]
@nikitosing yes

From fresh log:

```
2022-09-14T11:28:10.943 [error] #PID<0.12254.0> running BlockScoutWeb.Endpoint (connection #PID<0.12253.0>, stream id 1) terminated
Server: ... (http)
Request: GET /smart-contracts/0x93d0c9a35c43f6BC999416A06aaDF21E68B29EBA?function_name=balanceOf&method_id=00fdd58e&args%5B%5D=0x4320f0ba8333ba285506d885cf798bc2ca578ad7&args%5B%5D=873
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Integer.parse/2
        (elixir 1.13.1) lib/integer.ex:275: Integer.parse(nil, 10)
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/smart_contract_controller.ex:167: BlockScoutWeb.SmartContractController.show/2
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 4.1.8) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
```
