### ISSUE TITLE
Search results: no function clause matching in BlockScoutWeb.AddressView.token_title/1

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#5519]
```
Request: GET /search-results?q=xdai&type=JSON
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in BlockScoutWeb.AddressView.token_title/1
        (block_scout_web 0.0.1) lib/block_scout_web/views/address_view.ex:286: BlockScoutWeb.AddressView.token_title(%{address_hash: "0xdBF3Ea6F5beE45c02255B2c26a16F300502F68da", block_hash: nil, block_number: 0, foreign_chain_id: #Decimal<1>, foreign_token_hash: "0x19062190B1925b5b6689D7073fDfC8c2976EF8Cb", holder_count: 207363, inserted_at: ~U[2021-06-11 07:13:22.006166Z], name: "BZZ on xDai", symbol: "BZZ", tx_hash: nil, type: "token"})
        (block_scout_web 0.0.1) lib/block_scout_web/templates/search/_tile.html.eex:24: BlockScoutWeb.SearchView."_tile.html"/1
        (phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.13) lib/phoenix/view.ex:479: Phoenix.View.render_to_string/3
        (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/search_controller.ex:31: BlockScoutWeb.SearchController.search_results/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/search_controller.ex:1: BlockScoutWeb.SearchController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/search_controller.ex:1: BlockScoutWeb.SearchController.phoenix_controller_pipeline/2
```

**Comment by vbaranov** [comment]
Resolved
