### ISSUE TITLE
Internal server error in token overview_view 

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#5590]
I think something escaped in this commit https://github.com/blockscout/blockscout/commit/726938148193799edc0f020b188a3432d6e81999 or this one https://github.com/blockscout/blockscout/commit/f47e1dd8961ee6ee32cd6d8c57725e4f53fbd1bb

Is it because conditions no longer check for `instance.metadata`?

Error:
```
** (exit) an exception was raised:
    ** (ArgumentError) the Access calls for keywords expect the key to be an atom, got: "image"
        (elixir 1.13.0) lib/access.ex:310: Access.get/3
        (block_scout_web 0.0.1) lib/block_scout_web/views/tokens/instance/overview_view.ex:48: BlockScoutWeb.Tokens.Instance.OverviewView.get_media_src/2
        (block_scout_web 0.0.1) lib/block_scout_web/views/tokens/instance/overview_view.ex:30: BlockScoutWeb.Tokens.Instance.OverviewView.media_src/2
        (block_scout_web 0.0.1) lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex:64: BlockScoutWeb.Tokens.Instance.OverviewView."_details.html"/1
        (block_scout_web 0.0.1) lib/block_scout_web/templates/tokens/instance/transfer/index.html.eex:2: BlockScoutWeb.Tokens.Instance.TransferView."index.html"/1
        (phoenix 1.5.13) lib/phoenix/view.ex:310: Phoenix.View.render_within/3
        (phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.13) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
```

### Environment

* Blockscout Version/branch: 4.1.3

**Comment by ss75710541** [comment]
I have the same problem

**Comment by vbaranov** [comment]
@cen1 @ss75710541 do you have an example of metadata, which can cause such error on the backend?

**Comment by cen1** [comment]
I can't see any more errors after adding this patch, makes sense?

```
defp get_media_src(metadata, high_quality_media?) do
    cond do
      - metadata["animation_url"] && high_quality_media? ->
      + metadata && metadata["animation_url"] && high_quality_media? ->
        retrieve_image(metadata["animation_url"])

      - metadata["image_url"] ->
      + metadata && metadata["image_url"] ->
        retrieve_image(metadata["image_url"])

      - metadata["image"] ->
      + metadata && metadata["image"] ->
        retrieve_image(metadata["image"])

      - metadata["properties"]["image"]["description"] ->
      + metadata && metadata["properties"]["image"]["description"] ->
        metadata["properties"]["image"]["description"]

```

**Comment by vbaranov** [comment]
@cen1 do you have this line in your instance https://github.com/blockscout/blockscout/blob/971b5d1041ef6a47776e05fcb16d12aeb9e20268/apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex#L35 ? If yes, the change, you suggested, looks reundant.

**Comment by cen1** [comment]
I do. Not sure.. since I can't find any instances of this error in our logs at the moment I can't reproduce it. I'll close this for now and reopen if I ever see it again.
