### ISSUE TITLE
Database error on installation "This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval"

### ISSUE THREAD

**Issue by nikolay-nikolaev** [blockscout/blockscout#5608]
When trying to `mix do ecto.create, ecto.migrate`
Get next error:

** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
    (elixir 1.13.0) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.13.0) lib/enum.ex:143: Enumerable.reduce/3
    (elixir 1.13.0) lib/enum.ex:4143: Enum.reverse/1
    (elixir 1.13.0) lib/keyword.ex:186: Keyword.new/2
    (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
    (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
    (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
    (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
    (explorer 0.0.1) lib/explorer/repo.ex:2: Explorer.Repo.config/0
    (ecto 3.7.1) lib/mix/tasks/ecto.create.ex:53: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir 1.13.0) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (elixir 1.13.0) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]
Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Operating System:
Ubuntu 20.04
* Blockscout Version/branch: 
commit 8e4c73cfd480be54fde2eb895d330a7e4f2b281c (HEAD -> master, origin/master, origin/HEAD)

Database RDS in AWS with PostgreSQL. Tried versions: 13.4, 13.6, 14.2

### Steps to reproduce
Install as described here https://docs.blockscout.com/for-developers/manual-deployment

```
git clone https://github.com/poanetwork/blockscout
cd blockscout
mix do deps.get, local.rebar --force, deps.compile
mix phx.gen.secret
export SECRET_KEY_BASE=...
export DATABASE_URL=...
...
mix compile
mix do ecto.create, ecto.migrate
```

### Expected behaviour

blockscout should be installed & can be run.

### Actual behaviour

Can't finish because of database error

**Comment by vbaranov** [comment]
@nikolay-nikolaev could you try updating to Elixir 1.13.4?

**Comment by nikolay-nikolaev** [comment]
I updated to Elixir 1.13.4 & installed `sudo apt-get install libgmp3-dev`
but didn't update nodejs to 16 version yet. So `mix do ecto.create, ecto.migrate` gives error:

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir 1.13.4) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.13.4) lib/enum.ex:143: Enumerable.reduce/3
    (elixir 1.13.4) lib/enum.ex:4144: Enum.reverse/1
    (elixir 1.13.4) lib/keyword.ex:186: Keyword.new/2
    (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
    (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
    (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
    (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
    (explorer 0.0.1) lib/explorer/repo.ex:2: Explorer.Repo.config/0
    (ecto 3.7.1) lib/mix/tasks/ecto.create.ex:53: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Comment by nikolay-nikolaev** [comment]
Yes, I set it just before execute. I tried with Postgres 14. Without set DATABASE_URL I get different error:
```
15:00:22.519 [error] GenServer #PID<0.763.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

15:00:22.539 [error] GenServer #PID<0.769.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Explorer.Repo couldn't be created: killed
```

**Comment by nikolay-nikolaev** [comment]
@vbaranov also tried with Postgres 13.4. The same error.

**Comment by nikolay-nikolaev** [comment]
@vbaranov I tried from scratch. And returned back to the initial error:

Here is the steps on Ubuntu 20.04

```
wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
sudo apt-get update
sudo apt-get install esl-erlang
sudo apt-get install nodejs
sudo apt-get install libgmp3-dev
sudo apt-get install npm
sudo apt-get install automake
sudo apt-get install libtool
sudo apt-get install inotify-tools
sudo apt install make
sudo apt-get install g++
sudo apt-get install cargo
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh


curl -s https://deb.nodesource.com/setup_16.x | sudo bash
sudo apt-get install -y nodejs

git clone https://github.com/elixir-lang/elixir.git
cd elixir
make clean install

#Add elixir to the PATH

git clone https://github.com/poanetwork/blockscout
cd blockscout
mix do deps.get, local.rebar --force, deps.compile, compile
mix phx.gen.secret

export SECRET_KEY_BASE=...
export ETHEREUM_JSONRPC_VARIANT=besu
export ETHEREUM_JSONRPC_HTTP_URL=http://...:8545
export ETHEREUM_JSONRPC_WS_URL=ws://...:8550
export ETHEREUM_JSONRPC_TRACE_URL=http://...:8545
export BLOCK_TRANSFORMER=base
export COIN=EKTA
export NETWORK=EKTA Chain
export SUBNETWORK=EktaScan
export DATABASE_URL=postgresql://postgres:...@....rds.amazonaws.com:5432/explorer

mix do ecto.create, ecto.migrate
```


```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
    (elixir 1.13.4) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.13.4) lib/enum.ex:143: Enumerable.reduce/3
    (elixir 1.13.4) lib/enum.ex:4144: Enum.reverse/1
    (elixir 1.13.4) lib/keyword.ex:186: Keyword.new/2
    (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
    (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
    (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
    (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
    (explorer 0.0.1) lib/explorer/repo.ex:2: Explorer.Repo.config/0
    (ecto 3.7.1) lib/mix/tasks/ecto.drop.ex:80: Mix.Tasks.Ecto.Drop.drop_database/2
    (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Comment by nikolay-nikolaev** [comment]
@vbaranov the same problem with docker version. Here is the steps to repeat

Compile
```
git clone https://github.com/poanetwork/blockscout
cd blockscout
cp docker/Dockerfile .
docker build -t blockscout --build-arg COIN=EKTA .
```
Run it
```
docker run --rm --name test \
>     -e 'MIX_ENV=prod' \
>     -e 'DATABASE_URL=postgresql://postgres:...@...:5432/explorer' \
>     -e 'ETHEREUM_JSONRPC_VARIANT=besu' \
>     -e 'ETHEREUM_JSONRPC_HTTP_URL=http://...:8545' \
>     -e 'ETHEREUM_JSONRPC_WS_URL=ws://...:8550' \
>     -e 'ETHEREUM_JSONRPC_TRACE_URL=http://...:8545' \
>     -e 'BLOCK_TRANSFORMER=base' \
>     -e 'COIN=EKTA' \
>     -e 'NETWORK=EKTA Chain' \
>     -e 'SUBNETWORK=EktaScan' \
>     -p 4000:4000 \
>     blockscout /bin/sh -c "mix phx.server"
```

And result is:
```
2022-05-26T04:30:04.914 application=tzdata [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Wed, 16 Mar 2022 13:36:02 GMT.
2022-05-26T04:30:09.798 application=tzdata [info] Tzdata has updated the release from 2021e to 2022a
2022-05-26T04:30:15.895 application=que [info] [Que] Booting Que
2022-05-26T04:30:15.896 application=que [info] [Que] Booting Server Supervisor for Workers
2022-05-26T04:30:15.898 [notice] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Repo
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
            (elixir 1.13.1) lib/enum.ex:1: Enumerable.impl_for!/1
            (elixir 1.13.1) lib/enum.ex:143: Enumerable.reduce/3
            (elixir 1.13.1) lib/enum.ex:4144: Enum.reverse/1
            (elixir 1.13.1) lib/keyword.ex:186: Keyword.new/2
            (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
            (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
            (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
            (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
2022-05-26T04:30:15.899 [notice] Application cbor exited: :stopped
2022-05-26T04:30:15.900 [notice] Application con_cache exited: :stopped
2022-05-26T04:30:15.900 [notice] Application spandex_ecto exited: :stopped
2022-05-26T04:30:15.901 [notice] Application que exited: :stopped
2022-05-26T04:30:15.901 [notice] Application ex_utils exited: :stopped
2022-05-26T04:30:15.901 [notice] Application memento exited: :stopped
2022-05-26T04:30:15.902 [notice] Application mnesia exited: :stopped
2022-05-26T04:30:15.902 [notice] Application prometheus_ecto exited: :stopped
2022-05-26T04:30:15.902 [notice] Application prometheus_ex exited: :stopped
2022-05-26T04:30:15.903 [notice] Application prometheus exited: :stopped
2022-05-26T04:30:15.903 [notice] Application quantile_estimator exited: :stopped
2022-05-26T04:30:15.904 [notice] Application postgrex exited: :stopped
2022-05-26T04:30:15.904 [notice] Application nimble_csv exited: :stopped
2022-05-26T04:30:15.904 [notice] Application poison exited: :stopped
2022-05-26T04:30:15.905 [notice] Application phoenix_html exited: :stopped
2022-05-26T04:30:15.905 [notice] Application math exited: :stopped
2022-05-26T04:30:15.906 [notice] Application ecto_sql exited: :stopped
2022-05-26T04:30:15.906 [notice] Application db_connection exited: :stopped
2022-05-26T04:30:15.906 [notice] Application connection exited: :stopped
2022-05-26T04:30:15.907 [notice] Application ecto exited: :stopped
2022-05-26T04:30:15.907 [notice] Application dataloader exited: :stopped
2022-05-26T04:30:15.907 [notice] Application comeonin exited: :stopped
2022-05-26T04:30:15.908 [notice] Application briefly exited: :stopped
2022-05-26T04:30:15.908 [notice] Application bcrypt_elixir exited: :stopped
2022-05-26T04:30:15.908 [notice] Application tesla exited: :stopped
2022-05-26T04:30:15.909 [notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Repo
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
            (elixir 1.13.1) lib/enum.ex:1: Enumerable.impl_for!/1
            (elixir 1.13.1) lib/enum.ex:143: Enumerable.reduce/3
            (elixir 1.13.1) lib/enum.ex:4144: Enum.reverse/1
            (elixir 1.13.1) lib/keyword.ex:186: Keyword.new/2
            (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
            (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
            (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
            (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
```

**Comment by nikolay-nikolaev** [comment]
@vbaranov sorry for bothering you. But looks like installation of the latest version from master is not working completely because ion this error. Even docker version.

**Comment by vbaranov** [comment]
@nikolay-nikolaev not really, The latest master was installed on several production instances without issues. Most likely, the issue is with `DATABASE_URL` value, which you use on your instance. Please provide details, how does DB connection string look like (hide sensitive info).

**Comment by nikolay-nikolaev** [comment]
export DATABASE_URL=postgresql://postgres:Kjhuw778-1j33jsl-KsjJds@ektascan.ccdpijlt90im.ap-northeast-2.rds.amazonaws.com:5432/explorer

**Comment by nikolay-nikolaev** [comment]
@vbaranov 
May be something wrong with Erlang version?
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit:ns]
Elixir 1.13.4 (compiled with Erlang/OTP 24)

**Comment by vbaranov** [comment]
> May be something wrong with Erlang version?

The last tested by the team is `1.13.4-otp-24 `
https://github.com/blockscout/blockscout/blob/e7774476bb456c210f31b7fe0d13bfaa207e4795/.tool-versions#L1

**Comment by vbaranov** [comment]
@nikolay-nikolaev I suppose, most likely your issue relates to this one https://github.com/blockscout/blockscout/issues/5331#issuecomment-1083321312 (special characters in the password field)

**Comment by ekawibisono** [comment]
Hello,

I Have Same A Problem, How to Fix it? @nikolay-nikolaev @vbaranov 
![Screenshot from 2022-07-11 12-39-09](https://user-images.githubusercontent.com/22586872/178196772-ec6ab5b5-6cac-44db-9969-637d9814f375.png)

Please Help
