### ISSUE TITLE
Install Node.js dependencies gives 2 high severity vulnerabilities

### ISSUE THREAD

**Issue by nikolay-nikolaev** [blockscout/blockscout#5609]
NPM INSTALL doesn't work
`cd apps/block_scout_web/assets; npm install && node_modules/webpack/bin/webpack.js --mode production; cd -`
```
found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[webpack-cli] HookWebpackError: Not supported
    at makeWebpackError (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at hooks.processAssets.callAsync.err (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:3058:12)
    at eval (eval at create (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:54:1)
    at err (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:509:26)
    at compilation.hooks.processAssets.tapAsync (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/copy-webpack-plugin/dist/index.js:708:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-- inner error --
Error: Not supported
    at compilation.hooks.processAssets.tapAsync (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/copy-webpack-plugin/dist/index.js:704:13)
    at fn (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:508:9)
    at Hook.eval [as callAsync] (eval at create (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:3055:34)
    at createChunkAssets.err (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:3103:10)
    at symbolIterator (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/neo-async/async.js:3485:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
caused by plugins in Compilation.hooks.processAssets
Error: Not supported
    at compilation.hooks.processAssets.tapAsync (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/copy-webpack-plugin/dist/index.js:704:13)
    at fn (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:508:9)
    at Hook.eval [as callAsync] (eval at create (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:3055:34)
    at createChunkAssets.err (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:3103:10)
    at symbolIterator (/home/ekta/blockscout/apps/block_scout_web/assets/node_modules/neo-async/async.js:3485:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]
Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Operating System:
Ubuntu 20.04
npm --version
6.14.4
nodejs --version
v10.19.0

* Blockscout Version/branch: 
commit https://github.com/blockscout/blockscout/commit/8e4c73cfd480be54fde2eb895d330a7e4f2b281c (HEAD -> master, origin/master, origin/HEAD)

### Steps to reproduce

Installation process breaks on NPM INSTALL
`cd apps/block_scout_web/assets; npm install && node_modules/webpack/bin/webpack.js --mode production; cd -`

npm audit fix doesn't help

### Expected behaviour

Installed modules

### Actual behaviour

Error

**Comment by nikolay-nikolaev** [comment]
@vbaranov not sure I know how to do it. I used this instruction for ubuntu https://elixir-lang.org/install.html#gnulinux

**Comment by vbaranov** [comment]
@nikolay-nikolaev most likely `libgmp3-dev` is missing. Can you try https://github.com/blockscout/blockscout/issues/3593#issuecomment-1016022910 ?
