### ISSUE TITLE
ERROR 22021 (character_not_in_repertoire) invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by SKlayer** [blockscout/blockscout#5618]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions:Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit]
* Operating System: Ubuntu 22.04
* Blockscout Version/branch: 9e64d3685bb50ac4558605fdb20b9aa0f8d54fee

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour
`
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [%Explorer.Chain.Hash{byte_count: 20, bytes: <<211, 176, 238, 103, 16, 113, 232, 207, 253, 181, 112, 203, 212, 87, 183, 215, 223, 151, 229, 144>>}], callback_module: Indexer.FeONRPC.HTTP.HTTPoison, url: "http://10.0.1.127:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Ganache], metadata: []}]
2022-05-26T20:18:22.477 [error] Task #PID<0.182.127> started from Indexer.Fetcher.Token terminating
** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire) invalid byte sequence for encoding "UTF8": 0xf0 0x9f 0x8c
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (explorer 0.0.1) lib/explorer/chain.ex:5751: anonymous fn/3 in Explorer.Chain.update_token/2
    (ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.7.1) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4
    (ecto 3.7.1) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4
    (explorer 0.0.1) lib/explorer/chain.ex:5761: Explorer.Chain.update_token/2
    (indexer 0.1.0) lib/indexer/fetcher/token.ex:77: Indexer.Fetcher.Token.catalog_token/1
    (indexer 0.1.0) lib/indexer/fetcher/token.ex:59: Indexer.Fetcher.Token.run/2
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
`

**Comment by vbaranov** [comment]
@SKlayer do you have a token on address hash `0xd3b0ee671071e8cffdb570cbd457b7d7df97e590`? Is it visible from Blockscout's UI?

**Comment by SKlayer** [comment]
Here is this erc-20 token name and symbol:
Information
Name
🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙
Symbol
🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙🌙
Total Supply
1,000
Decimals
0
Contract code:
`608060405234801561001057600080fd5b50600436106101215760003560e01c806370a08231116100ad57806395d89b411161007157806395d89b4114610235578063a457c2d71461023d578063a9059cbb14610250578063dd62ed3e14610263578063f2fde38b1461029c57610121565b806370a08231146101e4578063715018a6146101f7578063797bec77146101ff57806379cc6790146102075780638da5cb5b1461021a57610121565b806323b872dd116100f457806323b872dd14610181578063313ce5671461019457806339509351146101a957806340c10f19146101bc57806342966c68146101cf57610121565b8063044ab74e1461012657806306fdde0314610144578063095ea7b31461014c57806318160ddd1461016f575b600080fd5b61012e6102af565b60405161013b9190610d15565b60405180910390f35b61012e610341565b61015f61015a366004610cd4565b610350565b604051901515815260200161013b565b6002545b60405190815260200161013b565b61015f61018f366004610c99565b610366565b60085460405160ff909116815260200161013b565b61015f6101b7366004610cd4565b610415565b61015f6101ca366004610cd4565b610451565b6101e26101dd366004610cfd565b610488565b005b6101736101f2366004610c46565b610495565b6101e26104b4565b600754610173565b6101e2610215366004610cd4565b6104ea565b6005546040516001600160a01b03909116815260200161013b565b61012e610570565b61015f61024b366004610cd4565b61057f565b61015f61025e366004610cd4565b610618565b610173610271366004610c67565b6001600160a01b03918216600090815260016020908152604080832093909416825291909152205490565b6101e26102aa366004610c46565b610625565b6060600680546102be90610dcc565b80601f01602080910402602001604051908101604052809291908181526020018280546102ea90610dcc565b80156103375780601f1061030c57610100808354040283529160200191610337565b820191906000526020600020905b81548152906001019060200180831161031a57829003601f168201915b5050505050905090565b6060600380546102be90610dcc565b600061035d3384846106bd565b50600192915050565b60006103738484846107e1565b6001600160a01b0384166000908152600160209081526040808320338452909152902054828110156103fd5760405162461bcd60e51b815260206004820152602860248201527f45524332303a207472616e7366657220616d6f756e74206578636565647320616044820152676c6c6f77616e636560c01b60648201526084015b60405180910390fd5b61040a85338584036106bd565b506001949350505050565b3360008181526001602090815260408083206001600160a01b0387168452909152812054909161035d91859061044c908690610d9d565b6106bd565b6005546000906001600160a01b0316331461047e5760405162461bcd60e51b81526004016103f490610d68565b61035d83836109b0565b6104923382610a8f565b50565b6001600160a01b0381166000908152602081905260409020545b919050565b6005546001600160a01b031633146104de5760405162461bcd60e51b81526004016103f490610d68565b6104e86000610bdd565b565b60006104f68333610271565b9050818110156105545760405162461bcd60e51b8152602060048201526024808201527f45524332303a206275726e20616d6f756e74206578636565647320616c6c6f77604482015263616e636560e01b60648201526084016103f4565b61056183338484036106bd565b61056b8383610a8f565b505050565b6060600480546102be90610dcc565b3360009081526001602090815260408083206001600160a01b0386168452909152812054828110156106015760405162461bcd60e51b815260206004820152602560248201527f45524332303a2064656372656173656420616c6c6f77616e63652062656c6f77604482015264207a65726f60d81b60648201526084016103f4565b61060e33858584036106bd565b5060019392505050565b600061035d3384846107e1565b6005546001600160a01b0316331461064f5760405162461bcd60e51b81526004016103f490610d68565b6001600160a01b0381166106b45760405162461bcd60e51b815260206004820152602660248201527f4f776e61626c653a206e6577206f776e657220697320746865207a65726f206160448201526564647265737360d01b60648201526084016103f4565b61049281610bdd565b6001600160a01b03831661071f5760405162461bcd60e51b8152602060048201526024808201527f45524332303a20617070726f76652066726f6d20746865207a65726f206164646044820152637265737360e01b60648201526084016103f4565b6001600160a01b0382166107805760405162461bcd60e51b815260206004820152602260248201527f45524332303a20617070726f766520746f20746865207a65726f206164647265604482015261737360f01b60648201526084016103f4565b6001600160a01b0383811660008181526001602090815260408083209487168084529482529182902085905590518481527f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925910160405180910390a3505050565b6001600160a01b0383166108455760405162461bcd60e51b815260206004820152602560248201527f45524332303a207472616e736665722066726f6d20746865207a65726f206164604482015264647265737360d81b60648201526084016103f4565b6001600160a01b0382166108a75760405162461bcd60e51b815260206004820152602360248201527f45524332303a207472616e7366657220746f20746865207a65726f206164647260448201526265737360e81b60648201526084016103f4565b6001600160a01b0383166000908152602081905260409020548181101561091f5760405162461bcd60e51b815260206004820152602660248201527f45524332303a207472616e7366657220616d6f756e7420657863656564732062604482015265616c616e636560d01b60648201526084016103f4565b6001600160a01b03808516600090815260208190526040808220858503905591851681529081208054849290610956908490610d9d565b92505081905550826001600160a01b0316846001600160a01b03167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040516109a291815260200190565b60405180910390a350505050565b6001600160a01b038216610a065760405162461bcd60e51b815260206004820152601f60248201527f45524332303a206d696e7420746f20746865207a65726f20616464726573730060448201526064016103f4565b8060026000828254610a189190610d9d565b90915550506001600160a01b03821660009081526020819052604081208054839290610a45908490610d9d565b90915550506040518181526001600160a01b038316906000907fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9060200160405180910390a35050565b6001600160a01b038216610aef5760405162461bcd60e51b815260206004820152602160248201527f45524332303a206275726e2066726f6d20746865207a65726f206164647265736044820152607360f81b60648201526084016103f4565b6001600160a01b03821660009081526020819052604090205481811015610b635760405162461bcd60e51b815260206004820152602260248201527f45524332303a206275726e20616d6f756e7420657863656564732062616c616e604482015261636560f01b60648201526084016103f4565b6001600160a01b0383166000908152602081905260408120838303905560028054849290610b92908490610db5565b90915550506040518281526000906001600160a01b038516907fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9060200160405180910390a361056b565b600580546001600160a01b038381166001600160a01b0319831681179093556040519116919082907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e090600090a35050565b80356001600160a01b03811681146104af57600080fd5b600060208284031215610c57578081fd5b610c6082610c2f565b9392505050565b60008060408385031215610c79578081fd5b610c8283610c2f565b9150610c9060208401610c2f565b90509250929050565b600080600060608486031215610cad578081fd5b610cb684610c2f565b9250610cc460208501610c2f565b9150604084013590509250925092565b60008060408385031215610ce6578182fd5b610cef83610c2f565b946020939093013593505050565b600060208284031215610d0e578081fd5b5035919050565b6000602080835283518082850152825b81811015610d4157858101830151858201604001528201610d25565b81811115610d525783604083870101525b50601f01601f1916929092016040019392505050565b6020808252818101527f4f776e61626c653a2063616c6c6572206973206e6f7420746865206f776e6572604082015260600190565b60008219821115610db057610db0610e07565b500190565b600082821015610dc757610dc7610e07565b500390565b600181811c90821680610de057607f821691505b60208210811415610e0157634e487b7160e01b600052602260045260246000fd5b50919050565b634e487b7160e01b600052601160045260246000fdfea2646970667358221220a3ef43621c5a6ce8c41dbb34be8b5bd1a1f2b218d9ee4523f6555a26c53d2c0164736f6c63430008030033`

**Comment by vbaranov** [comment]
Resolved by https://github.com/blockscout/blockscout/pull/6475
