### ISSUE TITLE
Manual Deployment fails on ecto.create, ecto.migrate 

### ISSUE THREAD

**Issue by ZeljkoBenovic** [blockscout/blockscout#5688]
Hi,

When following [Manual Delployment ](https://docs.blockscout.com/for-developers/manual-deployment) instructions the process fails when `migrate database` step is reached.
Specifically, when the user tries to run step `10) Create and migrate database mix do ecto.create, ecto.migrate` it fails with an error:   
 `** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom.`

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): `Elixir 1.13.0` / `Erlang/OTP 24 [erts-12.3.1]`
* Operating System: Ubuntu 20.04 LTS ( AWS AMI )
* Blockscout Version/branch:  branch: `master` , commit: 81cc3808f74a260e3ca0b78d75670409d0e94ba3

### Steps to reproduce

Spin up a fresh Ubuntu 20.04 server and try following the [Manual Deployment](https://docs.blockscout.com/for-developers/manual-deployment) instructions. The bug should appear at step 10.

In case additional instructions for manual deployment on Ubuntu are needed, check out [this](https://edge-docs.polygon.technology/docs/additional-features/blockscout) instructions

One thig to note: The build runs just fine with branch `v4.1.1-beta` and it fails from branch `v4.1.2-beta` and above.

### Expected behaviour

The Manual Deployment process should run without any issues.

### Actual behaviour

Step 10 on Manual Deployment doc fails with an error.   
Full error log:
```
ubuntu@ip-10-230-254-88:~/blockscout$ mix do ecto.drop, ecto.create, ecto.migrate
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
    (elixir 1.13.0) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.13.0) lib/enum.ex:143: Enumerable.reduce/3
    (elixir 1.13.0) lib/enum.ex:4143: Enum.reverse/1
    (elixir 1.13.0) lib/keyword.ex:186: Keyword.new/2
    (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
    (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
    (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
    (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
    (explorer 0.0.1) lib/explorer/repo.ex:2: Explorer.Repo.config/0
    (ecto 3.7.1) lib/mix/tasks/ecto.drop.ex:80: Mix.Tasks.Ecto.Drop.drop_database/2
    (elixir 1.13.0) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (elixir 1.13.0) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Comment by vbaranov** [comment]
@ZeljkoBenovic could you please apply this update https://github.com/blockscout/blockscout/pull/5690? It is meant to resolve the issue.

**Comment by iamhammadaali** [comment]
I'm still getting this error.

**Comment by lamnn8** [comment]
so do i, how to fix it.

**Comment by YounesBM** [comment]
Hi @iamhammadaali, @lamnn8,

Does your DATABASE_URL match the following regex ?

https://github.com/blockscout/blockscout/blob/e8e52edb47f2ab9884d9383127c736ceb0e21c93/apps/explorer/lib/explorer/repo/config_helper.ex#L45

I had the same problem, I just forgot to specify the port.

**Comment by nowjean** [comment]
Super weird! I got same error on v4.1.5-beta. 
But, this issue can be resolved with v4.0.0-beta
