### ISSUE TITLE
Relation "last_fetched_counters" does not exist

### ISSUE THREAD

**Issue by Microsxema** [blockscout/blockscout#5722]
Please help me to solve the problem to avoid it in the future. There was a day with such an error, after that everything was fine. As if he did not create this table, or perhaps the migration did not go through.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit] Elixir 1.13.3 (compiled with Erlang/OTP 22)
* Operating System: Centos
* Blockscout Version/branch: [bb54235](https://github.com/blockscout/blockscout/commit/bb542353d9220a70686e742c6aecf63d5461cd0e)

### Actual behaviour
![image](https://user-images.githubusercontent.com/30797028/177262004-2d277679-7ea8-4b88-9d6a-603322136063.png)

```
2022-06-24T12:22:11.651 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({%Postgrex.Error{connection_id: 54101, message: nil, pos
tgres: %{code: :undefined_table, file: "parse_relation.c", line: "1384", message: "relation \"last_fetched_counters\" does not exist", pg_code: "42P01", position: "24", ro
utine: "parserOpenTable", severity: "ERROR", unknown: "ERROR"}, query: "SELECT l0.\"value\" FROM \"last_fetched_counters\" AS l0 WHERE (l0.\"counter_type\" = $1)"}, [{Ecto
.Adapters.SQL, :raise_sql_call_error, 1, [file: 'lib/ecto/adapters/sql.ex', line: 756, error_info: %{module: Exception}]}, {Ecto.Adapters.SQL, :execute, 5, [file: 'lib/ect
o/adapters/sql.ex', line: 689]}, {Ecto.Repo.Queryable, :execute, 4, [file: 'lib/ecto/repo/queryable.ex', line: 219]}, {Ecto.Repo.Queryable, :all, 3, [file: 'lib/ecto/repo/
queryable.ex', line: 19]}, {Ecto.Repo.Queryable, :one!, 3, [file: 'lib/ecto/repo/queryable.ex', line: 154]}, {Explorer.Chain, :get_last_fetched_counter, 1, [file: 'lib/exp
lorer/chain.ex', line: 2918]}, {Indexer.Block.Catchup.Fetcher, :last_block, 0, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 360]}, {Indexer.Block.Catchup.Fetcher,
:task, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 83]}]}). Restarting
2022-06-24T12:22:11.655 fetcher=block_catchup [error] Task #PID<0.9640.0> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "last_fetched_counters" does not exist

    query: SELECT l0."value" FROM "last_fetched_counters" AS l0 WHERE (l0."counter_type" = $1)
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one!/3
    (explorer 0.0.1) lib/explorer/chain.ex:2918: Explorer.Chain.get_last_fetched_counter/1
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:360: Indexer.Block.Catchup.Fetcher.last_block/0
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:83: Indexer.Block.Catchup.Fetcher.task/1
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_argumen
ts: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://10.114.0.10/", http_options: [recv_timeout: 600000, timeout: 6
00000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency
: 10, memory_monitor: Indexer.Memory.Monitor}]
2022-06-24T12:22:11.656 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({%Postgrex.Error{connection_id: 54102, message: nil, pos
tgres: %{code: :undefined_table, file: "parse_relation.c", line: "1384", message: "relation \"last_fetched_counters\" does not exist", pg_code: "42P01", position: "24", ro
utine: "parserOpenTable", severity: "ERROR", unknown: "ERROR"}, query: "SELECT l0.\"value\" FROM \"last_fetched_counters\" AS l0 WHERE (l0.\"counter_type\" = $1)"}, [{Ecto
.Adapters.SQL, :raise_sql_call_error, 1, [file: 'lib/ecto/adapters/sql.ex', line: 756, error_info: %{module: Exception}]}, {Ecto.Adapters.SQL, :execute, 5, [file: 'lib/ect
o/adapters/sql.ex', line: 689]}, {Ecto.Repo.Queryable, :execute, 4, [file: 'lib/ecto/repo/queryable.ex', line: 219]}, {Ecto.Repo.Queryable, :all, 3, [file: 'lib/ecto/repo/
queryable.ex', line: 19]}, {Ecto.Repo.Queryable, :one!, 3, [file: 'lib/ecto/repo/queryable.ex', line: 154]}, {Explorer.Chain, :get_last_fetched_counter, 1, [file: 'lib/exp
lorer/chain.ex', line: 2918]}, {Indexer.Block.Catchup.Fetcher, :last_block, 0, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 360]}, {Indexer.Block.Catchup.Fetcher,
:task, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 83]}]}). Restarting
2022-06-24T12:22:11.660 fetcher=block_catchup [error] Task #PID<0.9642.0> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "last_fetched_counters" does not exist
```

**Comment by vbaranov** [comment]
@Microsxema the only possible reason would be the migration https://github.com/blockscout/blockscout/blob/master/apps/explorer/priv/repo/migrations/20200527144742_add_counters_table.exs wasn't executed or failed for some reason. If you have the logs from the DB migration, please, attach them.

**Comment by vbaranov** [comment]
I am closing this for now. Please re-open if you still experience the issue.
