### ISSUE TITLE
(MatchError) no match of right hand side value: <<216, 131, 1, 10, 20, 132, 103, 101, 1 16, 104, 136, 103, 111, 49, 46, 49, 56, 46, 49, 133, 108, 105, 110, 117, 120>>

### ISSUE THREAD

**Issue by mzyan11** [blockscout/blockscout#5750]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):  
  Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]
  Elixir 1.13.4 (compiled with Erlang/OTP 22)
* Operating System: ubuntu 22.04 
* Blockscout Version/branch:  blockscout-4.1.5-beta

### ENV
export DATABASE_URL="postgresql://blockroot:blockRoot@localhost:5432/block"

export DB_HOST="127.0.0.1"
export DB_PASSWORD="blockRoot"
export DB_PORT=5432
export DB_USERNAME="blockroot"
export SECRET_KEY_BASE="pxqV6QNO/tM8yi986PyTqCDmfF6/rD3GAwi3uoUZ/yCKkDE9ShMPc2pn5wurfDig"

export COIN="ETH"
export ETHEREUM_JSONRPC_VARIANT="geth"
export ETHEREUM_JSONRPC_HTTP_URL="http://192.168.0.30:8545" 
export ETHEREUM_JSONRPC_WS_URL="ws://192.168.0.30:8546" 
export ETHEREUM_JSONRPC_TRACE_URL="http://192.168.0.30:8545" 
export BLOCK_TRANSFORMER="clique"
export NETWORK="Ethereum"
export MIX_ENV="prod"

export PORT=4000
export BLOCKSCOUT_VERSION="v4.1.5-beta"

### error log

 2022-07-14T18:57:55.256 application=tzdata [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Wed, 16 Mar 2022 13:36:02 GMT.
2022-07-14T18:57:58.862 application=tzdata [info] Tzdata has updated the release from 2021e to 2022a
2022-07-14T18:58:04.966 application=que [info] [Que] Booting Que
2022-07-14T18:58:04.966 application=que [info] [Que] Booting Server Supervisor for Workers
2022-07-14T18:58:04.978 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.979 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.979 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.983 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.985 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.989 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.989 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.989 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.989 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.989 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.998 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.998 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.998 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.998 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.998 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.999 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:04.999 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.004 application=explorer [info] tx/per day chart: collect records for txs per day stats
2022-07-14T18:58:05.004 application=explorer [info] tx/per day chart: earliest date 2022-06-05 00:00:00Z
2022-07-14T18:58:05.004 application=explorer [info] tx/per day chart: latest date 2022-06-05 23:59:59Z
2022-07-14T18:58:05.014 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.014 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.014 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.014 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.018 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.018 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.021 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.023 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.023 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.024 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.027 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.029 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.029 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.032 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.032 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.033 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.038 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.038 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.038 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.038 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.038 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.038 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.039 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.041 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.045 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.046 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.046 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.047 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.047 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.047 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.048 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.049 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.049 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:05.049 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-14T18:58:06.988 application=explorer [info] tx/per day chart: collect records for txs per day stats
2022-07-14T18:58:06.988 application=explorer [info] tx/per day chart: earliest date 2022-06-06 00:00:00Z
2022-07-14T18:58:06.988 application=explorer [info] tx/per day chart: latest date 2022-06-06 23:59:59Z
2022-07-14T18:58:07.161 application=explorer [warning] Failed to get exchange rates with reason 'Source URL is nil'.
2022-07-14T18:58:07.987 application=explorer [info] tx/per day chart: collect records for txs per day stats
2022-07-14T18:58:07.987 application=explorer [info] tx/per day chart: earliest date 2022-06-07 00:00:00Z
2022-07-14T18:58:07.987 application=explorer [info] tx/per day chart: latest date 2022-06-07 23:59:59Z
2022-07-14T18:58:08.051 application=explorer [info] tx/per day chart: collect records for txs per day stats
2022-07-14T18:58:08.051 application=explorer [info] tx/per day chart: earliest date 2022-06-08 00:00:00Z
2022-07-14T18:58:08.051 application=explorer [info] tx/per day chart: latest date 2022-06-08 23:59:59Z
2022-07-14T18:58:08.068 application=explorer [info] tx/per day chart: collect records for txs per day stats
2022-07-14T18:58:08.068 application=explorer [info] tx/per day chart: earliest date 2022-06-09 00:00:00Z
2022-07-14T18:58:08.068 application=explorer [info] tx/per day chart: latest date 2022-06-09 23:59:59Z
2022-07-14T18:58:08.083 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)
2022-07-14T18:58:08.088 application=phoenix [info] Access BlockScoutWeb.Endpoint at https://localhost:4000
2022-07-14T18:58:08.092 application=explorer [info] tx/per day chart: collect records for txs per day stats
2022-07-14T18:58:08.092 application=explorer [info] tx/per day chart: earliest date 2022-06-10 00:00:00Z
2022-07-14T18:58:08.092 application=explorer [info] tx/per day chart: latest date 2022-06-10 23:59:59Z
2022-07-14T18:58:08.101 application=explorer [info] tx/per day chart: collect records for txs per day stats
2022-07-14T18:58:08.101 application=explorer [info] tx/per day chart: earliest date 2022-06-11 00:00:00Z
2022-07-14T18:58:08.101 application=explorer [info] tx/per day chart: latest date 2022-06-11 23:59:59Z
2022-07-14T18:58:08.112 application=indexer fetcher=block_catchup first_block_number=681 last_block_number=672 [error] ** (MatchError) no match of right hand side value: <<216, 131, 1, 10, 20, 132, 103, 101, 1
16, 104, 136, 103, 111, 49, 46, 49, 56, 46, 49, 133, 108, 105, 110, 117, 120>>
    (indexer 0.1.0) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
    (indexer 0.1.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:132: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:205: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

Retrying.
2022-07-14T18:58:08.115 application=explorer [info] tx/per day chart: collect records for txs per day stats
2022-07-14T18:58:08.115 application=explorer [info] tx/per day chart: earliest date 2022-06-12 00:00:00Z
2022-07-14T18:58:08.115 application=explorer [info] tx/per day chart: latest date 2022-06-12 23:59:59Z
2022-07-14T18:58:08.115 application=indexer fetcher=block_catchup first_block_number=591 last_block_number=582 [error] ** (MatchError) no match of right hand side value: <<216, 131, 1, 10, 20, 132, 103, 101, 1
16, 104, 136, 103, 111, 49, 46, 49, 56, 46, 49, 133, 108, 105, 110, 117, 120>>
    (indexer 0.1.0) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
    (indexer 0.1.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:132: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:205: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

Retrying.

**Comment by mzyan11** [comment]
This will be a problem when I build an eth private chain. When I connect to the eth main chain, there will be no such problem.

**Comment by mzyan11** [comment]
My eth private chain genesis block configuration

{
  "config": {
    "chainId": 8888,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0
  },
  "alloc": {},
  "coinbase": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x20000",
  "extraData": "",
  "gasLimit": "0x2fefd8",
  "nonce": "0x0000000000000042",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
