### ISSUE TITLE
(ArgumentError) invalid Unix time

### ISSUE THREAD

**Issue by TW001ChenYI** [blockscout/blockscout#5897]
(ArgumentError) invalid Unix time

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):12
* Operating System:VMware Ubuntu 18.04 
* Blockscout Version/branch: master
* Private chain:Quorum

### Steps to reproduce

`$ git clone https://github.com/blockscout/blockscout.git master`
`$ cd master/docker`
`$ sudo PORT=4000 ETHEREUM_JSONRPC_VARIANT=geth ETHEREUM_JSONRPC_WS_URL=ws://192.168.216.133:22005 ETHEREUM_JSONRPC_HTTP_URL=http://192.168.216.133:22000 ETHEREUM_JSONRPC_TRACE_URL=http://192.168.216.133:22000 COIN=ETH make start`

### Expected behaviour

![image](https://user-images.githubusercontent.com/86778581/184108756-1f6e4dcd-b6d4-4b1e-a914-37a5e7e26938.png)

### Actual behaviour

Retrying.
2022-08-11T09:53:41.970 application=indexer fetcher=block_catchup first_block_number=2 last_block_number=0 missing_block_count=3 shrunk=false [info] Index had to catch up.
2022-08-11T09:53:41.970 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
2022-08-11T09:53:44.219 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
2022-08-11T09:53:44.238 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
2022-08-11T09:53:44.492 application=indexer fetcher=block_catchup first_block_number=2 last_block_number=0 [error] ** (ArgumentError) invalid Unix time 1660105952047879643
    (elixir 1.13.1) lib/calendar/datetime.ex:402: DateTime.from_unix!/3
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/block.ex:594: EthereumJSONRPC.Block.entry_to_elixir/1
    (elixir 1.13.1) lib/enum.ex:1597: anonymous fn/3 in Enum.map/2
    (stdlib 3.17) maps.erl:410: :maps.fold_1/3
    (elixir 1.13.1) lib/enum.ex:2408: Enum.map/2
    (elixir 1.13.1) lib/enum.ex:1496: Enum.into/3
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2

**Comment by TW001ChenYI** [comment]
@vbaranov Please can you tell me what to do, thanks

**Comment by taoyq1988** [comment]
@TW001ChenYI did you found solution?

**Comment by goodmai** [comment]
I am have same problem with besu  `2024-02-15T14:27:52.282 [error] GenServer Indexer.Block.Catchup.MissingRangesCollector terminating
** (ArgumentError) invalid Unix time 1708002599114
    (elixir 1.14.5) lib/calendar/datetime.ex:413: DateTime.from_unix!/3
    (ethereum_jsonrpc 6.1.0) lib/ethereum_jsonrpc/block.ex:788: EthereumJSONRPC.Block.entry_to_elixir/2
    (elixir 1.14.5) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
    (stdlib 3.17) maps.erl:410: :maps.fold_1/3
    (elixir 1.14.5) lib/enum.ex:2480: Enum.map/2
    (elixir 1.14.5) lib/enum.ex:1552: Enum.into/3
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 6.1.0) lib/ethereum_jsonrpc/blocks.ex:47: EthereumJSONRPC.Blocks.from_responses/2
Last message: {:continue, :ok}
State: %{max_fetched_block_number: nil, min_fetched_block_number: nil}`
