### ISSUE TITLE
GenServer.call(Indexer.Fetcher.InternalTransaction error from RDS 

### ISSUE THREAD

**Issue by royki** [blockscout/blockscout#5928]
*Describe your issue here.*
We have recently upgraded blockscout version to v4.1.5-beta. -> https://explorer.energyweb.org/
Everything was working fine. However from last week, Blockscout db started throwing error of 

```shell
blockscout_1  | 2022-08-12T14:53:30.577 [error] Task #PID<0.3980.361> started from Indexer.Block.Realtime.Fetcher terminating
blockscout_1  | ** (stop) exited in: GenServer.call(Indexer.Fetcher.InternalTransaction, {:buffer, [19426479]}, 10000)
blockscout_1  |     ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
blockscout_1  |     (elixir 1.13.1) lib/gen_server.ex:1019: GenServer.call/3
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:385: Indexer.Block.Realtime.Fetcher.async_import_remaining_block_data/2
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:224: Indexer.Block.Realtime.Fetcher.import/2
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/fetcher.ex:167: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:293: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
blockscout_1  |     (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:276: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
blockscout_1  |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout_1  | Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
blockscout_1  |     Args: [19426479, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://parity:8545", method_to_url: [eth_getBalance: "http://parity:8545", trace_block: "http://parity:8545", trace_replayTransaction: "http://parity:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, false]
```

Constantly throws error logs, and explorer is down time to time, No update of Transaction, Blocks in the explorer even though explorer is up.
- **Recreate Blockscout container gives relief for sometime, however the error appears after sometime and explorer gets stuck again.**

More logs -> https://gist.github.com/royki/8c8a13674f625e6d5a4c87cbd63eefcd
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): `Elixir 1.13.1 (compiled with Erlang/OTP 24)`
* Operating System: `Ubuntu 18.04.1 LTS`
* Blockscout Version/branch: `BlockScout v4.1.5-beta`

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*
- Branch - https://github.com/energywebfoundation/blockscout/tree/ewc_canon
- Release Tag - https://github.com/energywebfoundation/blockscout/tree/v4.1.5-beta

### Expected behaviour
No downtime of Explorer, Transaction, Blocks etc are updated in real time, No blockscout error logs.

### Actual behaviour
Explorer is down time to time, Throws internal server error.
Constantly throws error logs, and explorer is down time to time, No update of Transaction, Blocks in the explorer even though explorer is up. 
No need to recreate the blockscout container.

**Comment by royki** [comment]
Hi @vbaranov , Can you please take a look at this error logs. EWC explorer is facing this issue, however volta explorer is running without any issue.

**Comment by vbaranov** [comment]
@royki do you have enough memory on the application server? Didn't you reach OOM?

**Comment by royki** [comment]
Hi @vbaranov ,
Yes, we have sufficient memory and didn't reach OOM. 

Along with this I also noticed there is DBConnection error and DB connection dropped in a certain interval. 
`application=db_connection [info] Postgrex.Protocol (#PID<0.951.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5712.86> exited`
This doesn't stop the application , here is more logs -> 
I also make the `POOL_SIZE=40`
```
blockscout_1  | 2022-08-19T10:10:07.198 application=plug request_id=Fwy3NnkDE_q5qA0CgQaB [info] Sent 200 in 18ms
blockscout_1  | 2022-08-19T10:10:07.491 application=db_connection [info] Postgrex.Protocol (#PID<0.951.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5712.86> exited
blockscout_1  | 2022-08-19T10:10:08.329 application=plug request_id=Fwy3Nr2YYb4GY70CgQeB [info] GET /api
blockscout_1  | 2022-08-19T10:10:08.522 application=plug request_id=Fwy3Nr2YYb4GY70CgQeB [info] Sent 200 in 192ms
blockscout_1  | 2022-08-19T10:10:09.097 application=plug request_id=Fwy3Nutbgvr6gT8CGvJD [info] GET /api
blockscout_1  | 2022-08-19T10:10:09.282 application=plug request_id=Fwy3Nutbgvr6gT8CGvJD [info] Sent 200 in 185ms
blockscout_1  | 2022-08-19T10:10:09.741 application=plug request_id=Fwy3NxHBE_fZv7QCGvJj [info] GET /api
blockscout_1  | 2022-08-19T10:10:09.894 application=plug request_id=Fwy3NxHBE_fZv7QCGvJj [info] Sent 200 in 152ms
blockscout_1  | 2022-08-19T10:10:10.378 application=plug request_id=Fwy3Nzes8a2R7yYBvzsk [info] GET /api
blockscout_1  | 2022-08-19T10:10:10.536 application=plug request_id=Fwy3Nzes8a2R7yYBvzsk [info] Sent 200 in 158ms
blockscout_1  | 2022-08-19T10:10:10.688 application=plug request_id=Fwy3N0ovl_75H88BvztE [info] GET /block/17613597
blockscout_1  | 2022-08-19T10:10:10.688 application=plug request_id=Fwy3N0ovl_75H88BvztE [info] Sent 302 in 236µs
blockscout_1  | 2022-08-19T10:10:11.040 application=plug request_id=Fwy3N18tYGKgg_cBvztk [info] GET /api
blockscout_1  | 2022-08-19T10:10:11.190 application=plug request_id=Fwy3N18tYGKgg_cBvztk [info] Sent 200 in 149ms
blockscout_1  | 2022-08-19T10:10:11.683 application=plug request_id=Fwy3N4V6-8bMZhABvzvE [info] GET /api
blockscout_1  | 2022-08-19T10:10:11.841 application=plug request_id=Fwy3N4V6-8bMZhABvzvE [info] Sent 200 in 157ms
blockscout_1  | 2022-08-19T10:10:12.031 application=plug request_id=Fwy3N5o7lPAHCzcBvzvk [info] GET /api
blockscout_1  | 2022-08-19T10:10:12.033 application=plug request_id=Fwy3N5o7lPAHCzcBvzvk [info] Sent 200 in 2ms

```

**Comment by royki** [comment]
Hi @vbaranov ,
Still receiving the similar error ->

```shell
2022-09-16T02:03:45.483 [error] Task #PID<0.15236.27> started from Indexer.Block.Realtime.Fetcher terminating
blockscout_1  | ** (stop) exited in: GenServer.call(Indexer.Fetcher.InternalTransaction, {:buffer, [20019539]}, 10000)
blockscout_1  |     ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
blockscout_1  |     (elixir 1.13.1) lib/gen_server.ex:1019: GenServer.call/3
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:385: Indexer.Block.Realtime.Fetcher.async_import_remaining_block_data/2
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:224: Indexer.Block.Realtime.Fetcher.import/2
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/fetcher.ex:167: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:293: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
blockscout_1  |     (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
blockscout_1  |     (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:276: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
blockscout_1  |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout_1  | Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
blockscout_1  |     Args: [20019539, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://parity:8545", method_to_url: [eth_getBalance: "http://parity:8545", trace_block: "http://parity:8545", trace_replayTransaction: "http://parity:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, false]
blockscout_1  | 2022-09-16T02:03:45.877 application=phoenix [info] CONNECTED TO BlockScoutWeb.UserSocket in 64µs
```

**Comment by vbaranov** [comment]
@royki you can manage indexer memory limit through `INDEXER_MEMORY_LIMIT` env variable. I also recommend update Blockscout version to the latest release 5.1.0. It contains various indexer perfomance improvements. I am closing this issue. Let me know, if you still experience issue.

**Comment by royki** [comment]
Hi @vbaranov , yes we still face this time to time. Restarting blockscout helps to get rid of this for time beings. 
Yes, we'll update Blockscout version soon. 
Thanks
