### ISSUE TITLE
mix do ecto.create, ecto.migrate error "No such file  ... btree_gist.control"

### ISSUE THREAD

**Issue by youngqqcn** [blockscout/blockscout#5933]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):

```
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1]
Elixir 1.13.3 (compiled with Erlang/OTP 25)
```

* Operating System: CentOS7.9
* Blockscout Version/branch: master, commit 3e7047060efe7cfb40abfbad52b2f6cffbb45c70

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

```
12:35:03.554 [info]  == Running 20180522154252 Explorer.Repo.Migrations.CreateBtreeGistExtension.change/0 forward

12:35:03.555 [info]  execute "CREATE EXTENSION IF NOT EXISTS btree_gist"
** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/pgsql-14/share/extension/btree_gist.control": No such file or directory
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.13.3) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3

```

**Comment by youngqqcn** [comment]
same as issue #5186.   my postgresql version is `14`

**Comment by youngqqcn** [comment]
`yum install postgresql14-contrib`  soloved this issue
