### ISSUE TITLE
Re-enable test/indexer/supervisor_test.exs:30 for geth_http

### ISSUE THREAD

**Issue by KronicDeth** [blockscout/blockscout#597]
Test disabled with `@tag :no_geth` because it kept failing on PRs unrelated to Geth support

See https://circleci.com/gh/poanetwork/blockscout/22128

### Expected behaviour

Test works with Geth on real node.

### Actual behaviour

```
22:59:03.133 [error] Task #PID<0.5054.0> started from #PID<0.5052.0> terminating
     ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Receipt.elixir_to_logs/1
         (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:47: EthereumJSONRPC.Receipt.elixir_to_logs(%{})
         (elixir) lib/enum.ex:2950: Enum.flat_map_list/2
         (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:141: EthereumJSONRPC.Receipts.fetch/2
         (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
         (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
         (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
     Function: &:erlang.apply/2
         Args: [#Function<1.35918518/1 in Indexer.BlockFetcher.Receipts.fetch/2>, [[%{block_hash: "0x147cb78da2e26c0f5d6ac97de71bda70174842cbbf17b6930e2b9954e236a7c7", block_number: 6201719, from_address_hash: "0xf6747cf23c398088048684cb2195378560a40c33", gas: 116644, gas_price: 60000000000, hash: "0xfd0b9a04ffa481774af5b2cd7a6ecbf19ec79f9311dd16c155d71e5f65a2457a", index: 0, input: "0x3ccfd60b", nonce: 89, r: 25413559716606813899941943027531998462899943714527001417824468205581867310526, s: 51075552739100734124401038932114805269001303382604195325237509019594547551762, to_address_hash: "0xa62142888aba8370742be823c1782d17a0389da1", v: 38, value: 0}, %{block_hash: "0x147cb78da2e26c0f5d6ac97de71bda70174842cbbf17b6930e2b9954e236a7c7", block_number: 6201719, from_address_hash: "0xa95350d70b18fa29f6b5eb8d627ceeeee499340d", gas: 21000, gas_price: 60000000000, hash: "0xa30cf0c3cce153d0f281d1b67de55728ef2be2aaf814d7c8a9169d0837ce5fc1", index: 1, input: "0x", nonce: 53986, r: 28290436645700951624342496957239605462012896924293797973713223858641131720553, s: 28743654436680253849892293091268592995986587309817012677592696194540727652252, to_address_hash: "0x17174838021e30cb9047f1ee6c353b5fa1e88630", v: 27, value: 1790000000000000000}, %{block_hash: "0x147cb78da2e26c0f5d6ac97de71bda70174842cbbf17b6930e2b9954e236a7c7", block_number: 6201719, from_address_hash: "0xddfeb0f1f7782dcbcd76fb77a36dc2e81148855c", gas: 21000, gas_price: 34000000000, hash: "0xd4a3c8891ac6142ee73ea20bf2cfb8bea584fe1cebc8221d122b69156f192aae", index: 2, input: "0x", nonce: 1, r: 58033545295045842919127559598883614953723796661283295347593676348200492689574, s: 35856790509836606765532479992895952203807484277493503606305086676497071553588, to_address_hash: "0x70faa28a6b8d6829a4b1e649d26ec9a2a39ba413", v: 27, value: 1316699446772842}, %{block_hash: "0x147cb78da2e26c0f5d6ac97de71bda70174842cbbf17b6930e2b9954e236a7c7", block_number: 6201719, from_address_hash: "0x9332827459be3767d03b4cbe145ec9b3ee6ac4fa", gas: 21000, gas_price: 34000000000, hash: "0x43cf385a366afb0f915e4cfdfec5d6853ff941741b5cc4e1c1878cd95354572f", index: 3, input: "0x", nonce: 1, r: 20484716309758477524773051222146569962052948460580688960693777380059477258505, s: 22111991652991647533751935921723055210566928147835694015758845966016757651486, to_address_hash: "0x70faa28a6b8d6829a4b1e649d26ec9a2a39ba413", v: 27, value: 1216680000000000}, %{block_hash: "0x147cb78da2e26c0f5d6ac97de71bda70174842cbbf17b6930e2b9954e236a7c7", block_number: 6201719, from_address_hash: "0xe2f35b376461e7fdd2f2e45248e4c3cd9626a933", gas: 2900000, gas_price: 1900000001, hash: "0x048ca6f0ca0908dcee9e0477c6985565398fdb481f084f97f727bafa779c026a", index: 4, input: "0xf725839f0000000000000000000000008e306b005773bee6ba6a6e8972bc79d766cc15c80000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000140000000000000000000000006fce6c3fb8c84ee76706c733f44f1ca44f1981dd0000000000000000000000006fce715a53e2fdf4b175be7f87632c8b278e715a0000000000000000000000006fce71f019ba3f3f56a4af605409dd48ca7d3a6e0000000000000000000000006fce732bdf6c0c8ffdcbd5d44eb6de33d0f0e58b0000000000000000000000006fce73eebd13c0195a52c8f74256f92d2e32674e0000000000000000000000006fce74800aef9d9a72334b17349958854b30a2170000000000000000000000006fce82758af9f178946d80634dc1b47d61364ce90000000000000000000000006fce8875b5752a58c4b0a69715c3a44b4a2fe3a20000000000000000000000006fce921a62044d0bfbc6bab6d7e686ff892746780000000000000000000000006fce9ed13a34e0294c3b01981f0cf61a9af301080000000000000000000000006fcebbe38e44a459293df4866562f00d2919feed0000000000000000000000006fced573663043dd406efb222be2f0710048297b0000000000000000000000006fcedaf2cd8b84dcf922906581bfa588e49b1b670000000000000000000000006fcedbeecbc2a8288aba2d4220bdb3133c8d81550000000000000000000000006fcee8aab2909e4275a8bf938a841b3a1c0f96df0000000000000000000000006fcef20756e24b845850e05e5f054b5cd8ecbd1d0000000000000000000000006fcef4407977ee4f2cab15acef6d3b7ffb2b95b10000000000000000000000006fcef97c01f2cafe36ecea8e1bc17bed8f601564000000000000000000000000f1c477a2bf286486103127fb7c761d8b181599cd000000000000000000000000f1c478b9e3c90594c3e8683b5336783e1185b9b6000000000000000000000000000000000000000000000000000000000000390000000000000000000000000000000000000000000000000000000000000002c01be0d280a5a39acd93670868b6c9da9557c8a65bdde3d4f9deacde6dda922830ee71433434840d32617a8baa661c2b11e0130da38c66c5abc2ea6216d608da03db7a6ef52c35b68f382b4d8b134d94780f25b726534ad2581472b3502975ef78f9adec9a18301b8053c289b407fbea1c9b553d2c0d13aed497ae56aa893e8d87c5def106d6fb192e1c37148f7881cc5639b7514bc88206212026c452d82a51613e11ab13c15a4d186e14d8f1b7d350ff2832f6d2a8c21f85a43e051672d8efa6cf40909405b4c15c19dd6070d37fce330601bb123527a96c197fd591d6482f85ac5f1b808d93662dbdfd965d59f4ef3028b470241ea18f7805cb912d41eafa645809afd04a2315b8b3f16c8289afb2f8adf855361125904582aa108aa651f88aa4236db03ddc87a7fa13cc88a8e88405b46a9147dcc6a1f4b6cb6a9255876a4f9bdba70333dc960ba0181c72af4f1316b4d32a14926ae4428a6a530e686ffb64ae71a5cc13ca4d52300c50d3578001e020ea03b51d89c7d080d082ae20c3eddefb6d1e0bd2372cb308c6171ef547ba49481f0d4fd79b5c957c077d7360b2eb6fb3d2ad9dac5e867248b141a4778ac5c28d939d477b5bddd9fc69112b8ce4fd7e9710c85e578b270b4d5145537fff836fcf033b7de41d982142cfb0835ef3e06f8a99cd7c3209205f2553bd7cfac3b310e1a49b92803eba8774c056b98e61f569fc99406056b5bd4af124d8cced14747e52704eb4188d2d0225a7ab093dc6c8864a8c6c26478cf17835b70b027eae195b14a909c85f9c59bdf9fa96b622f9003243aafa04b5f343a27ca4a022cdad3c05815cd267ea86abe574ed23e545a1c95093012bb4162a0b320715e1f810d059b90bd669187596dfd80a4ce9f0722b559024d5938fd72d08ed68c0584e38df8792101873a9603d94565893663a3f7efae61e74a86b2f0aceaa39987ce1ee5e1150dc99db6336cca1bf9a005c776d0e3fc300000000000000000000000000000000000000000000000000000000000002c0742746d749432c9d38528853b68b5648c6cb480d5120d5ccad1b41732113c672ee71433434840d32617a8baa661c2b11e0130da38c66c5abc2ea6216d608da03db7a6ef52c35b68f382b4d8b134d94780f25b726534ad2581472b3502975ef78f9adec9a18301b8053c289b407fbea1c9b553d2c0d13aed497ae56aa893e8d87c5def106d6fb192e1c37148f7881cc5639b7514bc88206212026c452d82a51613e11ab13c15a4d186e14d8f1b7d350ff2832f6d2a8c21f85a43e051672d8efa6cf40909405b4c15c19dd6070d37fce330601bb123527a96c197fd591d6482f85ac5f1b808d93662dbdfd965d59f4ef3028b470241ea18f7805cb912d41eafa645809afd04a2315b8b3f16c8289afb2f8adf855361125904582aa108aa651f88aa4236db03ddc87a7fa13cc88a8e88405b46a9147dcc6a1f4b6cb6a9255876a4f9bdba70333dc960ba0181c72af4f1316b4d32a14926ae4428a6a530e686ffb64ae71a5cc13ca4d52300c50d3578001e020ea03b51d89c7d080d082ae20c3eddefb6d1e0bd2372cb308c6171ef547ba49481f0d4fd79b5c957c077d7360b2eb6fb3d2ad9dac5e867248b141a4778ac5c28d939d477b5bddd9fc69112b8ce4fd7e9710c85e578b270b4d5145537fff836fcf033b7de41d982142cfb0" <> ..., nonce: 151, r: 107144225938782897076089415463709327880046418503862323646437270481930752873201, s: 19679692418030380977516582462390938074090416935202641928932051753549880495497, to_address_hash: "0x182ebf4c80b28efc45ad992ecbb9f730e31e8c7f", v: 38, value: 0}, %{block_hash: "0x147cb78da2e26c0f5d6ac97de71bda70174842cbbf17b6930e2b9954e236a7c7", block_number: 6201719, from_address_hash: "0x713169615e3eba3d135ffed26c487ee18f47ca06", gas: 3200000, gas_price: 1700000000, hash: "0x5c07c14210f64ff475bf67493ffce683a6ac739eb6200fc1e68b4f6fb54fc701", index: 5, input: "0xf725839f0000000000000000000000008e306b005773bee6ba6a6e8972bc79d766cc15c80000000000000000000000000000000000000000 (truncated)
     22:59:03.140 [error] GenServer #PID<0.5050.0> terminating
     ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Receipt.elixir_to_logs/1
         (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:47: EthereumJSONRPC.Receipt.elixir_to_logs(%{})
         (elixir) lib/enum.ex:2950: Enum.flat_map_list/2
         (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:141: EthereumJSONRPC.Receipts.fetch/2
         (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
         (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
         (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
     Last message: {:EXIT, #PID<0.5049.0>, {:function_clause, [{EthereumJSONRPC.Receipt, :elixir_to_logs, [%{}], [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 47]}, {Enum, :flat_map_list, 2, [file: 'lib/enum.ex', line: 2950]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 141]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
     22:59:03.140 [error] Realtime index stream exited with reason ({:function_clause, [{EthereumJSONRPC.Receipt, :elixir_to_logs, [%{}], [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 47]}, {Enum, :flat_map_list, 2, [file: 'lib/enum.ex', line: 2950]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 141]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}).  The next realtime index task will fill the missing block if the lastest block number has not advanced by then or the catch up index will fill the missing block.
```

**Comment by vbaranov** [comment]
not relevant anymore
