### ISSUE TITLE
Batch request length too long JSONRPC Indexer.Fetcher.CoinBalance terminating

### ISSUE THREAD

**Issue by NengakDakup** [blockscout/blockscout#6129]
Blockscout service runs but returns the following error and the web app is not accesible
According to my research it's about not running an archive node, i don't know if this is right, but i'm using a normal polygon-edge node rpc, and i can't seem to find how to run an archive node for polygon-edge

Sep 16 21:40:57 beetrade.technology mix[5124]: 2022-09-16T21:40:57.106 fetcher=coin_balance count=500 [error] Task #PID<0.6568.0> started from Indexer.Fetcher.CoinBalance terminating
Sep 16 21:40:57 beetrade.technology mix[5124]: ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1
Sep 16 21:40:57 beetrade.technology mix[5124]:     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"})
Sep 16 21:40:57 beetrade.technology mix[5124]:     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
Sep 16 21:40:57 beetrade.technology mix[5124]:     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
Sep 16 21:40:57 beetrade.technology mix[5124]:     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
Sep 16 21:40:57 beetrade.technology mix[5124]:     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
Sep 16 21:40:57 beetrade.technology mix[5124]:     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:192: EthereumJSONRPC.fetch_balances/2
Sep 16 21:40:57 beetrade.technology mix[5124]:     (indexer 0.1.0) lib/indexer/fetcher/coin_balance.ex:97: Indexer.Fetcher.CoinBalance.run/2
Sep 16 21:40:57 beetrade.technology mix[5124]:     (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Sep 16 21:40:57 beetrade.technology mix[5124]: Function: &Indexer.BufferedTask.log_run/1
Sep 16 21:40:57 beetrade.technology mix[5124]:     Args: [%{batch: [{<<0, 0,………….. ...}, {...}, ...], callback_module: Indexer.Fetcher.CoinBalance, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://jsonrpcipadddress:3004", method_to_url: [eth_getBalance: "http://jsonrpcipaddress:3004", trace_block: "http://jsonrpcipaddress:3004", trace_replayTransaction: "http://jsonrpcipaddress:3004"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], metadata: [fetcher: :coin_balance]}]

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit],Elixir 1.13.4 (compiled with Erlang/OTP 22)
* Node JS version (`node -v`): 16.15.1
* Operating System: ubuntu 18.04
* Blockscout Version/branch/commit: 
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): polygon-edge-node

**Comment by NengakDakup** [comment]
Fixed this by disabling address coin balance fetcher  in the environment variables
INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER="true"
