### ISSUE TITLE
ArgumentError crashed at `contract_verifications/new` cookie store expects conn.secret_key_base to be at least 64 bytes

### ISSUE THREAD

**Issue by youngqqcn** [blockscout/blockscout#6154]
git commit :  I merged `blockscout/master` eea679df823723b3cb410912c1b0208a8f91dd4e

![image](https://user-images.githubusercontent.com/30211020/191905304-83a28f72-c01d-4e74-8ce7-65b23aad02d9.png)

error log

```
 Parameters: %{}
2022-09-23T15:23:45.038 application=plug request_id=FxdscgcigTdlcx4ABUTB [info] Sent 500 in 699ms
2022-09-23T15:23:45.038 [error] #PID<0.8585.1> running BlockScoutWeb.Endpoint (connection #PID<0.8584.1>, stream id 1) terminated
Server: explorer-test.rarefy.vip:80 (http)
Request: GET /address/0xC3cB1aE2fEcA636aa23291ccC07e66c18C6bFf4A/contract_verifications/new
** (exit) an exception was raised:
    ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
        (block_scout_web 4.1.8) lib/block_scout_web/plug/redis_cookie.ex:130: BlockScoutWeb.Plug.RedisCookie.validate_secret_key_base/1
        (block_scout_web 4.1.8) lib/block_scout_web/plug/redis_cookie.ex:122: BlockScoutWeb.Plug.RedisCookie.derive/3
        (block_scout_web 4.1.8) lib/block_scout_web/plug/redis_cookie.ex:39: BlockScoutWeb.Plug.RedisCookie.put/4
        (plug 1.13.6) lib/plug/session.ex:96: anonymous fn/3 in Plug.Session.before_send/2
        (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug 1.13.6) lib/plug/conn.ex:1690: Plug.Conn.run_before_send/2
        (plug 1.13.6) lib/plug/conn.ex:399: Plug.Conn.send_resp/1
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.action/2
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 4.1.8) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web 4.1.8) lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web 4.1.8) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
        (block_scout_web 4.1.8) lib/spandex_phoenix.ex:156: BlockScoutWeb.Endpoint.call/2
        (phoenix 1.5.13) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /data/blockscout/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /data/blockscout/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /data/blockscout/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
2022-09-23T15:23:48.966 application=phoenix [info] CONNECTED TO BlockScoutWeb.UserSocket in 45µs
```

**Comment by youngqqcn** [comment]
I solved this issue by adding `SECRET_KEY_BASE=` in ENV.
