### ISSUE TITLE
Unable to start docker-compose on Ubuntu

### ISSUE THREAD

**Issue by viranribic** [blockscout/blockscout#6170]
Can't run basic setup on `geth` or `ganache` using `docker compose` setup. 

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker compose (installed with docker-compose-plugin)
* Operating System:
  * Distributor ID:	Ubuntu
  * Description:	Ubuntu 20.04.5 LTS
  * Release:	20.04
* Blockscout Version/branch/commit: 3a1a3b
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth/Ganache

### Steps to reproduce

Straightforward setup: 
1. Provision a cloud instance (Digital Ocean in my case)
2. Pull latest repo.
3. Move to `docker-compose` and run `docker compose up --build` or similar for ganache or geth premade config.

### Expected behaviour

UI should be hosted on 4000, app should be running.

### Actual behaviour

Stuck on an error:

```bash
Starting dependencies..
Starting repos..
Create Explorer.Repo database if it doesn't exist
Create Explorer.Repo.Account database if it doesn't exist
Running migrations for explorer
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2895ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  4. Tracking down slow queries and making sure they are running fast enough
  5. Increasing the pool_size (although this increases resource consumption)
  6. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:678: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:504: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    lib/release_tasks.ex:23: Explorer.ReleaseTasks.create_and_migrate/0
2022-09-26T23:18:50.216 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :explorer, Explorer.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.
```

**Comment by viranribic** [comment]
I solved my problem by adding 7432 to the firewall rules. I will have to read up on `'host.docker.internal:host-gateway'` as I expected that this would work without changes to the firewall. Closing this for now.
