### ISSUE TITLE
_**getting error deploy using docker before deploy using docker im delete files node_modules and build**_

### ISSUE THREAD

**Issue by Apdlrcjafg19** [blockscout/blockscout#6262]
_**getting error deploy using docker before deploy using docker im delete files node_modules and build**_ 

```
821 │                 color: $additional-font;
    │                        ^^^^^^^^^^^^^^^^
    ╵
  css/theme/_dark-theme.scss 821:12  @import
  css/main-page.scss 76:9            root stylesheet
    at Object.<anonymous> (/app/apps/block_scout_web/assets/node_modules/css-loader/dist/cjs.js!/app/apps/block_scout_web/assets/node_modules/postcss-loader/dist/cjs.js!/app/apps/block_scout_web/assets/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[3]!/app/apps/block_scout_web/assets/css/main-page.scss:1:7)
    at /app/apps/block_scout_web/assets/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/app/apps/block_scout_web/assets/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at /app/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:5057:39
    at tryRunOrWebpackError (/app/apps/block_scout_web/assets/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/app/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:5055:12)
    at __webpack_require__ (/app/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:5012:18)
    at /app/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:5083:20
    at symbolIterator (/app/apps/block_scout_web/assets/node_modules/neo-async/async.js:3485:9)
    at done (/app/apps/block_scout_web/assets/node_modules/neo-async/async.js:3527:9)

Generated code for /app/apps/block_scout_web/assets/node_modules/css-loader/dist/cjs.js!/app/apps/block_scout_web/assets/node_modules/postcss-loader/dist/cjs.js!/app/apps/block_scout_web/assets/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[3]!/app/apps/block_scout_web/assets/css/main-page.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Undefined variable.\n    ╷\n821 │                 color: $additional-font;\n    │                        ^^^^^^^^^^^^^^^^\n    ╵\n  css/theme/_dark-theme.scss 821:12  @import\n  css/main-page.scss 76:9            root stylesheet");

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 6 errors in 444278 ms
The command '/bin/sh -c cd apps/block_scout_web/assets/ &&     npm install &&     npm run deploy &&     cd /app/apps/explorer/ &&     npm install &&     apk update &&     apk del --force-broken-world alpine-sdk gmp-dev automake libtool inotify-tools autoconf python3' returned a non-zero code: 1
make: *** [Makefile:396: build] Error 1
```

```
OS : Ubuntu Pro 22
Docker Version : 20.10.19 Api 1.41 Go go1.18.7
Node :  v14.7.0
NPM : 6.14.7
NVM : 0.39.1
```

Step : 
cd/blockscout/docker :

```
$ export COIN=XXX
$ export NETWORK=XXX
$ export ETHEREUM_JSONRPC_HTTP_URL= rpclink
```

cd/blockscout/docker-compose :
`docker-compose up --build`

_Originally posted by @avenbreaks in https://github.com/blockscout/blockscout/discussions/6261_

**Comment by vbaranov** [comment]
@Apdlrcjafg19 please update node and npm:
> blockscout % node -v
> v16.17.1
> blockscout % npm -v
> 8.15.0
