### ISSUE TITLE
indexer (MatchError) no match of right hand side value: ""

### ISSUE THREAD

**Issue by piotr-sikora-v** [blockscout/blockscout#6326]
Hello,

I try to setup via docker-compose... everything startup OK, and when indexer start I see huge amount  errors...
I'am not elixir developer so it's hard to me to debug this.

```
blockscout                 | 2022-10-24T10:28:53.784 application=indexer fetcher=block_catchup first_block_number=719401 last_block_number=719392 [error] ** (MatchError) no match of right hand side value: ""
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout                 |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout                 |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:135: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout                 |     (stdlib 3.17) timer.erl:166: :timer.tc/1
blockscout                 |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
blockscout                 |
blockscout                 |
```
Block numbers is correct, so it's connected to my chain

Thanks in advanced for help

**Comment by vbaranov** [comment]
@piotr-sikora-v it is possible when the node cannot process all requests from Blockscout. You can try reducing the batch size and concurrency for the catchup fetcher by setting `INDEXER_CATCHUP_BLOCKS_BATCH_SIZE` and/or `INDEXER_CATCHUP_BLOCKS_CONCURRENCY` to less than 10. The default value for both env variables is 10.

**Comment by piotr-sikora-v** [comment]
@vbaranov Thanks for fast replay.
I set both values to `1` and I have a asem error :/

**Comment by piotr-sikora-v** [comment]
```
blockscout                 | 2022-10-24T10:55:34.566 application=explorer [info] tx/per day chart: latest date 2022-10-22 23:59:59Z
blockscout                 | 2022-10-24T10:55:34.609 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2022-10-24T10:55:34.609 application=explorer [info] tx/per day chart: earliest date 2022-10-23 00:00:00Z
blockscout                 | 2022-10-24T10:55:34.609 application=explorer [info] tx/per day chart: latest date 2022-10-23 23:59:59Z
blockscout                 | 2022-10-24T10:55:34.629 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2022-10-24T10:55:34.630 application=explorer [info] tx/per day chart: records collected [%{date: ~D[2022-10-23], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2022-10-22], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2022-10-21], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2022-10-20], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2022-10-19], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2022-10-18], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2022-10-17], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2022-10-16], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2022-10-15], gas_used: 0, number_of_transactions: 0, total_fee: 0}]
blockscout                 | 2022-10-24T10:55:34.631 application=explorer [info] tx/per day chart: save records
blockscout                 | 2022-10-24T10:55:34.647 application=explorer [info] tx/per day chart: number of inserted 10
blockscout                 | 2022-10-24T10:55:34.658 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)
blockscout                 | 2022-10-24T10:55:34.663 application=phoenix [info] Access BlockScoutWeb.Endpoint at ://:4000
blockscout                 | 2022-10-24T10:55:34.914 application=indexer fetcher=block_catchup first_block_number=723805 last_block_number=723805 [error] ** (MatchError) no match of right hand side value: ""
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout                 |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout                 |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:135: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout                 |     (stdlib 3.17) timer.erl:166: :timer.tc/1
blockscout                 |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
blockscout                 |
blockscout                 |
blockscout                 | Retrying.
blockscout                 | 2022-10-24T10:55:34.922 application=indexer fetcher=block_catchup first_block_number=723804 last_block_number=723804 [error] ** (MatchError) no match of right hand side value: ""
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout                 |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout                 |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:135: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout                 |     (stdlib 3.17) timer.erl:166: :timer.tc/1
blockscout                 |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
blockscout                 |
blockscout                 |
blockscout                 | Retrying.
blockscout                 | 2022-10-24T10:55:34.925 application=indexer fetcher=block_catchup first_block_number=723803 last_block_number=723803 [error] ** (MatchError) no match of right hand side value: ""
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout                 |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout                 |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:135: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout                 |     (stdlib 3.17) timer.erl:166: :timer.tc/1
blockscout                 |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
blockscout                 |
blockscout                 |
blockscout                 | Retrying.
blockscout                 | 2022-10-24T10:55:34.930 application=indexer fetcher=block_catchup first_block_number=723802 last_block_number=723802 [error] ** (MatchError) no match of right hand side value: ""
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout                 |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout                 |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:135: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout                 |     (stdlib 3.17) timer.erl:166: :timer.tc/1
blockscout                 |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
blockscout                 |
blockscout                 |
blockscout                 | Retrying.
blockscout                 | 2022-10-24T10:55:34.936 application=indexer fetcher=block_catchup first_block_number=723801 last_block_number=723801 [error] ** (MatchError) no match of right hand side value: ""
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout                 |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout                 |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:135: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout                 |     (stdlib 3.17) timer.erl:166: :timer.tc/1
blockscout                 |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
blockscout                 |
blockscout                 |
blockscout                 | Retrying.
blockscout                 | 2022-10-24T10:55:34.941 application=indexer fetcher=block_catchup first_block_number=723800 last_block_number=723800 [error] ** (MatchError) no match of right hand side value: ""
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
blockscout                 |     (indexer 4.1.8) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout                 |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout                 |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:135: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout                 |     (stdlib 3.17) timer.erl:166: :timer.tc/1
blockscout                 |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout                 |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
blockscout                 |
blockscout                 |
blockscout                 | Retrying.
```

**Comment by piotr-sikora-v** [comment]
@vbaranov it's fork of evmos blockchain ... maybe here is problem? But is compatible with geth... metamask also works normal with json-rpc.
and also it's running here: https://evm.evmos.org/

**Comment by vbaranov** [comment]
@piotr-sikora-v which docker-compose.yml did you use exactly? If `BLOCK_TRANSFORMER` env variable is set. Please, try to unset it.

**Comment by vbaranov** [comment]
@piotr-sikora-v which docker-compose.yml did you use exactly? If `BLOCK_TRANSFORMER` env variable is set. Please, try to unset it.

**Comment by piotr-sikora-v** [comment]
@vbaranov before unset I have setted to clique ... now is unset, but I think this is ovverrided with environment from docer-compose.
I run it with:
```
docker-compose -f docker-compose-no-build-geth.yml up
```

**Comment by vbaranov** [comment]
@piotr-sikora-v please, remove the corresponding line (BLOCK_TRANSFORMER=...) in docker-compose-no-build-geth.yml

**Comment by piotr-sikora-v** [comment]
@vbaranov Works! Big Thanks!
