### ISSUE TITLE
Cannot Connect Database Dropped from queue after 2962ms

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6406]
# Cannot Connect Database PostgreSQL  

Cannot Connect Database Dropped from queue after 2962ms. 

```
Starting repos..
Create Explorer.Repo database if it doesn't exist
Create Explorer.Repo.Account database if it doesn't exist
Running migrations for explorer
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2962ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:905: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:997: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.0) lib/ecto/migrator.ex:672: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.9.0) lib/ecto/migrator.ex:486: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.9.0) lib/ecto/migrator.ex:398: Ecto.Migrator.run/4
    (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    lib/release_tasks.ex:23: Explorer.ReleaseTasks.create_and_migrate/0
2022-11-07T15:40:15.887 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :explorer, Explorer.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

Starting dependencies..
Starting repos..
Create Explorer.Repo database if it doesn't exist
Create Explorer.Repo.Account database if it doesn't exist
Running migrations for explorer
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2962ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:905: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:997: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.0) lib/ecto/migrator.ex:672: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.9.0) lib/ecto/migrator.ex:486: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.9.0) lib/ecto/migrator.ex:398: Ecto.Migrator.run/4
    (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    lib/release_tasks.ex:23: Explorer.ReleaseTasks.create_and_migrate/0
2022-11-07T15:40:29.291 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :explorer, Explorer.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations
```

### Environment

* Deployment type : `(Docker-compose)`
* Port Open : `4000, 5432, 7432, 6379, 8043, 80, 443 `
* Server : `VM Ubuntu 20.04, 12 vCPU, 64GB RAM, 2TB SSD NVMe `

### Steps to reproduce
$ cd /home/root/docker-compose 
docker compose -f docker-compose.yml up --build -d 
env file : https://txt.mariomichel.com/?34576e25be905004#8rVZV4dy2c3ugqEUPJW4BocmdzTnfoNoJfGmUaXMdJFK
docker-compose : https://txt.mariomichel.com/?849c775c0e9e24fb#Bgdto4LHgng3Kv6RWtHmvCxpBHDE7GzLZeYf9SG8efjZ

### Expected behaviour

working perfectly

**Comment by avenbreaks** [comment]
@vbaranov can you help me sir ?

**Comment by avenbreaks** [comment]
same issue, building manual 


![image](https://user-images.githubusercontent.com/93043826/200437617-8eef627a-2600-406b-bdf9-6cd802dbbe07.png)

**Comment by avenbreaks** [comment]
> same issue, building manual
> 
> ```
> ** (Mix) The database for Explorer.Repo couldn't be created: connection not available and request was dropped from queue after 2000ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
> 
>   1. Ensuring your database is available and that you can connect to it
>   2. Tracking down slow queries and making sure they are running fast enough
>   3. Increasing the pool_size (although this increases resource consumption)
>   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
> 
> See DBConnection.start_link/2 for more information
> ```
> 
> ![image](https://user-images.githubusercontent.com/93043826/200437617-8eef627a-2600-406b-bdf9-6cd802dbbe07.png)

solved, create new database, but getting new eror : 


```
2022-11-08T00:32:47.341 application=db_connection [error] Postgrex.Protocol (#PID<0.1038.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.343 application=db_connection [error] Postgrex.Protocol (#PID<0.1010.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.343 application=db_connection [error] Postgrex.Protocol (#PID<0.1009.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.343 application=db_connection [error] Postgrex.Protocol (#PID<0.1040.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.343 application=db_connection [error] Postgrex.Protocol (#PID<0.1012.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.345 application=explorer [info] tx/per day chart: earliest date 2022-09-30 00:00:00Z
2022-11-08T00:32:47.346 application=db_connection [error] Postgrex.Protocol (#PID<0.1042.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.347 application=explorer [info] tx/per day chart: latest date 2022-09-30 23:59:59Z
2022-11-08T00:32:47.349 application=db_connection [error] Postgrex.Protocol (#PID<0.1045.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.351 application=db_connection [error] Postgrex.Protocol (#PID<0.1041.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.351 application=db_connection [error] Postgrex.Protocol (#PID<0.1044.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.352 application=db_connection [error] Postgrex.Protocol (#PID<0.1043.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.353 application=db_connection [error] Postgrex.Protocol (#PID<0.1046.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "defi"
2022-11-08T00:32:47.360 [notice] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :invalid_password, file: "auth.c", line: "326", message: "password authentication failed for user \"defi\"", pg_code: "28P01", routine: "auth_failed", severity: "FATAL", unknown: "FATAL"}, query: nil}}
            (explorer 4.1.8) lib/explorer/chain/events/listener.ex:17: Explorer.Chain.Events.Listener.init/1
            (stdlib 4.0.1) gen_server.erl:848: :gen_server.init_it/2
            (stdlib 4.0.1) gen_server.erl:811: :gen_server.init_it/6
            (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2022-11-08T00:32:47.361 [notice] Application redix exited: :stopped
2022-11-08T00:32:47.361 [notice] Application cloak_ecto exited: :stopped
2022-11-08T00:32:47.361 [notice] Application cloak exited: :stopped
2022-11-08T00:32:47.361 [notice] Application cbor exited: :stopped
2022-11-08T00:32:47.361 [notice] Application con_cache exited: :stopped
2022-11-08T00:32:47.362 [notice] Application spandex_ecto exited: :stopped
2022-11-08T00:32:47.362 [notice] Application que exited: :stopped
2022-11-08T00:32:47.362 [notice] Application ex_utils exited: :stopped
2022-11-08T00:32:47.362 [notice] Application memento exited: :stopped
2022-11-08T00:32:47.363 [notice] Application plug_cowboy exited: :stopped
2022-11-08T00:32:47.363 [notice] Application cowboy_telemetry exited: :stopped
2022-11-08T00:32:47.363 [notice] Application prometheus_ecto exited: :stopped
2022-11-08T00:32:47.363 [notice] Application prometheus_ex exited: :stopped
2022-11-08T00:32:47.363 [notice] Application mnesia exited: :stopped
2022-11-08T00:32:47.364 [notice] Application prometheus exited: :stopped
2022-11-08T00:32:47.364 [notice] Application quantile_estimator exited: :stopped
2022-11-08T00:32:47.364 [notice] Application postgrex exited: :stopped
2022-11-08T00:32:47.364 [notice] Application nimble_csv exited: :stopped
2022-11-08T00:32:47.364 [notice] Application poison exited: :stopped
2022-11-08T00:32:47.365 [notice] Application phoenix_html exited: :stopped
2022-11-08T00:32:47.365 [notice] Application math exited: :stopped
2022-11-08T00:32:47.365 [notice] Application ecto_sql exited: :stopped
2022-11-08T00:32:47.365 [notice] Application db_connection exited: :stopped
2022-11-08T00:32:47.365 [notice] Application connection exited: :stopped
2022-11-08T00:32:47.366 [notice] Application ecto exited: :stopped
2022-11-08T00:32:47.366 [notice] Application dataloader exited: :stopped
2022-11-08T00:32:47.366 [notice] Application briefly exited: :stopped
2022-11-08T00:32:47.366 [notice] Application bcrypt_elixir exited: :stopped
2022-11-08T00:32:47.366 [notice] Application comeonin exited: :stopped
2022-11-08T00:32:47.367 [notice] Application bamboo exited: :stopped
2022-11-08T00:32:47.367 [notice] Application tesla exited: :stopped
2022-11-08T00:32:47.367 [notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :invalid_password, file: "auth.c", line: "326", message: "password authentication failed for user \"defi\"", pg_code: "28P01", routine: "auth_failed", severity: "FATAL", unknown: "FATAL"}, query: nil}}
            (explorer 4.1.8) lib/explorer/chain/events/listener.ex:17: Explorer.Chain.Events.Listener.init/1
            (stdlib 4.0.1) gen_server.erl:848: :gen_server.init_it/2
            (stdlib 4.0.1) gen_server.erl:811: :gen_server.init_it/6
            (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by avenbreaks** [comment]
# Cannot sync block / stuck 
blocks can't sync, they get back in sync after a few minutes or a few hours. is my configuration wrong? because I installed another explorer block syncs smoothly

Blockscout Explorer
![image](https://user-images.githubusercontent.com/93043826/200744833-3c6e7fc8-740a-4798-9ca2-599a5e5fb8c7.png)

Other Explorer
![image](https://user-images.githubusercontent.com/93043826/200745198-d03fa33c-8175-4c01-8bff-bb43c536d2ea.png)

**Comment by vbaranov** [comment]
@avenbreaks you can try increasing `POOL_SIZE` environment variable, which manages DB pool size. By default, it is 50.

**Comment by KevinSmall** [comment]
I get same database issue, using `docker-compose up --build` eventually shows this in the docker logs for blockscout:

```
blockscout exited with code 1
blockscout               | Starting dependencies..
blockscout               | Starting repos..
blockscout               | Create Explorer.Repo database if it doesn't exist
blockscout               | Create Explorer.Repo.Account database if it doesn't exist
blockscout               | Running migrations for explorer
blockscout               | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2954ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
blockscout               |
blockscout               |   1. Ensuring your database is available and that you can connect to it
blockscout               |   2. Tracking down slow queries and making sure they are running fast enough
blockscout               |   3. Increasing the pool_size (although this increases resource consumption)
blockscout               |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
blockscout               |
blockscout               | See DBConnection.start_link/2 for more information
blockscout               |
blockscout               |     (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:905: Ecto.Adapters.SQL.raise_sql_call_error/1
blockscout               |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout               |     (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:997: Ecto.Adapters.SQL.execute_ddl/4
blockscout               |     (ecto_sql 3.9.0) lib/ecto/migrator.ex:672: Ecto.Migrator.verbose_schema_migration/3
blockscout               |     (ecto_sql 3.9.0) lib/ecto/migrator.ex:486: Ecto.Migrator.lock_for_migrations/4
blockscout               |     (ecto_sql 3.9.0) lib/ecto/migrator.ex:398: Ecto.Migrator.run/4
blockscout               |     (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
blockscout               |     lib/release_tasks.ex:23: Explorer.ReleaseTasks.create_and_migrate/0
blockscout               | 2022-11-10T13:21:26.257 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:
blockscout               |
blockscout               |   * The database does not exist
blockscout               |   * The "schema_migrations" table, which Ecto uses for managing
blockscout               |     migrations, was defined by another library
blockscout               |   * There is a deadlock while migrating (such as using concurrent
blockscout               |     indexes with a migration_lock)
blockscout               |
blockscout               | To fix the first issue, run "mix ecto.create".
blockscout               |
blockscout               | To address the second, you can run "mix ecto.drop" followed by
blockscout               | "mix ecto.create". Alternatively you may configure Ecto to use
blockscout               | another table and/or repository for managing migrations:
blockscout               |
blockscout               |     config :explorer, Explorer.Repo,
blockscout               |       migration_source: "some_other_table_for_schema_migrations",
blockscout               |       migration_repo: AnotherRepoForSchemaMigrations
blockscout               |
blockscout               | The full error report is shown below.
blockscout               |
blockscout exited with code 1
blockscout               | Starting dependencies..
blockscout               | Starting repos..
blockscout               | Create Explorer.Repo database if it doesn't exist
```

But the logs for postgres show it is ok:
```
$ docker logs postgres
PostgreSQL Database directory appears to contain a database; Skipping initialization
2022-11-10 13:24:00.830 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-2.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-11-10 13:24:00.830 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-11-10 13:24:00.830 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-11-10 13:24:00.856 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-11-10 13:24:00.880 UTC [25] LOG:  database system was shut down at 2022-11-10 13:21:40 UTC
2022-11-10 13:24:00.900 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by avenbreaks** [comment]
> d

try to create database new and pool_size 200

**Comment by avenbreaks** [comment]
> > @avenbreaks you can try increasing `POOL_SIZE` environment variable, which manages DB pool size. By default, it is 50.
> 
> Sure, Im done increase 50-70 but not working.. and i question, how to sync Block live ? My Block not sync, stopped 1 hours and produce again,

hello @vbaranov how to fix batch request length to long ? 

`(ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"})`

**Comment by vbaranov** [comment]
@avenbreaks it is hard to say which batch request type is an exact culprit from the given information. However, you can try decreasing different batch sizes:
- first of all, you can decrease the batch size of the catchup fetcher, which is managed by `INDEXER_CATCHUP_BLOCKS_BATCH_SIZE` env variable. By default, the value is 10.
- https://github.com/blockscout/blockscout/blob/4f693e29afac4b44077275ed7c2ca052ddc40c61/apps/indexer/lib/indexer/fetcher/internal_transaction.ex#L24 - batch size of internal transactions fetcher
- https://github.com/blockscout/blockscout/blob/4f693e29afac4b44077275ed7c2ca052ddc40c61/apps/indexer/lib/indexer/block/fetcher.ex#L74 - transactions receipts batch size
- https://github.com/blockscout/blockscout/blob/4f693e29afac4b44077275ed7c2ca052ddc40c61/apps/indexer/lib/indexer/fetcher/coin_balance.ex#L25 - coin balances fetcher batch size
- batch sizes of other fetchers. Usually, they are defined in `@max_batch_size` attribute of the fetcher.
