### ISSUE TITLE
Installing with docker-compose gives database error

### ISSUE THREAD

**Issue by KevinSmall** [blockscout/blockscout#6459]
I am trying to do the most vanilla "out of the box" install of blockscout using the docker-compose method. Starting with a clean VM and geth, and then installing blockscout with docker-compose (as described [here](https://github.com/blockscout/blockscout/tree/master/docker-compose)) I get a database error `(DBConnection.ConnectionError) connection not available and request was dropped from queue`.

### Environment
* Deployment type (Manual/Docker/Docker-compose): `docker-compose`
* Docker version `20.10.12, build 20.10.12-0ubuntu2~20.04.1`
* Docker Compose version `v2.12.2`
* Operating System: `Ubuntu 20.04`
* Blockscout Version/branch/commit: commit f500550b8b21c3901f7c96c613e5794e153c9b6e (HEAD -> master, origin/master, origin/HEAD)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): `Geth archive node`

### Steps to reproduce
1) Installed prerequisites:
```
$ docker -v
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
$ docker-compose -v
Docker Compose version v2.12.2
```

2) Check Geth is running on `0.0.0.0:7545` ok:
```
$ curl -sH 'Content-type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true],"id":1}'  http://0.0.0.0:7545
<gives correct output>
``` 

3) Edits made to `./envs/common-blockscout.env` were:
```
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:7545
ETHEREUM_JSONRPC_WS_URL=ws://localhost:7546
POOL_SIZE=200
POOL_SIZE_API=100
```
(I edited the pool sizes above as suggested [in another issue](https://github.com/blockscout/blockscout/issues/6406) that looked related)

4) Build blockscout:
```
cd ~/blockscout/docker-compose
docker-compose up --build
```

After some time for building, the logs settle down into a loop like this, which gets repeated over and over:
```
blockscout exited with code 1
blockscout               | Starting dependencies..
blockscout               | Starting repos..
blockscout               | Create Explorer.Repo database if it doesn't exist
blockscout               | Create Explorer.Repo.Account database if it doesn't exist
blockscout               | Running migrations for explorer
blockscout               | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2963ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
blockscout               |
blockscout               |   1. Ensuring your database is available and that you can connect to it
blockscout               |   2. Tracking down slow queries and making sure they are running fast enough
blockscout               |   3. Increasing the pool_size (although this increases resource consumption)
blockscout               |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
blockscout               |
blockscout               | See DBConnection.start_link/2 for more information
blockscout               |
blockscout               |     (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:905: Ecto.Adapters.SQL.raise_sql_call_error/1
blockscout               |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout               |     (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:997: Ecto.Adapters.SQL.execute_ddl/4
blockscout               |     (ecto_sql 3.9.0) lib/ecto/migrator.ex:672: Ecto.Migrator.verbose_schema_migration/3
blockscout               |     (ecto_sql 3.9.0) lib/ecto/migrator.ex:486: Ecto.Migrator.lock_for_migrations/4
blockscout               |     (ecto_sql 3.9.0) lib/ecto/migrator.ex:398: Ecto.Migrator.run/4
blockscout               |     (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
blockscout               |     lib/release_tasks.ex:23: Explorer.ReleaseTasks.create_and_migrate/0
blockscout               | 2022-11-16T13:51:36.727 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:
blockscout               |
blockscout               |   * The database does not exist
blockscout               |   * The "schema_migrations" table, which Ecto uses for managing
blockscout               |     migrations, was defined by another library
blockscout               |   * There is a deadlock while migrating (such as using concurrent
blockscout               |     indexes with a migration_lock)
blockscout               |
blockscout               | To fix the first issue, run "mix ecto.create".
blockscout               |
blockscout               | To address the second, you can run "mix ecto.drop" followed by
blockscout               | "mix ecto.create". Alternatively you may configure Ecto to use
blockscout               | another table and/or repository for managing migrations:
blockscout               |
blockscout               |     config :explorer, Explorer.Repo,
blockscout               |       migration_source: "some_other_table_for_schema_migrations",
blockscout               |       migration_repo: AnotherRepoForSchemaMigrations
blockscout               |
blockscout               | The full error report is shown below.
blockscout               |
blockscout exited with code 1
```

Full log is here: https://pastebin.com/8mPh4QPq.

### Expected behaviour
Blockscout runs.

### Actual behaviour
Database error as shown above.

**Comment by Baal19** [comment]
Hello, i have the same issue, increasing pool size wont help.
Any idea?
Thanks!

**Comment by vbaranov** [comment]
@KevinSmall could you try with the current Blockscout version? Do you experience the same issue?

**Comment by vbaranov** [comment]
Closing due to lack of response. Please create a new issue, if it still persists.
