### ISSUE TITLE
Neon: ** (FunctionClauseError) no function clause matching in Indexer.Transform.AddressCoinBalances.transactions_params_reducer/2

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#6489]
```
2022-11-21T19:36:57.332 application=indexer fetcher=block_catchup first_block_number=171591134 last_block_number=171591125 [error] ** (FunctionClauseError) no function clause matching in Indexer.Transform.AddressCoinBalances.transactions_params_reducer/2
    (indexer 4.1.8) lib/indexer/transform/address_coin_balances.ex:73: Indexer.Transform.AddressCoinBalances.transactions_params_reducer(%{block_hash: "0x212fee37e84c6db8d75e0b7a0d6387c432d1fd2e6b299da1ae79e3baa398a521", block_number: 171591128, created_contract_address_hash: nil, cumulative_gas_used: 33618960, from_address_hash: nil, gas: :error, gas_price: :error, gas_used: 33618960, hash: "0xc63b79b716def14e1af1f673c9ba6fd99ad329a11987aa937d4db3fd6d4b6bd0", index: 11, input: "", nonce: :error, r: :error, s: :error, status: :ok, to_address_hash: nil, transaction_hash: "0xc63b79b716def14e1af1f673c9ba6fd99ad329a11987aa937d4db3fd6d4b6bd0", transaction_index: 11, type: 0, v: :error, value: :error}, #MapSet<[%{address_hash: "0x3d0dc511c2845eff2cb8b521261b1ab707cb4919", block_number: 171591125}, %{address_hash: "0xceb43400d4b964b03ed250bf064b04f065056560", block_number: 171591125}, %{address_hash: "0x350ea361c373b5064dfbfac9c44e51aa3dbf0b7e", block_number: 171591125}, %{address_hash: "0x13464d01115ee37dfe801b27502ee24f724339ee", block_number: 171591125}, %{address_hash: "0x1ca86ed4b66660076bcdc49371c44b978c8305f9", block_number: 171591128}, %{address_hash: "0x0000000000000000000000000000000000000000", block_number: 171591133}, %{address_hash: "0x0e3c4c4c49c861a08486ecb222da2fc925c2c274", block_number: 171591125}, %{address_hash: "0xfbc0b976ea465b5d69fc0e0c8cefdc567e75aef9", block_number: 171591128}, %{address_hash: "0xfa48f1c7f262243e919b87f808727e866cb34002", block_number: 171591129}, %{address_hash: "0x23f61b271c4fc543b5263898d99e31b209404a09", block_number: 171591126}, %{address_hash: "0x9763dee41fe2c213643a26b553543a1441974285", block_number: 171591125}, %{address_hash: "0x71626585fb7e3e408f223ac345910a08d8a0f26c", block_number: 171591129}, %{address_hash: "0x3c1edad1b893dd9ea758f329b95eee5f5817f430", block_number: 171591125}, %{address_hash: "0x84aa66b4bd7bffcf54ff2b493fa33dc28dd7cfdf", block_number: 171591128}, %{address_hash: "0x0000000000000000000000000000000000000000", block_number: 171591127}, %{address_hash: "0x09cb95ba84d8a2412cb1279af5d3c2ec0c4ed45f", block_number: 171591125}, %{address_hash: "0x0000000000000000000000000000000000000000", block_number: 171591126}, %{address_hash: "0xab4004dd6174e0028ce114d18e3bc15948c09195", block_number: 171591125}, %{address_hash: "0xc8249c1c9decb6493cea4bed07b3a9cfa1dd6dba", block_number: 171591129}, %{address_hash: "0x80b72808d8a2349b790e926421ca0e3d2ff346b7", block_number: 171591128}, %{address_hash: "0x4bd7f8496cd91701c9f156debc624d6a6e89c0a6", block_number: 171591128}, %{address_hash: "0x94e79fcaa93f10f2bfec739a0f7b61d3cd342cc8", block_number: 171591127}, %{address_hash: "0x685fd3ef72f843c1d7994871a9487018f1b42087", block_number: 171591125}, %{address_hash: "0xd429896917ad41488f3c8ff40ee9066949dac720", block_number: 171591128}, %{address_hash: "0x9670ecf432b42282433067eb6ff98d9e96d0023e", block_number: 171591133}, %{address_hash: "0xde2b157291dc1be4acff02a6d91f6036962f142d", block_number: 171591125}, %{address_hash: "0x9fe91e363f2d2a165f005af3aed57c6a7bb32822", block_number: 171591125}, %{address_hash: "0x5ba8709dda6e23571edacd4a04149508d173c0cd", block_number: 171591129}, %{address_hash: "0x8d13871b114642b62fc22d7f15e26b93631ee69c", block_number: 171591128}, %{address_hash: "0xa5672d918ca278f13e5f25e7f12240bcfe222f9c", block_number: 171591125}, %{address_hash: "0xf44331eb6a5a17ffdd2bfbf655dbdeac88da7fba", block_number: 171591125}, %{address_hash: "0x003d28cc9c4cb22f436410c44bdecc534a7ead47", block_number: 171591129}, %{address_hash: "0xa1d1538613ebf5173f12871c708008f3e9a17ecd", block_number: 171591125}, %{address_hash: "0x575f94a6e51a8bf37a807634551cd44eb4517c55", block_number: 171591125}, %{address_hash: "0x86ab0d7f35e825d906d9764a5fe0ca510d0332af", block_number: 171591132}, %{address_hash: "0x40eb0070e57586275909152def7e50cd9be88fd9", block_number: 171591128}, %{address_hash: "0x5dfeec45f94ab4f1127c58632892cf2bb884555d", block_number: 171591128}, %{address_hash: "0xe0e00a38a07814f8dd93c4c46778a3d6bc33bc12", block_number: 171591125}, %{address_hash: "0xbca2c01e5b2849163ae6cf7fed6dad1cb6b3ac8c", block_number: 171591128}, %{address_hash: "0xba2d2ff740320fd818567bee075463b62be3fc18", block_number: 171591128}, %{address_hash: "0x9b1df523ba9072987ff126c1d9c72081db888b04", block_number: 171591130}, %{address_hash: "0x20c469cd88303099f4a45f814ea7356372ce815c", block_number: 171591129}, %{address_hash: "0x8b3088b470dc33b30e0574fb2e6cc92606a3a861", block_number: 171591129}, %{address_hash: "0xdfc1da28a55a69a2818632633a185a06422c67a3", block_number: 171591125}, %{address_hash: "0xf5a7605d1252b5d2e190f7c68f92043fb2178781", block_number: 171591127}, %{address_hash: "0x0000000000000000000000000000000000000000", block_number: 171591134}, %{address_hash: "0x42a89a8317bbe99efb07e12320e188c032b45f5e", block_number: 171591128}, %{address_hash: "0x31ec836a3ed1b28cf61e4ffb3e7acf72d7ab8cbc", block_number: 171591125}, %{address_hash: "0x1435d0bd474ff20338b9d5a4e4beae9ac67544b4", ...}, %{...}, ...]>)
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib 3.17) maps.erl:410: :maps.fold_1/3
    (indexer 4.1.8) lib/indexer/block/fetcher.ex:159: Indexer.Block.Fetcher.fetch_and_import_range/2
    (stdlib 3.17) timer.erl:166: :timer.tc/1
    (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4


Retrying.
```

**Comment by vbaranov** [comment]
I don't see this error on given instance for a long time anymore.
