### ISSUE TITLE
** (Ecto.StaleEntryError) attempted to delete a stale struct

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#6551]
```
2022-12-05T19:46:05.492 [error] Task #PID<0.21270.0> started from #PID<0.21224.0> terminating
** (Ecto.StaleEntryError) attempted to delete a stale struct:

%Explorer.Chain.Address.CurrentTokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_current_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<216, 218, 107, 242, 105, 100, 175, 157, 126, 237, 158, 3, 229, 52, 21, 211, 122, 169, 96, 69>>}, block_number: 16118418, id: 4326621822, inserted_at: ~U[2022-12-05 11:56:13.903479Z], max_block_number: nil, old_value: nil, token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<56, 230, 184, 63, 170, 163, 219, 153, 236, 120, 136, 102, 102, 128, 129, 218, 51, 204, 211, 41>>}, token_id: nil, token_type: "ERC-20", updated_at: ~U[2022-12-05 11:56:13.903479Z], value: #Decimal<102720597365740053100386202611007>, value_fetched_at: ~U[2022-12-05 11:51:13.565998Z]}

    (ecto 3.9.2) lib/ecto/repo/schema.ex:773: Ecto.Repo.Schema.apply/4
    (ecto 3.9.2) lib/ecto/repo/schema.ex:552: anonymous fn/11 in Ecto.Repo.Schema.do_delete/4
    (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (indexer 4.1.8) lib/indexer/fetcher/token_balance_on_demand.ex:85: Indexer.Fetcher.TokenBalanceOnDemand.fetch_and_update/3
    (indexer 4.1.8) lib/indexer/fetcher/token_balance_on_demand.ex:41: Indexer.Fetcher.TokenBalanceOnDemand.do_trigger_fetch/4
    (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<1.38671258/0 in BlockScoutWeb.AddressTokenBalanceController.index/2>
    Args: []
```

**Comment by vbaranov** [comment]
Fixed by https://github.com/blockscout/blockscout/commit/540a3c36f27ac8d2fbdac3fcd839ba9d14a27a13
