### ISSUE TITLE
Failed to decode Ethereum JSONRPC response and about erc721a

### ISSUE THREAD

**Issue by Rimwu** [blockscout/blockscout#6589]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):Manual
* Elixir & Erlang/OTP versions (`elixir -version`):Elixir 1.13.4/Erlang/OTP 24 [erts-12.3.2.1]
* Node JS version (`node -v`):v16.9.1
* Operating System:CentOS Linux release 7.9.2009 (Core)
* Blockscout Version/branch/commit:v4.1.8-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):Geth

### Steps to reproduce

You can make erc721a contract in the private poa network,and mint 10000 nft in one transaction,the poa network is ok,i can use eth_getTransactionReceipt get things from rpc api,but the blockscout could`t analyse it,it response " Failed to decode Ethereum JSONRPC response"
![image](https://user-images.githubusercontent.com/32615318/207564033-87f6fb63-89ce-42da-b79d-c89a64e2a6c3.png)
![image](https://user-images.githubusercontent.com/32615318/207564937-8bec7773-96ca-491a-abfa-9ecd7a440074.png)

in this pic ,the hash 0x83750e8e1b63aa0b49221b84fcac98b188d229e94efe94da35c82b8cbd1419d2,couldn`t analyse by blockscout,and i can use postman to get things like this
![image](https://user-images.githubusercontent.com/32615318/207565036-6effcb09-845c-43d2-ad16-6eeb239f1573.png)

i think the transaction it too big,how can i increase someting timeout num or memory?to solve it

**Comment by vbaranov** [comment]
@rimwu, you can set `INDEXER_RECEIPTS_BATCH_SIZE` env variable. If it is not set, the default value is 500. It means 500 tx receipts are requested in the batch. Try to reduce it to 50 or even less.

**Comment by rimwu** [comment]
i try export INDEXER_RECEIPTS_BATCH_SIZE="5" in env,it`s not work
btw INDEXER_RECEIPTS_BATCH_SIZE default value is 250.

`** (EthereumJSONRPC.DecodeError) Failed to decode Ethereum JSONRPC response:

  request:

    url: http://172.16.16.21:25001

    body: [{"id":9,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x11ff7c4c9d67d102c5d7288714b3093f1f3fea61bf123297d8a7af9d7a56ba05"]},{"id":8,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xb5c3bd38700d7b84dce7ce6d50da8a2cd0d5723499a41dd9aa4043d4b6f9b00a"]},{"id":7,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xb21f853a2f69ac974d1dce2bf6cf9dbae196e96f68738a0702d9a6f634940afd"]},{"id":6,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x1caf13dadac7cf0284680afe726f3e0349232450c9dae0feddc6f136811e3ab1"]},{"id":5,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xc6048304d54fcdf19fa0f7474ff6eff99ce9ebfb46dd22a5fe5720735

  response:

    status code: 200

    body: 

    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:117: EthereumJSONRPC.HTTP.decode_json/1
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:69: EthereumJSONRPC.HTTP.chunked_json_rpc/3
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/receipts.ex:136: EthereumJSONRPC.Receipts.fetch/2
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.124558711/1 in Indexer.Block.Fetcher.Receipts.fetch/2>, [[%{block_hash: "0xce31ee7cd516f97d6c8b9d299f097dd111fa5726292464449d257a525e1b7bb2", block_number: 2608936, from_address_hash: "0x97ab8c06b039a6c94666895d4adf58b484a0ea58", gas: 19724682, gas_price: 1000000000, hash: "0x076f9b3dfa9cfc5302e805cead78b07c0c4f7e47eb6dce1f7b7b01e8d25cc49f", index: 0, input: "0x2e81aaea0000000000000000000000000d190c48f33708af8c30a69f1910f1f9bc2dd5f40000000000000000000000000000000000000000000000000000002c461bfb810000000000000000000000000000000000000000000000000000000000002710", nonce: 76724, r: 33809363747734507561849009520763704589290912993515016562304979155003601727658, s: 44429035248360191190114870396140674816784242167863319212085493747129094686531, to_address_hash: "0x4267244dcc16a74bc39cccedf9cf3d9c327b92e1", transaction_index: 0, type: 0, v: 10020, value: 0}, %{block_hash: "0x86bcb966fb6a488722fa09b448889ff02902704e7b2706ce2b00797936fb4b01", block_number: 2608937, from_address_hash: "0x97ab8c06b039a6c94666895d4adf58b484a0ea58", gas: 19724682, gas_price: 1000000000, hash: "0x646795c1be46081b9154d0fbef61c428142f2a379a8e3e7ad26f099dbe3ae275", index: 0, input: "0x2e81aaea0000000000000000000000000d190c48f33708af8c30a69f1910f1f9bc2dd5f40000000000000000000000000000000000000000000000000000002c461d82210000000000000000000000000000000000000000000000000000000000002710", nonce: 76725, r: 89546388514125957656768098650399279415154401650472007611005342180098633434301, s: 38311129307787485815655972767334948732742391390839184530153632264425648812971, to_address_hash: "0x4267244dcc16a74bc39cccedf9cf3d9c327b92e1", transaction_index: 0, type: 0, v: 10019, value: 0}, %{block_hash: "0x92adc5cce2007f24acb98665c0213185137d4d142b0736f016110775b15f6c4c", block_number: 2608938, from_address_hash: "0x97ab8c06b039a6c94666895d4adf58b484a0ea58", gas: 19724682, gas_price: 1000000000, hash: "0xaa639f4b9870b2108414a0bab2191909b726c44433b883166fde5bad4d53d503", index: 0, input: "0x2e81aaea0000000000000000000000000d190c48f33708af8c30a69f1910f1f9bc2dd5f40000000000000000000000000000000000000000000000000000002c461f08c10000000000000000000000000000000000000000000000000000000000002710", nonce: 76726, r: 9430257947309275436671681202812350321526644847108719973101658453243958978875, s: 43978807827295908098947553703278490616474850850102062522226924439450988117646, to_address_hash: "0x4267244dcc16a74bc39cccedf9cf3d9c327b92e1", transaction_index: 0, type: 0, v: 10020, value: 0}, %{block_hash: "0x74590991cb5acbe347f3b6a4dff27e679ee4936e7bfcd8e1ac8495155544be37", block_number: 2608939, from_address_hash: "0x97ab8c06b039a6c94666895d4adf58b484a0ea58", gas: 19724682, gas_price: 1000000000, hash: "0xc1c9dc42ea4941c0df4960db3d225ff951c0d02c37eccf6ac029c56eb519734b", index: 0, input: "0x2e81aaea0000000000000000000000000d190c48f33708af8c30a69f1910f1f9bc2dd5f40000000000000000000000000000000000000000000000000000002c46208f610000000000000000000000000000000000000000000000000000000000002710", nonce: 76727, r: 70733876971825412289803225814536138441267602219920500187786620954760562827170, s: 47665134880380420703638024700347575841470005076259122966269717415015543908310, to_address_hash: "0x4267244dcc16a74bc39cccedf9cf3d9c327b92e1", transaction_index: 0, type: 0, v: 10019, value: 0}, %{block_hash: "0x318a80b48752ad98aa10337e0795bec109d5d62dbdc71687e36c73b09da27c33", block_number: 2608940, from_address_hash: "0x97ab8c06b039a6c94666895d4adf58b484a0ea58", gas: 19724682, gas_price: 1000000000, hash: "0x0d7cbbdd700954d6f8002a5d8d47890b380cfe654c0fb599d735319bbcbcce2e", index: 0, input: "0x2e81aaea0000000000000000000000000d190c48f33708af8c30a69f1910f1f9bc2dd5f40000000000000000000000000000000000000000000000000000002c462216010000000000000000000000000000000000000000000000000000000000002710", nonce: 76728, r: 74737095866232268772013487438240112344292614592549331165709704939455662755401, s: 6083894173851634816814179688719596191732688664387533911269896643070914421057, to_address_hash: "0x4267244dcc16a74bc39cccedf9cf3d9c327b92e1", transaction_index: 0, type: 0, v: 10019, value: 0}, %{block_hash: "0x6632650bdc482ae9e9f8ba366be3659c03224ee7d67be0a6cfa4495e2a5bee23", block_number: 2608941, from_address_hash: "0x97ab8c06b039a6c94666895d4adf58b484a0ea58", gas: 19724682, gas_price: 1000000000, hash: "0xc6048304d54fcdf19fa0f7474ff6eff99ce9ebfb46dd22a5fe5720735bd784aa", index: 0, input: "0x2e81aaea0000000000000000000000000d190c48f33708af8c30a69f1910f1f9bc2dd5f40000000000000000000000000000000000000000000000000000002c46239ca10000000000000000000000000000000000000000000000000000000000002710", nonce: 76729, r: 89991011844004064199455736436111312249994850392508016468551221451886394890845, s: 31581147607336474113789593079975284781122755600078058907288076420422861020262, to_address_hash: "0x4267244dcc16a74bc39cccedf9cf3d9c327b92e1", transaction_index: 0, type: 0, v: 10020, value: 0}, %{block_hash: "0x17bf03df3b6c0b39e07de51faab64cb1ef1540bfa2d25eb6e77a5f185d1226bd", block_number: 2608942, from_address_hash: "0x97ab8c06b039a6c94666895d4adf58b484a0ea58", gas: 19724682, gas_price: 1000000000, hash: "0x1caf13dadac7cf0284680afe726f3e0349232450c9dae0feddc6f136811e3ab1", index: 0, input: "0x2e81aaea0000000000000000000000000d190c48f33708af8c30a69f1910f1f9bc2dd5f40000000000000000000000000000000000000000000000000000002c462523410000000000000000000000000000000000000000000000000000000000002710", nonce: 76730, r: 7656508906731015434367619274478249361393333414256721036150161667270964559420, s: 24221847943553536687949210159003745777031426829779503475960793079963269094344, to_address_hash: "0x4267244dcc16a74bc39cccedf9cf3d9c327b92e1", transaction_index: 0, type: 0, v: 10020, value: 0}, %{block_hash: "0x2952f662e03ec2445c1df8501d9ed21f219f22ccf3d898e55464fe114ecfb83a", block_number: 2608943, from_address_hash: "0x97ab8c06b039a6c94666895d4adf58b484a0ea58", gas: 19724682, gas_price: 1000000000, hash: "0xb21f853a2f69ac974d1dce2bf6cf9dbae196e96f68738a0702d9a6f634940afd", index: 0, input: "0x2e81aaea0000000000000000000000000d190c48f33708af8c30a69f1910f1f9bc2dd5f40000000000000000000000000000000000000000000000000000002c4626a9e10000000000000000000000000000000000000000000000000000000000002710", nonce: 76731, r: 81071602659654715378622313897384163791070037436510875201372170643973371073047, s: 2895477347967882748657678056742628113126 (truncated)
2022-12-15T10:31:02.281 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({%EthereumJSONRPC.DecodeError{request: %EthereumJSONRPC.DecodeError.Request{body: [91, ["{\"", [[] | "id"], "\":", "9", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0x11ff7c4c9d67d102c5d7288714b3093f1f3fea61bf123297d8a7af9d7a56ba05"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "8", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0xb5c3bd38700d7b84dce7ce6d50da8a2cd0d5723499a41dd9aa4043d4b6f9b00a"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "7", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0xb21f853a2f69ac974d1dce2bf6cf9dbae196e96f68738a0702d9a6f634940afd"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "6", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0x1caf13dadac7cf0284680afe726f3e0349232450c9dae0feddc6f136811e3ab1"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "5", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0xc6048304d54fcdf19fa0f7474ff6eff99ce9ebfb46dd22a5fe5720735bd784aa"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "4", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0x0d7cbbdd700954d6f8002a5d8d47890b380cfe654c0fb599d735319bbcbcce2e"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "3", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0xc1c9dc42ea4941c0df4960db3d225ff951c0d02c37eccf6ac029c56eb519734b"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "2", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0xaa639f4b9870b2108414a0bab2191909b726c44433b883166fde5bad4d53d503"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "1", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0x646795c1be46081b9154d0fbef61c428142f2a379a8e3e7ad26f099dbe3ae275"], 34], 93], 125], 44, ["{\"", [[] | "id"], "\":", "0", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getTransactionReceipt"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "0x076f9b3dfa9cfc5302e805cead78b07c0c4f7e47eb6dce1f7b7b01e8d25cc49f"], 34], 93], 125], 93], url: "http://172.16.17.23:25001"}, response: %EthereumJSONRPC.DecodeError.Response{body: "", status_code: 200}}, [{EthereumJSONRPC.HTTP, :decode_json, 1, [file: 'lib/ethereum_jsonrpc/http.ex', line: 117]}, {EthereumJSONRPC.HTTP, :chunked_json_rpc, 3, [file: 'lib/ethereum_jsonrpc/http.ex', line: 69]}, {EthereumJSONRPC.RequestCoordinator, :"-perform/4-fun-0-", 3, [file: 'lib/ethereum_jsonrpc/request_coordinator.ex', line: 86]}, {EthereumJSONRPC.RequestCoordinator, :trace_request, 2, [file: 'lib/ethereum_jsonrpc/request_coordinator.ex', line: 106]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 136]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}). Restarting
2022-12-15T10:31:02.279 [error] GenServer :block_catchup_sequencer terminating
`

**Comment by rimwu** [comment]
> @rimwu, you can set `INDEXER_RECEIPTS_BATCH_SIZE` env variable. If it is not set, the default value is 500. It means 500 tx receipts are requested in the batch. Try to reduce it to 50 or even less.

hello~could you please help me to troubleshoot this problem
