### ISSUE TITLE
Error 500 when open the information about the token

### ISSUE THREAD

**Issue by agnitiy** [blockscout/blockscout#6671]
After the transaction, when opening the link from Transaction Details got 500 error:

`application=indexer fetcher=block_catchup first_block_number=560778 last_block_number=560778 [error] ** (KeyError) key "0x279c7e08bb7faa15c611d138640d98169bdcf470" not found in: %{"0x0000000000000000000000000000000000000000" => 560778, "0x0577B02b7D0E7a1C1A4B5E3452ca43bD13Eaa825" => 560778, "0x279c7e08bB7fAA15C611d138640D98169bDCF470" => 560778, "0x8B2eca2E82733DB8B9A6942162ae23118855B5d1" => 560778, "0x8c2a0755479f6f52beb55852e618a0f8f1592aa2" => 560778}
    :erlang.map_get("0x279c7e08bb7faa15c611d138640d98169bdcf470", %{"0x0000000000000000000000000000000000000000" => 560778, "0x0577B02b7D0E7a1C1A4B5E3452ca43bD13Eaa825" => 560778, "0x279c7e08bB7fAA15C611d138640D98169bDCF470" => 560778, "0x8B2eca2E82733DB8B9A6942162ae23118855B5d1" => 560778, "0x8c2a0755479f6f52beb55852e618a0f8f1592aa2" => 560778})
    (indexer 4.1.8) lib/indexer/block/fetcher.ex:264: anonymous fn/2 in Indexer.Block.Fetcher.async_import_coin_balances/2
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (indexer 4.1.8) lib/indexer/block/fetcher.ex:263: Indexer.Block.Fetcher.async_import_coin_balances/2
    (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:174: Indexer.Block.Catchup.Fetcher.async_import_remaining_block_data/2
    (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:160: Indexer.Block.Catchup.Fetcher.import/2
    (stdlib 3.17) timer.erl:166: :timer.tc/1
    (indexer 4.1.8) lib/indexer/block/fetcher.ex:238: Indexer.Block.Fetcher.import/2
Retrying.
`

Environment

Deployment type (Docker-compose): latest version

Steps to reproduce

Open this link [https://explorer.chainers.io/tx/0xf07a280c2d54cbd73bee36244ec9cf1b1ed6ca1c243d3862b973f9a7d1a39ab6](url)

<img width="774" alt="image" src="https://user-images.githubusercontent.com/55990238/210762924-71a5c190-0634-415c-b3c2-9ab6bb9bdc2e.png">

and open information about token 

[https://explorer.chainers.io/token/0x0577b02b7d0e7a1c1a4b5e3452ca43bd13eaa825/instance/0x3138313830343635303335373238363735333931](url)

Expected behaviour

get error 500

**Comment by agnitiy** [comment]
.
