### ISSUE TITLE
Verifying a Smart Contract using RUST_VERIFICATION_SERVICE

### ISSUE THREAD

**Issue by dorijan** [blockscout/blockscout#6758]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): manual
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.13.4 
* Node JS version (`node -v`): v16.18.1
* Operating System: ubuntu
* Blockscout Version/branch/commit: latest, git clone on 25.1
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): polygon-edge

### Steps to reproduce

when I try to verify contract, I go to http://xxxx:4000/address/0xD62C41764cB477c4048Ce02689f4d4c786839801/verify-via-flattened-code/new

upload everything

click Verify and publish, got Loading, and nothing happens

in log:

```
Jan 24 23:17:05 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:05.106 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
Jan 24 23:17:08 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:08.891 application=plug request_id=Fz1h2tEkm24o3j0AAFYI [info] POST /verify_smart_contract/contract_verifications
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]: warning: Supervisor.start_child/2 with a list of args is deprecated, please use DynamicSupervisor instead
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]:   (elixir 1.13.4) lib/supervisor.ex:826: Supervisor.start_child/2
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]:   (que 0.10.1) lib/que/server_supervisor.ex:48: Que.ServerSupervisor.add/2
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]:   (block_scout_web 5.0.0) lib/block_scout_web/controllers/address_contract_verification_controller.ex:74: BlockScoutWeb.AddressContractVerificationController.create/2
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]:   (block_scout_web 5.0.0) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.action/2
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]:   (block_scout_web 5.0.0) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.phoenix_controller_pipeline/2
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]:   (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:09.181 application=que [info] [Que] Spawning Server for worker: Explorer.SmartContract.Solidity.PublisherWorker
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:09.181 application=que [info] [Que] Queued new Job for Explorer.SmartContract.Solidity.PublisherWorker
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:09.181 application=que [info] [Que] Starting Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:09.182 application=plug request_id=Fz1h2tEkm24o3j0AAFYI [info] Sent 204 in 291ms
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:09.858 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
Jan 24 23:17:09 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:09.858 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:12.342 [error] Task #PID<0.1886.0> started from #PID<0.1885.0> terminating
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]: ** (UndefinedFunctionError) function nil.bytes/0 is undefined
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]:     nil.bytes()
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]:     (explorer 5.0.0) lib/explorer/smart_contract/helper.ex:46: Explorer.SmartContract.Helper.add_contract_code_md5/1
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]:     (explorer 5.0.0) lib/explorer/smart_contract/solidity/publisher.ex:215: Explorer.SmartContract.Solidity.Publisher.unverified_smart_contract/5
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]:     (explorer 5.0.0) lib/explorer/smart_contract/solidity/publisher.ex:67: Explorer.SmartContract.Solidity.Publisher.publish/3
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]:     (explorer 5.0.0) lib/explorer/smart_contract/solidity/publisher_worker.ex:14: Explorer.SmartContract.Solidity.PublisherWorker.perform/1
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]:     (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]:     (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]: Function: #Function<3.131974459/0 in Que.Job.perform/1>
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]:     Args: []
Jan 24 23:17:12 BlockScout-mainnet3 mix[54941]: 2023-01-24T23:17:12.343 application=que [info] [Que] Failed Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker

```

also, I see that request was triggerer inside smart-contract-verifier-http

```
2023-01-24T22:24:36.203812Z  INFO actix_server::builder: starting 128 workers
2023-01-24T22:24:36.203981Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
2023-01-24T22:57:23.654492Z  INFO HTTP request{http.method=POST http.route=/api/v1/solidity/verify/multiple-files http.flavor=1.1 http.scheme=http http.host=0.0.0.0:8043 http.client_ip=127.0.0.1 http.user_agent=hackney/1.18.1 http.target=/api/v1/solidity/verify/multiple-files otel.name=HTTP POST /api/v1/solidity/verify/multiple-files otel.kind="server" request_id=83fa8bfe-b8bb-430b-85d1-f36d481e65ca}: compiler_cache: installing file version v0.8.17+commit.8df45f5f
2023-01-24T23:00:00.000809Z  INFO smart_contract_verifier::compiler::versions_fetcher: looking for new compilers versions
2023-01-24T23:00:00.004378Z  INFO smart_contract_verifier::compiler::versions_fetcher: looking for new compilers versions
2023-01-24T23:00:00.049407Z  INFO smart_contract_verifier::compiler::versions_fetcher: no new versions found
2023-01-24T23:00:00.238315Z  INFO smart_contract_verifier::compiler::versions_fetcher: no new versions found

```

one thing that also bothers me is that I had to manually use /verify-via-flattened-code/new, I am missing Code option in my version, do I need something else to be enabled? 
I have 
```
ENABLE_RUST_VERIFICATION_SERVICE=true
RUST_VERIFICATION_SERVICE_URL=http://0.0.0.0:8043/

```

Thank you

**Comment by dorijan** [comment]
Ok, now I see the contract in the blockscout, click verify here

![image](https://user-images.githubusercontent.com/2230204/214466742-04e66abd-1f15-4098-820a-5c70b918ab84.png)

but still got error

```
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]: 2023-01-25T02:16:23.789 [error] Task #PID<0.14457.0> started from #PID<0.4779.0> terminating
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]: ** (UndefinedFunctionError) function nil.bytes/0 is undefined
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]:     nil.bytes()
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]:     (explorer 4.1.8) lib/explorer/smart_contract/helper.ex:46: Explorer.SmartContract.Helper.add_contract_code_md5/1
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]:     (explorer 4.1.8) lib/explorer/chain.ex:3862: Explorer.Chain.create_smart_contract/3
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]:     (explorer 4.1.8) lib/explorer/smart_contract/solidity/publisher_worker.ex:14: Explorer.SmartContract.Solidity.PublisherWorker.perform/1
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]:     (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]:     (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]: Function: #Function<3.131974459/0 in Que.Job.perform/1>
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]:     Args: []
Jan 25 02:16:23 BlockScout-mainnet3 mix[100782]: 2023-01-25T02:16:23.790 application=que [info] [Que] Failed Job # 3 with Explorer.SmartContract.Solidity.PublisherWorker


```

**Comment by dorijan** [comment]
hm, it seems that the problem is that polygon-edge does not support 
`the method trace_replayBlockTransactions does not exist/is not available`
so I had to turn on 
`INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER="true"`

is there anyway around that?

**Comment by vbaranov** [comment]
@dorijan  The node, which Blockscout connected to, should support one of these twom methods https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#enable-tracing-to-fetch-internal-transactions. Does Polygon Edge support any of them?

**Comment by ekawibisono** [comment]
Hello @dorijan 
Can you show us the ENV settings you made?

**Comment by vbaranov** [comment]
Closing this issue due lack of feedback from user.
