### ISSUE TITLE
internal_transaction fetcher failed with `Block without total difficulty calculated was suggested for processing`

### ISSUE THREAD

**Issue by abcfy2** [blockscout/blockscout#6829]
*Describe your issue here.*

Nowadays I find lots of internal_transaction fetcher errors like:

```
2023-02-07T02:10:44.438 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:45.574 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:46.031 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:46.995 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
2023-02-07T02:10:47.031 application=indexer fetcher=empty_blocks_to_refetch [info] Block with number 16573837 and hash 0xc190bcecd5f4b19829190c6dc96f5cec47b378d5f8f01440a2a1264f97dac288 is full of transactions. We should set consensus=false for it in order to refetch.
2023-02-07T02:10:47.044 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
2023-02-07T02:10:47.502 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:47.952 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:48.337 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:50.008 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:50.024 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:50.083 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:51.689 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:52.080 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:52.316 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-07T02:10:57.044 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
```

And I find Nethermind log contains like this errors:

```
2023-02-07 02:12:38.1404|INFO|23|Executing JSON RPC call trace_replayBlockTransactions with params [0xFB8354, [
  "trace"
]] 
2023-02-07 02:12:38.1432|ERROR|23|Error during method execution, request: ID 1, trace_replayBlockTransactions(0xFB8354,[
  "trace"
]) System.InvalidOperationException: Block without total difficulty calculated was suggested for processing
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunSimpleChecksAheadOfProcessing(Block suggestedBlock, ProcessingOptions options)
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes)
   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-02-07 02:12:38.1432|WARN|23|Error when handling ID 1, trace_replayBlockTransactions(0xFB8354,[
  "trace"
]) | {"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"System.InvalidOperationException: Block without total difficulty calculated was suggested for processing\n   at Nethermind.Consensus.Processing.BlockchainProcessor.RunSimpleChecksAheadOfProcessing(Block suggestedBlock, ProcessingOptions options)\n   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes)\n   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Object, IntPtr*)\n   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)"},"id":1} 
2023-02-07 02:12:38.1432|INFO|23|Executing JSON RPC call trace_replayBlockTransactions with params [0xFCE55C, [
  "trace"
]] 
2023-02-07 02:12:38.2607|INFO|23|Executing JSON RPC call trace_replayBlockTransactions with params [0xFCE572, [
  "trace"
]] 
2023-02-07 02:12:38.4086|INFO|23|Executing JSON RPC call trace_replayBlockTransactions with params [0xFCE584, [
  "trace"
]]
```

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.14.3 (compiled with Erlang/OTP 24)
* Node JS version (`node -v`): v18.14.0
* Operating System: Ubuntu 22.04
* Blockscout Version/branch/commit: 752def6ae256505f5ec961b3bf2b25a94f5516d5
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Nethermind

**Comment by vbaranov** [comment]
@abcfy2 it looks like the error is in with Nethermind's client response. Could you create an issue there instead?

**Comment by abcfy2** [comment]
Sure. Thanks. https://github.com/NethermindEth/nethermind/issues/5238

**Comment by abcfy2** [comment]
Seems `%{"blockNumber" => 16483156}` contains some special data. I find the errors always point to this block number.

**Comment by vbaranov** [comment]
I am closing this issue. For those who is intersted, please track progress on linked Nethermind issue.
