### ISSUE TITLE
"Unknown cipher or invalid key size" when logging in with Auth0

### ISSUE THREAD

**Issue by martinbutt** [blockscout/blockscout#6867]
Getting a 500 error when attempting to login using Auth0

```
2023-02-10T20:05:14.469 application=plug request_id=F0KPP45YF4D-ALcAABdR [info] GET /auth/auth0/callback
2023-02-10T20:05:15.131 application=plug request_id=F0KPP45YF4D-ALcAABdR [info] Sent 500 in 662ms
2023-02-10T20:05:15.132 [error] #PID<0.4760.0> running BlockScoutWeb.Endpoint (connection #PID<0.4721.0>, stream id 3) terminated
Server: [redacted]:4000 (http)
Request: GET /auth/auth0/callback?code=aiIxFvbwHw2S4f2hHGgKMh2Lkm5o_Qb0R3IYXKB7Ylb7m&state=YKnwLDQ9XJX1ERgwtii6OtAh
** (exit) an exception was raised:
** (ErlangError) Erlang error: {:badarg, {'aead.c', 90}, 'Unknown cipher or invalid key size'}
         (crypto 5.0.5) crypto.erl:945: :crypto.crypto_one_time_aead(:aes_256_gcm, "", <<211, 57, 29, 35, 236, 25, 70, 72, 4, 126, 111, 241, 113, 208, 1, 144>>, "https://lh3.googleusercontent.com/a/AEdFTp4u_k_us-[redacted]=s96-c", "AES256GCM", 16, true)
         (cloak 1.1.2) lib/cloak/ciphers/aes_gcm.ex:47: Cloak.Ciphers.AES.GCM.encrypt/2
         (explorer 5.0.0) lib/cloak_ecto/type.ex:37: Explorer.Encrypted.Binary.dump/1
         (ecto 3.9.4) lib/ecto/type.ex:941: Ecto.Type.process_dumpers/3
         (ecto 3.9.4) lib/ecto/repo/schema.ex:1006: Ecto.Repo.Schema.dump_field!/6
         (ecto 3.9.4) lib/ecto/repo/schema.ex:1019: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
         (stdlib 3.17) maps.erl:410: :maps.fold_1/3
         (ecto 3.9.4) lib/ecto/repo/schema.ex:1017: Ecto.Repo.Schema.dump_fields!/5
```

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`):
```Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [jit:no-native-stack]
Elixir 1.13.1 (compiled with Erlang/OTP 24)
```
* Node JS version (`node -v`):
v16.13.1
* Operating System:
Alpine Linux 3.15
* Blockscout Version/branch/commit:
5.0.0
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):
Polygon Edge

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Run with this ENV vars
```
ACCOUNT_ENABLED="true"
ACCOUNT_AUTH0_DOMAIN="[redacted].us.auth0.com"
ACCOUNT_AUTH0_CLIENT_ID="[redacted]"
ACCOUNT_AUTH0_CLIENT_SECRET="[redacted]"
ACCOUNT_AUTH0_LOGOUT_URL="https://[redacted].us.auth0.com/v2/logout"
ACCOUNT_AUTH0_LOGOUT_RETURN_URL="http://[redacted]:4000/auth/logout"
```

### Expected behaviour

User should be logged in

### Actual behaviour

User is presented with 500 error page

**Comment by nikitosing** [comment]
@martinbutt You need to set `ACCOUNT_CLOAK_KEY` env variable. How to generate: https://hexdocs.pm/cloak_ecto/generate_keys.html#content
