### ISSUE TITLE
BlockScout on polygon-edge 0.6.3 error while indexig blocks: 

### ISSUE THREAD

**Issue by Kankalius** [blockscout/blockscout#6959]
Good morning everyone, 
we are using BlockScout together with polygon-edge 0.6.3 and some of the blocks dont get imported with the following error: 

Feb 24 03:42:40 pooking mix[866]: 2023-02-24T03:42:40.471 application=indexer fetcher=block_catchup first_block_number=1982373 last_block_number=1982373 step=import [error] failed to validate: [#Ecto.Changeset<action: nil, changes: %{}, errors: [hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Address<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 1982373}, errors: [address_hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Address.CoinBalance<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: #Decimal<1982373>, gas_limit: #Decimal<1000000000>, gas_used: #Decimal<0>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<116, 78, 205, 4, 23, 192, 156, 206, 13, 171, 191, 7, 153, 136, 251, 133, 212, 146, 122, 169, 73, 68, 235, 167, 248, 86, 188, 229, 30, 139, 155, 139>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<0, 0, 0, 0, 0, 0, 0, 0>>}, number: 1982373, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<144, 207, 41, 166, 216, 92, 134, 212, 206, 171, 46, 20, 111, 206, 3, 40, 137, 57, 196, 246, 12, 167, 35, 209, 109, 141, 36, 63, 100, 226, 228, 245>>}, size: 4923, timestamp: ~U[2023-02-24 00:45:34.000000Z], total_difficulty: #Decimal<1982373>}, errors: [miner_hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{day: ~D[2023-02-24]}, errors: [address_hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Address.CoinBalanceDaily<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{address_type: :validator, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<116, 78, 205, 4, 23, 192, 156, 206, 13, 171, 191, 7, 153, 136, 251, 133, 212, 146, 122, 169, 73, 68, 235, 167, 248, 86, 188, 229, 30, 139, 155, 139>>}, reward: #Explorer.Chain.Wei<0>}, errors: [address_hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Block.Reward<>, valid?: false>]. Retrying.

Polygon-Edge is running in PoA mode. 

### Environment

* Deployment type (Manual/Docker/Docker-compose): manual

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] 
                                                                            Elixir 1.13.4 (compiled with Erlang/OTP 22)

* Node JS version (`node -v`): v16.19.0
* Operating System: Ubuntu Linux 20.04LTS 
* Blockscout Version/branch/commit: main 5.0 
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): polygon-edge 0.6.3 (afaik nethermind)

* ENV_VARS.ENV:
 
  ETHEREUM_JSONRPC_VARIANT=nethermind
  JSON_RPC=https://mainnet.poochain.co/rpc
  ETHEREUM_JSONRPC_HTTP_URL=127.0.0.1:10002
  ETHEREUM_JSONRPC_TRACE_URL=127.0.0.1:10002
  ETHEREUM_JSONRPC_HTTP_INSECURE=true
  DATABASE_URL='postgresql://pooscan:zqrohuXqQtRFo5NrLkJ7xwUZ5@localhost:5432/pooscan'
  SECRET_KEY_BASE="VhgLEGAmeqlVuEzCNYDPHWIgDdYh0jQZ8MiiJ1UR9JXoBKn8uwZgYgykxe7iJsWZ"
  ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:10002/ws
  CHAIN_ID=20202021
  HEART_COMMAND="sudo systemctl restart explorer.service"
  NETWORK=Block
  SUBNETWORK=PooChain
  LOGO="/images/poochain.png"
  LOGO_FOOTER="/images/poochain.png"
  COIN=POOP
  COIN_NAME=PooChain
  INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true
  INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
  INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
  INDEXER_DISABLE_CATALOGED_TOKEN_UPDATER_FETCHER=true
  MIX_ENV=prod
  BLOCKSCOUT_PROTOCOL=http
  PORT=4000
  DISABLE_EXCHANGE_RATES=true
  POOL_SIZE=200
  POOL_SIZE_API=300
  ECTO_USE_SSL=false
  HEART_BEAT_TIMEOUT=60
  INDEXER_MEMORY_LIMIT=10Gb
  FETCH_REWARDS_WAY=manual
  INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=1
  INDEXER_RECEIPTS_BATCH_SIZE=10
  INDEXER_COIN_BALANCES_BATCH_SIZE=10
  INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE=10
  DISPLAY_TOKEN_ICONS=true
  ENABLE_RUST_VERIFICATION_SERVICE=true
  RUST_VERIFICATION_SERVICE_URL=http://127.0.0.1:8043/
  RE_CAPTCHA_SECRET_KEY=xxxxx
  RE_CAPTCHA_CLIENT_KEY=xxxxx
  GAS_PRICE=750000
  SUPPORTED_CHAINS=[ { title: "PooChain", url: "https://blockscout.poochain.co" } ]
  FOOTER_CHAT_LINK=https://t.me/PooChainPortal
  HIDE_BLOCK_MINER=true
  PERMANENT_DARK_MODE_ENABLED=true
  
### Steps to reproduce

The issue looks like to be here since the start. We waited until the chain import is done. But issue still persists

### Expected behaviour

We'd like to have all blocks indexed and therfore visible. Maybe this also has to do with our API call problem reported a while back?

### Actual behaviour

BlockScout shows that not all Blocks are imported / indexed. Therefore we cant find all Transactions. 

Thank you very much for your help.

**Comment by Kankalius** [comment]
The issue could be solved with help by pengwyn in the blockscout discord server. 
Solution was to add `BLOCK_TRANSFORMER=clique` and also change the file: 

https://github.com/blockscout/blockscout/blob/e898a2331b60566afcc9f49dabe9225791a2d57f/apps/indexer/lib/indexer/transform/blocks/clique.ex#L16

`%{block | miner_hash: miner_address}' to '%{block | miner_hash: "0x0000000000000000000000000000000000000000"}`

and also delete Line 14 in that file. 

Then recompile and restart Blockscout. 

Thank you, pengwyn, for the solution. Highly appreciated.

**Comment by haidarabdillah** [comment]
> Then recompile and restart Blockscout.



> Solution was to add `BLOCK_TRANSFORMER=clique` into the file env_vars.env and also change the file:
when i use BLOCK_TRANSFORMER=base i got error like above, when i use BLOCK_TRANSFORMER=clique i got error like this 


`backend  | {"time":"2023-12-22T09:21:05.325Z","severity":"error","message":"** (MatchError) no match of right hand side value: {:error, :invalid_recovery_id}\n    (indexer 5.3.3) lib/indexer/transform/blocks.ex:96: Indexer.Transform.Blocks.recover_pub_key/2\n    (indexer 5.3.3) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 5.3.3) lib/indexer/block/fetcher.ex:139: Indexer.Block.Fetcher.fetch_and_import_range/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 5.3.3) lib/indexer/block/catchup/fetcher.ex:195: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","first_block_number":5355735,"last_block_number":5355726}}
`
