### ISSUE TITLE
Docker compose container blockscout crashloop using hardhat

### ISSUE THREAD

**Issue by sherpya** [blockscout/blockscout#6975]
I'm trying to start blockscout and make it connect to my local hardhat node, as suggested in the doc:

`docker-compose -f docker-compose-no-build-hardhat-network.yml up` (but without -d)

### Environment

* Deployment type: Docker-compose
* Operating System: Debian sid
* Blockscout Version/branch/commit: 1cd121dbe690c7d7f5f959149d9631a801428821

### Steps to reproduce

`docker-compose -f docker-compose-no-build-hardhat-network.yml up` (but without -d)

### Expected behaviour

Something working

### Actual behaviour

```
blockscout                 | warning: redefining module ConfigHelper (current version defined in memory)
blockscout                 |   config/config_helper.exs:1
blockscout                 | 
blockscout                 | Starting dependencies..
blockscout                 | Starting repos..
blockscout                 | Create Explorer.Repo database if it doesn't exist
blockscout                 | Create Explorer.Repo.Account database if it doesn't exist
blockscout                 | Running migrations for explorer
blockscout                 | 2023-02-25T16:31:57.837 application=ecto_sql [info] Migrations already up
blockscout                 | Running migrations for explorer
blockscout                 | Success!
blockscout                 | 2023-02-25T16:31:57.844 application=ecto_sql [info] Migrations already up
blockscout                 | warning: redefining module ConfigHelper (current version defined in memory)
blockscout                 |   config/config_helper.exs:1
blockscout                 | 
blockscout                 | 2023-02-25T16:32:00.184 application=que [info] [Que] Booting Que
blockscout                 | 2023-02-25T16:32:00.185 application=que [info] [Que] Booting Server Supervisor for Workers
blockscout                 | 2023-02-25T16:32:00.265 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.265 application=explorer [info] tx/per day chart: earliest date 2023-02-16 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.265 application=explorer [info] tx/per day chart: latest date 2023-02-16 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.276 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.276 application=explorer [info] tx/per day chart: earliest date 2023-02-17 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.276 application=explorer [info] tx/per day chart: latest date 2023-02-17 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.284 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.284 application=explorer [info] tx/per day chart: earliest date 2023-02-18 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.284 application=explorer [info] tx/per day chart: latest date 2023-02-18 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.291 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.291 application=explorer [info] tx/per day chart: earliest date 2023-02-19 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.291 application=explorer [info] tx/per day chart: latest date 2023-02-19 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.296 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.296 application=explorer [info] tx/per day chart: earliest date 2023-02-20 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.296 application=explorer [info] tx/per day chart: latest date 2023-02-20 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.303 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.303 application=explorer [info] tx/per day chart: earliest date 2023-02-21 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.303 application=explorer [info] tx/per day chart: latest date 2023-02-21 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.304 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)
blockscout                 | 2023-02-25T16:32:00.308 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.308 application=explorer [info] tx/per day chart: earliest date 2023-02-22 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.308 application=explorer [info] tx/per day chart: latest date 2023-02-22 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.308 application=phoenix [info] Access BlockScoutWeb.Endpoint at ://:4000
blockscout                 | 2023-02-25T16:32:00.316 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.316 application=explorer [info] tx/per day chart: earliest date 2023-02-23 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.316 application=explorer [info] tx/per day chart: latest date 2023-02-23 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.325 application=db_connection [info] Postgrex.Protocol (#PID<0.4115.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4845.0> exited
blockscout                 | 2023-02-25T16:32:00.325 application=db_connection [info] Postgrex.Protocol (#PID<0.4123.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4868.0> exited
blockscout                 | 2023-02-25T16:32:00.325 application=db_connection [info] Postgrex.Protocol (#PID<0.4132.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4876.0> exited
blockscout                 | 2023-02-25T16:32:00.326 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.326 application=explorer [info] tx/per day chart: earliest date 2023-02-24 00:00:00Z
blockscout                 | 2023-02-25T16:32:00.326 application=explorer [info] tx/per day chart: latest date 2023-02-24 23:59:59Z
blockscout                 | 2023-02-25T16:32:00.326 [notice] Application indexer exited: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Supervisor
blockscout                 |     ** (EXIT) shutdown: failed to start child: Indexer.Block.Catchup.Supervisor
blockscout                 |         ** (EXIT) shutdown: failed to start child: Indexer.Block.Catchup.MissingRangesCollector
blockscout                 |             ** (EXIT) an exception was raised:
blockscout                 |                 ** (MatchError) no match of right hand side value: {:error, :econnrefused}
blockscout                 |                     (indexer 5.1.0) lib/indexer/block/catchup/missing_ranges_collector.ex:196: Indexer.Block.Catchup.MissingRangesCollector.fetch_max_block_number/0
blockscout                 |                     (indexer 5.1.0) lib/indexer/block/catchup/missing_ranges_collector.ex:113: Indexer.Block.Catchup.MissingRangesCollector.get_initial_min_max/0
blockscout                 |                     (indexer 5.1.0) lib/indexer/block/catchup/missing_ranges_collector.ex:42: Indexer.Block.Catchup.MissingRangesCollector.default_init/0
blockscout                 |                     (indexer 5.1.0) lib/indexer/block/catchup/missing_ranges_collector.ex:24: Indexer.Block.Catchup.MissingRangesCollector.init/1
blockscout                 |                     (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
blockscout                 |                     (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
blockscout                 |                     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
postgres                   | 2023-02-25 16:32:00.331 UTC [576] LOG:  unexpected EOF on client connection with an open transaction
postgres                   | 2023-02-25 16:32:00.331 UTC [592] LOG:  unexpected EOF on client connection with an open transaction
blockscout                 | 2023-02-25T16:32:00.336 application=explorer [info] tx/per day chart: collect records for txs per day stats
blockscout                 | 2023-02-25T16:32:00.336 application=explorer [info] tx/per day chart: records collected [%{date: ~D[2023-02-24], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-02-23], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-02-22], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-02-21], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-02-20], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-02-19], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-02-18], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-02-17], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-02-16], gas_used: 0, number_of_transactions: 0, total_fee: 0}]
blockscout                 | 2023-02-25T16:32:00.337 application=explorer [info] tx/per day chart: save records
blockscout                 | 2023-02-25T16:32:00.342 application=explorer [info] tx/per day chart: number of inserted 10
blockscout                 | {"Kernel pid terminated",application_controller,"{application_start_failure,indexer,{{shutdown,{failed_to_start_child,'Elixir.Indexer.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Indexer.Block.Catchup.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Indexer.Block.Catchup.MissingRangesCollector',{{badmatch,{error,econnrefused}},[{'Elixir.Indexer.Block.Catchup.MissingRangesCollector',fetch_max_block_number,0,[{file,\"lib/indexer/block/catchup/missing_ranges_collector.ex\"},{line,196}]},{'Elixir.Indexer.Block.Catchup.MissingRangesCollector',get_initial_min_max,0,[{file,\"lib/indexer/block/catchup/missing_ranges_collector.ex\"},{line,113}]},{'Elixir.Indexer.Block.Catchup.MissingRangesCollector',default_init,0,[{file,\"lib/indexer/block/catchup/missing_ranges_collector.ex\"},{line,42}]},{'Elixir.Indexer.Block.Catchup.MissingRangesCollector',init,1,[{file,\"lib/indexer/block/catchup/missing_ranges_collector.ex\"},{line,24}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}}}}}},{'Elixir.Indexer.Application',start,[normal,[]]}}}"}
blockscout                 | Kernel pid terminated (application_controller) ({application_start_failure,indexer,{{shutdown,{failed_to_start_child,'Elixir.Indexer.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Indexer.Block.Catchup.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Indexer.Block.Catchup.MissingRangesCollector',{{badmatch,{error,econnrefused}},[{'Elixir.Indexer.Block.Catchup.MissingRangesCollector',fetch_max_block_number,0,[{file,"lib/indexer/block/catchup/missing_ranges_collector.ex"},{line,196}]},{'Elixir.Indexer.Block.Catchup.MissingRangesCollector',get_initial_min_max,0,[{file,"lib/indexer/block/catchup/missing_ranges_collector.ex"},{line,113}]},{'Elixir.Indexer.Block.Catchup.MissingRangesCollector',default_init,0,[{file,"lib/indexer/block/catchup/missing_ranges_collector.ex"},{line,42}]},{'Elixir.Indexer.Block.Catchup.MissingRangesCollector',init,1,[{file,"lib/indexer/block/catchup/missing_ranges_collector.ex"},{line,24}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{fil
blockscout                 | 
blockscout                 | Crash dump is being written to: erl_crash.dump...done
blockscout exited with code 1
```

**Comment by vbaranov** [comment]
@sherpya most likely, you have the same issue as described [here](https://github.com/blockscout/blockscout/issues/6875). Could you try https://github.com/blockscout/blockscout/issues/6875#issuecomment-1428046605 ?

**Comment by sherpya** [comment]
> @sherpya most likely, you have the same issue as described [here](https://github.com/blockscout/blockscout/issues/6875). Could you try [#6875 (comment)](https://github.com/blockscout/blockscout/issues/6875#issuecomment-1428046605) ?

yes it works, but I don't think is a good idea to crash if the node is not reachable, a connection refused message would made me known more about the problem
