### ISSUE TITLE
blockscout can't got new blocks after restart our chain.

### ISSUE THREAD

**Issue by LuxesOwen** [blockscout/blockscout#6982]
We got this error '[ERROR] polygon.txpool: enqueue request: err="nonce too low"' in my chain ,then we restart our chain nodes.
Then our chain returns to normal,but blockscout can't got any new blocks,restart can't solve it.

There are error.log:
```
2023-02-27T13:28:01.747 fetcher=internal_transaction count=10 [error] Task #PID<0.3125.0> started from Indexer.Fetcher.InternalTransaction terminating
** (CaseClauseError) no case clause matching: {:error, [#Ecto.Changeset<action: nil, changes: %{block_number: 6489975, call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<90, 118, 203, 219, 195, 158, 66, 206, 166, 194, 94, 38, 202, 27, 131, 246, 52, 7, 74, 10>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 18, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<53, 56, 103, 97, 146, 82, 250, 170, 164, 177, 93, 163, 137, 84, 20, 199, 234, 248, 204, 177>>}, trace_address: [0, 8, 0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<52, 70, 72, 86, 100, 250, 83, 203, 217, 79, 250, 173, 92, 44, 50, 197, 81, 188, 229, 1, 233, 186, 117, 141, 63, 22, 82, 43, 223, 233, 141, 248>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<877797455726400>}, errors: [input: {"is invalid", [type: Explorer.Chain.Data, validation: :cast]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 6489975, call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<90, 118, 203, 219, 195, 158, 66, 206, 166, 194, 94, 38, 202, 27, 131, 246, 52, 7, 74, 10>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 15, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<53, 56, 103, 97, 146, 82, 250, 170, 164, 177, 93, 163, 137, 84, 20, 199, 234, 248, 204, 177>>}, trace_address: [0, 7, 0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<52, 70, 72, 86, 100, 250, 83, 203, 217, 79, 250, 173, 92, 44, 50, 197, 81, 188, 229, 1, 233, 186, 117, 141, 63, 22, 82, 43, 223, 233, 141, 248>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<515246147326800>}, errors: [input: {"is invalid", [type: Explorer.Chain.Data, validation: :cast]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 6489975, call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<93, 14, 69, 173, 195, 108, 227, 151, 194, 122, 149, 211, 118, 167, 83, 249, 215, 176, 28, 159>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 10, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<53, 56, 103, 97, 146, 82, 250, 170, 164, 177, 93, 163, 137, 84, 20, 199, 234, 248, 204, 177>>}, trace_address: [0, 4], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<52, 70, 72, 86, 100, 250, 83, 203, 217, 79, 250, 173, 92, 44, 50, 197, 81, 188, 229, 1, 233, 186, 117, 141, 63, 22, 82, 43, 223, 233, 141, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<200000000000000000000>}, errors: [input: {"is invalid", [type: Explorer.Chain.Data, validation: :cast]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 6489918, call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<90, 118, 203, 219, 195, 158, 66, 206, 166, 194, 94, 38, 202, 27, 131, 246, 52, 7, 74, 10>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 16, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<53, 56, 103, 97, 146, 82, 250, 170, 164, 177, 93, 163, 137, 84, 20, 199, 234, 248, 204, 177>>}, trace_address: [0, 6, 0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<206, 46, 95, 25, 181, 254, 233, 227, 204, 78, 192, 192, 42, 118, 243, 134, 48, 239, 209, 40, 144, 144, 42, 18, 13, 42, 56, 73, 71, 73, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<156078349176962210484>}, errors: [input: {"is invalid", [type: Explorer.Chain.Data, validation: :cast]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 6489918, call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<90, 118, 203, 219, 195, 158, 66, 206, 166, 194, 94, 38, 202, 27, 131, 246, 52, 7, 74, 10>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 13, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<53, 56, 103, 97, 146, 82, 250, 170, 164, 177, 93, 163, 137, 84, 20, 199, 234, 248, 204, 177>>}, trace_address: [0, 5, 0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<206, 46, 95, 25, 181, 254, 233, 227, 204, 78, 192, 192, 42, 118, 243, 134, 48, 239, 209, 40, 144, 144, 42, 18, 13, 42, 56, 73, 71, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<41615265267610766153>}, errors: [input: {"is invalid", [type: Explorer.Chain.Data, validation: :cast]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 6489918, call_type: :call, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<93, 14, 69, 173, 195, 108, 227, 151, 194, 122, 149, 211, 118, 167, 83, 249, 215, 176, 28, 159>>}, gas: #Decimal<0>, gas_used: #Decimal<0>, index: 10, output: %Explorer.Chain.Data{bytes: ""}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<53, 56, 103, 97, 146, 82, 250, 170, 164, 177, 93, 163, 137, 84, 20, 199, 234, 248, 204, 177>>}, trace_address: [0, 4], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<206, 46, 95, 25, 181, 254, 233, 227, 204, 78, 192, 192, 42, 118, 243, 134, 48, 239, 209, 40, 144, 144, 42, 18, 13, 42, 56, 73, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<12953080242229913796>}, errors: [input: {"is invalid", [type: Explorer.Chain.Data, validation: :cast]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>]}
    (indexer 5.1.0) lib/indexer/fetcher/internal_transaction.ex:232: Indexer.Fetcher.InternalTransaction.import_internal_transaction/2
    (indexer 5.1.0) lib/indexer/fetcher/internal_transaction.ex:196: Indexer.Fetcher.InternalTransaction.safe_import_internal_transaction/2
    (indexer 5.1.0) lib/indexer/fetcher/internal_transaction.ex:117: Indexer.Fetcher.InternalTransaction.run/2
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [6490194, 6490162, 6490196, 6490197, 6489975, 6490198, 6490199, 6489918, 6490184, 6490187], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://127.0.0.1:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]
```
we set up blockscout manually,and had upgrade to last version.

**Comment by vbaranov** [comment]
@LuxesOwen will the issue been resolved, if you set:
```
INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE=js
```
?
Could you try?

If it it doesn't help does the node support any of these tracing methods https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#enable-tracing-to-fetch-internal-transactions?

**Comment by LuxesOwen** [comment]
hi @vbaranov ,I always had this env variable. I added this config shortly after you guys updated it. 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/66360114/221595118-2148e54f-86b1-465b-8b76-3b02238578a8.png">
It has been running well until one token transfer transaction got stuck just one hour ago.

**Comment by LuxesOwen** [comment]
I tried.
Originally, this error kept occurring, then I modified INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE=call_tracer, the error log no longer generated,but the Blocks in the page still hasn't moved.
Now that error log doesn't happen again, even if I change back to the original configuration as “INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE=js”.

**Comment by LuxesOwen** [comment]
I think that stuck transaction and our operation to restart the chain may have broken the data integrity of blockscout,If I reinstall blockscout and make sync afresh it will fixed,can I do this?

**Comment by vbaranov** [comment]
If you restarted the chain from scratch (blocks have different hashesfor the same height), yes, you have to restart Blockscout from scratch (on a fresh DB).

**Comment by LuxesOwen** [comment]
I found the reason.I forgot to restart the local node of our chain which running in the same server as blockscout.This node only use for blockscout sync blocks. thank you @vbaranov ,sorry for my fault.
