### ISSUE TITLE
C1: CSV for Transaction History fails to export

### ISSUE THREAD

**Issue by metipton** [blockscout/blockscout#7192]
CSV transaction export failing with error for this url https://explorer-mainnet-cardano-evm.c1.milkomeda.com/csv-export?address=0xc790bF7b439e5A10C478249b4B25b621eeDCe3e4&type=transactions: 

recaptcha__en.js:199         
       Uncaught Error: No reCAPTCHA clients exist.
    at Array.<anonymous> (recaptcha__en.js:199:187)
    at recaptcha__en.js:431:242
    at HTMLButtonElement.<anonymous> (datepicker-b7ab4e5b91898751d47dc6d988cab457.js?vsn=d:2:199938)
    at HTMLButtonElement.dispatch (datepicker-b7ab4e5b91898751d47dc6d988cab457.js?vsn=d:2:66481)
    at y.handle (datepicker-b7ab4e5b91898751d47dc6d988cab457.js?vsn=d:2:64476)

### Environment
* BlockScout Version: v4.1.2-beta

* User Agent: All browsers (Brave, edge, chrome)

### Steps to reproduce

Go to link and click export csv -

### Expected Behaviour

Should export the csv

### Actual Behaviour
Download spinner just spins indefinitely

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance. The maintainer should set reCAPTCHA v2 client and secret in order to make csv export functionality work.
