### ISSUE TITLE
no function clause matching in Ecto.Repo.Schema.delete/4

### ISSUE THREAD

**Issue by bretep** [blockscout/blockscout#7198]
```
2023-04-02T23:00:40.120 fetcher=block_catchup first_block_number=16466008 last_block_number=15467677 [error] Task #PID<0.13711.1> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating
** (FunctionClauseError) no function clause matching in Ecto.Repo.Schema.delete/4
    (ecto 3.9.5) lib/ecto/repo/schema.ex:515: Ecto.Repo.Schema.delete(Explorer.Repo, Explorer.Repo, nil, {%{adapter: Ecto.Adapters.Postgres, cache: #Reference<0.3208346970.873594881.115206>, opts: [repo: Explorer.Repo, timeout: 60000, pool_size: 40, pool: DBConnection.ConnectionPool], pid: #PID<0.4113.0>, repo: Explorer.Repo, sql: Ecto.Adapters.Postgres.Connection, stacktrace: nil, telemetry: {Explorer.Repo, :debug, [:explorer, :repo, :query]}}, []})
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (indexer 5.1.2) lib/indexer/block/catchup/fetcher.ex:79: Indexer.Block.Catchup.Fetcher.task/1
    (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://execution-explorer-archive.service.us-east-1.consul:80/", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [:insecure, {:pool, :ethereum_jsonrpc}]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 50, receipts_concurrency: 10}, memory_monitor: Indexer.Memory.Monitor}]
```

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System: Linux
* Blockscout Version/branch/commit: 5.1.2-Beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

Index ethereum mainnet
https://github.com/blockscout/blockscout/blob/c175d2b3bb96a5913c678987613b92fb2f357bb1/apps/indexer/lib/indexer/block/catchup/fetcher.ex#L79

### Expected behaviour

Should not throw error

### Actual behaviour

```
2023-04-02T23:00:40.120 fetcher=block_catchup first_block_number=16466008 last_block_number=15467677 [error] Task #PID<0.13711.1> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating
** (FunctionClauseError) no function clause matching in Ecto.Repo.Schema.delete/4
    (ecto 3.9.5) lib/ecto/repo/schema.ex:515: Ecto.Repo.Schema.delete(Explorer.Repo, Explorer.Repo, nil, {%{adapter: Ecto.Adapters.Postgres, cache: #Reference<0.3208346970.873594881.115206>, opts: [repo: Explorer.Repo, timeout: 60000, pool_size: 40, pool: DBConnection.ConnectionPool], pid: #PID<0.4113.0>, repo: Explorer.Repo, sql: Ecto.Adapters.Postgres.Connection, stacktrace: nil, telemetry: {Explorer.Repo, :debug, [:explorer, :repo, :query]}}, []})
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (indexer 5.1.2) lib/indexer/block/catchup/fetcher.ex:79: Indexer.Block.Catchup.Fetcher.task/1
    (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://execution-explorer-archive.service.us-east-1.consul:80/", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [:insecure, {:pool, :ethereum_jsonrpc}]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 50, receipts_concurrency: 10}, memory_monitor: Indexer.Memory.Monitor}]
```

**Comment by bretep** [comment]
Thanks @vbaranov!

**Comment by Qwerty5Uiop** [comment]
Hi @bretep! Are you running more than one instance of app using one database in this case?

**Comment by bretep** [comment]
Yes. I have a single database [db.r6i.24xlarge](https://instances.vantage.sh/aws/rds/db.r6i.24xlarge)

6 frontends 
1 indexer 

I have more indexers, but they are disabled due to SQL deadlocks

**Comment by vbaranov** [comment]
@bretep You shouldn't use several indexers - it is unsupported configuration. With a single indexer and multiple frontends do you still see the originally posted error?

**Comment by vbaranov** [comment]
I am closing this issue. Please create a new one, if you still experience this error when single indexer is used.
