### ISSUE TITLE
Linea Testnet: <Issue Title>

### ISSUE THREAD

**Issue by Py-DragonXx** [blockscout/blockscout#7237]
So, I feel there's an issue with the testnet on https://swap.goerli.linea.build/. Tokens don't pop up on the list, expect ETH (Linea) and crWETH. I tried importing crUSDC, it imported and swapped successfully, although when adding liquidity to the pool, immediately I paste crUSDC's contract address, and select the "Exotic pairs" percentage, it returns and error while the page just goes blank. 

The error codes were like this: Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ns (https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3414520)
    at tf (https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3379876)
    at https://swap.goerli.linea.build/static/js/main.ff0e20dd.chunk.js:1:389505
    at ru (https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3405043)
    at Es (https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3425255)
    at https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3423990
    at Os (https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3424056)
    at us (https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3417775)
    at qi (https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3358239)
    at Es (https://swap.goerli.linea.build/static/js/4.972e6442.chunk.js:2:3425397)

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; TECNO KG5k) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Well, what's expected is that the page should maintain its form, and proceed to allowing access in creating a liquidity pool for the pair crWETH/crUSDC.*

### Actual Behaviour

*Page just went blank, and returned the error codes listed in the first paragraph's description.*

**Comment by vbaranov** [comment]
Please reach out Linea testnet support. There is nothing related to Blockscout explorer in your question.
