### ISSUE TITLE
API v2: state change endpoint internal server error

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#7281]
https://base-goerli.blockscout.com/tx/0x0d4e808a0ce8bac3b4e4b8b3075ed11a75c359af93b588ae2733b5df7b210e74?tab=state

![Screenshot 2023-04-14 at 12 08 26](https://user-images.githubusercontent.com/4341812/232000040-42b18b67-beec-48ca-934d-a494f6659eca.png)

```
Request: GET /api/v2/transactions/0x0d4e808a0ce8bac3b4e4b8b3075ed11a75c359af93b588ae2733b5df7b210e74/state-changes
** (exit) an exception was raised:
    ** (KeyError) key :hash not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (block_scout_web 5.1.3) lib/block_scout_web/models/transaction_state_helper.ex:37: BlockScoutWeb.Models.TransactionStateHelper.state_changes/1
        (block_scout_web 5.1.3) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:246: BlockScoutWeb.API.V2.TransactionController.state_changes/2
        (block_scout_web 5.1.3) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2
        (block_scout_web 5.1.3) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 5.1.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
```

**Comment by vbaranov** [comment]
@sl1depengwyn the same issue in current UI as well:
https://blockscout.com/xdai/mainnet/tx/0x2ba9246c78780e67c389261c5c233e5132c7f330dc29a8de657560b0d47908de/state

![Screenshot 2023-04-14 at 12 29 49](https://user-images.githubusercontent.com/4341812/232005972-bc6a6f07-bc39-49e7-b437-0ab104291bd1.png)
