### ISSUE TITLE
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2943ms. This means requests are coming in and your connection pool cannot serve them fast enough.

### ISSUE THREAD

**Issue by BrooksYang** [blockscout/blockscout#7296]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System: Ubuntu 20.04.1 LTS
* Blockscout Version/branch/commit: v5.1.3-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):Geth

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*
should run

### Actual behaviour

*Tell us what happens instead.*
Can not start blockscout container
<img width="1513" alt="image" src="https://user-images.githubusercontent.com/20674504/232634920-fa1f4c10-8275-454b-9674-462093042c4d.png">
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/20674504/232634996-768a83f8-2e08-4be0-aa07-c89bbf50301c.png">

Here is the docker log:
[blockscout.log](https://github.com/blockscout/blockscout/files/11256604/blockscout.log)

**Comment by vbaranov** [comment]
@BrooksYang how much host machine resources allocated for Docker itself? You also can try increase `POOL_SIZE` env variable if 90 (default value) is not enough.

**Comment by BrooksYang** [comment]
> 

I have increased POOL_SIZE env to 99, but it is still the same error. 
What is the maximum value?

**Comment by BrooksYang** [comment]
> @BrooksYang how much host machine resources allocated for Docker itself? You also can try increase `POOL_SIZE` env variable if 90 (default value) is not enough.

I have increased POOL_SIZE env to 99, but it is still the same error.
What is the maximum value?

**Comment by ishanjain28** [comment]
This also does not work for me. I also tried with `POOL_SIZE` values from 90 to 5000 and it was failing with the exact same errors in the exact same time(~3 seconds)  

<details>
<summary>
Logs</br>
I am using latest version of blockscout an deploying it with docker.

```
blockscout/blockscout                        latest    7103c12c3c97   46 hours ago   493MB
redis                                        alpine    1e5fefbc0ede   7 days ago     30.2MB
postgres                                     14        db0d0947787d   7 days ago     409MB
ghcr.io/blockscout/smart-contract-verifier   latest    7e04f7f64221   10 days ago    197MB
ghcr.io/blockscout/sig-provider              latest    cce35037e705   6 weeks ago    175MB
ghcr.io/blockscout/visualizer                latest    532d65fd8694   4 months ago   865MB

```
</summary>


````
blockscout               | warning: redefining module ConfigHelper (current version defined in memory)
blockscout               |   config/config_helper.exs:1
blockscout               |
blockscout               | warning: redefining module ConfigHelper (current version defined in memory)
blockscout               |   config/config_helper.exs:1
blockscout               |
blockscout               | Starting dependencies..
blockscout               | Starting repos..
blockscout               | Create Explorer.Repo database if it doesn't exist
blockscout               | Create Explorer.Repo.Account database if it doesn't exist
blockscout               | Running migrations for explorer
blockscout               | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2972ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
blockscout               |
blockscout               |   1. Ensuring your database is available and that you can connect to it
blockscout               |   2. Tracking down slow queries and making sure they are running fast enough
blockscout               |   3. Increasing the pool_size (although this increases resource consumption)
blockscout               |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
blockscout               |
blockscout               | See DBConnection.start_link/2 for more information
blockscout               |
blockscout               |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
blockscout               |     (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
blockscout               |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
blockscout               |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:738: Ecto.Migrator.verbose_schema_migration/3
blockscout               |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:552: Ecto.Migrator.lock_for_migrations/4
blockscout               |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4
blockscout               |     (elixir 1.14.0) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
blockscout               |     nofile:1: (file)
blockscout               | 2023-06-22T17:54:47.098 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:
blockscout               |
blockscout               |   * The database does not exist
blockscout               |   * The "schema_migrations" table, which Ecto uses for managing
blockscout               |     migrations, was defined by another library
blockscout               |   * There is a deadlock while migrating (such as using concurrent
blockscout               |     indexes with a migration_lock)
blockscout               |
blockscout               | To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
blockscout               |
blockscout               | To address the second, you can run "mix ecto.drop" followed by
blockscout               | "mix ecto.create", both for the desired MIX_ENV. Alternatively you may
blockscout               | configure Ecto to use another table and/or repository for managing
blockscout               | migrations:
blockscout               |
blockscout               |     config :explorer, Explorer.Repo,
blockscout               |       migration_source: "some_other_table_for_schema_migrations",
blockscout               |       migration_repo: AnotherRepoForSchemaMigrations
blockscout               |
blockscout               | The full error report is shown below.
blockscout               |
blockscout exited with code 1
blockscout               | warning: redefining module ConfigHelper (current version defined in memory)
blockscout               |   config/config_helper.exs:1
blockscout               |
blockscout               | warning: redefining module ConfigHelper (current version defined in memory)
blockscout               |   config/config_helper.exs:1
blockscout               |
blockscout               | Starting dependencies..
blockscout               | Starting repos..
blockscout               | Create Explorer.Repo database if it doesn't exist
blockscout               | Create Explorer.Repo.Account database if it doesn't exist
blockscout               | Running migrations for explorer
blockscout               | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2969ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
blockscout               |
blockscout               |   1. Ensuring your database is available and that you can connect to it
blockscout               |   2. Tracking down slow queries and making sure they are running fast enough
blockscout               |   3. Increasing the pool_size (although this increases resource consumption)
blockscout               |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
blockscout               |
blockscout               | See DBConnection.start_link/2 for more information
blockscout               |
blockscout               |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
blockscout               |     (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
blockscout               |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
blockscout               |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:738: Ecto.Migrator.verbose_schema_migration/3
blockscout               |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:552: Ecto.Migrator.lock_for_migrations/4
blockscout               |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4
blockscout               |     (elixir 1.14.0) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
blockscout               |     nofile:1: (file)
blockscout               | 2023-06-22T17:55:00.331 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:
blockscout               |
blockscout               |   * The database does not exist
blockscout               |   * The "schema_migrations" table, which Ecto uses for managing
blockscout               |     migrations, was defined by another library
blockscout               |   * There is a deadlock while migrating (such as using concurrent
blockscout               |     indexes with a migration_lock)
blockscout               |
blockscout               | To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
blockscout               |
blockscout               | To address the second, you can run "mix ecto.drop" followed by
blockscout               | "mix ecto.create", both for the desired MIX_ENV. Alternatively you may
blockscout               | configure Ecto to use another table and/or repository for managing
blockscout               | migrations:
blockscout               |
blockscout               |     config :explorer, Explorer.Repo,
blockscout               |       migration_source: "some_other_table_for_schema_migrations",
blockscout               |       migration_repo: AnotherRepoForSchemaMigrations
blockscout               |
blockscout               | The full error report is shown below.
blockscout               |
blockscout exited with code 1
blockscout               | warning: redefining module ConfigHelper (current version defined in memory)
blockscout               |   config/config_helper.exs:1
blockscout               |
blockscout               | warning: redefining module ConfigHelper (current version defined in memory)
blockscout               |   config/config_helper.exs:1
blockscout               |
````

</details>

**Comment by ishanjain28** [comment]
This was happening because of the firewall. I use `ufw` on the host and I had a rule to allow any traffic in the default docker network(`172.17.0.0/24`) but this project/docker-compose creates it's own network which in my case was using the subnet  `172.19.0.0/24`. 

It works perfectly after adding a rule like,

```
sudo ufw allow from 172.19.0.0/24
```

**Comment by ipatka** [comment]
> This was happening because of the firewall. I use `ufw` on the host and I had a rule to allow any traffic in the default docker network(`172.17.0.0/24`) but this project/docker-compose creates it's own network which in my case was using the subnet `172.19.0.0/24`.
> 
> It works perfectly after adding a rule like,
> 
> ```
> sudo ufw allow from 172.19.0.0/24
> ```

thanks this fixed it for me too when running the docker instance on a digital ocean droplet!

for future reference you can take these steps

```
docker network ls

NETWORK ID     NAME                     DRIVER    SCOPE
91d0acc275e6   bridge                   bridge    local
fa76585c2c9e   docker-compose_default   bridge    local
05d9b72a4cf3   host                     host      local
89bcdefcd60d   none                     null      local
```

then using the docker compose network ID

```
docker network inspect -f '{{range .IPAM.Config}}{{.Subnet}}{{end}}' fa76585c2c9e
172.18.0.0/16
```

then `sudo ufw allow from 172.18.0.0/24`
