### ISSUE TITLE
LoadTest API v1: Slow queries or lack of DB connections with >30 RPS profile

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#7306]
When running load tests for API v1 on https://eth-goerli.blockscout.com/ with more than 30 RPS we've encountered a lot of errors like:

```
"2023-04-20T13:37:02.943 application=api request_id=de0832f6f41c222ac9a21ee0fbc32186 [error] Error while calling RPC action\"** (Plug.Conn.WrapperError) ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1333ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\\n\\n 1. Ensuring your database is available and that you can connect to it\\n 2. Tracking down slow queries and making sure they are running fast enough\\n 3. Increasing the pool_size (although this increases resource consumption)\\n 4. Allowing requests to wait longer by increasing :queue_target and :queue_interval\\n\\nSee DBConnection.start_link/2 for more information\\n\\n (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1\\n (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6\\n (ecto 3.10.1) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4\\n (ecto 3.10.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\\n (ecto 3.10.1) lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3\\n (block_scout_web 5.1.3) lib/block_scout_web/controllers/api/rpc/address_controller.ex:512: BlockScoutWeb.API.RPC.AddressController.get_token_balance/1\\n (block_scout_web 5.1.3) lib/block_scout_web/controllers/api/rpc/address_controller.ex:193: BlockScoutWeb.API.RPC.AddressController.tokenbalance/2\\n (block_scout_web 5.1.3) lib/block_scout_web/controllers/api/rpc/address_controller.ex:1: BlockScoutWeb.API.RPC.AddressController.action/2\\n\"\n"

```

**Comment by vbaranov** [comment]
Please re-test with 6.0.0 installed. I am closing this for now.
