### ISSUE TITLE
Postgrex expected an integer in .., got ...

### ISSUE THREAD

**Issue by shufps** [blockscout/blockscout#7404]
We see such errors in the logs:

```
2023-05-04T10:04:41.929 [error] Task #PID<0.32200.6> started from #PID<0.32190.6> terminating
** (DBConnection.EncodeError) Postgrex expected an integer in -9223372036854775808..9223372036854775807, got 36893488147420095501. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    (postgrex 0.17.1) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes.encode_params/3
    (postgrex 0.17.1) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.5.0) lib/db_connection.ex:1323: DBConnection.encode/5
    (db_connection 2.5.0) lib/db_connection.ex:1423: DBConnection.run_prepare_execute/5
    (db_connection 2.5.0) lib/db_connection.ex:1527: DBConnection.run/6
    (db_connection 2.5.0) lib/db_connection.ex:656: DBConnection.parsed_prepare_execute/5
    (db_connection 2.5.0) lib/db_connection.ex:648: DBConnection.prepare_execute/4
    (postgrex 0.17.1) lib/postgrex.ex:340: Postgrex.query/4
Function: #Function<5.43351853/0 in Explorer.Chain.address_counters/2>
    Args: []
```

Unfortunately we are no erlang developers, so we have no idea how to fix this (or what causes this).

What does `Explorer.Chain.address_counters/2` do? Perhaps it gives a clou ...

Do you have any ideas?

**Comment by vbaranov** [comment]
Address counter function apart from counters for transactions, token transfers, blocks vaildated, calculates the sum of gas used and saves it into the DB. `gas_used` column in `addresses` table has `bigint` type and `-9223372036854775808..9223372036854775807` is exactly range for Postgres's bigint type, and error means that application tries to insert a value, bigger than `bigint` limit.
