### ISSUE TITLE
Unknown token transfer format Goerli testnet

### ISSUE THREAD

**Issue by sl1depengwyn** [blockscout/blockscout#7686]
Error from goerli, probably related to https://github.com/blockscout/blockscout/pull/7653
```
2023-06-09T12:10:32.327 application=indexer fetcher=block_catchup first_block_number=9146282 last_block_number=9146273 [error] Unknown token transfer format: %{address_hash: "0xb1b5cc387d5e25adcdd5d732c87133bcc4e8db2a", block_hash: "0xfafa7671e3636808fd8b1ea55d493b1e3a7cfe5c08fb1590548aca7ec031f8e1", block_number: 9146278, data: "0x0000000000000000000000002f9997629ff1d73fada6dc6824a335fb20e3a73100000000000000000000000000000000000000000000000000071afd498d0000", first_topic: "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c", fourth_topic: nil, index: 0, second_topic: nil, third_topic: nil, transaction_hash: "0x7001ddcd8c6a1423301b3970385b101f55e389dd9e0446b4ef306a19f06245a8"}** (MatchError) no match of right hand side value: ""
    (ex_abi 0.6.0) lib/abi/type_decoder.ex:365: ABI.TypeDecoder.decode_uint/2
    (ex_abi 0.6.0) lib/abi/type_decoder.ex:190: anonymous fn/3 in ABI.TypeDecoder.do_decode_raw/2
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_abi 0.6.0) lib/abi/type_decoder.ex:185: ABI.TypeDecoder.do_decode_raw/2
    (ex_abi 0.6.0) lib/abi/type_decoder.ex:179: ABI.TypeDecoder.decode_raw/2
    (indexer 5.1.5) lib/indexer/transform/token_transfers.ex:241: Indexer.Transform.TokenTransfers.parse_params/1
    (indexer 5.1.5) lib/indexer/transform/token_transfers.ex:129: Indexer.Transform.TokenTransfers.do_parse/3
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (indexer 5.1.5) lib/indexer/transform/token_transfers.ex:32: Indexer.Transform.TokenTransfers.parse/1
    (indexer 5.1.5) lib/indexer/block/fetcher.ex:141: Indexer.Block.Fetcher.fetch_and_import_range/2
    (stdlib 4.3) timer.erl:235: :timer.tc/1
    (indexer 5.1.5) lib/indexer/block/catchup/fetcher.ex:178: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by vbaranov** [comment]
Goerli is the deprecated chain.
