### ISSUE TITLE
Problem when trying to start server

### ISSUE THREAD

**Issue by alex-bratu** [blockscout/blockscout#7689]
I am trying to redeploy blockscout but when I try to run mix phx.server I got errors from postgres. i deleted everything, I puuled the newest version of blockscout, reinstalled a newer version of postgres (13), and checked every dependency version.
### Environment

Manual deployment
Ubuntu 18

### Expected behaviour

run and start syncing with the node

*Tell us what happens instead.mix phx.server
warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

2023-06-12T12:49:10.651 [warning] The on_load function for module Elixir.ExKeccak returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29\' not found (required by /home/blockscout/_build/prod/lib/ex_keccak/priv/native/libexkeccak-v0.7.1-nif
-2.16-x86_64-unknown-linux-gnu.so)\''}}

2023-06-12T12:49:14.903 [warning] The on_load function for module Elixir.ExKeccak returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29\' not found (required by /home/blockscout/_build/prod/lib/ex_keccak/priv/native/libexkeccak-v0.7.1-nif
-2.16-x86_64-unknown-linux-gnu.so)\''}}

2023-06-12T12:49:14.911 application=que [info] [Que] Booting Que
2023-06-12T12:49:14.911 application=que [info] [Que] Booting Server Supervisor for Workers
2023-06-12T12:49:14.922 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.922 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.923 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.922 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.924 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.927 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.928 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.928 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.929 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.929 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.929 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.929 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.929 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.934 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.934 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.934 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.935 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.935 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.935 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.935 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.935 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.936 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.936 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.936 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.936 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.936 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.941 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.942 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.943 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.943 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.943 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.944 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.945 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.946 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.946 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.947 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.945 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.947 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.947 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.947 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.949 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.949 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.949 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.951 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.952 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.954 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.955 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.956 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.961 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.962 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.967 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.968 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.970 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-06-12T12:49:14.970 application=explorer [info] tx/per day chart: earliest date 2023-05-04 00:00:00Z
2023-06-12T12:49:14.970 application=explorer [info] tx/per day chart: latest date 2023-05-04 23:59:59Z
2023-06-12T12:49:14.976 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.977 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.977 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.977 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.982 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
2023-06-12T12:49:14.983 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.983 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.983 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.983 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.984 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.984 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.991 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.992 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.994 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.994 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.994 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.996 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.996 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.996 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
2023-06-12T12:49:14.996 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-06-12T12:49:14.996 application=explorer [info] tx/per day chart: earliest date 2023-05-05 00:00:00Z
2023-06-12T12:49:14.996 application=explorer [info] tx/per day chart: latest date 2023-05-05 23:59:59Z
2023-06-12T12:49:14.997 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:14.998 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.004 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.004 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.004 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
2023-06-12T12:49:15.007 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.008 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.009 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.010 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
2023-06-12T12:49:15.010 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-06-12T12:49:15.011 application=explorer [info] tx/per day chart: earliest date 2023-05-06 00:00:00Z
2023-06-12T12:49:15.011 application=explorer [info] tx/per day chart: latest date 2023-05-06 23:59:59Z
2023-06-12T12:49:15.010 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.012 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.013 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.013 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.013 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.014 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
2023-06-12T12:49:15.013 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.015 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
2023-06-12T12:49:15.015 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-06-12T12:49:15.015 application=explorer [info] tx/per day chart: earliest date 2023-05-07 00:00:00Z
2023-06-12T12:49:15.015 application=explorer [info] tx/per day chart: latest date 2023-05-07 23:59:59Z
2023-06-12T12:49:15.017 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.018 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.018 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.019 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.020 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.021 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
2023-06-12T12:49:15.022 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.023 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.024 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
2023-06-12T12:49:15.024 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-06-12T12:49:15.024 application=explorer [info] tx/per day chart: earliest date 2023-05-08 00:00:00Z
2023-06-12T12:49:15.024 application=explorer [info] tx/per day chart: latest date 2023-05-08 23:59:59Z
2023-06-12T12:49:15.024 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.025 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.025 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.026 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.026 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.026 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.029 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
2023-06-12T12:49:15.030 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.034 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.034 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.034 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.034 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
2023-06-12T12:49:15.035 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-06-12T12:49:15.035 application=explorer [info] tx/per day chart: earliest date 2023-05-09 00:00:00Z
2023-06-12T12:49:15.035 application=explorer [info] tx/per day chart: latest date 2023-05-09 23:59:59Z
2023-06-12T12:49:15.036 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.039 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
2023-06-12T12:49:15.040 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2023-06-12T12:49:15.042 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
2023-06-12T12:49:15.042 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-06-12T12:49:15.042 application=explorer [info] tx/per day chart: earliest date 2023-05-10 00:00:00Z
2023-06-12T12:49:15.042 application=explorer [info] tx/per day chart: latest date 2023-05-10 23:59:59Z
2023-06-12T12:49:15.044 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
2023-06-12T12:49:15.045 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
2023-06-12T12:49:15.045 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-06-12T12:49:15.045 application=explorer [info] tx/per day chart: earliest date 2023-05-11 00:00:00Z
2023-06-12T12:49:15.045 application=explorer [info] tx/per day chart: latest date 2023-05-11 23:59:59Z
2023-06-12T12:49:15.047 [notice] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:bad_return_from_init, {:stop, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :too_many_connection
s, file: "proc.c", line: "362", message: "sorry, too many clients already", pg_code: "53300", routine: "InitProcess", severity: "FATAL", unknown: "FATAL"}, query: nil}, %Postgrex.SimpleCon
nection{auto_reconnect: false, idle_interval: 5000, protocol: nil, reconnect_backoff: 500, state: {Postgrex.Notifications, %Postgrex.Notifications{auto_reconnect: false, connected: false, 
from: nil, listener_channels: %{}, listeners: %{}, ref: nil}}}}}}
            (explorer 5.1.5) lib/explorer/chain/events/listener.ex:17: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.17.2.1) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17.2.1) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2023-06-12T12:49:15.048 [notice] Application hammer_backend_redis exited: :stopped
2023-06-12T12:49:15.053 [notice] Application hammer exited: :stopped
2023-06-12T12:49:15.054 [notice] Application redix exited: :stopped
2023-06-12T12:49:15.054 [notice] Application nimble_options exited: :stopped
2023-06-12T12:49:15.054 [notice] Application cloak_ecto exited: :stopped
2023-06-12T12:49:15.054 [notice] Application cloak exited: :stopped
2023-06-12T12:49:15.054 [notice] Application cbor exited: :stopped
2023-06-12T12:49:15.055 application=db_connection [info] Postgrex.Protocol (#PID<0.975.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1431.0> exited
2023-06-12T12:49:15.062 [notice] Application con_cache exited: :stopped
2023-06-12T12:49:15.062 [notice] Application spandex_ecto exited: :stopped
2023-06-12T12:49:15.078 [notice] Application que exited: :stopped
2023-06-12T12:49:15.078 [notice] Application ex_utils exited: :stopped
2023-06-12T12:49:15.078 [notice] Application memento exited: :stopped
2023-06-12T12:49:15.078 [notice] Application prometheus_ecto exited: :stopped
2023-06-12T12:49:15.078 [notice] Application prometheus_ex exited: :stopped
2023-06-12T12:49:15.079 [notice] Application mnesia exited: :stopped
2023-06-12T12:49:15.080 [notice] Application prometheus exited: :stopped
2023-06-12T12:49:15.080 [notice] Application quantile_estimator exited: :stopped
2023-06-12T12:49:15.080 [notice] Application postgrex exited: :stopped
2023-06-12T12:49:15.080 [notice] Application nimble_csv exited: :stopped
2023-06-12T12:49:15.080 [notice] Application poison exited: :stopped
2023-06-12T12:49:15.080 [notice] Application phoenix_html exited: :stopped
2023-06-12T12:49:15.080 [notice] Application math exited: :stopped
2023-06-12T12:49:15.081 [notice] Application ecto_sql exited: :stopped
2023-06-12T12:49:15.081 [notice] Application db_connection exited: :stopped
2023-06-12T12:49:15.082 [notice] Application ecto exited: :stopped
2023-06-12T12:49:15.082 [notice] Application dataloader exited: :stopped
2023-06-12T12:49:15.082 [notice] Application briefly exited: :stopped
2023-06-12T12:49:15.082 [notice] Application bcrypt_elixir exited: :stopped
2023-06-12T12:49:15.082 [notice] Application comeonin exited: :stopped
2023-06-12T12:49:15.083 [notice] Application bamboo exited: :stopped
2023-06-12T12:49:15.083 [notice] Application tesla exited: :stopped
2023-06-12T12:49:15.083 [notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:bad_return_from_init, {:stop, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :too_many_connection
s, file: "proc.c", line: "362", message: "sorry, too many clients already", pg_code: "53300", routine: "InitProcess", severity: "FATAL", unknown: "FATAL"}, query: nil}, %Postgrex.SimpleCon
nection{auto_reconnect: false, idle_interval: 5000, protocol: nil, reconnect_backoff: 500, state: {Postgrex.Notifications, %Postgrex.Notifications{auto_reconnect: false, connected: false, 
from: nil, listener_channels: %{}, listeners: %{}, ref: nil}}}}}}
            (explorer 5.1.5) lib/explorer/chain/events/listener.ex:17: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.17.2.1) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17.2.1) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by vbaranov** [comment]
Please, pull updates from master branch: the issues shouldn't be reproducible anymore.

**Comment by lepar** [comment]
Having the same problem. Started from scratch, installed everything except on ubuntu 22 and postgres 14.
Cloned from master, checked all versions and dependencies from the manual deployment
