### ISSUE TITLE
Internal transactions opcode tracer: failed to fetch internal transactions for blocks: ** (MatchError) no match of right hand side value: {"0x0", ["0x1f2d0065"]}

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#7876]
Internal transactions opcode tracer:

```
2023-07-07T14:33:45.512 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: ** (MatchError) no match of right hand side value: {"0x0", ["0x1f2d0065"]}
    (ethereum_jsonrpc 5.2.0) lib/ethereum_jsonrpc/geth/tracer.ex:257: EthereumJSONRPC.Geth.Tracer.call_op/3
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ethereum_jsonrpc 5.2.0) lib/ethereum_jsonrpc/geth/tracer.ex:49: EthereumJSONRPC.Geth.Tracer.replay/3
    (ethereum_jsonrpc 5.2.0) lib/ethereum_jsonrpc/geth.ex:148: anonymous fn/5 in EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 5.2.0) lib/ethereum_jsonrpc/geth.ex:146: EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
    (indexer 5.2.0) lib/indexer/fetcher/internal_transaction.ex:206: anonymous fn/3 in Indexer.Fetcher.InternalTransaction.fetch_block_internal_transactions_by_transactions/2
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by vbaranov** [comment]
Can be bypassed by switching to `polygon_edge` type of `INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE`
