### ISSUE TITLE
CSV export returns 500

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/blockscout#7984]
**Where:** Goerli, v5.2.1

**Steps to reproduce:**

1. https://eth-goerli.blockscout.com/csv-export?type=transactions&filterType=address&filterValue=undefined&address=0x1B809925ba90c541d895D19f0b7D70eE281a987F
2. From: 07/19/2000 To: 07/20/2023
3. 500 error response

Maybe connected to https://github.com/blockscout/blockscout/issues/5009 ?

**Comment by vbaranov** [comment]
Query is timeouting

```
Request: GET /transactions-csv?address_id=0x1B809925ba90c541d895D19f0b7D70eE281a987F&from_period=2020-01-19&to_period=2023-07-20&filter_type=address&filter_value=null&recaptcha_response=...
** (exit) an exception was raised:
    ** (RuntimeError) Query fetching address transactions timed out.
        (explorer 5.2.0) lib/explorer/chain.ex:571: anonymous fn/1 in Explorer.Chain.wait_for_address_transactions/1
        (elixir 1.14.0) lib/enum.ex:4249: Enum.flat_map_list/2
        (elixir 1.14.0) lib/enum.ex:4250: Enum.flat_map_list/2
        (explorer 5.2.0) lib/explorer/chain.ex:446: Explorer.Chain.address_to_transactions_without_rewards/3
        (explorer 5.2.0) lib/explorer/chain/csv_export/address_transaction_csv_exporter.ex:30: Explorer.Chain.CSVExport.AddressTransactionCsvExporter.export/5
        (block_scout_web 5.2.0) lib/block_scout_web/controllers/address_transaction_controller.ex:200: BlockScoutWeb.AddressTransactionController.items_csv/3
        (block_scout_web 5.2.0) lib/block_scout_web/controllers/address_transaction_controller.ex:1: BlockScoutWeb.AddressTransactionController.action/2
        (block_scout_web 5.2.0) lib/block_scout_web/controllers/address_transaction_controller.ex:1: BlockScoutWeb.AddressTransactionController.phoenix_controller_pipeline/2
2023-07-20T11:26:37.368 [error] Task #PID<0.435.517> started from Indexer.Fetcher.TokenInstance.Sanitize terminating
```

**Comment by 0xtzData** [comment]
Reduced severity to minor for now, since it's not clear who is using CSV API and how. However it has both issues and limitations under load.

**Comment by alyonakostina** [comment]
no longer reproduces

**Comment by yvaskov** [comment]
Cannot reproduce on v7.0.2+
