### ISSUE TITLE
"Pending tx sanitizer" termination

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8118]
```
2023-08-04 11:21:22.459 | State: %Indexer.PendingTransactionsSanitizer{interval: 10800000, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://x", fallback_url: nil, fallback_trace_url: nil, method_to_url: [eth_getBalance: "http://x", trace_block: "http://x", trace_replayBlockTransactions: "http://x", trace_replayTransaction: "http://x"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Erigon]} |  
-- | -- | --
  |   | 2023-08-04 11:21:22.459 | Last message: :sanitize_pending_transactions |  
  |   | 2023-08-04 11:21:22.459 | (indexer 5.2.1) lib/indexer/pending_transactions_sanitizer.ex:73: Indexer.PendingTransactionsSanitizer.sanitize_pending_transactions/1 |  
  |   | 2023-08-04 11:21:22.459 | (elixir 1.14.0) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2 |  
  |   | 2023-08-04 11:21:22.459 | (indexer 5.2.1) lib/indexer/pending_transactions_sanitizer.ex:121: Indexer.PendingTransactionsSanitizer.fetch_pending_transaction_and_delete/1 |  
  |   | 2023-08-04 11:21:22.459 | (ecto 3.10.3) lib/ecto/repo/schema.ex:560: anonymous fn/11 in Ecto.Repo.Schema.do_delete/4 |  
  |   | 2023-08-04 11:21:22.459 | (ecto 3.10.3) lib/ecto/repo/schema.ex:769: Ecto.Repo.Schema.apply/4 |  
  |   | 2023-08-04 11:21:22.459 | (ecto 3.10.3) lib/ecto/repo/schema.ex:788: Ecto.Repo.Schema.constraints_to_errors/3 |  
  |   | 2023-08-04 11:21:22.459 | (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2 |  
  |   | 2023-08-04 11:21:22.459 | (ecto 3.10.3) lib/ecto/repo/schema.ex:804: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3 |  
  |   | 2023-08-04 11:21:22.459 |   |  
  |   | 2023-08-04 11:21:22.459 | The changeset has not defined any constraint. |  
  |   | 2023-08-04 11:21:22.459 |   |  
  |   | 2023-08-04 11:21:22.459 | `:name` as an option. |  
  |   | 2023-08-04 11:21:22.459 | call `foreign_key_constraint/3` on your changeset with the constraint |  
  |   | 2023-08-04 11:21:22.459 | exception and instead add it as an error to your changeset, please |  
  |   | 2023-08-04 11:21:22.459 | If you would like to stop this constraint violation from raising an |  
  |   | 2023-08-04 11:21:22.459 |   |  
  |   | 2023-08-04 11:21:22.459 | * "internal_transactions_transaction_hash_fkey" (foreign_key_constraint) |  
  |   | 2023-08-04 11:21:22.459 |   |  
  |   | 2023-08-04 11:21:22.459 | ** (Ecto.ConstraintError) constraint error when attempting to delete struct: |  
  |   | 2023-08-04 11:21:22.458 | 2023-08-04T08:21:22.457 [error] GenServer #PID<0.7186.0> terminating
```

**Comment by vbaranov** [comment]
Resolved by setting missing cascade deletion of internal transactions with transactions via:
```
ALTER TABLE public.internal_transactions
DROP CONSTRAINT internal_transactions_transaction_hash_fkey,
ADD CONSTRAINT internal_transactions_transaction_hash_fkey
   FOREIGN KEY (transaction_hash)
   REFERENCES transactions(hash)
   ON DELETE CASCADE;
```
