### ISSUE TITLE
Manual Deployment Failure and Error

### ISSUE THREAD

**Issue by aacostarua** [blockscout/blockscout#8119]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): 1.14.5-otp-25  (OTP 25.0)
* Node JS version (`node -v`): 20.5.0
* Operating System: Ubuntu 20.04.6 LTS (64 bit)
* Blockscout Version/branch/commit: latest
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): OpenEthereum (private network)

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
Server should run

### Actual behaviour

2023-08-04T13:41:36.168 [notice] Application tesla exited: :stopped
2023-08-04T13:41:36.168 [notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Counters.AverageBlockTime
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "blocks" does not exist

    query: SELECT b0."number", b0."timestamp" FROM "blocks" AS b0 WHERE (b0."consensus" = TRUE) ORDER BY b0."number" DESC LIMIT 100 OFFSET 100
            (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
            (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
            (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (explorer 5.2.1) lib/explorer/counters/average_block_time.ex:83: Explorer.Counters.AverageBlockTime.refresh_timestamps/0
            (explorer 5.2.1) lib/explorer/counters/average_block_time.ex:45: Explorer.Counters.AverageBlockTime.init/1
            (stdlib 4.3.1.2) gen_server.erl:851: :gen_server.init_it/2
            (stdlib 4.3.1.2) gen_server.erl:814: :gen_server.init_it/6

**Comment by vbaranov** [comment]
@aacostarua did you run DB migrations?

> 11) Create and migrate database mix do ecto.create, ecto.migrate

**Comment by aacostarua** [comment]
Ran that command.  Then tried running it getting this error:
2023-08-06T13:41:16.470 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
2023-08-06T13:41:16.475 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
2023-08-06T13:41:16.528 application=indexer fetcher=pending_transaction [error] connection_refused
2023-08-06T13:41:17.529 application=indexer fetcher=pending_transaction [error] connection_refused
2023-08-06T13:41:18.531 application=indexer fetcher=pending_transaction [error] connection_refused
2023-08-06T13:41:19.533 application=indexer fetcher=pending_transaction [error] connection_refused
2023-08-06T13:41:20.535 application=indexer fetcher=pending_transaction [error] connection_refused

My .env file looks like this:

ETHEREUM_JSONRPC_VARIANT=openethereum
ETHEREUM_JSONRPC_HTTP_URL=https://bc1.mycryptobox.com/node
DATABASE_URL=postgres://postgres:xxx@127.0.0.1:5432/blockscout
COIN=BIO
MIX_ENV=prod
SECRET_KEY_BASE=<valid generated secret>

**Comment by aacostarua** [comment]
This is a private network that uses zero gas if that helps at all.
