### ISSUE TITLE
5.2.1: failed to start child: Indexer.Fetcher.TokenTotalSupplyUpdater: 1st argument: out of range

### ISSUE THREAD

**Issue by ericlee42** [blockscout/blockscout#8134]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): latest
* Node JS version (`node -v`): latest
* Operating System: ubuntu 22
* Blockscout Version/branch/commit: 5.2.1
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

### Steps to reproduce

the instance can't be started.

```
warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

Starting dependencies..
Starting repos..
Create Explorer.Repo database if it doesn't exist
Create Explorer.Repo.Account database if it doesn't exist
Running migrations for explorer
2023-08-07T10:43:58.147 application=ecto_sql [info] Migrations already up
Running migrations for explorer
Success!
2023-08-07T10:43:58.154 application=ecto_sql [info] Migrations already up
warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

2023-08-07T10:55:44.662 application=que [info] [Que] Booting Que
2023-08-07T10:55:44.662 application=que [info] [Que] Booting Server Supervisor for Workers
2023-08-07T10:55:44.910 application=explorer [info] tx/per day chart: collect records for txs per day stats
2023-08-07T10:55:44.910 application=explorer [info] tx/per day chart: earliest date 2023-06-29 00:00:00Z
2023-08-07T10:55:44.910 application=explorer [info] tx/per day chart: latest date 2023-06-29 23:59:59Z
2023-08-07T10:55:45.089 application=explorer [info] tx/per day chart: min/max block numbers [1554274, 1558585]
2023-08-07T10:55:45.132 application=explorer [info] tx/per day chart: num of transactions 4312
2023-08-07T10:55:45.166 application=explorer [info] tx/per day chart: total gas used 5245560499
2023-08-07T10:55:45.168 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.10.0 at 0.0.0.0:4000 (http)
2023-08-07T10:55:45.170 application=phoenix [info] Access BlockScoutWeb.Endpoint at https://goerli.explorer.metisdevops.link:4000
2023-08-07T10:55:45.174 application=db_connection [info] Postgrex.Protocol (#PID<0.4272.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4925.0> exited
2023-08-07T10:55:45.174 application=db_connection [info] Postgrex.Protocol (#PID<0.4080.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4929.0> exited
2023-08-07T10:55:45.174 application=db_connection [info] Postgrex.Protocol (#PID<0.4094.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4921.0> exited
2023-08-07T10:55:45.174 application=db_connection [info] Postgrex.Protocol (#PID<0.4089.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4917.0> exited
2023-08-07T10:55:45.174 application=db_connection [info] Postgrex.Protocol (#PID<0.4115.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4913.0> exited
2023-08-07T10:55:45.174 application=db_connection [info] Postgrex.Protocol (#PID<0.4208.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4909.0> exited
2023-08-07T10:55:45.175 application=db_connection [info] Postgrex.Protocol (#PID<0.4154.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4901.0> exited
2023-08-07T10:55:45.175 application=db_connection [info] Postgrex.Protocol (#PID<0.4209.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4897.0> exited
2023-08-07T10:55:45.175 application=db_connection [info] Postgrex.Protocol (#PID<0.4192.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4893.0> exited
2023-08-07T10:55:45.175 application=db_connection [info] Postgrex.Protocol (#PID<0.4232.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4889.0> exited
2023-08-07T10:55:45.175 [notice] Application indexer exited: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Supervisor
    ** (EXIT) shutdown: failed to start child: Indexer.Fetcher.TokenTotalSupplyUpdater
        ** (EXIT) an exception was raised:
            ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: out of range

                :erlang.send_after(-12, #PID<0.4934.0>, :update)
                (indexer 5.2.1) lib/indexer/fetcher/token_total_supply_updater.ex:49: Indexer.Fetcher.TokenTotalSupplyUpdater.schedule_next_update/0
                (indexer 5.2.1) lib/indexer/fetcher/token_total_supply_updater.ex:21: Indexer.Fetcher.TokenTotalSupplyUpdater.init/1
                (stdlib 4.0.1) gen_server.erl:848: :gen_server.init_it/2
                (stdlib 4.0.1) gen_server.erl:811: :gen_server.init_it/6
                (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2023-08-07T10:55:45.176 application=db_connection [info] Postgrex.Protocol (#PID<0.4216.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4868.0> exited
2023-08-07T10:55:45.176 application=db_connection [info] Postgrex.Protocol (#PID<0.4160.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4866.0> exited
2023-08-07T10:55:45.181 application=db_connection [info] Postgrex.Protocol (#PID<0.4170.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4627.0> exited
2023-08-07T10:55:45.181 application=db_connection [info] Postgrex.Protocol (#PID<0.4119.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4626.0> exited
2023-08-07T10:55:45.181 application=db_connection [info] Postgrex.Protocol (#PID<0.4197.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4616.0> exited
2023-08-07T10:55:45.182 application=db_connection [info] Postgrex.Protocol (#PID<0.4140.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4596.0> exited
2023-08-07T10:55:45.183 application=db_connection [info] Postgrex.Protocol (#PID<0.4091.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4605.0> exited
{"Kernel pid terminated",application_controller,"{application_start_failure,indexer,{{shutdown,{failed_to_start_child,'Elixir.Indexer.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Indexer.Fetcher.TokenTotalSupplyUpdater',{badarg,[{erlang,send_after,[-12,<0.4934.0>,update],[{error_info,#{cause => time,module => erl_erts_errors}}]},{'Elixir.Indexer.Fetcher.TokenTotalSupplyUpdater',schedule_next_update,0,[{file,\"lib/indexer/fetcher/token_total_supply_updater.ex\"},{line,49}]},{'Elixir.Indexer.Fetcher.TokenTotalSupplyUpdater',init,1,[{file,\"lib/indexer/fetcher/token_total_supply_updater.ex\"},{line,21}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,848}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,811}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}}}},{'Elixir.Indexer.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,indexer,{{shutdown,{failed_to_start_child,'Elixir.Indexer.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Indexer.Fetcher.TokenTotalSupplyUpdater',{badarg,[{erlang,send_after,[-12,<0.4934.0>,update],[{error_info,#{cause => time,module => erl_erts_errors}}]},{'Elixir.Indexer.Fetcher.TokenTotalSupplyUpdater',schedule_next_update,0,[{file,"lib/indexer/fetcher/token_total_supply_updater.ex"},{line,49}]},{'Elixir.Indexer.Fetcher.TokenTotalSupplyUpdater',init,1,[{file,"lib/indexer/fetcher/token_total_supply_updater.ex"},{line,21}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,848}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,811}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}},{'Elixir.Indexer.Application',start,[normal,[]]}}})

Crash dump is being written to: erl_crash.dump...done
```

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@ericlee42 what is the block time in the chain, which you're indexing?

**Comment by ericlee42** [comment]
close. since we don't use blockscout any more.
