### ISSUE TITLE
Indexer.Fetcher.TokenBalance terminating: ERROR 40P01 (deadlock_detected) deadlock detected

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8361]
Explorer logs:

```
2023-08-31 13:06:08.519 | 2023-08-31T10:06:08.517 count=100 [error] Task #PID<0.27622.1479> started from Indexer.Fetcher.TokenBalance terminating |  
-- | -- | --
  |   | 2023-08-31 13:06:08.296 | Args: [%{batch: [{<<215, 86, 165, 106, 139, 163, 188, 193, 206, 116, 164, 34, 38, 83, 201, 213, 26, 169, 160, 224>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858818, "ERC-20", nil, 0}, {<<215, 88, 60, 29, 233, 91, 111, 235, 212, 87, 46, 177, 218, 39, 226, 0, 75, 43, 79, 76>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858814, "ERC-20", nil, 0}, {<<215, 88, 161, 178, 67, 237, 4, 111, 78, 125, 205, 168, 108, 171, 199, 255, 58, 203, 122, 49>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858814, "ERC-20", nil, 0}, {<<215, 88, 226, 35, 210, 254, 162, 67, 24, 124, 141, 202, 57, 119, 148, 40, 124, 165, 34, 127>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858818, "ERC-20", nil, 0}, {<<215, 90, 100, 56, 84, 127, 53, 9, 108, 205, 50, 10, 227, 78, 87, 133, 229, 117, 140, 148>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858803, "ERC-20", nil, 0}, {<<215, 90, 248, 37, 71, 26, 237, 73, 94, 5, 49, 176, 232, 86, 225, 11, 27, 135, 247, 160>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858804, "ERC-20", nil, 0}, {<<215, 92, 28, 112, 180, 136, 243, 121, 215, 140, 229, 58, 96, 172, 207, 63, 133, 43, 180, 217>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858816, "ERC-20", nil, 0}, {<<215, 92, 48, 126, 173, 227, 175, 200, 122, 195, 128, 87, 225, 220, 207, 201, 246, 44, 244, 230>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858815, "ERC-20", nil, 0}, {<<215, 93, 233, 149, 65, 49, 147, 22, 195, 50, 231, 76, 134, 190, 199, 92, 117, 29, 27, 24>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858804, "ERC-20", nil, 0}, {<<215, 94, 85, 31, 47, 224, 225, 112, 181, 86, 20, 80, 148, 90, 238, 181, 148, 127, 75, 126>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858813, "ERC-20", nil, 0}, {<<215, 94, 128, 134, 156, 173, 182, 159, 163, 75, 212, 107, 217, 141, 160, 64, 180, 3, 11, 145>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858810, "ERC-20", nil, 0}, {<<215, 95, 106, 53, 135, 146, 153, 247, 64, 129, 163, 154, 222, 117, 148, 185, 15, 170, 117, 112>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858821, "ERC-20", nil, 0}, {<<215, 95, 249, 132, 24, 41, 173, 19, 64, 147, 252, 85, 177, 100, 118, 249, 91, 118, 176, 2>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858814, "ERC-20", nil, 0}, {<<215, 97, 191, 235, 97, 210, 151, 168, 229, 86, 125, 26, 31, 250, 214, 79, 242, 74, 211, 141>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858803, "ERC-20", nil, 0}, {<<215, 98, 77, 117, 17, 207, 56, 78, 226, 208, 129, 128, 239, 212, 189, 158, 87, 82, 5, 83>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858808, "ERC-20", nil, 0}, {<<215, 100, 26, 142, 5, 125, 36, 155, 105, 210, 243, 255, 193, 187, 41, 245, 246, 230, 12, 166>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858804, "ERC-20", nil, 0}, {<<215, 101, 60, 240, 217, 106, 110, 21, 90, 44, 156, 241, 8, 107, 131, 56, 241, 186, 99, 223>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858816, "ERC-20", nil, 0}, {<<215, 101, 226, 161, 0, 12, 250, 52, 208, 149, 237, 119, 190, 85, 141, 11, 165, 17, 73, 173>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858808, "ERC-20", nil, 0}, {<<215, 102, 145, 173, 225, 109, 223, 153, 171, 8, 55, 160, 215, 117, 139, 131, 28, 29, 48, 33>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858803, "ERC-20", nil, 0}, {<<215, 108, 75, 120, 42, 11, 91, 244, 70, 136, 102, 144, 173, 23, 85, 167, 52, 175, 75, 34>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858818, "ERC-20", nil, 0}, {<<215, 109, 58, 82, 157, 10, 18, 66, 226, 72, 10, 221, 182, 211, 206, 230, 12, 166, 160, 119>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858816, "ERC-20", nil, 0}, {<<215, 109, 91, 110, 199, 179, 70, 106, 167, 100, 24, 116, 17, 47, 160, 163, 197, 109, 54, 242>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858809, "ERC-20", nil, 0}, {<<215, 109, 148, 211, 47, 213, 8, 124, 106, 14, 64, 110, 99, 141, 42, 193, 79, 194, 187, 197>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858815, "ERC-20", nil, 0}, {<<215, 111, 87, 27, 237, 139, 193, 153, 53, 47, 115, 81, 245, 76, 37, 220, 114, 219, 137, 80>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858806, "ERC-20", nil, 0}, {<<215, 111, 236, 143, 137, 170, 205, 174, 18, 58, 17, 137, 177, 216, 30, 85, 87, 154, 160, 47>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858821, "ERC-20", nil, 0}, {<<215, 111, 247, 215, 213, 94, 249, 63, 57, 175, 161, 92, 228, 237, 178, 254, 237, 28, 31, 191>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, 225>>, 3858814, "ERC-20", nil, 0}, {<<215, 114, 99, 137, 188, 222, 145, 254, 1, 73, 109, 252, 61, 39, 113, 86, 9, 152, 76, 246>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, 215, ...>>, 3858814, "ERC-20", nil, 0}, {<<215, 119, 95, 236, 29, 0, 145, 63, 86, 66, 84, 73, 160, 128, 166, 141, 105, 200, 117, ...>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, 194, ...>>, 3858803, "ERC-20", nil, 0}, {<<215, 127, 84, 191, 86, 28, 187, 162, 185, 194, 176, 186, 173, 141, 209, 243, 13, 40, ...>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, 192, ...>>, 3858813, "ERC-20", nil, 0}, {<<215, 127, 144, 79, 83, 122, 77, 236, 211, 0, 235, 146, 216, 123, 214, 79, 255, ...>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, 125, 145, 206, ...>>, 3858816, "ERC-20", nil, 0}, {<<215, 134, 104, 24, 106, 92, 78, 229, 243, 71, 127, 69, 162, 198, 26, 185, ...>>, <<84, 250, 81, 127, 5, 225, 31, 250, 135, 244, 178, 42, 232, (truncated) |  
  |   | 2023-08-31 13:06:08.296 | Function: &Indexer.BufferedTask.log_run/1 |  
  |   | 2023-08-31 13:06:08.296 | (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3 |  
  |   | 2023-08-31 13:06:08.296 | (ecto 3.10.3) lib/ecto/multi.ex:844: Ecto.Multi.apply_operation/5 |  
  |   | 2023-08-31 13:06:08.296 | (explorer 5.2.2) lib/explorer/prometheus/instrumenter.ex:17: Explorer.Prometheus.Instrumenter.block_import_stage_runner/4 |  
  |   | 2023-08-31 13:06:08.296 | (stdlib 4.3.1.2) timer.erl:235: :timer.tc/1 |  
  |   | 2023-08-31 13:06:08.296 | (explorer 5.2.2) lib/explorer/chain/import/runner/tokens.ex:70: Explorer.Chain.Import.Runner.Tokens.update_holder_counts_with_deltas/3 |  
  |   | 2023-08-31 13:06:08.296 | (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4 |  
  |   | 2023-08-31 13:06:08.296 | (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6 |  
  |   | 2023-08-31 13:06:08.296 | (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1 |  
  |   | 2023-08-31 13:06:08.296 | Process 386374 waits for ExclusiveLock on tuple (301,120) of relation 17519 of database 16690; blocked by process 475052. |  
  |   | 2023-08-31 13:06:08.296 | Process 385272 waits for ShareLock on transaction 8725513; blocked by process 386374. |  
  |   | 2023-08-31 13:06:08.296 | Process 475052 waits for ExclusiveLock on tuple (301,120) of relation 17519 of database 16690; blocked by process 385272. |  
  |   | 2023-08-31 13:06:08.296 |   |  
  |   | 2023-08-31 13:06:08.296 | hint: See server log for query details. |  
  |   | 2023-08-31 13:06:08.296 |   |  
  |   | 2023-08-31 13:06:08.296 | ** (Postgrex.Error) ERROR 40P01 (deadlock_detected) deadlock detected
```

Postgres logs:
```
2023-08-31 00:00:01.367 UTC,"eth_sepolia","eth_sepolia",3733983,"10.42.181.138:48574",64efca94.38f9df,220,"UPDATE",2023-08-30 23:02:44 UTC,106/503311,7256585,ERROR,40P01,"deadlock detected","Process 3733983 waits for ExclusiveLock on tuple (888,57) of relation 17519 of database 16690; blocked by process 3776681.
Process 3776681 waits for ShareLock on transaction 7256585; blocked by process 3733983.
Process 3733983: UPDATE ""tokens"" AS t0 SET ""holder_count"" = t0.""holder_count"" + f1.""delta"", ""updated_at"" = $1 FROM (SELECT unnest($2::bytea[]) as contract_address_hash, unnest($3::bigint[]) as delta) AS f1 WHERE (t0.""contract_address_hash"" = f1.""contract_address_hash"") AND (t0.""contract_address_hash"" IN (SELECT st0.""contract_address_hash"" FROM ""tokens"" AS st0 WHERE (st0.""contract_address_hash"" = ANY($4)) ORDER BY st0.""contract_address_hash"" FOR NO KEY UPDATE)) AND (NOT (t0.""holder_count"" IS NULL)) RETURNING t0.""contract_address_hash"", t0.""holder_count""
Process 3776681: UPDATE ""tokens"" AS t0 SET ""holder_count"" = t0.""holder_count"" + f1.""delta"", ""updated_at"" = $1 FROM (SELECT unnest($2::bytea[]) as contract_address_hash, unnest($3::bigint[]) as delta) AS f1 WHERE (t0.""contract_address_hash"" = f1.""contract_address_hash"") AND (t0.""contract_address_hash"" IN (SELECT st0.""contract_address_hash"" FROM ""tokens"" AS st0 WHERE (st0.""contract_address_hash"" = ANY($4)) ORDER BY st0.""contract_address_hash"" FOR NO KEY UPDATE)) AND (NOT (t0.""holder_count"" IS NULL)) RETURNING t0.""contract_address_hash"", t0.""holder_count""","See server log for query details.",,,,"UPDATE ""tokens"" AS t0 SET ""holder_count"" = t0.""holder_count"" + f1.""delta"", ""updated_at"" = $1 FROM (SELECT unnest($2::bytea[]) as contract_address_hash, unnest($3::bigint[]) as delta) AS f1 WHERE (t0.""contract_address_hash"" = f1.""contract_address_hash"") AND (t0.""contract_address_hash"" IN (SELECT st0.""contract_address_hash"" FROM ""tokens"" AS st0 WHERE (st0.""contract_address_hash"" = ANY($4)) ORDER BY st0.""contract_address_hash"" FOR NO KEY UPDATE)) AND (NOT (t0.""holder_count"" IS NULL)) RETURNING t0.""contract_address_hash"", t0.""holder_count""",,,"","client backend",,6132160019150173564
```

**Comment by vbaranov** [comment]
Resolved by https://github.com/blockscout/blockscout/pull/8398 and https://github.com/blockscout/blockscout/pull/8362
