### ISSUE TITLE
Indexer.Fetcher.TokenInstance.Sanitize: (Postgrex.Error) ERROR 22P05 (untranslatable_character) unsupported Unicode escape sequence

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8385]
ETH Sepolia:
	
 `Args: [%{batch: [%{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 173, 236, 148, 177, 48, 45, 221, 59, 191, 106, 183, 243, 150, 109, 2, 81, 89, 250, 196>>}, token_id: Decimal.new("2")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 173, 236, 148, 177, 48, 45, 221, 59, 191, 106, 183, 243, 150, 109, 2, 81, 89, 250, 196>>}, token_id: Decimal.new("3")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 174, 116, 118, 174, 119, 45, 4, 102, 81, 15, 17, 56, 233, 235, 192, 223, 146, 101, 86>>}, token_id: Decimal.new("0")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 174, 116, 118, 174, 119, 45, 4, 102, 81, 15, 17, 56, 233, 235, 192, 223, 146, 101, 86>>}, token_id: Decimal.new("1")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 174, 233, 199, 216, 175, 109, 192, 239, 192, 70, 4, 169, 216, 127, 63, 106, 176, 7, 216>>}, token_id: Decimal.new("0")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 176, 97, 194, 37, 133, 69, 247, 200, 31, 203, 211, 247, 38, 148, 2, 204, 128, 194, 29>>}, token_id: Decimal.new("0")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 178, 204, 40, 90, 55, 127, 106, 159, 114, 230, 101, 44, 44, 104, 228, 105, 115, 180, 62>>}, token_id: Decimal.new("1")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 178, 204, 40, 90, 55, 127, 106, 159, 114, 230, 101, 44, 44, 104, 228, 105, 115, 180, 62>>}, token_id: Decimal.new("2")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 178, 204, 40, 90, 55, 127, 106, 159, 114, 230, 101, 44, 44, 104, 228, 105, 115, 180, 62>>}, token_id: Decimal.new("3")}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<62, 178, 204, 40, 90, 55, 127, 106, 159, 114, 230, 101, 44, 44, 104, 228, 105, 115, 180, 62>>}, token_id: Decimal.new("4")}], callback_module: Indexer.Fetcher.TokenInstance.Sanitize, callback_module_state: [], metadata: []}]`

```
Function: &Indexer.BufferedTask.log_run/1	
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3	
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4	
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2	
    (indexer 5.2.2) lib/indexer/fetcher/token_instance/sanitize.ex:44: Indexer.Fetcher.TokenInstance.Sanitize.run/2	
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2	
    (ecto 3.10.3) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4	
    (ecto 3.10.3) lib/ecto/repo/schema.ex:764: Ecto.Repo.Schema.apply/4	
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1	
\u0000 cannot be converted to text.	
	
** (Postgrex.Error) ERROR 22P05 (untranslatable_character) unsupported Unicode escape sequence
```

**Comment by vbaranov** [comment]
More examples from ETH Goerli:
```
2023-12-19T16:34:49.901 [error] Task #PID<0.8990.0> started from Indexer.Fetcher.TokenInstance.Realtime terminating
** (Postgrex.Error) ERROR 22P05 (untranslatable_character) unsupported Unicode escape sequence

\u0000 cannot be converted to text.
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.11.1) lib/ecto/repo/schema.ex:775: Ecto.Repo.Schema.apply/4
    (ecto 3.11.1) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (indexer 5.3.3) lib/indexer/fetcher/token_instance/realtime.ex:40: Indexer.Fetcher.TokenInstance.Realtime.run/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [%{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<26, 79, 240, 136, 175, 97, 244, 86, 77, 67, 183, 6, 12, 196, 190, 2, 116, 189, 211, 212>>}, token_id: Decimal.new("123350")}], callback_module: Indexer.Fetcher.TokenInstance.Realtime, callback_module_state: [], metadata: []}]
 ```
