### ISSUE TITLE
indexer - Unknown token transfer format

### ISSUE THREAD

**Issue by bretep** [blockscout/blockscout#8427]
Seeing this error after upgrading to 5.2.2
```
2023-09-09T18:55:20.889 fetcher=block_catchup first_block_number=18268945 last_block_number=18268945 [error] Task #PID<0.18074.0> started from #PID<0.5025.0> terminating
** (stop) exited in: GenServer.call(#PID<0.4508.0>, {:lock, :transactions, #Reference<0.195305594.305397763.186909>}, 5000)
    ** (EXIT) time out
    (elixir 1.14.5) lib/gen_server.ex:1038: GenServer.call/3
    (con_cache 1.0.0) lib/con_cache/lock.ex:22: ConCache.Lock.exec/4
    (indexer 5.2.2) lib/indexer/block/fetcher.ex:205: Indexer.Block.Fetcher.fetch_and_import_range/2
    (stdlib 4.3.1.2) timer.erl:235: :timer.tc/1
    (indexer 5.2.2) lib/indexer/block/catchup/fetcher.ex:195: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<16.68786450/1 in Indexer.Block.Catchup.Fetcher.stream_fetch_and_import/2>, [18268945..18268945]]
2023-09-09T18:55:20.922 [error] GenServer :block_catchup_sequencer terminating
** (stop) exited in: GenServer.call(#PID<0.4508.0>, {:lock, :transactions, #Reference<0.195305594.305397763.186909>}, 5000)
    ** (EXIT) time out
Last message: {:EXIT, #PID<0.5025.0>, {:timeout, {GenServer, :call, [#PID<0.4508.0>, {:lock, :transactions, #Reference<0.195305594.305397763.186909>}, 5000]}}}
State: %Indexer.Block.Catchup.Sequence{current: nil, bound_queue: %Indexer.BoundQueue{queue: {[{18268908, 18268908}, {18268910, 18268910}, {18268911, 18268911}, {18268914, 18268914}, {18268917, 18268917}, {18268918, 18268918}, {18268919, 18268919}, {18268921, 18268921}, {18268923, 18268923}, {18268924, 18268924}, {18268927, 18268927}, {18268928, 18268928}, {18268930, 18268930}, {18268931, 18268931}], [{18268941, 18268941}, {18268940, 18268940}, {18268938, 18268938}, {18268936, 18268936}, {18268933, 18268933}]}, size: 19, maximum_size: nil}, step: -1}
2023-09-09T18:55:20.940 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({:timeout, {GenServer, :call, [#PID<0.4508.0>, {:lock, :transactions, #Reference<0.195305594.305397763.186909>}, 5000]}}). Restarting
2023-09-09T18:55:21.260 application=indexer fetcher=block_catchup first_block_number=18268946 last_block_number=18268946 [error] Unknown token transfer format: %{address_hash: "0x6e158c90637809db28fe6426576ae5655e4c92cf", block_hash: "0x21d5e8c75c26d06919092831d6d2414459c0229cb818417539b3bde130cc7cb2", block_number: 18268946, data: "0x000000000000000000000000a0d254a39ea8645ffc79a9353c32f02504c5f3e7000000000000000000000000000000000000000000000004620d638bc433ec5f", first_topic: "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c", fourth_topic: nil, index: 6, second_topic: nil, third_topic: nil, transaction_hash: "0xe5a4892d81bfc6ca445b759a48e9ec5457df004bd4a960e6cd69d030dc6b31a4"}** (MatchError) no match of right hand side value: ""
    (ex_abi 0.6.0) lib/abi/type_decoder.ex:365: ABI.TypeDecoder.decode_uint/2
    (ex_abi 0.6.0) lib/abi/type_decoder.ex:190: anonymous fn/3 in ABI.TypeDecoder.do_decode_raw/2
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_abi 0.6.0) lib/abi/type_decoder.ex:185: ABI.TypeDecoder.do_decode_raw/2
    (ex_abi 0.6.0) lib/abi/type_decoder.ex:179: ABI.TypeDecoder.decode_raw/2
    (indexer 5.2.2) lib/indexer/transform/token_transfers.ex:241: Indexer.Transform.TokenTransfers.parse_params/1
    (indexer 5.2.2) lib/indexer/transform/token_transfers.ex:129: Indexer.Transform.TokenTransfers.do_parse/3
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by dreadedhamish** [comment]
Likewise.

**Comment by ekawibisono** [comment]
### Environment

* Deployment type (Manual/Docker/Docker-compose): ?
* Elixir & Erlang/OTP versions (`elixir -version`): ?
* Node JS version (`node -v`): ?
* Operating System: ?
* Blockscout Version/branch/commit: ?
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): ?

**Comment by qwang1113** [comment]
Same error here, Does anyone know how to skip this error? This will cause block_catchup to stop working.

**Comment by vbaranov** [comment]
See https://github.com/blockscout/blockscout/issues/10228#issuecomment-2160169838
