### ISSUE TITLE
GenServer :block_catchup_sequencer terminating

### ISSUE THREAD

**Issue by bretep** [blockscout/blockscout#8428]
At this point, this is the only error I am seeing running the blockscout indexer. 

I'm running a7008a0d8c7, which is the current head of master. I was previously running the release from 3 weeks ago, but there have been additions between then and now that resolved a lot of database issues. 

Not sure how to resolve this one. It's not related to querying the erigon node. The timeout happens too fast.

```
2023-09-09T22:33:21.968 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({:timeout, {GenServer, :call, [#PID<0.4510.0>, {:lock, :transactions, #Reference<0.3535298100.1679294466.131407>}, 5000]}}). Restarting
2023-09-09T22:33:21.968 [error] GenServer :block_catchup_sequencer terminating
** (stop) exited in: GenServer.call(#PID<0.4510.0>, {:lock, :transactions, #Reference<0.3535298100.1679294466.131407>}, 5000)
    ** (EXIT) time out
Last message: {:EXIT, #PID<0.5812.8>, {:timeout, {GenServer, :call, [#PID<0.4510.0>, {:lock, :transactions, #Reference<0.3535298100.1679294466.131407>}, 5000]}}}
State: %Indexer.Block.Catchup.Sequence{current: nil, bound_queue: %Indexer.BoundQueue{queue: {[{18269306, 18269306}, {18269307, 18269307}, {18269308, 18269308}, {18269309, 18269309}, {18269310, 18269310}, {18269311, 18269311}, {18269312, 18269312}, {18269313, 18269313}, {18269314, 18269314}, {18269315, 18269315}, {18269316, 18269316}, {18269317, 18269317}, {18269318, 18269318}, {18269319, 18269319}, {18269320, 18269320}, {18269321, 18269321}, {18269322, 18269322}, {18269323, 18269323}, {18269324, 18269324}, {18269325, 18269325}, {18269365, 18269365}], [{18269438, 18269438}, {18269437, 18269437}, {18269435, 18269435}, {18269434, 18269434}, {18269430, 18269430}, {18269429, 18269429}, {18269428, 18269428}, {18269426, 18269426}, {18269385, 18269385}, {18269384, 18269384}, {18269383, 18269383}, {18269382, 18269382}, {18269381, 18269381}, {18269380, 18269380}, {18269379, 18269379}, {18269376, 18269376}, {18269375, 18269375}, {18269374, 18269374}, {18269373, 18269373}, {18269369, 18269369}, {18269368, 18269368}, {18269367, 18269367}]}, size: 43, maximum_size: nil}, step: -1}
2023-09-09T22:33:26.302 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 10
2023-09-09T22:33:28.682 [error] Task #PID<0.8483.8> started from Indexer.Block.Realtime.Fetcher terminating
** (stop) exited in: GenServer.call(#PID<0.4510.0>, {:lock, :transactions, #Reference<0.3535298100.1679818753.170279>}, 5000)
    ** (EXIT) time out
    (elixir 1.14.5) lib/gen_server.ex:1038: GenServer.call/3
    (con_cache 1.0.0) lib/con_cache/lock.ex:22: ConCache.Lock.exec/4
    (indexer 5.2.2) lib/indexer/block/fetcher.ex:208: Indexer.Block.Fetcher.fetch_and_import_range/2
    (stdlib 4.3.1.2) timer.erl:235: :timer.tc/1
    (indexer 5.2.2) lib/indexer/block/realtime/fetcher.ex:307: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 5.2.2) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 5.2.2) lib/indexer/block/realtime/fetcher.ex:287: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [18270283, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:80/", fallback_url: nil, fallback_trace_url: nil, method_to_url: [eth_getBalance: "http://localhost:80/", trace_block: "http://localhost:80/", trace_replayBlockTransactions: "http://localhost:80/", trace_replayTransaction: "http://localhost:80/"], http_options: [recv_timeout: 3000000000, timeout: 3000000000, hackney: [:insecure, {:pool, :ethereum_jsonrpc}]]], variant: EthereumJSONRPC.Erigon], receipts_batch_size: 250, receipts_concurrency: 10}, false]
```

**Comment by vbaranov** [comment]
Please update to [v6](https://github.com/blockscout/blockscout/releases/tag/v6.5.0-beta) and let us know, if the issue still persists.
