### ISSUE TITLE
zkEVM: block page - devision by zero

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8456]
```
** (exit) an exception was raised:
    ** (Decimal.Error) invalid_operation: 0 / 0
        (decimal 2.1.1) lib/decimal.ex:528: Decimal.div/2
        (block_scout_web 5.2.2) lib/block_scout_web/views/api/v2/block_view.ex:89: BlockScoutWeb.API.V2.BlockView.gas_target/1
        (block_scout_web 5.2.2) lib/block_scout_web/views/api/v2/block_view.ex:57: BlockScoutWeb.API.V2.BlockView.prepare_block/3
        (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
        (block_scout_web 5.2.2) lib/block_scout_web/controllers/api/v2/main_page_controller.ex:1: BlockScoutWeb.API.V2.MainPageController.action/2
        (block_scout_web 5.2.2) lib/block_scout_web/controllers/api/v2/main_page_controller.ex:1: BlockScoutWeb.API.V2.MainPageController.phoenix_controller_pipeline/2
```

**Comment by vbaranov** [comment]
Resolved by https://github.com/blockscout/blockscout/commit/690e174e2b74071a06723fc9af024e619cc5737f
