### ISSUE TITLE
** (stop) exited in: :gen_statem.call(#PID<0.21466.0>, {:recv, -1, 5000}, :infinity)

### ISSUE THREAD

**Issue by nikitosing** [blockscout/blockscout#8492]
Probably related to https://github.com/blockscout/blockscout/issues/8491

```
2023-09-20T12:21:08.319 [error] GenServer Explorer.ExchangeRates.TokenExchangeRates terminating
** (stop) exited in: :gen_statem.call(#PID<0.21466.0>, {:recv, -1, 5000}, :infinity)
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: []
            (ssl 10.9.1.1) ssl_gen_statem.erl:1650: :ssl_gen_statem.iovec_from_front/4
            (ssl 10.9.1.1) ssl_gen_statem.erl:1486: :ssl_gen_statem.read_application_data_bin/8
            (ssl 10.9.1.1) tls_gen_connection.erl:414: :tls_gen_connection.handle_protocol_record/3
            (stdlib 4.3.1.2) gen_statem.erl:1426: :gen_statem.loop_state_callback/11
            (ssl 10.9.1.1) tls_connection.erl:160: :tls_connection.init/1
            (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (stdlib 4.3.1.2) gen.erl:243: :gen.do_call/4
    (stdlib 4.3.1.2) gen_statem.erl:900: :gen_statem.call_dirty/4
    (ssl 10.9.1.1) ssl_gen_statem.erl:1242: :ssl_gen_statem.call/2
    (hackney 1.18.2) /Users/nikitosing/work/blockscout/blockscout/deps/hackney/src/hackney_response.erl:170: :hackney_response.stream_body_recv/2
    (hackney 1.18.2) /Users/nikitosing/work/blockscout/blockscout/deps/hackney/src/hackney_response.erl:312: :hackney_response.read_body/3
    (hackney 1.18.2) /Users/nikitosing/work/blockscout/blockscout/deps/hackney/src/hackney.erl:520: anonymous fn/2 in :hackney.body/2
    (httpoison 2.1.0) lib/httpoison/base.ex:888: HTTPoison.Base.request/6
    (explorer 5.2.2) lib/explorer/exchange_rates/source.ex:123: Explorer.ExchangeRates.Source.http_request/2
    (explorer 5.2.2) lib/explorer/exchange_rates/source.ex:48: Explorer.ExchangeRates.Source.fetch_token_hashes_with_market_data/0
    (explorer 5.2.2) lib/explorer/exchange_rates/token_exchange_rates.ex:51: Explorer.ExchangeRates.TokenExchangeRates.handle_info/2
    (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :fetch
State: %Explorer.ExchangeRates.TokenExchangeRates{max_batch_size: 150, interval: 5000, refetch_interval: 3600000, tokens_to_fetch: nil}
```

**Comment by vbaranov** [comment]
Resolved with https://github.com/blockscout/blockscout/pull/8510
