### ISSUE TITLE
hardhat verify command doesn't work

### ISSUE THREAD

**Issue by kaliubuntu0206** [blockscout/blockscout#8668]
### Description

Used the following config for hardhat.config.js

```
etherscan: {
    apiKey: {
      custom: 'abc'
    },
    customChains: [
      {
        network: 'custom',
        chainId: process.env.CHAIN_ID,
        urls: {
          apiURL: process.env.BLOCKSCOUT + '/api',
          browserURL: process.env.BLOCKSCOUT
        }
      }
    ]
  },
```

Causing the following error from blockscout

```
2023-10-22T10:14:06.388 application=api request_id=F5BmZaxBpxHlj18AAJSG [error] Error while calling RPC action"** (Plug.Conn.WrapperError) ** (ArgumentError) construction of binary failed: segment 3 of type 'binary': expected a binary but got: nil\n    (explorer 5.3.0) lib/explorer/third_party_integrations/sourcify.ex:439: Explorer.ThirdPartyIntegrations.Sourcify.get_metadata_any_url/0\n    (explorer 5.3.0) lib/explorer/third_party_integrations/sourcify.ex:22: Explorer.ThirdPartyIntegrations.Sourcify.check_by_address_any/1\n    (explorer 5.3.0) lib/explorer/smart_contract/solidity/publish_helper.ex:180: Explorer.SmartContract.Solidity.PublishHelper.check_by_address_in_sourcify/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:354: BlockScoutWeb.API.RPC.ContractController.getsourcecode/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.action/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.phoenix_controller_pipeline/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:119: BlockScoutWeb.API.RPC.RPCTranslator.call_controller/3\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:37: BlockScoutWeb.API.RPC.RPCTranslator.call/2\n"
2023-10-22T10:14:06.388 application=api request_id=F5BmZaxBpxHlj18AAJSG [info] Sent 500 in 1ms
2023-10-22T10:14:11.257 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2023-10-22T10:14:11.257 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
2023-10-22T10:14:12.787 application=api request_id=F5BmZymC0nv2cXkAAKPF [info] /api?
warning: Supervisor.start_child/2 with a list of args is deprecated, please use DynamicSupervisor instead
  (elixir 1.14.4) lib/supervisor.ex:906: Supervisor.start_child/2
  (que 0.10.1) lib/que/server_supervisor.ex:48: Que.ServerSupervisor.add/2
  (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:121: BlockScoutWeb.API.RPC.ContractController.verifysourcecode/2
  (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.action/2
  (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.phoenix_controller_pipeline/2
  (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:119: BlockScoutWeb.API.RPC.RPCTranslator.call_controller/3

2023-10-22T10:14:12.790 application=que [info] [Que] Spawning Server for worker: Explorer.SmartContract.Solidity.PublisherWorker
2023-10-22T10:14:12.790 application=que [info] [Que] Queued new Job for Explorer.SmartContract.Solidity.PublisherWorker
2023-10-22T10:14:12.791 application=que [info] [Que] Starting Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker
2023-10-22T10:14:12.791 application=api request_id=F5BmZymC0nv2cXkAAKPF [info] Sent 200 in 3ms
2023-10-22T10:14:12.792 application=explorer [info] Smart-contract verification via standard json input started
2023-10-22T10:14:13.635 application=api request_id=F5BmZ1xN1bjTrAAAAN_C [info] /api?apikey=abc&module=contract&action=checkverifystatus&guid=5fc8d32690cc91d4c39d9d3abcbd16989f8757076534f5f4
2023-10-22T10:14:13.636 application=api request_id=F5BmZ1xN1bjTrAAAAN_C [info] Sent 200 in 1ms
2023-10-22T10:14:15.185 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
2023-10-22T10:14:15.395 application=explorer [warning] Unknown verifier error: {:error, :constructor_arguments}
2023-10-22T10:14:15.395 [error] Task #PID<0.19700.0> started from #PID<0.19699.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:error, :constructor_arguments} of type Tuple. This protocol is implemented for the following type(s): Atom, BitString, Cldr.Currency, Cldr.LanguageTag, Cldr.LanguageTag.T, Cldr.LanguageTag.U, Cldr.Unit, Date, DateTime, Decimal, ExJsonSchema.Validator.Error.AdditionalItems, ExJsonSchema.Validator.Error.AdditionalProperties, ExJsonSchema.Validator.Error.AllOf, ExJsonSchema.Validator.Error.AnyOf, ExJsonSchema.Validator.Error.Const, ExJsonSchema.Validator.Error.Contains, ExJsonSchema.Validator.Error.ContentEncoding, ExJsonSchema.Validator.Error.ContentMediaType, ExJsonSchema.Validator.Error.Dependencies, ExJsonSchema.Validator.Error.Enum, ExJsonSchema.Validator.Error.False, ExJsonSchema.Validator.Error.Format, ExJsonSchema.Validator.Error.IfThenElse, ExJsonSchema.Validator.Error.ItemsNotAllowed, ExJsonSchema.Validator.Error.MaxItems, ExJsonSchema.Validator.Error.MaxLength, ExJsonSchema.Validator.Error.MaxProperties, ExJsonSchema.Validator.Error.Maximum, ExJsonSchema.Validator.Error.MinItems, ExJsonSchema.Validator.Error.MinLength, ExJsonSchema.Validator.Error.MinProperties, ExJsonSchema.Validator.Error.Minimum, ExJsonSchema.Validator.Error.MultipleOf, ExJsonSchema.Validator.Error.Not, ExJsonSchema.Validator.Error.OneOf, ExJsonSchema.Validator.Error.Pattern, ExJsonSchema.Validator.Error.PropertyNames, ExJsonSchema.Validator.Error.Required, ExJsonSchema.Validator.Error.Type, ExJsonSchema.Validator.Error.UniqueItems, Explorer.Chain.Address, Explorer.Chain.Data, Explorer.Chain.Hash, FileInfo.Mime, Float, Floki.Selector, Floki.Selector.AttributeSelector, Floki.Selector.Combinator, Floki.Selector.Functional, Floki.Selector.PseudoClass, Hex.Solver.Assignment, Hex.Solver.Constraints.Empty, Hex.Solver.Constraints.Range, Hex.Solver.Constraints.Union, Hex.Solver.Incompatibility, Hex.Solver.PackageRange, Hex.Solver.Term, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Que.Job, RemoteIp.Block, Time, URI, Version, Version.Requirement
    (elixir 1.14.4) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.14.4) lib/string/chars.ex:22: String.Chars.to_string/1
    (explorer 5.3.0) lib/explorer/smart_contract/solidity/publisher.ex:225: Explorer.SmartContract.Solidity.Publisher.unverified_smart_contract/5
    (explorer 5.3.0) lib/explorer/smart_contract/solidity/publisher.ex:103: Explorer.SmartContract.Solidity.Publisher.publish_with_standard_json_input/2
    (explorer 5.3.0) lib/explorer/smart_contract/solidity/publisher_worker.ex:54: Explorer.SmartContract.Solidity.PublisherWorker.perform/1
    (elixir 1.14.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<3.128813672/0 in Que.Job.perform/1>
    Args: []
2023-10-22T10:14:15.396 application=que [info] [Que] Failed Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker
```

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Backend version

v5.3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.4 (compiled with Erlang/OTP 25)

### Operating system

Ubuntu

**Comment by RonTuretzky** [comment]
try adding this 
```SECRET_KEY_BASE="56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN"```
to common-blockscout.env @kaliubuntu0206

**Comment by kaliubuntu0206** [comment]
@RonTuretzky It now works, why the specific SECRET_KEY_BASE is required?

**Comment by kaliubuntu0206** [comment]
Now I get another strange error

```
2023-10-23T16:29:09.507 application=api request_id=F5DJcafoWHQ33qYACECC [error] Error while calling RPC action"** (Plug.Conn.WrapperError) ** (ArgumentError) construction of binary failed: segment 3 of type 'binary': expected a binary but got: nil\n    (explorer 5.3.0) lib/explorer/third_party_integrations/sourcify.ex:439: Explorer.ThirdPartyIntegrations.Sourcify.get_metadata_any_url/0\n    (explorer 5.3.0) lib/explorer/third_party_integrations/sourcify.ex:22: Explorer.ThirdPartyIntegrations.Sourcify.check_by_address_any/1\n    (explorer 5.3.0) lib/explorer/smart_contract/solidity/publish_helper.ex:180: Explorer.SmartContract.Solidity.PublishHelper.check_by_address_in_sourcify/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:354: BlockScoutWeb.API.RPC.ContractController.getsourcecode/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.action/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.phoenix_controller_pipeline/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:119: BlockScoutWeb.API.RPC.RPCTranslator.call_controller/3\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:37: BlockScoutWeb.API.RPC.RPCTranslator.call/2\n"
```

**Comment by RonTuretzky** [comment]
> @RonTuretzky It now works, why the specific SECRET_KEY_BASE is required?

I don't know, just saw it on another issue

**Comment by RonTuretzky** [comment]
> Now I get another strange error
> 
> ```
> 2023-10-23T16:29:09.507 application=api request_id=F5DJcafoWHQ33qYACECC [error] Error while calling RPC action"** (Plug.Conn.WrapperError) ** (ArgumentError) construction of binary failed: segment 3 of type 'binary': expected a binary but got: nil\n    (explorer 5.3.0) lib/explorer/third_party_integrations/sourcify.ex:439: Explorer.ThirdPartyIntegrations.Sourcify.get_metadata_any_url/0\n    (explorer 5.3.0) lib/explorer/third_party_integrations/sourcify.ex:22: Explorer.ThirdPartyIntegrations.Sourcify.check_by_address_any/1\n    (explorer 5.3.0) lib/explorer/smart_contract/solidity/publish_helper.ex:180: Explorer.SmartContract.Solidity.PublishHelper.check_by_address_in_sourcify/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:354: BlockScoutWeb.API.RPC.ContractController.getsourcecode/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.action/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.phoenix_controller_pipeline/2\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:119: BlockScoutWeb.API.RPC.RPCTranslator.call_controller/3\n    (block_scout_web 5.3.0) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:37: BlockScoutWeb.API.RPC.RPCTranslator.call/2\n"
> ```

Are you trying to use sourcify? Did u set the proper env variables for it?

**Comment by kaliubuntu0206** [comment]
@RonTuretzky I disabled it with the following env

```
SOURCIFY_INTEGRATION_ENABLED=false
```

**Comment by nikitosing** [comment]
@kaliubuntu0206 Hello! I want to follow up, is this issue still reproducible with the latest release?

**Comment by kaliubuntu0206** [comment]
@nikitosing Sorry for late reply I think I had confirmed that the issue is solved from the discord
