### ISSUE TITLE
construction of binary failed while opening /addresss/${contract}/contracts page

### ISSUE THREAD

**Issue by kaliubuntu0206** [blockscout/blockscout#8675]
### Description

```
023-10-23T15:58:21.295 application=block_scout_web request_id=F5DHw1XUz93olqEABrxl [info] Sent 200 in 3ms
2023-10-23T15:58:21.455 application=block_scout_web request_id=F5DHw1-YylL2a3YABryF [info] GET /address/0xAA16139b04E45852564d5FAf2e2246819e91EAFd/contracts
2023-10-23T15:58:21.457 application=block_scout_web request_id=F5DHw1-YylL2a3YABryF [info] Sent 500 in 1ms
2023-10-23T15:58:21.458 [error] #PID<0.10463.78> running BlockScoutWeb.Endpoint (connection #PID<0.10449.78>, stream id 1) terminated
Request: GET /address/0xAA16139b04E45852564d5FAf2e2246819e91EAFd/contracts
** (exit) an exception was raised:
    ** (ArgumentError) construction of binary failed: segment 3 of type 'binary': expected a binary but got: nil
        (explorer 5.3.0) lib/explorer/third_party_integrations/sourcify.ex:439: Explorer.ThirdPartyIntegrations.Sourcify.get_metadata_any_url/0
        (explorer 5.3.0) lib/explorer/third_party_integrations/sourcify.ex:22: Explorer.ThirdPartyIntegrations.Sourcify.check_by_address_any/1
        (explorer 5.3.0) lib/explorer/smart_contract/solidity/publish_helper.ex:180: Explorer.SmartContract.Solidity.PublishHelper.check_by_address_in_sourcify/2
        (block_scout_web 5.3.0) lib/block_scout_web/controllers/address_contract_controller.ex:26: BlockScoutWeb.AddressContractController.index/2
        (block_scout_web 5.3.0) lib/block_scout_web/controllers/address_contract_controller.ex:2: BlockScoutWeb.AddressContractController.action/2
        (block_scout_web 5.3.0) lib/block_scout_web/controllers/address_contract_controller.ex:2: BlockScoutWeb.AddressContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v5.3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.4

**Comment by vbaranov** [comment]
At what chain id this contract has been deployed?

**Comment by kaliubuntu0206** [comment]
@vbaranov 2023, it is my private network created with Geth Clique

**Comment by vbaranov** [comment]
> @vbaranov 2023, it is my private network created with Geth Clique

Did you set `SOURCIFY_INTEGRATION_ENABLED`?

**Comment by kaliubuntu0206** [comment]
@vbaranov Yes I turned it off

```
SOURCIFY_INTEGRATION_ENABLED=false
```
