### ISSUE TITLE
"zkevm_batch_l2_transactions" does not exist

### ISSUE THREAD

**Issue by oxf71** [blockscout/blockscout#8690]
### Description

use va-zkevm branch Click transaction details to report an error

```
backend  | 2023-10-24T03:14:00.021 application=api_v2 request_id=F5Dsof5PoIQpzRYAAE9i [info] Sent 200 in 1ms
backend  | 2023-10-24T03:14:00.081 application=phoenix [info] JOINED blocks:indexing in 146µs
backend  |   Parameters: %{}
backend  | 2023-10-24T03:14:00.081 application=phoenix [info] JOINED blocks:indexing_internal_transactions in 16µs
backend  |   Parameters: %{}
backend  | 2023-10-24T03:14:00.340 application=api_v2 request_id=F5DsohFzNsyzI5YAAE_C [info] GET /api/v2/transactions/0x59ee57532518f0c9b7163df7498344e940b21e839c83cd7c6705ed581a0c5520
backend  | 2023-10-24T03:14:00.354 [error] Task #PID<0.10032.0> started from #PID<0.10030.0> terminating
backend  | ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "zkevm_batch_l2_transactions" does not exist
backend  |
backend  |     query: SELECT z0."batch_number", z0."hash", z0."inserted_at", z0."updated_at", z0."hash" FROM "zkevm_batch_l2_transactions" AS z0 WHERE (z0."hash" = $1)
backend  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
backend  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
backend  |     (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
backend  |     (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
backend  |     (ecto 3.10.3) lib/ecto/repo/preloader.ex:272: Ecto.Repo.Preloader.fetch_query/8
backend  |     (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
backend  |     (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
backend  |     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
backend  | Function: &:erlang.apply/2
backend  |     Args: [#Function<8.76891648/1 in Ecto.Repo.Preloader.maybe_pmap/3>, [#Function<20.76891648/1 in Ecto.Repo.Preloader.prepare_queries/6>]]
backend  | 2023-10-24T03:14:00.357 application=db_connection [info] Postgrex.Protocol (#PID<0.4226.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.10033.0> exited
backend  | 2023-10-24T03:14:00.358 [error] Ranch protocol #PID<0.10030.0> of listener BlockScoutWeb.Endpoint.HTTP (connection #PID<0.10029.0>, stream id 1) terminated
backend  | an exception was raised:
backend  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "zkevm_batch_l2_transactions" does not exist
backend  |
backend  |     query: SELECT z0."batch_number", z0."hash", z0."inserted_at", z0."updated_at", z0."hash" FROM "zkevm_batch_l2_transactions" AS z0 WHERE (z0."hash" = $1)
backend  |         (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
backend  |         (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
backend  |         (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
backend  |         (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
backend  |         (ecto 3.10.3) lib/ecto/repo/preloader.ex:272: Ecto.Repo.Preloader.fetch_query/8
backend  |         (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
backend  |         (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
backend  |         (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
backend  | 2023-10-24T03:14:01.272 application=indexer fetcher=internal_transaction count=1 error_count=1 [error] failed to fetch internal transactions for blocks: ** (ErlangError) Erlang error: [%{code: -32601, data: %{block_number: 1, transaction_hash: "0x59ee57532518f0c9b7163df7498344e940b21e839c83cd7c6705ed581a0c5520", transaction_index: 0}, message: "the method debug_traceTransaction does not exist/is not available"}]
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

cdk

### Type of the chain

L2

### Steps to reproduce

1. Start the chain using cdk quickstart

https://github.com/Snapchain/zkValidium-quickstart

2.  Compile the va-zkevm branch through docker compose build

3. Modifying backend env
```
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: http://192.168.2.197:8123/
        ETHEREUM_JSONRPC_TRACE_URL: http://192.168.2.197:8123/
        # ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
        INDEXER_ZKEVM_BATCHES_ENABLED: true
        CHAIN_ID: '1001'
```

4. docker compose up -d 

### Backend version

v5.3.0

### Frontend version

 v1.16.0-alpha

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

macOS

### Additional information

<img width="1344" alt="截屏2023-10-24 11 23 31" src="https://github.com/blockscout/blockscout/assets/144757737/09af4223-4f21-46f7-884f-64de88581533">

**Comment by oxf71** [comment]
set CHAIN_TYPE=polygon_zkevm successful
