### ISSUE TITLE
Long execution query at init of Explorer.TokenInstanceOwnerAddressMigration.Worker

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8729]
### Description

Long execution query at init of Explorer.TokenInstanceOwnerAddressMigration.Worker

https://github.com/blockscout/blockscout/blob/0e79ee5f81b4a3bfb98eae818f0af4f7fecbf6b8/apps/explorer/lib/explorer/token_instance_owner_address_migration/helper.ex#L18-L26

```
> Explorer.Repo.exists?(Explorer.TokenInstanceOwnerAddressMigration.Helper.filtered_token_instances_query(1))
** (DBConnection.ConnectionError) ssl recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:134: Ecto.Repo.Queryable.exists?/3
iex(blockscout@xdai-mainnet-blockscout-b96fb8cbb-6zph9)1>
09:14:31.911 [debug] QUERY ERROR source="token_instances" db=60001.5ms idle=1388.8ms
SELECT TRUE FROM "token_instances" AS t0 INNER JOIN "tokens" AS t1 ON t1."contract_address_hash" = t0."token_contract_address_hash" WHERE (t0."owner_address_hash" IS NULL) AND (t1."type" = 'ERC-721') LIMIT 1 []
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Any

### Backend version

v5.3.1

### Elixir & Erlang/OTP versions

Elixir 1.14.5

**Comment by nikitosing** [comment]
High response time for this query caused by completed migration. Decided to off this migration by default and add env for enabling.
