### ISSUE TITLE
Indexer.Fetcher.InternalTransaction terminating\n** (CaseClauseError) no case clause matching

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8751]
### Description

```
{"time":"2023-10-30T14:16:41.314Z","severity":"error","message":"Task #PID<0.16079.623> started from Indexer.Fetcher.InternalTransaction terminating\n** (CaseClauseError) no case clause matching: {:error, [#Ecto.Changeset<action: nil, changes: %{block_number: 9937377, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<13, 35, 154, 6, 14, 105, 112, 181, 4, 121, 185, 144, 129, 78, 143, 157, 253, 34, 48, 110>>}, gas: Decimal.new(\"314045\"), index: 3, input: %Explorer.Chain.Data{bytes: <<112, 160, 130, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 35, 154, 6, 14, 105, 112, 181, 4, 121, 185, 144, 129, 78, 143, 157, 253, 34, 48, 110>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<37, 45, 152, 250, 182, 72, 32, 58, 163, 51, 16, 114, 27, 187, 221, 250, 143, 27, 101, 135>>}, trace_address: [0, 1], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<121, 86, 143, 45, 57, 217, 154, 111, 13, 132, 180, 225, 253, 222, 40, 134, 252, 197, 65, 237, 2, 192, 245, 218, 221, 133, 254, 136, 65, 211, 250, 39>>}, transaction_index: 35, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {\"can't be blank for successful call\", [validation: :required]}, output: {\"can't be blank for successful call\", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 9937377, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<105, 179, 249, 178, 98, 128, 35, 247, 30, 75, 110, 155, 56, 178, 10, 61, 125, 105, 115, 25>>}, gas: Decimal.new(\"4800300\"), index: 2, input: %Explorer.Chain.Data{bytes: <<234, 126, 111, 251>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<105, 179, 249, 178, 98, 128, 35, 247, 30, 75, 110, 155, 56, 178, 10, 61, 125, 105, 115, 25>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<139, 142, 238, 151, 188, 252, 205, 74, 108, 120, 165, 63, 222, 159, 197, 92, 159, 95, 45, 69, 159, 92, 161, 58, 6, 80, 49, 238, 33, 77, 41, 160>>}, transaction_index: 135, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {\"can't be blank for successful call\", [validation: :required]}, output: {\"can't be blank for successful call\", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>]}\n    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:260: Indexer.Fetcher.InternalTransaction.import_internal_transaction/2\n    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:224: Indexer.Fetcher.InternalTransaction.safe_import_internal_transaction/2\n    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:128: Indexer.Fetcher.InternalTransaction.run/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nFunction: &Indexer.BufferedTask.log_run/1\n    Args: [%{batch: [9937377], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://.../\", fallback_url: \"https://rpc.ankr.com/eth_goerli\", fallback_trace_url: \"https://rpc.ankr.com/eth_goerli\", method_to_url: [debug_traceTransaction: \"http://.../\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]","metadata":{"count":1,"error":{"initial_call":null,"reason":"** (CaseClauseError) no case clause matching: {:error, [#Ecto.Changeset<action: nil, changes: %{block_number: 9937377, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<13, 35, 154, 6, 14, 105, 112, 181, 4, 121, 185, 144, 129, 78, 143, 157, 253, 34, 48, 110>>}, gas: Decimal.new(\"314045\"), index: 3, input: %Explorer.Chain.Data{bytes: <<112, 160, 130, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 35, 154, 6, 14, 105, 112, 181, 4, 121, 185, 144, 129, 78, 143, 157, 253, 34, 48, 110>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<37, 45, 152, 250, 182, 72, 32, 58, 163, 51, 16, 114, 27, 187, 221, 250, 143, 27, 101, 135>>}, trace_address: [0, 1], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<121, 86, 143, 45, 57, 217, 154, 111, 13, 132, 180, 225, 253, 222, 40, 134, 252, 197, 65, 237, 2, 192, 245, 218, 221, 133, 254, 136, 65, 211, 250, 39>>}, transaction_index: 35, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {\"can't be blank for successful call\", [validation: :required]}, output: {\"can't be blank for successful call\", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 9937377, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<105, 179, 249, 178, 98, 128, 35, 247, 30, 75, 110, 155, 56, 178, 10, 61, 125, 105, 115, 25>>}, gas: Decimal.new(\"4800300\"), index: 2, input: %Explorer.Chain.Data{bytes: <<234, 126, 111, 251>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<105, 179, 249, 178, 98, 128, 35, 247, 30, 75, 110, 155, 56, 178, 10, 61, 125, 105, 115, 25>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<139, 142, 238, 151, 188, 252, 205, 74, 108, 120, 165, 63, 222, 159, 197, 92, 159, 95, 45, 69, 159, 92, 161, 58, 6, 80, 49, 238, 33, 77, 41, 160>>}, transaction_index: 135, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {\"can't be blank for successful call\", [validation: :required]}, output: {\"can't be blank for successful call\", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>]}\n    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:260: Indexer.Fetcher.InternalTransaction.import_internal_transaction/2\n    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:224: Indexer.Fetcher.InternalTransaction.safe_import_internal_transaction/2\n    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:128: Indexer.Fetcher.InternalTransaction.run/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"},"fetcher":"internal_transaction"}}
```

### Type of the installation

Helm charts

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://base.blockscout.com/

### Backend version

v5.3.1

### Elixir & Erlang/OTP versions

Elixir 1.14.5

**Comment by vbaranov** [comment]
Resolved
