### ISSUE TITLE
A contract that has been successfully verified cannot be verified again. The contract has dependent libraries.

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8762]
### Description

A contract that has been successfully verified cannot be verified again. The contract has dependent libraries.
This phenomenon is also the same in eth-sepolia. The following uses eth-sepolia as an example.

Always loading：
<img width="678" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/288ce5aa-dd01-403e-a211-d6e00e11416e">

Related parameter information：
- contract address：0xEAa4E76768EE8Cf189c823a6916dbC704EC8108A
- v0.8.21+commit.d9974bed
- evm version：default
- contract code：
// File: yzh-solidity/utils/math/Math.sol

// OpenZeppelin Contracts (last updated v5.0.0) (utils/math/Math.sol)

pragma solidity ^0.8.20;

/**
 * @dev Standard math utilities missing in the Solidity language.
 */
library Math {
    /**
     * @dev Muldiv operation overflow.
     */
    error MathOverflowedMulDiv();

    enum Rounding {
        Floor, // Toward negative infinity
        Ceil, // Toward positive infinity
        Trunc, // Toward zero
        Expand // Away from zero
    }

    /**
     * @dev Returns the addition of two unsigned integers, with an overflow flag.
     */
    function tryAdd(uint256 a, uint256 b) external pure returns (bool, uint256) {
        unchecked {
            uint256 c = a + b;
            if (c < a) return (false, 0);
            return (true, c);
        }
    }

    /**
     * @dev Returns the subtraction of two unsigned integers, with an overflow flag.
     */
    function trySub(uint256 a, uint256 b) external pure returns (bool, uint256) {
        unchecked {
            if (b > a) return (false, 0);
            return (true, a - b);
        }
    }

    /**
     * @dev Returns the multiplication of two unsigned integers, with an overflow flag.
     */
    function tryMul(uint256 a, uint256 b) external pure returns (bool, uint256) {
        unchecked {
            // Gas optimization: this is cheaper than requiring 'a' not being zero, but the
            // benefit is lost if 'b' is also tested.
            // See: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/522
            if (a == 0) return (true, 0);
            uint256 c = a * b;
            if (c / a != b) return (false, 0);
            return (true, c);
        }
    }

    /**
     * @dev Returns the division of two unsigned integers, with a division by zero flag.
     */
    function tryDiv(uint256 a, uint256 b) public pure returns (bool, uint256) {
        unchecked {
            if (b == 0) return (false, 0);
            return (true, a / b);
        }
    }

    /**
     * @dev Returns the remainder of dividing two unsigned integers, with a division by zero flag.
     */
    function tryMod(uint256 a, uint256 b) public pure returns (bool, uint256) {
        unchecked {
            if (b == 0) return (false, 0);
            return (true, a % b);
        }
    }

    /**
     * @dev Returns the largest of two numbers.
     */
    function max(uint256 a, uint256 b) public pure returns (uint256) {
        return a > b ? a : b;
    }

    /**
     * @dev Returns the smallest of two numbers.
     */
    function min(uint256 a, uint256 b) public pure returns (uint256) {
        return a < b ? a : b;
    }

    /**
     * @dev Returns the average of two numbers. The result is rounded towards
     * zero.
     */
    function average(uint256 a, uint256 b) internal pure returns (uint256) {
        // (a + b) / 2 can overflow.
        return (a & b) + (a ^ b) / 2;
    }

    /**
     * @dev Returns the ceiling of the division of two numbers.
     *
     * This differs from standard division with `/` in that it rounds towards infinity instead
     * of rounding towards zero.
     */
    function ceilDiv(uint256 a, uint256 b) internal pure returns (uint256) {
        if (b == 0) {
            // Guarantee the same behavior as in a regular Solidity division.
            return a / b;
        }

        // (a + b - 1) / b can overflow on addition, so we distribute.
        return a == 0 ? 0 : (a - 1) / b + 1;
    }

    /**
     * @notice Calculates floor(x * y / denominator) with full precision. Throws if result overflows a uint256 or
     * denominator == 0.
     * @dev Original credit to Remco Bloemen under MIT license (https://xn--2-umb.com/21/muldiv) with further edits by
     * Uniswap Labs also under MIT license.
     */
    function mulDiv(uint256 x, uint256 y, uint256 denominator) internal pure returns (uint256 result) {
        unchecked {
            // 512-bit multiply [prod1 prod0] = x * y. Compute the product mod 2^256 and mod 2^256 - 1, then use
            // use the Chinese Remainder Theorem to reconstruct the 512 bit result. The result is stored in two 256
            // variables such that product = prod1 * 2^256 + prod0.
            uint256 prod0 = x * y; // Least significant 256 bits of the product
            uint256 prod1; // Most significant 256 bits of the product
            assembly {
                let mm := mulmod(x, y, not(0))
                prod1 := sub(sub(mm, prod0), lt(mm, prod0))
            }

            // Handle non-overflow cases, 256 by 256 division.
            if (prod1 == 0) {
                // Solidity will revert if denominator == 0, unlike the div opcode on its own.
                // The surrounding unchecked block does not change this fact.
                // See https://docs.soliditylang.org/en/latest/control-structures.html#checked-or-unchecked-arithmetic.
                return prod0 / denominator;
            }

            // Make sure the result is less than 2^256. Also prevents denominator == 0.
            if (denominator <= prod1) {
                revert MathOverflowedMulDiv();
            }

            ///////////////////////////////////////////////
            // 512 by 256 division.
            ///////////////////////////////////////////////

            // Make division exact by subtracting the remainder from [prod1 prod0].
            uint256 remainder;
            assembly {
                // Compute remainder using mulmod.
                remainder := mulmod(x, y, denominator)

                // Subtract 256 bit number from 512 bit number.
                prod1 := sub(prod1, gt(remainder, prod0))
                prod0 := sub(prod0, remainder)
            }

            // Factor powers of two out of denominator and compute largest power of two divisor of denominator.
            // Always >= 1. See https://cs.stackexchange.com/q/138556/92363.

            uint256 twos = denominator & (0 - denominator);
            assembly {
                // Divide denominator by twos.
                denominator := div(denominator, twos)

                // Divide [prod1 prod0] by twos.
                prod0 := div(prod0, twos)

                // Flip twos such that it is 2^256 / twos. If twos is zero, then it becomes one.
                twos := add(div(sub(0, twos), twos), 1)
            }

            // Shift in bits from prod1 into prod0.
            prod0 |= prod1 * twos;

            // Invert denominator mod 2^256. Now that denominator is an odd number, it has an inverse modulo 2^256 such
            // that denominator * inv = 1 mod 2^256. Compute the inverse by starting with a seed that is correct for
            // four bits. That is, denominator * inv = 1 mod 2^4.
            uint256 inverse = (3 * denominator) ^ 2;

            // Use the Newton-Raphson iteration to improve the precision. Thanks to Hensel's lifting lemma, this also
            // works in modular arithmetic, doubling the correct bits in each step.
            inverse *= 2 - denominator * inverse; // inverse mod 2^8
            inverse *= 2 - denominator * inverse; // inverse mod 2^16
            inverse *= 2 - denominator * inverse; // inverse mod 2^32
            inverse *= 2 - denominator * inverse; // inverse mod 2^64
            inverse *= 2 - denominator * inverse; // inverse mod 2^128
            inverse *= 2 - denominator * inverse; // inverse mod 2^256

            // Because the division is now exact we can divide by multiplying with the modular inverse of denominator.
            // This will give us the correct result modulo 2^256. Since the preconditions guarantee that the outcome is
            // less than 2^256, this is the final result. We don't need to compute the high bits of the result and prod1
            // is no longer required.
            result = prod0 * inverse;
            return result;
        }
    }

    /**
     * @notice Calculates x * y / denominator with full precision, following the selected rounding direction.
     */
    function mulDiv(uint256 x, uint256 y, uint256 denominator, Rounding rounding) internal pure returns (uint256) {
        uint256 result = mulDiv(x, y, denominator);
        if (unsignedRoundsUp(rounding) && mulmod(x, y, denominator) > 0) {
            result += 1;
        }
        return result;
    }

    /**
     * @dev Returns the square root of a number. If the number is not a perfect square, the value is rounded
     * towards zero.
     *
     * Inspired by Henry S. Warren, Jr.'s "Hacker's Delight" (Chapter 11).
     */
    function sqrt(uint256 a) internal pure returns (uint256) {
        if (a == 0) {
            return 0;
        }

        // For our first guess, we get the biggest power of 2 which is smaller than the square root of the target.
        //
        // We know that the "msb" (most significant bit) of our target number `a` is a power of 2 such that we have
        // `msb(a) <= a < 2*msb(a)`. This value can be written `msb(a)=2**k` with `k=log2(a)`.
        //
        // This can be rewritten `2**log2(a) <= a < 2**(log2(a) + 1)`
        // → `sqrt(2**k) <= sqrt(a) < sqrt(2**(k+1))`
        // → `2**(k/2) <= sqrt(a) < 2**((k+1)/2) <= 2**(k/2 + 1)`
        //
        // Consequently, `2**(log2(a) / 2)` is a good first approximation of `sqrt(a)` with at least 1 correct bit.
        uint256 result = 1 << (log2(a) >> 1);

        // At this point `result` is an estimation with one bit of precision. We know the true value is a uint128,
        // since it is the square root of a uint256. Newton's method converges quadratically (precision doubles at
        // every iteration). We thus need at most 7 iteration to turn our partial result with one bit of precision
        // into the expected uint128 result.
        unchecked {
            result = (result + a / result) >> 1;
            result = (result + a / result) >> 1;
            result = (result + a / result) >> 1;
            result = (result + a / result) >> 1;
            result = (result + a / result) >> 1;
            result = (result + a / result) >> 1;
            result = (result + a / result) >> 1;
            return min(result, a / result);
        }
    }

    /**
     * @notice Calculates sqrt(a), following the selected rounding direction.
     */
    function sqrt(uint256 a, Rounding rounding) internal pure returns (uint256) {
        unchecked {
            uint256 result = sqrt(a);
            return result + (unsignedRoundsUp(rounding) && result * result < a ? 1 : 0);
        }
    }

    /**
     * @dev Return the log in base 2 of a positive value rounded towards zero.
     * Returns 0 if given 0.
     */
    function log2(uint256 value) internal pure returns (uint256) {
        uint256 result = 0;
        unchecked {
            if (value >> 128 > 0) {
                value >>= 128;
                result += 128;
            }
            if (value >> 64 > 0) {
                value >>= 64;
                result += 64;
            }
            if (value >> 32 > 0) {
                value >>= 32;
                result += 32;
            }
            if (value >> 16 > 0) {
                value >>= 16;
                result += 16;
            }
            if (value >> 8 > 0) {
                value >>= 8;
                result += 8;
            }
            if (value >> 4 > 0) {
                value >>= 4;
                result += 4;
            }
            if (value >> 2 > 0) {
                value >>= 2;
                result += 2;
            }
            if (value >> 1 > 0) {
                result += 1;
            }
        }
        return result;
    }

    /**
     * @dev Return the log in base 2, following the selected rounding direction, of a positive value.
     * Returns 0 if given 0.
     */
    function log2(uint256 value, Rounding rounding) internal pure returns (uint256) {
        unchecked {
            uint256 result = log2(value);
            return result + (unsignedRoundsUp(rounding) && 1 << result < value ? 1 : 0);
        }
    }

    /**
     * @dev Return the log in base 10 of a positive value rounded towards zero.
     * Returns 0 if given 0.
     */
    function log10(uint256 value) internal pure returns (uint256) {
        uint256 result = 0;
        unchecked {
            if (value >= 10 ** 64) {
                value /= 10 ** 64;
                result += 64;
            }
            if (value >= 10 ** 32) {
                value /= 10 ** 32;
                result += 32;
            }
            if (value >= 10 ** 16) {
                value /= 10 ** 16;
                result += 16;
            }
            if (value >= 10 ** 8) {
                value /= 10 ** 8;
                result += 8;
            }
            if (value >= 10 ** 4) {
                value /= 10 ** 4;
                result += 4;
            }
            if (value >= 10 ** 2) {
                value /= 10 ** 2;
                result += 2;
            }
            if (value >= 10 ** 1) {
                result += 1;
            }
        }
        return result;
    }

    /**
     * @dev Return the log in base 10, following the selected rounding direction, of a positive value.
     * Returns 0 if given 0.
     */
    function log10(uint256 value, Rounding rounding) internal pure returns (uint256) {
        unchecked {
            uint256 result = log10(value);
            return result + (unsignedRoundsUp(rounding) && 10 ** result < value ? 1 : 0);
        }
    }

    /**
     * @dev Return the log in base 256 of a positive value rounded towards zero.
     * Returns 0 if given 0.
     *
     * Adding one to the result gives the number of pairs of hex symbols needed to represent `value` as a hex string.
     */
    function log256(uint256 value) internal pure returns (uint256) {
        uint256 result = 0;
        unchecked {
            if (value >> 128 > 0) {
                value >>= 128;
                result += 16;
            }
            if (value >> 64 > 0) {
                value >>= 64;
                result += 8;
            }
            if (value >> 32 > 0) {
                value >>= 32;
                result += 4;
            }
            if (value >> 16 > 0) {
                value >>= 16;
                result += 2;
            }
            if (value >> 8 > 0) {
                result += 1;
            }
        }
        return result;
    }

    /**
     * @dev Return the log in base 256, following the selected rounding direction, of a positive value.
     * Returns 0 if given 0.
     */
    function log256(uint256 value, Rounding rounding) internal pure returns (uint256) {
        unchecked {
            uint256 result = log256(value);
            return result + (unsignedRoundsUp(rounding) && 1 << (result << 3) < value ? 1 : 0);
        }
    }

    /**
     * @dev Returns whether a provided rounding mode is considered rounding up for unsigned integers.
     */
    function unsignedRoundsUp(Rounding rounding) internal pure returns (bool) {
        return uint8(rounding) % 2 == 1;
    }
}

// File: contracts/Box.sol

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.18;

// Import Ownable from the OpenZeppelin Contracts library

// Make Box inherit from the Ownable contract
contract Box {
    function add(uint256 a, uint256 b) external pure returns (uint256) {
        (bool success, uint256 res) = Math.tryAdd(a, b);
        return res;
    }

    function sub(uint256 a, uint256 b) external pure returns (uint256) {
        (bool success, uint256 res) = Math.trySub(a, b);
        return res;
    }
}

- library name：Math
- library address：0x35850EEb06EfcA8C28d6082630eC161fCB858035

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Link to the page

https://eth-sepolia.blockscout.com/address/0xEAa4E76768EE8Cf189c823a6916dbC704EC8108A/contract-verification

### Backend version

v5.2.3-beta

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by yzh-d** [comment]
Because simple contract verification allows repeated verification, I would like to know if repeated verification is not supported in this case. Is there a bug or some special logic?

**Comment by rimrakhimov** [comment]
@vbaranov For some reason we got the following error when trying to insert a data for already verified contracts which contain libraries. Could you please have a look?

```
{"time":"2023-11-30T13:47:57.112Z","severity":"error","message":"Task #PID<0.24919.85> started from #PID<0.28414.84> terminating\n** (RuntimeError) you are attempting to change relation :external_libraries of\nExplorer.Chain.SmartContract but the `:on_replace` option of this relation\nis set to `:raise`.\n\nBy default it is not possible to replace or delete embeds and\nassociations during `cast`. Therefore Ecto requires the parameters\ngiven to `cast` to have IDs matching the data currently associated\nto Explorer.Chain.SmartContract. Failing to do so results in this error message.\n\nIf you want to replace data or automatically delete any data\nnot sent to `cast`, please set the appropriate `:on_replace`\noption when defining the relation. The docs for `Ecto.Changeset`\ncovers the supported options in the \"Associations, embeds and on\nreplace\" section.\n\nHowever, if you don't want to allow data to be replaced or\ndeleted, only updated, make sure that:\n\n  * If you are attempting to update an existing entry, you\n    are including the entry primary key (ID) in the data.\n\n  * If you have a relationship with many children, all children\n    must be given on update.\n\n\n    (ecto 3.10.3) lib/ecto/changeset/relation.ex:246: Ecto.Changeset.Relation.on_replace/2\n    (ecto 3.10.3) lib/ecto/changeset/relation.ex:417: Ecto.Changeset.Relation.reduce_delete_changesets/5\n    (ecto 3.10.3) lib/ecto/changeset/relation.ex:173: Ecto.Changeset.Relation.change/3\n    (ecto 3.10.3) lib/ecto/changeset.ex:1750: Ecto.Changeset.put_change/7\n    (ecto 3.10.3) lib/ecto/changeset.ex:1741: Ecto.Changeset.put_change/3\n    (explorer 5.3.2) lib/explorer/chain/smart_contract.ex:921: Explorer.Chain.SmartContract.update_smart_contract/3\n    (explorer 5.3.2) lib/explorer/smart_contract/solidity/publisher_worker.ex:65: Explorer.SmartContract.Solidity.PublisherWorker.broadcast/4\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\nFunction: #Function<3.127712543/0 in Que.Job.perform/1>\n    Args: []","metadata":{"error":{"initial_call":null,"reason":"** (RuntimeError) you are attempting to change relation :external_libraries of\nExplorer.Chain.SmartContract but the `:on_replace` option of this relation\nis set to `:raise`.\n\nBy default it is not possible to replace or delete embeds and\nassociations during `cast`. Therefore Ecto requires the parameters\ngiven to `cast` to have IDs matching the data currently associated\nto Explorer.Chain.SmartContract. Failing to do so results in this error message.\n\nIf you want to replace data or automatically delete any data\nnot sent to `cast`, please set the appropriate `:on_replace`\noption when defining the relation. The docs for `Ecto.Changeset`\ncovers the supported options in the \"Associations, embeds and on\nreplace\" section.\n\nHowever, if you don't want to allow data to be replaced or\ndeleted, only updated, make sure that:\n\n  * If you are attempting to update an existing entry, you\n    are including the entry primary key (ID) in the data.\n\n  * If you have a relationship with many children, all children\n    must be given on update.\n\n\n    (ecto 3.10.3) lib/ecto/changeset/relation.ex:246: Ecto.Changeset.Relation.on_replace/2\n    (ecto 3.10.3) lib/ecto/changeset/relation.ex:417: Ecto.Changeset.Relation.reduce_delete_changesets/5\n    (ecto 3.10.3) lib/ecto/changeset/relation.ex:173: Ecto.Changeset.Relation.change/3\n    (ecto 3.10.3) lib/ecto/changeset.ex:1750: Ecto.Changeset.put_change/7\n    (ecto 3.10.3) lib/ecto/changeset.ex:1741: Ecto.Changeset.put_change/3\n    (explorer 5.3.2) lib/explorer/chain/smart_contract.ex:921: Explorer.Chain.SmartContract.update_smart_contract/3\n    (explorer 5.3.2) lib/explorer/smart_contract/solidity/publisher_worker.ex:65: Explorer.SmartContract.Solidity.PublisherWorker.broadcast/4\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n"}}}

```

**Comment by rimrakhimov** [comment]
@vbaranov Yeap, it seems to be working now

**Comment by yzh-d** [comment]
> @rimrakhimov would you plrease re-check? I patched eth-sepolia instance.

Thank you for your support. If this feature is fixed, please tell me which tag I should start using it from. Thank you.
