### ISSUE TITLE
Can't get blockscout to work work `geth --dev` mode

### ISSUE THREAD

**Issue by wighawag** [blockscout/blockscout#8777]
### Description

I used the docker-compose folder provided 

I am running geth with 

```
geth --dev --nousb --ws --ws.addr "0.0.0.0" --ws.origins "*" --http --http.vhosts "*" --http.addr "0.0.0.0" --http.corsdomain "*" --miner.gasprice $GETH_GASPRICE --dev.period $GETH_BLOCK_TIME --rpc.allow-unprotected-txs --datadir $HOME/.geth-dev --password $HOME/.geth-dev/password --http.api eth,web3,net,admin,db,debug,txpool
```

then  I tried 

```
docker compose -f docker-compose-no-build-geth-clique-consensus.yml up
```

It output errors in the console:

```

** (MatchError) no match of right hand side value: <<216, 131, 1, 13, 4, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 50, 49, 46, 51, 133, 108, 105, 110, 117, 120>>
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks.ex:92: Indexer.Transform.Blocks.recover_pub_key/2
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
backend                         |     (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
backend                         |     (indexer 5.3.1) lib/indexer/block/fetcher.ex:140: Indexer.Block.Fetcher.fetch_and_import_range/2
backend                         |     (stdlib 3.17) timer.erl:166: :timer.tc/1
backend                         |     (indexer 5.3.1) lib/indexer/block/realtime/fetcher.ex:318: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
backend                         |     (indexer 5.3.1) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
backend                         |     (indexer 5.3.1) lib/indexer/block/realtime/fetcher.ex:288: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
backend                         | Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
backend                         |     Args: [125, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://host.docker.internal:8545/", fallback_url: nil, fallback_trace_url: nil, method_to_url: [debug_traceTransaction: "http://host.docker.internal:8545/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
backend                         | 2023-11-02T17:29:55.138 application=indexer fetcher=block_catchup first_block_number=102 last_block_number=102 [error] ** (MatchError) no match of right hand side value: <<216, 131, 1, 13, 4, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 50, 49, 46, 51, 133, 108, 105, 110, 117, 120>>
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks.ex:92: Indexer.Transform.Blocks.recover_pub_key/2
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
backend                         |     (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
backend                         |     (indexer 5.3.1) lib/indexer/block/fetcher.ex:140: Indexer.Block.Fetcher.fetch_and_import_range/2
backend                         |     (stdlib 3.17) timer.erl:166: :timer.tc/1
backend                         |     (indexer 5.3.1) lib/indexer/block/catchup/fetcher.ex:195: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
backend                         |     (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
backend                         |     (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
backend                         | 
backend                         | 
backend                         | Retrying.
backend                         | 2023-11-02T17:29:55.138 application=indexer fetcher=block_catchup first_block_number=102 last_block_number=102 missing_block_count=1 shrunk=false [info] Index had to catch up.
backend                         | 2023-11-02T17:29:55.138 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
backend                         | 2023-11-02T17:29:56.191 application=tzdata [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Tue, 28 Mar 2023 20:25:39 GMT.
backend                         | 2023-11-02T17:29:57.312 application=tzdata [info] Tzdata has updated the release from 2021e to 2023c
backend                         | 2023-11-02T17:29:57.655 application=indexer fetcher=block_catchup first_block_number=102 last_block_number=102 [error] ** (MatchError) no match of right hand side value: <<216, 131, 1, 13, 4, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 50, 49, 46, 51, 133, 108, 105, 110, 117, 120>>
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks.ex:92: Indexer.Transform.Blocks.recover_pub_key/2
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
backend                         |     (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
backend                         |     (indexer 5.3.1) lib/indexer/block/fetcher.ex:140: Indexer.Block.Fetcher.fetch_and_import_range/2
backend                         |     (stdlib 3.17) timer.erl:166: :timer.tc/1
backend                         |     (indexer 5.3.1) lib/indexer/block/catchup/fetcher.ex:195: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
backend                         |     (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
backend                         |     (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
backend                         | 
backend                         | 
backend                         | Retrying.

```

as well as :

```
docker compose -f docker-compose-no-build-geth.yml up
```
this one do not show error in the console but no block get parsed it seems as when navigating to the frontend, it shows 

```
Blocks
Something went wrong. Try refreshing the page or come back later.
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

Local (--dev)

### Steps to reproduce

```
geth --dev --nousb --ws --ws.addr "0.0.0.0" --ws.origins "*" --http --http.vhosts "*" --http.addr "0.0.0.0" --http.corsdomain "*"  --rpc.allow-unprotected-txs  --http.api eth,web3,net,admin,db,debug,txpool
```

then

```
docker compose -f docker-compose-no-build-geth-clique-consensus.yml up
```

OR

```
docker compose -f docker-compose-no-build-geth.yml up
```

### Backend version

1e832d995cc71b3b66b8fc6d51d5273924c1bbba

### Frontend version

1e832d995cc71b3b66b8fc6d51d5273924c1bbba

### Elixir & Erlang/OTP versions

1e832d995cc71b3b66b8fc6d51d5273924c1bbba

### Operating system

Linux

**Comment by wighawag** [comment]
I also tried with a 3 node setup (bootnode, miner, rpc), see docker-compose : https://github.com/wighawag/ethereum-lan-node/blob/0c3f6e50a2fb9f899a71ecf0d504140efe24fa21/docker-compose.yml

But while I do not get errors in the console I get the same 

```
Blocks
Something went wrong. Try refreshing the page or come back later.
```

in the frontend

No tx or blocks seems to be picked up

The docker logs show progress of indexing though, so not sure what is wrong

**Comment by ekawibisono** [comment]
Can you show your common-blockscout.env and common-frontend.env configurations?

**Comment by wighawag** [comment]
I did not change anything from the github repo at commit : https://github.com/blockscout/blockscout/commit/1e832d995cc71b3b66b8fc6d51d5273924c1bbba

**Comment by wighawag** [comment]
I updated my geth --dev setup with latest version (1.13.4) and I get same errors when using `docker compose -f docker-compose-no-build-geth-clique-consensus.yml up`:

```
 2023-11-06T10:34:29.036 [error] Task #PID<0.25165.0> started from Indexer.Block.Realtime.Fetcher terminating
backend                         | ** (MatchError) no match of right hand side value: <<216, 131, 1, 13, 4, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 50, 49, 46, 51, 133, 108, 105, 110, 117, 120>>
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks.ex:92: Indexer.Transform.Blocks.recover_pub_key/2
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
backend                         |     (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
backend                         |     (indexer 5.3.1) lib/indexer/block/fetcher.ex:140: Indexer.Block.Fetcher.fetch_and_import_range/2
backend                         |     (stdlib 3.17) timer.erl:166: :timer.tc/1
backend                         |     (indexer 5.3.1) lib/indexer/block/realtime/fetcher.ex:318: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
backend                         |     (indexer 5.3.1) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
backend                         |     (indexer 5.3.1) lib/indexer/block/realtime/fetcher.ex:288: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
backend                         | Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
backend                         |     Args: [101, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://host.docker.internal:8545/", fallback_url: nil, fallback_trace_url: nil, method_to_url: [debug_traceTransaction: "http://host.docker.internal:8545/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
backend                         | 2023-11-06T10:34:29.316 application=indexer fetcher=block_catchup first_block_number=1509 last_block_number=440 missing_block_count=2 shrunk=false [info] Index had to catch up.
backend                         | 2023-11-06T10:34:29.316 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
backend                         | 2023-11-06T10:34:31.842 application=indexer fetcher=block_catchup first_block_number=1509 last_block_number=440 missing_block_count=2 shrunk=false [info] Index had to catch up.
backend                         | 2023-11-06T10:34:31.842 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
backend                         | 2023-11-06T10:34:33.953 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
backend                         | 2023-11-06T10:34:33.971 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
backend                         | 2023-11-06T10:34:34.049 [error] Task #PID<0.25555.0> started from Indexer.Block.Realtime.Fetcher terminating
backend                         | ** (MatchError) no match of right hand side value: <<216, 131, 1, 13, 4, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 50, 49, 46, 51, 133, 108, 105, 110, 117, 120>>
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks.ex:92: Indexer.Transform.Blocks.recover_pub_key/2
backend                         |     (indexer 5.3.1) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
backend                         |     (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
backend                         |     (indexer 5.3.1) lib/indexer/block/fetcher.ex:140: Indexer.Block.Fetcher.fetch_and_import_range/2
backend                         |     (stdlib 3.17) timer.erl:166: :timer.tc/1
backend                         |     (indexer 5.3.1) lib/indexer/block/realtime/fetcher.ex:318: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
backend                         |     (indexer 5.3.1) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
backend                         |     (indexer 5.3.1) lib/indexer/block/realtime/fetcher.ex:288: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
backend                         | Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3

```

see docker-compose: https://github.com/wighawag/ethereum-lan-node/blob/595fe36056053f17a15f265a8560b3e8262d8fc7/docker-compose.yml

**Comment by sl1depengwyn** [comment]
If you do not configure clique for your chain, you should use `docker compose -f docker-compose-no-build-geth.yml up`, from the error it seems that you do not use clique. Then, if you use the new frontend, probably you do so, check the browser console when you see `Blocks
Something went wrong. Try refreshing the page or come back later.`

**Comment by wighawag** [comment]
Thanks @sl1depengwyn 

Here is the log from the frontend:

Seems like CORS and websocket issue.

I am running the node on the LAN with hostname `ethereum.local`

Any config I should add ?

```
ethereum.local/:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/indexing-status' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/indexing-status:1 
        
        
       Failed to load resource: net::ERR_FAILED
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/stats' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/stats:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/stats/charts/transactions' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/stats/charts/transactions:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/blocks' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/blocks:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/transactions' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/transactions:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/config/backend-version' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/config/backend-version:1 
        
        
       Failed to load resource: net::ERR_FAILED
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/indexing-status' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/indexing-status:1 
        
        
       Failed to load resource: net::ERR_FAILED
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/stats' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/stats:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/stats/charts/transactions' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/stats/charts/transactions:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/blocks' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/blocks:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/transactions' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/transactions:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/config/backend-version' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/config/backend-version:1 
        
        
       Failed to load resource: net::ERR_FAILED
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/indexing-status' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/indexing-status:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/stats' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/stats:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/stats/charts/transactions' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/stats/charts/transactions:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/blocks' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/blocks:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/main-page/transactions' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/main-page/transactions:1 
        
        
       Failed to load resource: net::ERR_FAILED
ethereum.local/:1 Access to fetch at 'http://localhost/api/v2/config/backend-version' from origin 'http://ethereum.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/api/v2/config/backend-version:1 
        
        
       Failed to load resource: net::ERR_FAILED
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18
waitForSocketClosed @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18
waitForBufferDone @ _app-559dd2f562b9bf97.js:18
teardown @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18

(anonymous) @ _app-559dd2f562b9bf97.js:18
```

**Comment by wighawag** [comment]
Nevermind, I see that I need to replace `localhost` with `ethereum.local` in the env file.

All good it seems then. Thanks for your time

**Comment by wighawag** [comment]
@sl1depengwyn @ekawibisono any idea why I cannot access `ethereum.local:8080` nor `ethereum.local:8081` ?

should I edit more configuration file ?

(Note: I can access them from inside the host via `localhost:8080` and `localhost:8081`)
