### ISSUE TITLE
smart contract verification fails with error `Unknown UID`

### ISSUE THREAD

**Issue by refl3ction** [blockscout/blockscout#8842]
### Description

We are trying to verify a Smart Contract using blockscout API, but we are getting a weird response and the contract is not being verified. We are using the `smart-contract-verifier` microservice. The following environment variables are being used on Blockscout:

```yaml
      MICROSERVICE_SC_VERIFIER_ENABLED: "true"
      MICROSERVICE_SC_VERIFIER_URL: http://smart-contract-verifier.blockscout.svc.cluster.local:8050
```

### Command

```bash
forge create --rpc-url  http://localhost:8545/ --private-key <PK>  src/registries/RoleRegistry.sol:RoleRegistry   --legacy  --verify --verifier blockscout --verifier-url "https://blockscout.example.com/api?"

# Response
Deployer: 0xFE3B557E8Fb62b89F4916B721be55cEb828dBd73
Deployed to: 0x7653845854F904F2725E49B0A2560F56c6a12827
Transaction hash: 0xba8cbbc45293cbfc3b436d28657914e71a270d83bb2a97f0ef2fba57213b372e
Starting contract verification...
Waiting for blockscout to detect contract deployment...
Start verifying contract 0x7653845854F904F2725E49B0A2560F56c6a12827 deployed on dev

Submitting verification for [src/registries/RoleRegistry.sol:RoleRegistry] "0x7653845854F904F2725E49B0A2560F56c6a12827".
Submitted contract for verification:
        Response: OK
        GUID: 7653845854f904f2725e49b0a2560f56c6a128276554c4e5
        URL:
        https://blockscout.example.com/api?/address/0x7653845854f904f2725e49b0a2560f56c6a12827
Contract verification status:
Response: OK
Details: Unknown UID
```

### Blockscout Logs

```log
blockscout-edge-blockscout-55d747c659-fjk8k 2023-11-15T13:23:52.879 application=explorer [info] Smart-contract verification via standard json input started
blockscout-edge-blockscout-55d747c659-fjk8k 2023-11-15T13:23:55.731 [error] Task #PID<0.14040.1272> started from #PID<0.6835.1241> terminating
blockscout-edge-blockscout-55d747c659-fjk8k ** (KeyError) key :bytes not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
blockscout-edge-blockscout-55d747c659-fjk8k     (explorer 5.3.1) lib/explorer/smart_contract/helper.ex:44: Explorer.SmartContract.Helper.add_contract_code_md5/1
blockscout-edge-blockscout-55d747c659-fjk8k     (explorer 5.3.1) lib/explorer/smart_contract/solidity/publisher.ex:214: Explorer.SmartContract.Solidity.Publisher.unverified_smart_contract/5
blockscout-edge-blockscout-55d747c659-fjk8k     (explorer 5.3.1) lib/explorer/smart_contract/solidity/publisher.ex:103: Explorer.SmartContract.Solidity.Publisher.publish_with_standard_json_input/2
blockscout-edge-blockscout-55d747c659-fjk8k     (explorer 5.3.1) lib/explorer/smart_contract/solidity/publisher_worker.ex:54: Explorer.SmartContract.Solidity.PublisherWorker.perform/1
blockscout-edge-blockscout-55d747c659-fjk8k     (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout-edge-blockscout-55d747c659-fjk8k     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
blockscout-edge-blockscout-55d747c659-fjk8k Function: #Function<3.127712543/0 in Que.Job.perform/1>
blockscout-edge-blockscout-55d747c659-fjk8k     Args: []
blockscout-edge-blockscout-55d747c659-fjk8k 2023-11-15T13:23:55.732 application=que [info] [Que] Failed Job # 2 with Explorer.SmartContract.Solidity.PublisherWorker
```

### Type of the installation

Helm charts

### Type of the JSON RPC archive node

Polygon Edge

### Type of the chain

L2

### Backend version

v5.3.1

### Frontend version

latest

### Elixir & Erlang/OTP versions

We are using the Docker images

### Operating system

Linux

**Comment by vbaranov** [comment]
@refl3ction this is not publicly available endpoint
> MICROSERVICE_SC_VERIFIER_URL: http://smart-contract-verifier.blockscout.svc.cluster.local:8050

Please try setting:
https://github.com/blockscout/blockscout/blob/abce79ed493ed9e1fc187ef41e816b7d768f9a39/docker-compose/envs/common-blockscout.env#L219-L220

**Comment by refl3ction** [comment]
Hi @vbaranov, does it need to be public? I'm hosting the `smart-contract-verifier` service myself on Kubernetes.

**Comment by vbaranov** [comment]
> Hi @vbaranov, does it need to be public? I'm hosting the `smart-contract-verifier` service myself on Kubernetes.

No, it is not required. I thought initially, that you're using our local URL. Could you please check, if the problem persists with endpoint, I provided above?

**Comment by refl3ction** [comment]
@vbaranov let me check it and I'll get back to you as soon as I can.

**Comment by refl3ction** [comment]
@vbaranov got the same errors:

```log
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.283 application=api request_id=4c57f54d414e2632b58305c5d9020949 [info] /api?/&module=contract&action=getabi&address=0x4d2792f2f00d7c4bc5a9cc148bfe1d4ec829f20c
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.290 application=api request_id=4c57f54d414e2632b58305c5d9020949 [info] Sent 200 in 7ms
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.358 application=api request_id=9d608ae8c13623438d5a8b8fd56df74c [info] /api?/
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 warning: Supervisor.start_child/2 with a list of args is deprecated, please use DynamicSupervisor instead
blockscout-edge-blockscout-5d86cdc5f9-wfqp9   (elixir 1.14.5) lib/supervisor.ex:906: Supervisor.start_child/2
blockscout-edge-blockscout-5d86cdc5f9-wfqp9   (que 0.10.1) lib/que/server_supervisor.ex:48: Que.ServerSupervisor.add/2
blockscout-edge-blockscout-5d86cdc5f9-wfqp9   (block_scout_web 5.3.1) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:121: BlockScoutWeb.API.RPC.ContractController.verifysourcecode/2
blockscout-edge-blockscout-5d86cdc5f9-wfqp9   (block_scout_web 5.3.1) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.action/2
blockscout-edge-blockscout-5d86cdc5f9-wfqp9   (block_scout_web 5.3.1) lib/block_scout_web/controllers/api/rpc/contract_controller.ex:1: BlockScoutWeb.API.RPC.ContractController.phoenix_controller_pipeline/2
blockscout-edge-blockscout-5d86cdc5f9-wfqp9   (block_scout_web 5.3.1) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:119: BlockScoutWeb.API.RPC.RPCTranslator.call_controller/3
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.361 application=que [info] [Que] Spawning Server for worker: Explorer.SmartContract.Solidity.PublisherWorker
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.362 application=que [info] [Que] Queued new Job for Explorer.SmartContract.Solidity.PublisherWorker
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.362 application=que [info] [Que] Starting Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.362 application=api request_id=9d608ae8c13623438d5a8b8fd56df74c [info] Sent 200 in 3ms
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.438 application=api request_id=f4a3b8c904150ac696a1fb03efa24926 [info] /api?/
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.438 application=api request_id=f4a3b8c904150ac696a1fb03efa24926 [info] Sent 200 in 164µs
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:45.552 application=explorer [info] Smart-contract verification via standard json input started
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 2023-11-16T13:17:46.687 [error] Task #PID<0.31154.5> started from #PID<0.31151.5> terminating
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 ** (KeyError) key :bytes not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
blockscout-edge-blockscout-5d86cdc5f9-wfqp9     (explorer 5.3.1) lib/explorer/smart_contract/helper.ex:44: Explorer.SmartContract.Helper.add_contract_code_md5/1
blockscout-edge-blockscout-5d86cdc5f9-wfqp9     (explorer 5.3.1) lib/explorer/smart_contract/solidity/publisher.ex:214: Explorer.SmartContract.Solidity.Publisher.unverified_smart_contract/5
blockscout-edge-blockscout-5d86cdc5f9-wfqp9     (explorer 5.3.1) lib/explorer/smart_contract/solidity/publisher.ex:103: Explorer.SmartContract.Solidity.Publisher.publish_with_standard_json_input/2
blockscout-edge-blockscout-5d86cdc5f9-wfqp9     (explorer 5.3.1) lib/explorer/smart_contract/solidity/publisher_worker.ex:54: Explorer.SmartContract.Solidity.PublisherWorker.perform/1
blockscout-edge-blockscout-5d86cdc5f9-wfqp9     (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout-edge-blockscout-5d86cdc5f9-wfqp9     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
blockscout-edge-blockscout-5d86cdc5f9-wfqp9 Function: #Function<3.127712543/0 in Que.Job.perform/1>
blockscout-edge-blockscout-5d86cdc5f9-wfqp9     Args: []
```

**Comment by vbaranov** [comment]
@refl3ction do you have the link to the contract on the explorer, which you're trying to verify?

**Comment by refl3ction** [comment]
@vbaranov let me reach out internally to see if we can share it, if it's possible, in that case can I send the link to you via email?

**Comment by vbaranov** [comment]
Yes, please

**Comment by refl3ction** [comment]
@vbaranov just to keep you posted, I'm still working on your access to our instance.

**Comment by 0xtrou** [comment]
@refl3ction would you mind sharing the root cause then?

**Comment by refl3ction** [comment]
> @refl3ction would you mind sharing the root cause then?

I'm sorry, I can't recall exactly, but it was something with Foundry, because when we tried to verify the contract using the UI it worked. Are you having this issue? If so, try upgrading your foundry version.
