### ISSUE TITLE
gas_used can't be blank for successful call 

### ISSUE THREAD

**Issue by bulbazavr1024** [blockscout/blockscout#8844]
### Description

Hello @vbaranov! Thanks for your work. I run new blockscout backend service and get such problem
```
2023-11-16T09:15:03.588 fetcher=internal_transaction count=10 [error] Task #PID<0.13978.13> started from Indexer.Fetcher.InternalTransaction terminating
** (CaseClauseError) no case clause matching: {:error, [#Ecto.Changeset<action: nil, changes: %{block_number: 367677, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<23, 148, 227, 53, 27, 195, 12, 112, 90, 223, 233, 216, 127, 92, 224, 17, 250, 172, 37, 191>>}, gas: Decimal.new("921169"), index: 4, input: %Explorer.Chain.Data{bytes: <<103, 228, 172, 44>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<121, 163, 170, 220, 218, 169, 47, 206, 54, 192, 246, 206, 147, 133, 17, 197, 76, 76, 84, 120>>}, trace_address: [0, 1], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<105, 179, 156, 245, 123, 129, 117, 122, 127, 29, 150, 105, 249, 226, 21, 191, 33, 219, 183, 128, 142, 5, 158, 183, 172, 47, 21, 110, 170, 51, 74, 123>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {"can't be blank for successful call", [validation: :required]}, output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 367677, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<23, 148, 227, 53, 27, 195, 12, 112, 90, 223, 233, 216, 127, 92, 224, 17, 250, 172, 37, 191>>}, gas: Decimal.new("931216"), index: 2, input: %Explorer.Chain.Data{bytes: <<68, 147, 107, 16>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<121, 163, 170, 220, 218, 169, 47, 206, 54, 192, 246, 206, 147, 133, 17, 197, 76, 76, 84, 120>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<105, 179, 156, 245, 123, 129, 117, 122, 127, 29, 150, 105, 249, 226, 21, 191, 33, 219, 183, 128, 142, 5, 158, 183, 172, 47, 21, 110, 170, 51, 74, 123>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {"can't be blank for successful call", [validation: :required]}, output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 369268, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<146, 46, 241, 218, 62, 64, 243, 219, 110, 145, 177, 241, 38, 196, 49, 233, 121, 88, 70, 55>>}, gas: Decimal.new("18375612"), index: 2, input: %Explorer.Chain.Data{bytes: <<142, 82, 178, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 89, 69, 241, 223, 100, 95, 252, 193, 11, 188, 232, 63, 30, 108, 49, 131, 60, 28, 56, 8, ...>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<21, 89, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<176, 0, 105, 113, 40, 10, 160, 215, 77, 139, 243, 218, 36, 7, 179, 171, 60, 189, 87, 187, 212, 216, 134, 170, 62, 228, 197, 71, 94, 94, 68, 227>>}, transaction_index: 1, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {"can't be blank for successful call", [validation: :required]}, output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 472051, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<91, 202, 19, 204, 184, 196, 33, 78, 243, 118, 139, 39, 187, 191, 133, 88, 114, 17, 241, 40>>}, gas: Decimal.new("926174"), index: 1, input: %Explorer.Chain.Data{bytes: <<85, 198, 118, 40>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<32, 99, 246, 116, 82, 29, 125, 239, 20, 52, 176, 160, 60, 167, 107, 243, 105, 224, 145, 238>>}, trace_address: [0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<195, 90, 117, 112, 151, 130, 5, 229, 175, 33, 200, 224, 132, 156, 169, 119, 167, 19, 12, 157, 173, 21, 88, 177, 21, 223, 7, 73, 234, 161, 125, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {"can't be blank for successful call", [validation: :required]}, output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 473032, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<91, 202, 19, 204, 184, 196, 33, 78, 243, 118, 139, 39, 187, 191, 133, 88, 114, 17, 241, 40>>}, gas: Decimal.new("931385"), index: 1, input: %Explorer.Chain.Data{bytes: <<85, 198, 118, 40>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<32, 99, 246, 116, 82, 29, 125, 239, 20, 52, 176, 160, 60, 167, 107, 243, 105, 224, 145, 238>>}, trace_address: [0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<100, 149, 184, 0, 219, 104, 176, 103, 121, 237, 12, 228, 141, 64, 93, 76, 250, 177, 177, 156, 25, 202, 251, 6, 75, 171, 22, 209, 121, 102, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [gas_used: {"can't be blank for successful call", [validation: :required]}, output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>]}
    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:260: Indexer.Fetcher.InternalTransaction.import_internal_transaction/2
    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:224: Indexer.Fetcher.InternalTransaction.safe_import_internal_transaction/2
    (indexer 5.3.1) lib/indexer/fetcher/internal_transaction.ex:128: Indexer.Fetcher.InternalTransaction.run/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [513120, 513159, 472051, 369268, 473032, 512944, 513143, 513102, 513153, 367677], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://104.236.1.104:8545/", fallback_url: nil, fallback_trace_url: nil, method_to_url: [debug_traceTransaction: "http://104.236.1.104:8545/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]
```
I use https://github.com/blockscout/blockscout/commit/13e9ccec3804d4d618cfc0402fdbe715afc85165 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

http://164.92.137.42/

### Backend version

v5.3.1-beta

### Frontend version

v1.17.0

### Elixir & Erlang/OTP versions

docker-compose

### Operating system

Ubuntu 22.04

**Comment by sl1depengwyn** [comment]
Related to https://github.com/blockscout/blockscout/issues/8751, @Qwerty5Uiop please take a look
Trace for this case:
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "calls": [
            {
                "calls": [
                    {
                        "calls": [
                            {
                                "from": "0x79a3aadcdaa92fce36c0f6ce938511c54c4c5478",
                                "gas": "0xde0c1",
                                "gasUsed": "0x943",
                                "input": "0x44936b10",
                                "output": "0x0000000000000000000000000000000000000000000000001158e460913d0000",
                                "to": "0xdc9e45eb34d57d27398cf5869c02c7b3fe473775",
                                "type": "DELEGATECALL"
                            }
                        ],
                        "from": "0x1794e3351bc30c705adfe9d87f5ce011faac25bf",
                        "gas": "0xe3590",
                        "gasUsed": "0x25d7",
                        "input": "0x44936b10",
                        "output": "0x0000000000000000000000000000000000000000000000001158e460913d0000",
                        "to": "0x79a3aadcdaa92fce36c0f6ce938511c54c4c5478",
                        "type": "STATICCALL"
                    },
                    {
                        "calls": [
                            {
                                "from": "0x79a3aadcdaa92fce36c0f6ce938511c54c4c5478",
                                "gas": "0xdd31d",
                                "gasUsed": "0x74c9",
                                "input": "0x67e4ac2c",
                                "output": "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000f9e259094696b79fdc5cf7aaf55223e0f8b62cd7000000000000000000000000b36639cd957dd3eb4cdbdbd157d086ea3f01c96300000000000000000000000068ac461fd5e4e9c6849bdec4d036fee9a29d26ea00000000000000000000000067568e3c12ddb13fc17a5af5fda28b3c263ebd9700000000000000000000000091b09d42242efce311ee6205e92dea549407bde1000000000000000000000000bec71b97dea6192ea7ea870630c0e12c8f44297f000000000000000000000000656beebe0adc0512bbed20a622b3ea608b239dab000000000000000000000000258146a085d174d6f5ed22c420307d5411766d99000000000000000000000000b14ba062860a5aac6a4b195dc1006a1dd1d90d00000000000000000000000000562e1373b54bd2370db0589d3848cc466108622a0000000000000000000000008d5a89adbc52d741c5c374122b540a490085cf26000000000000000000000000e9d0be970d20fe82f47dbd4d577cf9bb7f515e62",
                                "to": "0xdc9e45eb34d57d27398cf5869c02c7b3fe473775",
                                "type": "DELEGATECALL"
                            }
                        ],
                        "from": "0x1794e3351bc30c705adfe9d87f5ce011faac25bf",
                        "gas": "0xe0e51",
                        "gasUsed": "0x7841",
                        "input": "0x67e4ac2c",
                        "output": "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000f9e259094696b79fdc5cf7aaf55223e0f8b62cd7000000000000000000000000b36639cd957dd3eb4cdbdbd157d086ea3f01c96300000000000000000000000068ac461fd5e4e9c6849bdec4d036fee9a29d26ea00000000000000000000000067568e3c12ddb13fc17a5af5fda28b3c263ebd9700000000000000000000000091b09d42242efce311ee6205e92dea549407bde1000000000000000000000000bec71b97dea6192ea7ea870630c0e12c8f44297f000000000000000000000000656beebe0adc0512bbed20a622b3ea608b239dab000000000000000000000000258146a085d174d6f5ed22c420307d5411766d99000000000000000000000000b14ba062860a5aac6a4b195dc1006a1dd1d90d00000000000000000000000000562e1373b54bd2370db0589d3848cc466108622a0000000000000000000000008d5a89adbc52d741c5c374122b540a490085cf26000000000000000000000000e9d0be970d20fe82f47dbd4d577cf9bb7f515e62",
                        "to": "0x79a3aadcdaa92fce36c0f6ce938511c54c4c5478",
                        "type": "STATICCALL"
                    },
                    {
                        "calls": [
                            {
                                "calls": [
                                    {
                                        "error": "execution reverted",
                                        "from": "0xf61eb2dd88904aaad22ad8ff7dbcd931d3508213",
                                        "gas": "0xcdff4",
                                        "gasUsed": "0xa74",
                                        "input": "0x41976e09000000000000000000000000f9e259094696b79fdc5cf7aaf55223e0f8b62cd7",
                                        "to": "0xcfd1bff1b5a4cad5c278d101a3b75fcbe36c220a",
                                        "type": "STATICCALL"
                                    }
                                ],
                                "error": "execution reverted",
                                "from": "0xf61eb2dd88904aaad22ad8ff7dbcd931d3508213",
                                "gas": "0xd2888",
                                "gasUsed": "0x1ee0",
                                "input": "0xace1798e000000000000000000000000f9e259094696b79fdc5cf7aaf55223e0f8b62cd7",
                                "to": "0x3ef0a84aabef525e87627c60e60aacf412c37323",
                                "type": "DELEGATECALL"
                            }
                        ],
                        "error": "execution reverted",
                        "from": "0x1794e3351bc30c705adfe9d87f5ce011faac25bf",
                        "gas": "0xd7a6d",
                        "gasUsed": "0x3b78",
                        "input": "0xace1798e000000000000000000000000f9e259094696b79fdc5cf7aaf55223e0f8b62cd7",
                        "to": "0xf61eb2dd88904aaad22ad8ff7dbcd931d3508213",
                        "type": "CALL",
                        "value": "0x0"
                    }
                ],
                "error": "execution reverted",
                "from": "0x1794e3351bc30c705adfe9d87f5ce011faac25bf",
                "gas": "0xe976c",
                "gasUsed": "0x121dc",
                "input": "0x2e54bf950000000000000000000000000000000000000000000000056bc75e2d63100000",
                "to": "0x3ceb2e953a7da62c5b99f150662f2b8ff47a8476",
                "type": "DELEGATECALL"
            }
        ],
        "error": "execution reverted",
        "from": "0x3da6bcdceba9b420ede89ee62c27cab712d5217c",
        "gas": "0xeef24",
        "gasUsed": "0x13e74",
        "input": "0x2e54bf950000000000000000000000000000000000000000000000056bc75e2d63100000",
        "output": "0xa29c4986",
        "to": "0x1794e3351bc30c705adfe9d87f5ce011faac25bf",
        "type": "CALL",
        "value": "0x0"
    }
}
```

**Comment by bulbazavr1024** [comment]
@sl1depengwyn Thanks for your attention

**Comment by sl1depengwyn** [comment]
@bulbazavr1024 I could not reproduce the issue using the master branch, try to pull updates from master

**Comment by bulbazavr1024** [comment]
@sl1depengwyn Thanks, I will do it about 2 hours. After that I will inform you about the result

**Comment by bulbazavr1024** [comment]
@sl1depengwyn I've just try to deploy the last commit from main branch https://github.com/blockscout/blockscout/commit/f268c1cd933f8fc3245bcbb2b9cdd8b47981bae8
and get such problems 
```
55.18 ==> indexer
55.18 Compiling 76 files (.ex)
68.49 Generated indexer app
69.00 ==> block_scout_web
69.00 Compiling 284 files (.ex)
75.85 Generating BlockScoutWeb.Cldr for 2 locales named [:en, :und] with a default locale named :en
89.03 Compiling lib/block_scout_web/cldr.ex (it's taking more than 10s)
116.5 warning: unused alias AccessHelper
116.5   lib/block_scout_web/views/address_coin_balance_view.ex:4
116.5 
131.0 
131.0 == Compilation error in file lib/block_scout_web/views/layout_view.ex ==
131.0 ** (EEx.SyntaxError) lib/block_scout_web/templates/layout/app.html.eex:84:7: unexpected end of expression <% end %>
131.0     (eex 1.14.5) lib/eex/compiler.ex:398: EEx.Compiler.generate_buffer/4
131.0     (phoenix 1.5.14) lib/phoenix/template.ex:352: Phoenix.Template.compile/3
131.0     (phoenix 1.5.14) lib/phoenix/template.ex:167: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
131.0     (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
131.0     (phoenix 1.5.14) expanding macro: Phoenix.Template.__before_compile__/1
131.0     lib/block_scout_web/views/layout_view.ex:1: BlockScoutWeb.LayoutView (module)
------
failed to solve: process "/bin/sh -c mix compile && npm install npm@latest" did not complete successfully: exit code: 1
```

**Comment by bulbazavr1024** [comment]
@sl1depengwyn Can you take a look please ?

**Comment by bulbazavr1024** [comment]
@sl1depengwyn I've solved my all issues. I try to exec **latest** build of backend service, which hasn't your fixes 
https://hub.docker.com/layers/blockscout/blockscout/latest/images/sha256-709d840a162f840f9801863e4e34e4de852751d96e45dfd13837cbe4a5090edf?context=explore
Now I'm trying to use https://hub.docker.com/layers/blockscout/blockscout/5.3.1.commit.73ca07f7/images/sha256-8bf9412ec9b7680be43878d7ed1adad79e1712a17006491d315afac3d59d2d62?context=explore and it works fine! Thank you for help !
