### ISSUE TITLE
ETC: error in process_forked_token_transfers

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8948]
### Description

```
  | {"time":"2024-03-13T06:49:34.349Z","severity":"error","message":"Task #PID<0.31876.518> started from Indexer.Fetcher.UncleBlock terminating\n** (FunctionClauseError) no function clause matching in anonymous fn/1 in Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (explorer 6.2.2) anonymous fn(nil) in Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (elixir 1.14.5) lib/enum.ex:4049: anonymous fn/2 in Enum.aggregate_by/4\n    (elixir 1.14.5) lib/enum.ex:4067: Enum.aggregate_by/4\n    (explorer 6.2.2) lib/explorer/chain/import/runner/blocks.ex:706: anonymous fn/2 in Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.2.2) lib/explorer/chain/import/runner/blocks.ex:691: Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (explorer 6.2.2) lib/explorer/prometheus/instrumenter.ex:17: Explorer.Prometheus.Instrumenter.block_import_stage_runner/4\nFunction: &Indexer.BufferedTask.log_run/1\n    Args: [%{batch: [{<<3, 58, 97, 161, 175, 158, 191, 137, 26, 13, 10, 19, 84, 191, 223, 173, 165, 153, 78, 1, 92, 55, 200, 241, 116, 155, 6, 0, 33, 69, 42, 19>>, 0}, {<<10, 206, 28, 148, 71, 98, 168, 75, 250, 35, 195, 36, 88, 54, 12, 183, 115, 109, 71, 254, 45, 144, 54, 154, 180, 101, 176, 11, 129, 173, 250, 89>>, 0}, {<<12, 56, 167, 223, 9, 138, 134, 247, 223, 127, 138, 122, 237, 176, 177, 123, 248, 85, 79, 110, 60, 4, 18, 148, 69, 155, 249, 124, 39, 187, 24, 1>>, 0}, {<<15, 102, 162, 191, 112, 96, 236, 204, 39, 163, 169, 209, 161, 238, 115, 13, 2, 48, 157, 67, 248, 8, 246, 169, 242, 95, 214, 204, 137, 171, 203, 254>>, 0}, {<<34, 223, 37, 42, 117, 238, 107, 54, 7, 248, 180, 188, 18, 33, 134, 21, 74, 0, 252, 121, 231, 51, 203, 211, 76, 15, 68, 163, 172, 216, 153, 230>>, 0}, {<<36, 152, 203, 23, 23, 219, 83, 185, 220, 162, 16, 104, 248, 14, 221, 29, 247, 122, 140, 27, 198, 19, 55, 196, 50, 168, 44, 201, 61, 51, 1, 168>>, 0}, {<<39, 188, 136, 219, 133, 252, 187, 227, 232, 67, 129, 251, 29, 114, 163, 21, 178, 15, 5, 79, 132, 69, 147, 203, 2, 90, 44, 186, 46, 59, 219, 93>>, 0}, {<<56, 86, 65, 185, 196, 87, 102, 45, 217, 78, 85, 17, 92, 210, 59, 1, 104, 169, 148, 180, 106, 211, 243, 172, 198, 98, 97, 145, 50, 100, 95, 193>>, 0}, {<<57, 123, 112, 166, 51, 252, 112, 35, 185, 16, 205, 213, 139, 204, 11, 181, 149, 191, 164, 43, 179, 0, 42, 36, 199, 28, 116, 158, 69, 76, 107, 127>>, 0}, {<<57, 198, 12, 123, 90, 34, 90, 21, 69, 189, 107, 91, 109, 157, 174, 164, 126, 104, 227, 207, 212, 0, 129, 129, 121, 69, 204, 37, 157, 234, 55, 226>>, 0}], callback_module: Indexer.Fetcher.UncleBlock, callback_module_state: %Indexer.Block.Fetcher{broadcast: :uncle, callback_module: Indexer.Fetcher.UncleBlock, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"***\", fallback_url: \"***\", fallback_trace_url: \"***\", method_to_url: [eth_call: \"***\", debug_traceTransaction: \"***\", debug_traceBlockByNumber: \"***\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, metadata: [fetcher: :block_uncle]}]","metadata":{"count":10,"error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in anonymous fn/1 in Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (explorer 6.2.2) anonymous fn(nil) in Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (elixir 1.14.5) lib/enum.ex:4049: anonymous fn/2 in Enum.aggregate_by/4\n    (elixir 1.14.5) lib/enum.ex:4067: Enum.aggregate_by/4\n    (explorer 6.2.2) lib/explorer/chain/import/runner/blocks.ex:706: anonymous fn/2 in Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.2.2) lib/explorer/chain/import/runner/blocks.ex:691: Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (explorer 6.2.2) lib/explorer/prometheus/instrumenter.ex:17: Explorer.Prometheus.Instrumenter.block_import_stage_runner/4\n"},"fetcher":"block_uncle"}} |  
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Link to the page

https://etc.blockscout.com/

### Backend version

v5.3.2

### Elixir & Erlang/OTP versions

Elixir 1.14.5

**Comment by vbaranov** [comment]
The issue resolved by https://github.com/blockscout/blockscout/pull/10285 and re-fetching of affected ranges of the blocks.

**Comment by vbaranov** [comment]
The issue is reproducible at Rootstock instance.
