### ISSUE TITLE
Gnosis chain: no function clause matching in List.first in Explorer.Account.Notifier.Summary.fetch_summary/2

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8950]
```
{"time":"2023-12-05T18:03:06.992Z","severity":"info","message":"** (FunctionClauseError) no function clause matching in List.first/2\n    (elixir 1.14.5) lib/list.ex:293: List.first(nil, nil)\n    (explorer 5.3.2) lib/explorer/account/notifier/summary.ex:135: Explorer.Account.Notifier.Summary.fetch_summary/2\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (explorer 5.3.2) lib/explorer/account/notifier/summary.ex:30: Explorer.Account.Notifier.Summary.process/1\n    (explorer 5.3.2) lib/explorer/account/notifier/notify.ex:35: Explorer.Account.Notifier.Notify.process/1\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (explorer 5.3.2) lib/explorer/account/notify.ex:18: Explorer.Account.Notify.process/1\n","metadata":{"fetcher":"account"}}
```

**Comment by vbaranov** [comment]
Issue is gone.
