### ISSUE TITLE
Shibarium mainnet: /api/v2/search/check-redirect?q=%5C\n** (exit) an exception was raised

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8951]
```
{"time":"2023-12-05T19:14:48.786Z","severity":"error","message":"#PID<0.17928.178> running BlockScoutWeb.Endpoint (connection #PID<0.3430.178>, stream id 4) terminated\nServer: www.shibariumscan.io:80 (http)\nRequest: GET /api/v2/search/check-redirect?q=%5C\n** (exit) an exception was raised:\n    ** (Postgrex.Error) ERROR 22025 (invalid_escape_sequence) LIKE pattern must not end with escape character\n        (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n        (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6\n        (ecto 3.11.0) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4\n        (ecto 3.11.0) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\n        (explorer 5.3.2) lib/explorer/chain.ex:1353: Explorer.Chain.token_contract_address_from_token_name/1\n        (block_scout_web 5.3.2) lib/block_scout_web/chain.ex:470: BlockScoutWeb.Chain.token_address_from_name/1\n        (block_scout_web 5.3.2) lib/block_scout_web/controllers/api/v2/search_controller.ex:32: BlockScoutWeb.API.V2.SearchController.check_redirect/2\n        (block_scout_web 5.3.2) lib/block_scout_web/controllers/api/v2/search_controller.ex:1: BlockScoutWeb.API.V2.SearchController.action/2","metadata":{"error":{"initial_call":null,"reason":"** (Postgrex.Error) ERROR 22025 (invalid_escape_sequence) LIKE pattern must not end with escape character\n    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6\n    (ecto 3.11.0) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4\n    (ecto 3.11.0) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\n    (explorer 5.3.2) lib/explorer/chain.ex:1353: Explorer.Chain.token_contract_address_from_token_name/1\n    (block_scout_web 5.3.2) lib/block_scout_web/chain.ex:470: BlockScoutWeb.Chain.token_address_from_name/1\n    (block_scout_web 5.3.2) lib/block_scout_web/controllers/api/v2/search_controller.ex:32: BlockScoutWeb.API.V2.SearchController.check_redirect/2\n    (block_scout_web 5.3.2) lib/block_scout_web/controllers/api/v2/search_controller.ex:1: BlockScoutWeb.API.V2.SearchController.action/2\n"}}}
```

**Comment by vbaranov** [comment]
Issue is not reproducible anymore.
