### ISSUE TITLE
Shibarium Mainnet: (ArgumentError) errors were found at the given arguments:\n\n  * 1st argument: the table identifier does not refer to an existing ETS table

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8952]
```
{"time":"2023-12-05T20:57:16.596Z","severity":"error","message":"Ranch protocol #PID<0.31214.36> of listener BlockScoutWeb.Endpoint.HTTP (connection #PID<0.13009.36>, stream id 7) terminated\nan exception was raised:\n    ** (ArgumentError) errors were found at the given arguments:\n\n  * 1st argument: the table identifier does not refer to an existing ETS table\n\n        (stdlib 3.17) :ets.insert(:addresses_tabs_counters, {{\"0x55701a8a8f3bb87db53b38a9e27df23e85d024ab\", :validations}, {~U[2023-12-05 20:57:16.595200Z], 0}})\n        (explorer 5.3.2) lib/explorer/chain/cache/addresses_tabs_counters.ex:24: Explorer.Chain.Cache.AddressesTabsCounters.set_counter/4\n        (explorer 5.3.2) lib/explorer/chain/address/counters.ex:544: anonymous fn/5 in Explorer.Chain.Address.Counters.configure_task/5\n        (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n        (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n        (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3","metadata":{"error":{"initial_call":null,"reason":":badarg"}}}
```

**Comment by vbaranov** [comment]
@nikitosing the similar flaky test is in the web tests time to time:
```
  1) test /addresses/{address_hash}/tabs-counters check counters cache ttl (BlockScoutWeb.API.V2.AddressControllerTest)
Error:      test/block_scout_web/controllers/api/v2/address_controller_test.exs:2074
     ** (EXIT from #PID<0.18008.0>) an exception was raised:
         ** (ArgumentError) errors were found at the given arguments:
     
       * 1st argument: the table identifier does not refer to an existing ETS table
     
             (stdlib 4.3.1.3) :ets.delete(:addresses_tabs_counters, {:task, "0x000000000000000000000000000000000000dcb1", :txs_contract})
             (explorer 6.0.0) lib/explorer/chain/cache/addresses_tabs_counters.ex:37: Explorer.Chain.Cache.AddressesTabsCounters.drop_task/2
             (explorer 6.0.0) lib/explorer/chain/address/counters.ex:417: anonymous fn/3 in Explorer.Chain.Address.Counters.address_limited_counters/2
             (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
             (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
             (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
