### ISSUE TITLE
ETH Mainnet: TokenBalanceOnDemand no match of right hand side value: {:ok, %{}}

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8953]
```
{"time":"2023-12-05T20:51:45.971Z","severity":"error","message":"Task #PID<0.25315.3038> started from #PID<0.27698.3039> terminating\n** (MatchError) no match of right hand side value: {:ok, %{}}\n    (indexer 5.3.1) lib/indexer/fetcher/token_balance_on_demand.ex:127: Indexer.Fetcher.TokenBalanceOnDemand.fetch_and_update/3\n    (indexer 5.3.1) lib/indexer/fetcher/token_balance_on_demand.ex:58: Indexer.Fetcher.TokenBalanceOnDemand.do_trigger_fetch/3\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nFunction: #Function<2.94382677/0 in BlockScoutWeb.API.V2.AddressController.tokens/2>\n    Args: []","metadata":{"error":{"initial_call":null,"reason":"** (MatchError) no match of right hand side value: {:ok, %{}}\n    (indexer 5.3.1) lib/indexer/fetcher/token_balance_on_demand.ex:127: Indexer.Fetcher.TokenBalanceOnDemand.fetch_and_update/3\n    (indexer 5.3.1) lib/indexer/fetcher/token_balance_on_demand.ex:58: Indexer.Fetcher.TokenBalanceOnDemand.do_trigger_fetch/3\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"}}}
```

**Comment by vbaranov** [comment]
Duplicate of #8817
