### ISSUE TITLE
Sourcify (CaseClauseError) no case clause matching...

### ISSUE THREAD

**Issue by bretep** [blockscout/blockscout#9001]
### Description

Sourcify may be returning a new response that is not matched.
```log
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:ok, [%{\"address\" => \"0x7bFD406632483ad00c6EdF655E04De91A96f84bc\", \"chainIds\" => [\"369\"], \"status\" => \"perfect\"}]}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Link to the page

https://scan.mypinata.cloud/ipfs/bafybeidn64pd2u525lmoipjl4nh3ooa2imd7huionjsdepdsphl5slfowy/#/address/0x7bFD406632483ad00c6EdF655E04De91A96f84bc?tab=contract

### Steps to reproduce

1. Ensure sourcify is setup for your chain.
    (PulseChain 369) https://docs.sourcify.dev/docs/chains/
2. Ensure `SOURCIFY_INTEGRATION_ENABLED=true`
3. Navigate to contract tab for a supported contract.
    https://scan.mypinata.cloud/ipfs/bafybeidn64pd2u525lmoipjl4nh3ooa2imd7huionjsdepdsphl5slfowy/#/address/0x7bFD406632483ad00c6EdF655E04De91A96f84bc?tab=contract
4. Check backend server logs
```log
{"time":"2023-12-13T17:46:00.137Z","severity":"info","message":"Sent 500 in 411ms on GET /api/v2/smart-contracts/0x7bFD406632483ad00c6EdF655E04De91A96f84bc?","metadata":{"duration":411377,"endpoint":"/api/v2/smart-contracts/0x7bFD406632483ad00c6EdF655E04De91A96f84bc?","method":"GET","request_id":"F6B1PAFFUH67ewgAAY6C","status":"500","unit":"microsecond"}}
{"time":"2023-12-13T17:46:00.137Z","severity":"error","message":"#PID<0.24003.0> running BlockScoutWeb.Endpoint (connection #PID<0.23519.0>, stream id 10) terminated
Server: api.scan.pulsechain.com:80 (http)
Request: GET /api/v2/smart-contracts/0x7bFD406632483ad00c6EdF655E04De91A96f84bc
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:ok, [%{\"address\" => \"0x7bFD406632483ad00c6EdF655E04De91A96f84bc\", \"chainIds\" => [\"369\"], \"status\" => \"perfect\"}]}
        (explorer 5.3.3) lib/explorer/third_party_integrations/sourcify.ex:19: Explorer.ThirdPartyIntegrations.Sourcify.check_by_address/1
        (explorer 5.3.3) lib/explorer/smart_contract/solidity/publish_helper.ex:186: Explorer.SmartContract.Solidity.PublishHelper.check_by_address_in_sourcify/2
        (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:36: BlockScoutWeb.API.V2.SmartContractController.smart_contract/2
        (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.action/2
        (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2","metadata":{"error":{"initial_call":null,"reason":"** (CaseClauseError) no case clause matching: {:ok, [%{\"address\" => \"0x7bFD406632483ad00c6EdF655E04De91A96f84bc\", \"chainIds\" => [\"369\"], \"status\" => \"perfect\"}]}
    (explorer 5.3.3) lib/explorer/third_party_integrations/sourcify.ex:19: Explorer.ThirdPartyIntegrations.Sourcify.check_by_address/1
    (explorer 5.3.3) lib/explorer/smart_contract/solidity/publish_helper.ex:186: Explorer.SmartContract.Solidity.PublishHelper.check_by_address_in_sourcify/2
    (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:36: BlockScoutWeb.API.V2.SmartContractController.smart_contract/2
    (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.action/2
    (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.phoenix_controller_pipeline/2
    (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
    (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
    (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
    "}}}
```

### Backend version

v5.3.3

### Frontend version

v1.19.0

### Elixir & Erlang/OTP versions

Erlang/OTP 24

### Operating system

Linux

**Comment by bretep** [comment]
Any update on this. I know that it's the holiday season, just don't want this to get lost. :)

**Comment by vbaranov** [comment]
@nikitosing could you please check do we have this unhandled in master branch?

**Comment by dreadedhamish** [comment]
@vbarabov @nikitosing any movement on this? I've just made a not-insignificant effort to verify over 100K contracts on Pulsechain using sourcify, and they aren't being recognised in Blockscout.

**Comment by dreadedhamish** [comment]
I'm not 100% of this behaviour, but it looks like once it hits sourcify in the lookup heirachy, if it is verified it will throw the error. On the frontend the error is "Something went wrong. Try refreshing the page or come back later." - this takes over the whole Contract tab, so you can't see the opcode etc... or verify using any other method.

**Comment by bretep** [comment]
@nikitosing would love to get this handled. 

Not sure why hardhat is linked to this issue as it doesn't relate to the unhandled sourcify response.

**Comment by dreadedhamish** [comment]
10 months later...

**Comment by nikitosing** [comment]
is the issue reproducible on the latest backend version (6.8.1)?

**Comment by dreadedhamish** [comment]
> is the issue reproducible on the latest backend version (6.8.1)?

I assume so - the code to handle the response (sourcify.ex:252) hasn't changed at all.

**Comment by dreadedhamish** [comment]
missed it by a few days... but Happy Birthday github bug!

**Comment by dreadedhamish** [comment]
This issue is now over 1 year old. Can it not be resolved? It's quite serious - any contract that is verified on Sourcify but not Blockscout gets a totally blank and broken Contract tab.

**Comment by RaMurd-Crypto** [comment]
At-least - is there a workaround or any way to force verify on blockscout to overcome this error?

**Comment by 0xWhankFrite** [comment]
bump

**Comment by dreadedhamish** [comment]
13 months.

**Comment by vbaranov** [comment]
The issue is not reproducible with the latest release. You must update Blockscout's backend and frontend according to the latest releases.

Latest backend release https://github.com/blockscout/blockscout/releases/tag/v6.10.2.
Compatibility matrix between backend and frontend https://docs.blockscout.com/setup/requirements/back-front-compatibility-matrix.
