### ISSUE TITLE
Indexer.Fetcher.TokenInstance.Retry terminating

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#9011]
### Description

```
{"time":"2023-12-16T06:50:40.131Z","severity":"error","message":"Task #PID<0.2324.4> started from Indexer.Fetcher.TokenInstance.Retry terminating\n** (Postgrex.Error) ERROR 22P05 (untranslatable_character) unsupported Unicode escape sequence\n\n\\u0000 cannot be converted to text.\n    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto 3.11.0) lib/ecto/repo/schema.ex:775: Ecto.Repo.Schema.apply/4\n    (ecto 3.11.0) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 5.3.3) lib/indexer/fetcher/token_instance/retry.ex:52: Indexer.Fetcher.TokenInstance.Retry.run/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nFunction: &Indexer.BufferedTask.log_run/1\n    Args: [%{batch: [%{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<177, 100, 78, 11, 84, 190, 127, 195, 4, 231, 232, 146, 170, 167, 217, 98, 60, 6, 120, 201>>}, token_id: Decimal.new(\"111556622216125215405529543972979284731219262371476563149063324848414684982658\"), updated_at: ~U[2023-12-15 08:13:50.781008Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<98, 105, 140, 173, 89, 193, 63, 165, 247, 208, 165, 139, 255, 154, 89, 207, 112, 229, 72, 151>>}, token_id: Decimal.new(\"572749\"), updated_at: ~U[2023-12-15 08:11:08.575012Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<98, 105, 140, 173, 89, 193, 63, 165, 247, 208, 165, 139, 255, 154, 89, 207, 112, 229, 72, 151>>}, token_id: Decimal.new(\"537146\"), updated_at: ~U[2023-12-15 16:09:48.337702Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<188, 254, 254, 161, 232, 48, 96, 219, 206, 242, 237, 5, 19, 117, 93, 4, 159, 222, 149, 44>>}, token_id: Decimal.new(\"86790\"), updated_at: ~U[2023-12-12 15:32:00.284413Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<98, 105, 140, 173, 89, 193, 63, 165, 247, 208, 165, 139, 255, 154, 89, 207, 112, 229, 72, 151>>}, token_id: Decimal.new(\"298063\"), updated_at: ~U[2023-12-15 20:25:54.092625Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<98, 105, 140, 173, 89, 193, 63, 165, 247, 208, 165, 139, 255, 154, 89, 207, 112, 229, 72, 151>>}, token_id: Decimal.new(\"434278\"), updated_at: ~U[2023-12-15 18:51:07.865125Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<175, 177, 160, 200, 28, 132, 138, 213, 48, 118, 106, 212, 190, 47, 221, 220, 131, 62, 30, 150>>}, token_id: Decimal.new(\"45794503015933119568247566440025793907585212753987692779699093565633429198789\"), updated_at: ~U[2023-12-15 16:40:40.355591Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<98, 105, 140, 173, 89, 193, 63, 165, 247, 208, 165, 139, 255, 154, 89, 207, 112, 229, 72, 151>>}, token_id: Decimal.new(\"595295\"), updated_at: ~U[2023-12-15 18:51:08.259241Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<98, 105, 140, 173, 89, 193, 63, 165, 247, 208, 165, 139, 255, 154, 89, 207, 112, 229, 72, 151>>}, token_id: Decimal.new(\"197695\"), updated_at: ~U[2023-12-15 18:37:07.543723Z]}, %{contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<98, 105, 140, 173, 89, 193, 63, 165, 247, 208, 165, 139, 255, 154, 89, 207, 112, 229, 72, 151>>}, token_id: Decimal.new(\"548657\"), updated_at: ~U[2023-12-15 18:37:08.138740Z]}], callback_module: Indexer.Fetcher.TokenInstance.Retry, callback_module_state: [], metadata: []}]","metadata":{"error":{"initial_call":null,"reason":"** (Postgrex.Error) ERROR 22P05 (untranslatable_character) unsupported Unicode escape sequence\n\n\\u0000 cannot be converted to text.\n    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto 3.11.0) lib/ecto/repo/schema.ex:775: Ecto.Repo.Schema.apply/4\n    (ecto 3.11.0) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 5.3.3) lib/indexer/fetcher/token_instance/retry.ex:52: Indexer.Fetcher.TokenInstance.Retry.run/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"}}}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Nethermind

### Link to the page

https://gnosis.blockscout.com/

### Backend version

v5.3.3

### Elixir & Erlang/OTP versions

Elixir 1.14.5

**Comment by vbaranov** [comment]
Duplicate of https://github.com/blockscout/blockscout/issues/8385
