### ISSUE TITLE
indexing polygon_edge got a bunch of error

### ISSUE THREAD

**Issue by haidarabdillah** [blockscout/blockscout#9042]
### Description

got a bunch of error on indexing polygon edge, any  .env setting/option to solve this? 

```
2023-12-22 00:23:11 {"time":"2023-12-21T17:23:11.392Z","severity":"error","message":"Task #PID<0.10357.0> started from Indexer.Block.Realtime.Fetcher terminating\n** (MatchError) no match of right hand side value: {:error, :invalid_recovery_id}\n    (indexer 5.3.3) lib/indexer/transform/blocks.ex:96: Indexer.Transform.Blocks.recover_pub_key/2\n    (indexer 5.3.3) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 5.3.3) lib/indexer/block/fetcher.ex:139: Indexer.Block.Fetcher.fetch_and_import_range/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:316: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3\n    (indexer 5.3.3) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:286: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4\nFunction: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3\n    Args: [8290791, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"https://xxxxx.tech\", fallback_url: nil, fallback_trace_url: nil, method_to_url: [debug_traceTransaction: \"https://xxxx.tech\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]","metadata":{"error":{"initial_call":null,"reason":"** (MatchError) no match of right hand side value: {:error, :invalid_recovery_id}\n    (indexer 5.3.3) lib/indexer/transform/blocks.ex:96: Indexer.Transform.Blocks.recover_pub_key/2\n    (indexer 5.3.3) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 5.3.3) lib/indexer/block/fetcher.ex:139: Indexer.Block.Fetcher.fetch_and_import_range/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:316: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3\n    (indexer 5.3.3) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:286: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4\n"}}}
2023-12-22 00:23:11 {"time":"2023-12-21T17:23:11.422Z","severity":"error","message":"** (MatchError) no match of right hand side value: {:error, :invalid_recovery_id}\n    (indexer 5.3.3) lib/indexer/transform/blocks.ex:96: Indexer.Transform.Blocks.recover_pub_key/2\n    (indexer 5.3.3) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 5.3.3) lib/indexer/block/fetcher.ex:139: Indexer.Block.Fetcher.fetch_and_import_range/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 5.3.3) lib/indexer/block/catchup/fetcher.ex:195: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","first_block_number":8274594,"last_block_number":8274585}}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Backend version

V5.3.3

### Elixir & Erlang/OTP versions

1.14

**Comment by haidarabdillah** [comment]
`
2023-12-22 12:01:55 {"time":"2023-12-22T05:01:55.664Z","severity":"error","message":"Task #PID<0.28892.0> started from Indexer.Block.Realtime.Fetcher terminating\n** (MatchError) no match of right hand side value: {:error, :timeout}\n    (ethereum_jsonrpc 5.3.3) lib/ethereum_jsonrpc.ex:192: EthereumJSONRPC.fetch_balances/3\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:442: Indexer.Block.Realtime.Fetcher.balances/2\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:211: Indexer.Block.Realtime.Fetcher.import/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 5.3.3) lib/indexer/block/fetcher.ex:280: Indexer.Block.Fetcher.import/2\n    (indexer 5.3.3) lib/indexer/block/fetcher.ex:207: Indexer.Block.Fetcher.fetch_and_import_range/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:316: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3\nFunction: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3\n    Args: [8311692, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"https://xxx\", fallback_url: nil, fallback_trace_url: nil, method_to_url: [debug_traceTransaction: \"https://xxx\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]","metadata":{"error":{"initial_call":null,"reason":"** (MatchError) no match of right hand side value: {:error, :timeout}\n    (ethereum_jsonrpc 5.3.3) lib/ethereum_jsonrpc.ex:192: EthereumJSONRPC.fetch_balances/3\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:442: Indexer.Block.Realtime.Fetcher.balances/2\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:211: Indexer.Block.Realtime.Fetcher.import/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 5.3.3) lib/indexer/block/fetcher.ex:280: Indexer.Block.Fetcher.import/2\n    (indexer 5.3.3) lib/indexer/block/fetcher.ex:207: Indexer.Block.Fetcher.fetch_and_import_range/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 5.3.3) lib/indexer/block/realtime/fetcher.ex:316: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3\n"}}}
`

sometimes stoped and get this error

**Comment by haidarabdillah** [comment]
```
2023-12-22 12:03:46 {"time":"2023-12-22T05:03:46.220Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://xxxn\n    body: [{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBlockByNumber\",\"params\":[\"0x7ED3F3\",true]}]\n\n  response:\n\n    status code: 503\n\n    body: <html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n\n","metadata":{"block_number":8311795,"fetcher":"block_realtime"}}
2023-12-22 12:03:46 {"time":"2023-12-22T05:03:46.220Z","severity":"error","message":"failed to fetch: {:bad_response, \"https://xxx\"}.  Block will be retried by catchup indexer.","metadata":{"block_number":8311
```


the problem in RPC or in my settings? anyone can help ?

**Comment by vbaranov** [comment]
@haidarabdillah yes, the problem is that RPC returns 503 HTTP error

**Comment by haidarabdillah** [comment]
close this issue cause the RPC limited the request, change RPC and worked

**Comment by FournyP** [comment]
Hi @haidarabdillah 

Do you have some more information about `change RPC and worked` ?

Have a good day

**Comment by dorijan** [comment]
I am also interested what does that mean? I have same problem

**Comment by haidarabdillah** [comment]
i solved by re-configure the RPC, disable RPS limitation

**Comment by dorijan** [comment]
> i solved by re-configure the RPC, disable RPS limitation contact me on telegram https://t.me/haidar_nusatech if you get some trouble too

Great, thank you, will try :)

**Comment by puneet166** [comment]
having the same issue here is my logs -


backend          | {"time":"2024-02-17T07:18:08.167Z","severity":"error","message":"** (MatchError) no match of right hand side value: {:error, :invalid_recovery_id}\n    (indexer 6.1.0) lib/indexer/transform/blocks.ex:96: Indexer.Transform.Blocks.recover_pub_key/2\n    (indexer 6.1.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 6.1.0) lib/indexer/block/fetcher.ex:141: Indexer.Block.Fetcher.fetch_and_import_range/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 6.1.0) lib/indexer/block/catchup/fetcher.ex:195: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","first_block_number":50174,"last_block_number":50174}}
