### ISSUE TITLE
My indexer keeps terminating and restarting.

### ISSUE THREAD

**Issue by hhhroot** [blockscout/blockscout#9230]
### Description

My indexer keeps terminating and restarting. The suspect log is this:

```
2024-01-23T07:23:05.010 application=db_connection [error] Postgrex.Protocol (#PID<0.4182.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.14078.0> timed out because it queued and checked out the connection for longer than 60000ms

#PID<0.14078.0> was at location:
    :prim_inet.recv0/3
    (postgrex 0.17.4) lib/postgrex/protocol.ex:3194: Postgrex.Protocol.msg_recv/4
    (postgrex 0.17.4) lib/postgrex/protocol.ex:2219: Postgrex.Protocol.recv_bind/3
    (postgrex 0.17.4) lib/postgrex/protocol.ex:2074: Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.6.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.6.0) lib/db_connection.ex:1512: DBConnection.run_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:1607: DBConnection.run/6
    (db_connection 2.6.0) lib/db_connection.ex:743: DBConnection.parsed_prepare_execute/5

2024-01-23T07:23:05.012 [error] GenServer Indexer.Fetcher.TokenInstance.LegacySanitize terminating
** (Postgrex.Error) ERROR 57014 (query_canceled) canceling statement due to user request
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
                                                                                                                     291748,5      99%
    (indexer 6.0.0) lib/indexer/fetcher/token_instance/legacy_sanitize.ex:32: Indexer.Fetcher.TokenInstance.LegacySanitize.handle_cast/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :backfill}
State: %{batch_size: 10, concurrency: 2}
2024-01-23T07:39:59.599 application=indexer fetcher=block_catchup first_block_number=6072325 last_block_number=6072325 step=receipts [error] failed to fetch: [%{code: -32603, data: %{block_hash: "0x15015600bc9d663af4a0384323c3ccdf8bc06fe25933c890137acc6faadb35fe", block_number: 6072325, block_timestamp: ~U[2018-08-02 01:51:09Z], from_address_hash: "0xd32eb76b5dbe3a5800e2ea808dc45df0bb9a1517", gas: 21000, gas_price: 1000000000, hash: "0x48909b17543906c4ae7ce3739250ffcf47639a8a36f21e5322ccb3770b42e6d0", index: 113, input: "0x", nonce: 2, r: 65708534905042974176417953138378717026567771837319926008783452327567757695187, s: 29481565238168878239239011130164072903713712248688553174214408905983181907418, to_address_hash: "0x22dbfbc1e92699ebd763c1cdc50ed5bfdfe43726", transaction_index: 113, type: 0, v: 37, value: 30787400000000}, message: "no response"}, %{code: -32603, data: %{block_hash: "0x15015600bc9d663af4a0384323c3ccdf8bc06fe25933c890137acc6faadb35fe", block_number: 6072325, block_timestamp: ~U[2018-08-02 01:51:09Z], from_address_hash: "0x9d8b946faa88164233c6ba7f233bee5417194aae", gas: 60000, gas_price: 1000000000, hash: "0x6711d0282f6049f2923512ead934f10a80a1079ab43a3c7829952b63799193cb", index: 178, input: "0xa9059cbb000000000000000000000000111207d1273549132962ece72c786adcd780d3d6000000000000000000000000000000000000000000000000000000000007a120", nonce: 9, r: 48823776631406047492677318882556227766529639682122670496608626017020213346573, s: 19252966935162217433594194372251588088720922221702620267030704368191531967577, to_address_hash: "0x6dfe212d1461014be1781b0be710dda1c036d8ef", transaction_index: 178, type: 0, v: 28, value: 0}, message: "no response"}]. Retrying.
2024-01-23T07:39:59.599 fetcher=block_catchup first_block_number=6072328 last_block_number=6072327 [error] Task #PID<0.4886.0> started from #PID<0.4857.0> terminating
** (stop) exited in: GenServer.call(#PID<0.4879.0>, {:push_back, 6072328..6072327//-1}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.14.5) lib/gen_server.ex:1038: GenServer.call/3
    (indexer 6.0.0) lib/indexer/block/catchup/fetcher.ex:274: Indexer.Block.Catchup.Fetcher.push_back/2
    (indexer 6.0.0) lib/indexer/block/catchup/fetcher.ex:231: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<16.16752355/1 in Indexer.Block.Catchup.Fetcher.stream_fetch_and_import/2>, [6072328..6072327//-1]]
2024-01-23T07:39:59.599 fetcher=block_catchup first_block_number=6072325 last_block_number=6072325 [error] Task #PID<0.4887.0> started from #PID<0.4857.0> terminating
** (stop) exited in: GenServer.call(#PID<0.4879.0>, {:push_back, 6072325..6072325}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.14.5) lib/gen_server.ex:1038: GenServer.call/3
    (indexer 6.0.0) lib/indexer/block/catchup/fetcher.ex:274: Indexer.Block.Catchup.Fetcher.push_back/2
    (indexer 6.0.0) lib/indexer/block/catchup/fetcher.ex:231: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<16.16752355/1 in Indexer.Block.Catchup.Fetcher.stream_fetch_and_import/2>, [6072325..6072325]]
2024-01-23T07:39:59.602 application=indexer fetcher=block_catchup first_block_number=6071779 last_block_number=6071779 step=receipts [error] failed to fetch: [%{code: -32603, data: %{block_hash: "0x0334f9355717bd211739a3fdcfcf62f846c09b26d857722872a9f853e6eaf166", block_number: 6071779, block_timestamp: ~U[2018-08-01 23:46:13Z], from_address_hash: "0x918ada09787244e0f8f9bdd4fbf56a16b7692f91", gas: 60000, gas_price: 1100000000, hash: "0xa45d651d41fe31b99a949d22f694788e69954e769b311741a1c537cf7c6b3ead", index: 35, input: "0xa9059cbb00000000000000000000000042b2118a270cd1a58871fee82c7bb54d0dd4100a000000000000000000000000000000000000000000000000000000003b9aca00", nonce: 1, r: 35880739866223742481500670238474403859234626147376086636524437602880477859884, s: 33651535300967643074939389752111921955099318691503453199931879901123655427540, to_address_hash: "0x0e69d0a2bbb30abcb7e5cfea0e4fde19c00a8d47", transaction_index: 35, type: 0, v: 37, value: 0}, message: "no response"}, %{code: -32603, data: %{block_hash: "0x0334f9355717bd211739a3fdcfcf62f846c09b26d857722872a9f853e6eaf166", block_number: 6071779, block_timestamp: ~U[2018-08-01 23:46:13Z], from_address_hash: "0x553729516fef1c27cd3be53c4b55b2e1d58bf383", gas: 70000, gas_price: 1100000000, hash: "0x1d03380c7e4e737ecba9fe34682f700249777e146e05c83b0d2098c80639dfd6", index: 47, input: "0xa9059cbb00000000000000000000000067a35854f8956a86e0205b059e5bbb767e740eba000000000000000000000000000000000000000000000000000000012a05f200", nonce: 31419, r: 106709810684950121330680237114563117196805359111560725033260064914836961535962, s: 26861373220061194538480801216303714541340665510274372284620443899571110694334, to_address_hash: "0xc56b13ebbcffa67cfb7979b900b736b3fb480d78", transaction_index: 47, type: 0, v: 38, value: 0}, message: "no response"}]. Retrying.
2024-01-23T07:39:59.602 fetcher=block_catchup first_block_number=6071779 last_block_number=6071779 [error] Task #PID<0.4889.0> started from #PID<0.4857.0> terminating
** (stop) exited in: GenServer.call(#PID<0.4879.0>, {:push_back, 6072325..6072325}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.14.5) lib/gen_server.ex:1038: GenServer.call/3
    (indexer 6.0.0) lib/indexer/block/catchup/fetcher.ex:274: Indexer.Block.Catchup.Fetcher.push_back/2
    (indexer 6.0.0) lib/indexer/block/catchup/fetcher.ex:231: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<16.16752355/1 in Indexer.Block.Catchup.Fetcher.stream_fetch_and_import/2>, [6072325..6072325]]
2024-01-23T07:39:59.602 application=indexer fetcher=block_catchup first_block_number=6071779 last_block_number=6071779 step=receipts [error] failed to fetch: [%{code: -32603, data: %{block_hash: "0x0334f9355717bd211739a3fdcfcf62f846c09b26d857722872a9f853e6eaf166", block_number: 6071779, block_timestamp: ~U[2018-08-01 23:46:13Z], from_address_hash: "0x918ada09787244e0f8f9bdd4fbf56a16b7692f91", gas: 60000, gas_price: 1100000000, hash: "0xa45d651d41fe31b99a949d22f694788e69954e769b311741a1c537cf7c6b3ead", index: 35, input: "0xa9059cbb00000000000000000000000042b2118a270cd1a58871fee82c7bb54d0dd4100a000000000000000000000000000000000000000000000000000000003b9aca00", nonce: 1, r: 35880739866223742481500670238474403859234626147376086636524437602880477859884, s: 33651535300967643074939389752111921955099318691503453199931879901123655427540, to_address_hash: "0x0e69d0a2bbb30abcb7e5cfea0e4fde19c00a8d47", transaction_index: 35, type: 0, v: 37, value: 0}, message: "no response"}, %{code: -32603, data: %{block_hash: "0x0334f9355717bd211739a3fdcfcf62f846c09b26d857722872a9f853e6eaf166", block_number: 6071779, block_timestamp: ~U[2018-08-01 23:46:13Z], from_address_hash: "0x553729516fef1c27cd3be53c4b55b2e1d58bf383", gas: 70000, gas_price: 1100000000, hash: "0x1d03380c7e4e737ecba9fe34682f700249777e146e05c83b0d2098c80639dfd6", index: 47, input: "0xa9059cbb00000000000000000000000067a35854f8956a86e0205b059e5bbb767e740eba000000000000000000000000000000000000000000000000000000012a05f200", nonce: 31419, r: 106709810684950121330680237114563117196805359111560725033260064914836961535962, s: 26861373220061194538480801216303714541340665510274372284620443899571110694334, to_address_hash: "0xc56b13ebbcffa67cfb7979b900b736b3fb480d78", transaction_index: 47, type: 0, v: 38, value: 0}, message: "no response"}]. Retrying.
2024-01-23T07:39:59.602 fetcher=block_catchup first_block_number=6071779 last_block_number=6071779 [error] Task #PID<0.4889.0> started from #PID<0.4857.0> terminating
** (stop) exited in: GenServer.call(#PID<0.4879.0>, {:push_back, 6071779..6071779}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.14.5) lib/gen_server.ex:1038: GenServer.call/3
    (indexer 6.0.0) lib/indexer/block/catchup/fetcher.ex:274: Indexer.Block.Catchup.Fetcher.push_back/2
    (indexer 6.0.0) lib/indexer/block/catchup/fetcher.ex:231: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<16.16752355/1 in Indexer.Block.Catchup.Fetcher.stream_fetch_and_import/2>, [6071779..6071779]]
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

eth mainnet

### Backend version

v6.0.0

### Elixir & Erlang/OTP versions

using docker compose

### Operating system

ubuntu 22.04

### Additional information

1. I am running migration from v5.4.0 to v6.0.0 and denormalize process is currently running.

ctb_token_type | completed | 2024-01-22 11:46:29.677564 | 2024-01-23 01:33:40.568709
-- | -- | -- | --
denormalization | started | 2024-01-22 11:46:29.668591 | 2024-01-23 07:30:21.819165
tb_token_type | completed | 2024-01-22 11:46:29.684573 | 2024-01-23 06:51:12.371706

2. My indexer still terminate when I disable `TOKEN_INSTANCE_LEGACY_SANITIZE_FETCHER`
- `INDEXER_DISABLE_TOKEN_INSTANCE_LEGACY_SANITIZE_FETCHER=true`

**Comment by hhhroot** [comment]
I think related of #9013

**Comment by vbaranov** [comment]
@hhhroot could you try to adjust denormalization params according to https://docs.blockscout.com/for-developers/information-and-settings/env-variables#denormalization-management ? For instance, try to decrease `DENORMALIZATION_MIGRATION_BATCH_SIZE` or / and `DENORMALIZATION_MIGRATION_CONCURRENCY`.

**Comment by hhhroot** [comment]
After vacuuming, it runs well. Thank you for answer. It seems like there was a big load somewhere.
