### ISSUE TITLE
BadMapError

### ISSUE THREAD

**Issue by timwhite2** [blockscout/blockscout#9259]
### Description

Backend didn't index internal transaction,error msg:
{"time":"2024-01-26T01:56:31.105Z","severity":"error","message":"failed to fetch internal transactions for blocks: ** (BadMapError) expected a map, got: {\"from\", \"0x0617d41fe0361c4ef79ae0b2b919be7cf4d9c334\"}\n    (ethereum_jsonrpc 6.0.0) lib/ethereum_jsonrpc/geth.ex:227: anonymous fn/4 in EthereumJSONRPC.Geth.debug_trace_transaction_response_to_internal_transactions_params/2\n    (elixir 1.14.5) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2\n    (elixir 1.14.5) lib/enum.ex:4307: anonymous fn/3 in Enum.map/2\n    (elixir 1.14.5) lib/stream.ex:1801: anonymous fn/3 in Enumerable.Stream.reduce/3\n    (elixir 1.14.5) lib/stream.ex:1158: anonymous fn/3 in Stream.with_index/2\n    (elixir 1.14.5) lib/enum.ex:4751: Enumerable.List.reduce/3\n    (elixir 1.14.5) lib/stream.ex:1813: Enumerable.Stream.do_each/4\n    (elixir 1.14.5) lib/enum.ex:4307: Enum.map/2\n","metadata":{"count":10,"error_count":10,"fetcher":"internal_transaction"}}

here is rpc resp
```json
{
    "jsonrpc": "2.0",
    "id": "1",
    "result": {
        "error": "invalid opcode: PUSH0",
        "from": "0x0617d41fe0361c4ef79ae0b2b919be7cf4d9c334",
        "gas": "0x2b4154",
        "gasUsed": "0x2b4154",
        "input": "0x608060405234801562000010575f80fd5b5060405162001d7d38038062001d7d833981810160405281019062000036919062000395565b818181600390816200004991906200064f565b5080600490816200005b91906200064f565b5050506200009e3362000073620000a660201b60201c565b60ff16600a620000849190620008b0565b606462000092919062000900565b620000ae60201b60201c565b505062000a2e565b5f6012905090565b5f73ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16036200011f576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016200011690620009a8565b60405180910390fd5b620001325f83836200020b60201b60201c565b8060025f828254620001459190620009c8565b92505081905550805f808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f828254620001999190620009c8565b925050819055508173ffffffffffffffffffffffffffffffffffffffff165f73ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef83604051620001ff919062000a13565b60405180910390a35050565b505050565b5f604051905090565b5f80fd5b5f80fd5b5f80fd5b5f80fd5b5f601f19601f8301169050919050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52604160045260245ffd5b620002718262000229565b810181811067ffffffffffffffff8211171562000293576200029262000239565b5b80604052505050565b5f620002a762000210565b9050620002b5828262000266565b919050565b5f67ffffffffffffffff821115620002d757620002d662000239565b5b620002e28262000229565b9050602081019050919050565b5f5b838110156200030e578082015181840152602081019050620002f1565b5f8484015250505050565b5f6200032f6200032984620002ba565b6200029c565b9050828152602081018484840111156200034e576200034d62000225565b5b6200035b848285620002ef565b509392505050565b5f82601f8301126200037a576200037962000221565b5b81516200038c84826020860162000319565b91505092915050565b5f8060408385031215620003ae57620003ad62000219565b5b5f83015167ffffffffffffffff811115620003ce57620003cd6200021d565b5b620003dc8582860162000363565b925050602083015167ffffffffffffffff8111156200040057620003ff6200021d565b5b6200040e8582860162000363565b9150509250929050565b5f81519050919050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52602260045260245ffd5b5f60028204905060018216806200046757607f821691505b6020821081036200047d576200047c62000422565b5b50919050565b5f819050815f5260205f209050919050565b5f6020601f8301049050919050565b5f82821b905092915050565b5f60088302620004e17fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff82620004a4565b620004ed8683620004a4565b95508019841693508086168417925050509392505050565b5f819050919050565b5f819050919050565b5f62000537620005316200052b8462000505565b6200050e565b62000505565b9050919050565b5f819050919050565b620005528362000517565b6200056a62000561826200053e565b848454620004b0565b825550505050565b5f90565b6200058062000572565b6200058d81848462000547565b505050565b5b81811015620005b457620005a85f8262000576565b60018101905062000593565b5050565b601f8211156200060357620005cd8162000483565b620005d88462000495565b81016020851015620005e8578190505b62000600620005f78562000495565b83018262000592565b50505b505050565b5f82821c905092915050565b5f620006255f198460080262000608565b1980831691505092915050565b5f6200063f838362000614565b9150826002028217905092915050565b6200065a8262000418565b67ffffffffffffffff81111562000676576200067562000239565b5b6200068282546200044f565b6200068f828285620005b8565b5f60209050601f831160018114620006c5575f8415620006b0578287015190505b620006bc858262000632565b8655506200072b565b601f198416620006d58662000483565b5f5b82811015620006fe57848901518255600182019150602085019450602081019050620006d7565b868310156200071e57848901516200071a601f89168262000614565b8355505b6001600288020188555050505b505050505050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f8160011c9050919050565b5f808291508390505b6001851115620007bd5780860481111562000795576200079462000733565b5b6001851615620007a55780820291505b8081029050620007b58562000760565b945062000775565b94509492505050565b5f82620007d75760019050620008a9565b81620007e6575f9050620008a9565b8160018114620007ff57600281146200080a5762000840565b6001915050620008a9565b60ff8411156200081f576200081e62000733565b5b8360020a91508482111562000839576200083862000733565b5b50620008a9565b5060208310610133831016604e8410600b84101617156200087a5782820a90508381111562000874576200087362000733565b5b620008a9565b6200088984848460016200076c565b92509050818404811115620008a357620008a262000733565b5b81810290505b9392505050565b5f620008bc8262000505565b9150620008c98362000505565b9250620008f87fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8484620007c6565b905092915050565b5f6200090c8262000505565b9150620009198362000505565b9250828202620009298162000505565b9150828204841483151762000943576200094262000733565b5b5092915050565b5f82825260208201905092915050565b7f45524332303a206d696e7420746f20746865207a65726f2061646472657373005f82015250565b5f62000990601f836200094a565b91506200099d826200095a565b602082019050919050565b5f6020820190508181035f830152620009c18162000982565b9050919050565b5f620009d48262000505565b9150620009e18362000505565b9250828201905080821115620009fc57620009fb62000733565b5b92915050565b62000a0d8162000505565b82525050565b5f60208201905062000a285f83018462000a02565b92915050565b6113418062000a3c5f395ff3fe608060405234801561000f575f80fd5b50600436106100a7575f3560e01c8063395093511161006f578063395093511461016557806370a082311461019557806395d89b41146101c5578063a457c2d7146101e3578063a9059cbb14610213578063dd62ed3e14610243576100a7565b806306fdde03146100ab578063095ea7b3146100c957806318160ddd146100f957806323b872dd14610117578063313ce56714610147575b5f80fd5b6100b3610273565b6040516100c09190610c02565b60405180910390f35b6100e360048036038101906100de9190610cb3565b610303565b6040516100f09190610d0b565b60405180910390f35b610101610320565b60405161010e9190610d33565b60405180910390f35b610131600480360381019061012c9190610d4c565b610329565b60405161013e9190610d0b565b60405180910390f35b61014f610424565b60405161015c9190610db7565b60405180910390f35b61017f600480360381019061017a9190610cb3565b61042c565b60405161018c9190610d0b565b60405180910390f35b6101af60048036038101906101aa9190610dd0565b6104d3565b6040516101bc9190610d33565b60405180910390f35b6101cd610518565b6040516101da9190610c02565b60405180910390f35b6101fd60048036038101906101f89190610cb3565b6105a8565b60405161020a9190610d0b565b60405180910390f35b61022d60048036038101906102289190610cb3565b610697565b60405161023a9190610d0b565b60405180910390f35b61025d60048036038101906102589190610dfb565b6106b4565b60405161026a9190610d33565b60405180910390f35b60606003805461028290610e66565b80601f01602080910402602001604051908101604052809291908181526020018280546102ae90610e66565b80156102f95780601f106102d0576101008083540402835291602001916102f9565b820191905f5260205f20905b8154815290600101906020018083116102dc57829003601f168201915b5050505050905090565b5f61031661030f610736565b848461073d565b6001905092915050565b5f600254905090565b5f610335848484610900565b5f60015f8673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f61037c610736565b73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f20549050828110156103fb576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016103f290610f06565b60405180910390fd5b61041885610407610736565b85846104139190610f51565b61073d565b60019150509392505050565b5f6012905090565b5f6104c9610438610736565b848460015f610445610736565b73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f8873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f20546104c49190610f84565b61073d565b6001905092915050565b5f805f8373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f20549050919050565b60606004805461052790610e66565b80601f016020809104026020016040519081016040528092919081815260200182805461055390610e66565b801561059e5780601f106105755761010080835404028352916020019161059e565b820191905f5260205f20905b81548152906001019060200180831161058157829003601f168201915b5050505050905090565b5f8060015f6105b5610736565b73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f8573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205490508281101561066f576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161066690611027565b60405180910390fd5b61068c61067a610736565b8585846106879190610f51565b61073d565b600191505092915050565b5f6106aa6106a3610736565b8484610900565b6001905092915050565b5f60015f8473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f8373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f2054905092915050565b5f33905090565b5f73ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff16036107ab576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016107a2906110b5565b60405180910390fd5b5f73ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff1603610819576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161081090611143565b60405180910390fd5b8060015f8573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f8473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f20819055508173ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925836040516108f39190610d33565b60405180910390a3505050565b5f73ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff160361096e576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610965906111d1565b60405180910390fd5b5f73ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16036109dc576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016109d39061125f565b60405180910390fd5b6109e7838383610b73565b5f805f8573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f2054905081811015610a6a576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610a61906112ed565b60405180910390fd5b8181610a769190610f51565b5f808673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f2081905550815f808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f828254610b019190610f84565b925050819055508273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef84604051610b659190610d33565b60405180910390a350505050565b505050565b5f81519050919050565b5f82825260208201905092915050565b5f5b83811015610baf578082015181840152602081019050610b94565b5f8484015250505050565b5f601f19601f8301169050919050565b5f610bd482610b78565b610bde8185610b82565b9350610bee818560208601610b92565b610bf781610bba565b840191505092915050565b5f6020820190508181035f830152610c1a8184610bca565b905092915050565b5f80fd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f610c4f82610c26565b9050919050565b610c5f81610c45565b8114610c69575f80fd5b50565b5f81359050610c7a81610c56565b92915050565b5f819050919050565b610c9281610c80565b8114610c9c575f80fd5b50565b5f81359050610cad81610c89565b92915050565b5f8060408385031215610cc957610cc8610c22565b5b5f610cd685828601610c6c565b9250506020610ce785828601610c9f565b9150509250929050565b5f8115159050919050565b610d0581610cf1565b82525050565b5f602082019050610d1e5f830184610cfc565b92915050565b610d2d81610c80565b82525050565b5f602082019050610d465f830184610d24565b92915050565b5f805f60608486031215610d6357610d62610c22565b5b5f610d7086828701610c6c565b9350506020610d8186828701610c6c565b9250506040610d9286828701610c9f565b9150509250925092565b5f60ff82169050919050565b610db181610d9c565b82525050565b5f602082019050610dca5f830184610da8565b92915050565b5f60208284031215610de557610de4610c22565b5b5f610df284828501610c6c565b91505092915050565b5f8060408385031215610e1157610e10610c22565b5b5f610e1e85828601610c6c565b9250506020610e2f85828601610c6c565b9150509250929050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52602260045260245ffd5b5f6002820490506001821680610e7d57607f821691505b602082108103610e9057610e8f610e39565b5b50919050565b7f45524332303a207472616e7366657220616d6f756e74206578636565647320615f8201527f6c6c6f77616e6365000000000000000000000000000000000000000000000000602082015250565b5f610ef0602883610b82565b9150610efb82610e96565b604082019050919050565b5f6020820190508181035f830152610f1d81610ee4565b9050919050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f610f5b82610c80565b9150610f6683610c80565b9250828203905081811115610f7e57610f7d610f24565b5b92915050565b5f610f8e82610c80565b9150610f9983610c80565b9250828201905080821115610fb157610fb0610f24565b5b92915050565b7f45524332303a2064656372656173656420616c6c6f77616e63652062656c6f775f8201527f207a65726f000000000000000000000000000000000000000000000000000000602082015250565b5f611011602583610b82565b915061101c82610fb7565b604082019050919050565b5f6020820190508181035f83015261103e81611005565b9050919050565b7f45524332303a20617070726f76652066726f6d20746865207a65726f206164645f8201527f7265737300000000000000000000000000000000000000000000000000000000602082015250565b5f61109f602483610b82565b91506110aa82611045565b604082019050919050565b5f6020820190508181035f8301526110cc81611093565b9050919050565b7f45524332303a20617070726f766520746f20746865207a65726f2061646472655f8201527f7373000000000000000000000000000000000000000000000000000000000000602082015250565b5f61112d602283610b82565b9150611138826110d3565b604082019050919050565b5f6020820190508181035f83015261115a81611121565b9050919050565b7f45524332303a207472616e736665722066726f6d20746865207a65726f2061645f8201527f6472657373000000000000000000000000000000000000000000000000000000602082015250565b5f6111bb602583610b82565b91506111c682611161565b604082019050919050565b5f6020820190508181035f8301526111e8816111af565b9050919050565b7f45524332303a207472616e7366657220746f20746865207a65726f20616464725f8201527f6573730000000000000000000000000000000000000000000000000000000000602082015250565b5f611249602383610b82565b9150611254826111ef565b604082019050919050565b5f6020820190508181035f8301526112768161123d565b9050919050565b7f45524332303a207472616e7366657220616d6f756e74206578636565647320625f8201527f616c616e63650000000000000000000000000000000000000000000000000000602082015250565b5f6112d7602683610b82565b91506112e28261127d565b604082019050919050565b5f6020820190508181035f830152611304816112cb565b905091905056fea264697066735822122045f7e0dbacb967f8149f3a13953e60c9031c98ab958acedb3f9380194187c93264736f6c63430008170033000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000003757364000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000045553444300000000000000000000000000000000000000000000000000000000",
        "to": "0xd836b4ccdda8a2a8c66a4c7a7f8a336ba24f16b1",
        "type": "CREATE",
        "value": "0x0"
    }
}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ethermint

### Type of the chain

L1

### Backend version

image id: e00e07084b51

### Elixir & Erlang/OTP versions

ERLANG=24.2.2

### Operating system

ubuntu

**Comment by vbaranov** [comment]
> here is rpc resp

@timwhite2 how request exactly was look like for this response?

**Comment by paperzjt** [comment]
sorry for this, seem like it's my problem

**Comment by timwhite2** [comment]
seem like it's my problem

**Comment by phpmac** [comment]
> seem like it's my problem

how to solve
