### ISSUE TITLE
Flaking tests

### ISSUE THREAD

**Issue by sl1depengwyn** [blockscout/blockscout#9347]
Recommended format:
<details>
asd
</details>

**Comment by vbaranov** [comment]
More of flickering tests:
- [ ] test/explorer/chain/cache/gas_price_oracle_test.exs:362
<details>
test get_average_gas_price/4 return gas prices with average block time if earliest_processing_start is not available (Explorer.Chain.Cache.GasPriceOracleTest)
Error:      test/explorer/chain/cache/gas_price_oracle_test.exs:362
     ** (FunctionClauseError) no function clause matching in Decimal.decimal/1

     The following arguments were given to Decimal.decimal/1:

         # 1
         nil

     Attempted function clauses (showing 4 out of 4):

         defp decimal(-%Decimal{} = num-)
         defp decimal(num) when -is_integer(num)-
         defp decimal(num) when -is_binary(num)-
         defp decimal(other) when -is_float(other)-

     code: }, _} = GasPriceOracle.get_average_gas_price(3, 35, 60, 90)
     stacktrace:
       (decimal 2.1.1) lib/decimal.ex:1910: Decimal.decimal/1
       (decimal 2.1.1) lib/decimal.ex:996: Decimal.mult/2
       (explorer 6.7.2) lib/explorer/chain/cache/gas_price_oracle.ex:276: Explorer.Chain.Cache.GasPriceOracle.fiat_fee/2
       (explorer 6.7.2) lib/explorer/chain/cache/gas_price_oracle.ex:262: Explorer.Chain.Cache.GasPriceOracle.compose_gas_price/5
       (explorer 6.7.2) lib/explorer/chain/cache/gas_price_oracle.ex:229: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1
       (explorer 6.7.2) lib/explorer/chain/cache/gas_price_oracle.ex:177: Explorer.Chain.Cache.GasPriceOracle.get_average_gas_price/4
       test/explorer/chain/cache/gas_price_oracle_test.exs:461: (test)

.......................
Error: 08:52:49.447 [error] Task #PID<0.33760.0> started from #PID<0.33722.0> terminating
</details>

**Comment by nikitosing** [comment]
1) test current day values are saved in state (Explorer.Market.History.CatalogerTest)
    <details>
    Error:      test/explorer/market/history/cataloger_test.exs:167
         match (=) failed
         code:  assert [
                  %Explorer.Market.MarketHistory{date: ~D"2018-04-01"} = first_entry,
                  %Explorer.Market.MarketHistory{date: ~D"2018-04-02"} = second_entry
                ] = MarketHistory |> order_by(asc: :date) |> Repo.all()
         left:  [
                  %Explorer.Market.MarketHistory{date: ~D[2018-04-01]} = first_entry,
                  %Explorer.Market.MarketHistory{date: ~D[2018-04-02]} = second_entry
                ]
         right: [
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 100,
                    closing_price: Decimal.new("10"),
                    date: ~D[2018-04-01],
                    opening_price: Decimal.new("5"),
                    market_cap: nil,
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 351,
                    closing_price: Decimal.new("20"),
                    date: ~D[2018-04-02],
                    opening_price: Decimal.new("5"),
                    market_cap: nil,
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 349,
                    closing_price: nil,
                    date: ~D[2023-10-31],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 105,
                    closing_price: nil,
                    date: ~D[2023-11-01],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 114,
                    closing_price: nil,
                    date: ~D[2023-11-02],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 123,
                    closing_price: nil,
                    date: ~D[2023-11-03],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 132,
                    closing_price: nil,
                    date: ~D[2023-11-04],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 141,
                    closing_price: nil,
                    date: ~D[2023-11-05],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 150,
                    closing_price: nil,
                    date: ~D[2023-11-06],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 159,
                    closing_price: nil,
                    date: ~D[2023-11-07],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 168,
                    closing_price: nil,
                    date: ~D[2023-11-08],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 177,
                    closing_price: nil,
                    date: ~D[2023-11-09],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 185,
                    closing_price: nil,
                    date: ~D[2023-11-10],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 193,
                    closing_price: nil,
                    date: ~D[2023-11-11],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 201,
                    closing_price: nil,
                    date: ~D[2023-11-12],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 209,
                    closing_price: nil,
                    date: ~D[2023-11-13],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 217,
                    closing_price: nil,
                    date: ~D[2023-11-14],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 225,
                    closing_price: nil,
                    date: ~D[2023-11-15],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 233,
                    closing_price: nil,
                    date: ~D[2023-11-16],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 241,
                    closing_price: nil,
                    date: ~D[2023-11-17],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 249,
                    closing_price: nil,
                    date: ~D[2023-11-18],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 257,
                    closing_price: nil,
                    date: ~D[2023-11-19],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 265,
                    closing_price: nil,
                    date: ~D[2023-11-20],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 273,
                    closing_price: nil,
                    date: ~D[2023-11-21],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 281,
                    closing_price: nil,
                    date: ~D[2023-11-22],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 289,
                    closing_price: nil,
                    date: ~D[2023-11-23],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 297,
                    closing_price: nil,
                    date: ~D[2023-11-24],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 305,
                    closing_price: nil,
                    date: ~D[2023-11-25],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 313,
                    closing_price: nil,
                    date: ~D[2023-11-26],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 321,
                    closing_price: nil,
                    date: ~D[2023-11-27],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 329,
                    closing_price: nil,
                    date: ~D[2023-11-28],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 337,
                    closing_price: nil,
                    date: ~D[2023-11-29],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 344,
                    closing_price: nil,
                    date: ~D[2023-11-30],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 106,
                    closing_price: nil,
                    date: ~D[2023-12-01],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 115,
                    closing_price: nil,
                    date: ~D[2023-12-02],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 124,
                    closing_price: nil,
                    date: ~D[2023-12-03],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 133,
                    closing_price: nil,
                    date: ~D[2023-12-04],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 142,
                    closing_price: nil,
                    date: ~D[2023-12-05],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 151,
                    closing_price: nil,
                    date: ~D[2023-12-06],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 160,
                    closing_price: nil,
                    date: ~D[2023-12-07],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 169,
                    closing_price: nil,
                    date: ~D[2023-12-08],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 178,
                    closing_price: nil,
                    date: ~D[2023-12-09],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    secondary_coin: false
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 186,
                    closing_price: nil,
                    date: ~D[2023-12-10],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    tvl: nil,
                    ...
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 194,
                    closing_price: nil,
                    date: ~D[2023-12-11],
                    opening_price: nil,
                    market_cap: Decimal.new("0.0"),
                    ...
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 202,
                    closing_price: nil,
                    date: ~D[2023-12-12],
                    opening_price: nil,
                    ...
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 210,
                    closing_price: nil,
                    date: ~D[2023-12-13],
                    ...
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 218,
                    closing_price: nil,
                    ...
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    id: 226,
                    ...
                  },
                  %Explorer.Market.MarketHistory{
                    __meta__: #Ecto.Schema.Metadata<:loaded, "market_history">,
                    ...
                  },
                  %Explorer.Market.MarketHistory{...},
                  ...
                ]
         stacktrace:
           test/explorer/market/history/cataloger_test.exs:218: (test)
    </details>

**Comment by sl1depengwyn** [comment]
- [ ] test updates cache if initial value is zero (Explorer.Chain.Cache.BlockTest)
  <details>
  Error:      test/explorer/chain/cache/block_test.exs:18
       Assertion with == failed
       code:  assert updated_value == 2
       left:  0
       right: 2
       stacktrace:
         test/explorer/chain/cache/block_test.exs:29: (test)
  </>
  
- [ ] test updates cache if initial value is zero (Explorer.Chain.Cache.AddressSumTest)
    <details>
    Error:      test/explorer/chain/cache/address_sum_test.exs:18
       ** (FunctionClauseError) no function clause matching in Decimal.to_integer/1
  
       The following arguments were given to Decimal.to_integer/1:
  
           # 1
           0
  
       Attempted function clauses (showing 4 out of 4):
  
           def to_integer(-%Decimal{sign: sign, coef: coef, exp: 0}-) when -is_integer(coef)-
           def to_integer(-%Decimal{sign: sign, coef: coef, exp: exp}-) when -is_integer(coef)- and -exp > 0-
           def to_integer(-%Decimal{sign: sign, coef: coef, exp: exp}-) when -is_integer(coef)- and -exp < 0- and -rem(coef, 10) == 0-
           def to_integer(-%Decimal{coef: coef} = decimal-) when -is_integer(coef)-
  
       code: updated_value = Decimal.to_integer(AddressSum.get_sum())
       stacktrace:
         (decimal 2.1.1) lib/decimal.ex:1468: Decimal.to_integer/1
         test/explorer/chain/cache/address_sum_test.exs:28: (test)
    </>

**Comment by sl1depengwyn** [comment]
- [ ] Test account/api/account/v2/user watchlist address returns with token balances info + handle nil fiat values (BlockScoutWeb.Account.Api.V2.UserControllerTest)
  <details>
  Error:      test/block_scout_web/controllers/account/api/v2/user_controller_test.exs:799
       Assertion with == failed
       code:  assert wa1["tokens_fiat_value"] |> Decimal.new() |> Decimal.round(13) ==
                values |> Enum.reduce(Decimal.new(0), fn x, acc -> Decimal.add(x, acc) end) |> Decimal.round(13)
       left:  Decimal.new("8527.7466494321747")
       right: Decimal.new("8527.7466494321748")
       stacktrace:
         test/block_scout_web/controllers/account/api/v2/user_controller_test.exs:834: (test)
  </>
- [ ] Test account/api/account/v2/user watchlist address returns with token balances info (BlockScoutWeb.Account.Api.V2.UserControllerTest)
  <details>
  Error:      test/block_scout_web/controllers/account/api/v2/user_controller_test.exs:733
       Assertion with == failed
       code:  assert wa2["tokens_fiat_value"] |> Decimal.new() |> Decimal.round(13) ==
                values_1
                |> Enum.reduce(Decimal.new(0), fn x, acc -> Decimal.add(x, acc) end)
                |> Decimal.round(13)
       left:  Decimal.new("10192.8186647459866")
       right: Decimal.new("10192.8186647459867")
       stacktrace:
         test/block_scout_web/controllers/account/api/v2/user_controller_test.exs:792: (test)
  </>

**Comment by fedor-ivn** [comment]
- [ ] Test Check how works retry in realtime retry once after timeout (Indexer.Fetcher.TokenInstance.RealtimeTest). Example of [failed job](https://github.com/blockscout/blockscout/actions/runs/9890101172/job/27317628631?pr=9944#step:7:2950)
  <details>
    Error:      test/indexer/fetcher/token_instance/realtime_test.exs:29
         Assertion with == failed
         code:  assert instance.metadata == %{"name" => "name"}
         left:  nil
         right: %{"name" => "name"}
         stacktrace:
           test/indexer/fetcher/token_instance/realtime_test.exs:119: (test)
  </details>

**Comment by k1rill-fedoseev** [comment]
- [ ] test publish/2 with valid data creates a smart_contract (Explorer.SmartContract.Vyper.PublisherTest)
  <details>
  Error:      test/explorer/smart_contract/vyper/publisher_test.exs:24
     match (=) failed
     code:  assert {:ok, %SmartContract{} = smart_contract} = response
     left:  {:ok, %Explorer.Chain.SmartContract{} = smart_contract}
     right: {:error,
             #Ecto.Changeset<
               action: :insert,
               changes: %{
                 name: "SimpleContract",
                 compiler_version: "v0.3.10",
                 contract_source_code: "initialized: public(bool)\nvalue: public(uint256)\n\n@external\ndef __init__():\n    self.value = 123\n    self.initialized = False\n",
                 is_blueprint: false,
                 is_vyper_contract: true,
                 optimization: true,
                 partially_verified: false,
                 verified_via_eth_bytecode_db: false,
                 verified_via_sourcify: false,
                 verified_via_verifier_alliance: false
               },
               errors: [
                 contract_source_code: {"There was an error compiling your contract.",
                  []},
                 contract_code_md5: {"can't be blank",
                  [validation: :required]}
               ],
               data: #Explorer.Chain.SmartContract<>,
               valid?: false
             >}
     stacktrace:
       test/explorer/smart_contract/vyper/publisher_test.exs:40: (test)
  </>
- [ ] test publish/2 allows to re-verify vyper contracts (Explorer.SmartContract.Vyper.PublisherTest)
  <details>
  Error:      test/explorer/smart_contract/vyper/publisher_test.exs:50
     match (=) failed
     code:  assert {:ok, %SmartContract{}} = response
     left:  {:ok, %Explorer.Chain.SmartContract{}}
     right: {:error,
             #Ecto.Changeset<
               action: :insert,
               changes: %{
                 name: "SimpleContract",
                 compiler_version: "v0.3.10",
                 contract_source_code: "initialized: public(bool)\nvalue: public(uint256)\n\n@external\ndef __init__():\n    self.value = 123\n    self.initialized = False\n",
                 is_blueprint: false,
                 is_vyper_contract: true,
                 optimization: true,
                 partially_verified: false,
                 verified_via_eth_bytecode_db: false,
                 verified_via_sourcify: false,
                 verified_via_verifier_alliance: false
               },
               errors: [
                 contract_source_code: {"There was an error compiling your contract.",
                  []},
                 contract_code_md5: {"can't be blank",
                  [validation: :required]}
               ],
               data: #Explorer.Chain.SmartContract<>,
               valid?: false
             >}
     stacktrace:
       test/explorer/smart_contract/vyper/publisher_test.exs:66: (test)
  </>

**Comment by k1rill-fedoseev** [comment]
- [ ] test cover new functionality from https://github.com/blockscout/blockscout/pull/5479 return {:error, :deployed_bytecode} (Explorer.SmartContract.Solidity.VerifierTest)
  <details>
  Error:      test/explorer/smart_contract/solidity/verifier_test.exs:1167
     match (=) failed
     code:  assert {:error, :deployed_bytecode} = Verifier.evaluate_authenticity(contract_address.hash, params)
     left:  {:error, :deployed_bytecode}
     right: {:error,
             %{
               "code" => 3,
               "message" => "Json deserialize error: invalid type: null, expected a map at line 1 column 2757"
             }}
     stacktrace:
       test/explorer/smart_contract/solidity/verifier_test.exs:1193: (test)
  </>
- [ ] test check retries count and refetch after proper updates retries count and refetch after on retry (Indexer.Fetcher.TokenInstance.HelperTest)
  <details>
  Error:      test/indexer/fetcher/token_instance/helper_test.exs:412
     Assertion with < failed, both sides are exactly equal
     code: assert DateTime.diff(refetch_after, instance.refetch_after) < 1
     left: 1
     stacktrace:
       test/indexer/fetcher/token_instance/helper_test.exs:439: (test)
  </>

[failed job example](https://github.com/blockscout/blockscout/actions/runs/10073909598)

**Comment by fedor-ivn** [comment]
14 tests from `Explorer.Etherscan.LogsTest` started flickering again. The following is an example:

- [ ] :warning: test list_logs/1 paginates logs (Explorer.Etherscan.LogsTest)
  <details>
  Error:      test/explorer/etherscan/logs_test.exs:181
       Assertion with == failed
       code:  assert Enum.count(first_found_logs) == 1000
       left:  0
       right: 1000
       stacktrace:
         test/explorer/etherscan/logs_test.exs:201: (test)
  </>


[failed job example](https://github.com/blockscout/blockscout/actions/runs/10283403842/)

**Comment by sl1depengwyn** [comment]
- [ ] test viewing uncle blocks list lists uncle blocks (BlockScoutWeb.ViewingBlocksTest)
 <details>
  
  ```
Error:      test/block_scout_web/features/viewing_blocks_test.exs:167
     ** (Wallaby.ExpectationNotMetError) Expected to find 1 visible element that matched the css '[data-block-number='18662']', but 0 visible elements were found.

     code: |> assert_has(BlockListPage.block(uncle))
     stacktrace:
       test/block_scout_web/features/viewing_blocks_test.exs:170: (test)
  ```
  
  </details>

**Comment by sl1depengwyn** [comment]
- [ ] test Test account/api/account/v2/user watchlist address returns with token balances info (BlockScoutWeb.Account.Api.V2.UserControllerTest)

 <details>
  
 ```
 test/block_scout_web/controllers/account/api/v2/user_controller_test.exs:742
     Assertion with == failed
     code:  assert wa1["tokens_fiat_value"] |> Decimal.new() ==
              values
              |> Enum.reduce(Decimal.new(0), fn x, acc -> Decimal.add(x, acc) end)
              |> dbg(limit: :infinity, printable_limit: :infinity)
     left:  Decimal.new("8045.9498963133990495")
     right: Decimal.new("8045.9498963133990501266")
     stacktrace:
       test/block_scout_web/controllers/account/api/v2/user_controller_test.exs:794: (test)
 ```
  
  </details>

**Comment by sl1depengwyn** [comment]
- [ ] test /addresses/{address_hash}/nft/collections get paginated erc-721 collection (BlockScoutWeb.API.V2.AddressControllerTest)

 <details>
  
 ```
Error:      test/block_scout_web/controllers/api/v2/address_controller_test.exs:3421
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Cldr.Unit.Range, DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, Explorer.BoundQueue, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
     stacktrace:
       (elixir 1.17.3) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir 1.17.3) lib/enum.ex:166: Enumerable.reduce/3
       (elixir 1.17.3) lib/enum.ex:4423: Enum.reduce/3
       (stdlib 6.1.2) maps.erl:860: :maps.fold_1/4
       (mox 1.2.0) lib/mox.ex:848: Mox.__verify_mock_or_all__/2
       (mox 1.2.0) lib/mox.ex:819: anonymous fn/1 in Mox.verify_on_exit!/1
       (ex_unit 1.17.3) lib/ex_unit/on_exit_handler.ex:136: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit 1.17.3) lib/ex_unit/on_exit_handler.ex:122: ExUnit.OnExitHandler.on_exit_runner_loop/0

 ```
  
  </details>
