### ISSUE TITLE
Transform coin balances failed due to nil miner_hash

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#9366]
https://reya-cronos.blockscout.com/block/0

```
{"time":"2024-02-09T10:25:13.832Z","severity":"error","message":"** (FunctionClauseError) no function clause matching in anonymous fn/1 in Indexer.Transform.AddressCoinBalances.reducer/2\n    (indexer 6.1.0) anonymous fn(%{difficulty: 0, extra_data: \"0x\", gas_limit: 0, gas_used: 0, hash: \"0xc4e07ae30813ae32d44e545a15b7a07f5ac0e2fd15c6c1fc86f3523c7cbc0c2c\", logs_bloom: \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\", miner_hash: nil, mix_hash: \"0x0000000000000000000000000000000000000000000000000000000000000000\", nonce: \"0x0000000000000000\", number: 0, parent_hash: \"0x0000000000000000000000000000000000000000000000000000000000000000\", receipts_root: \"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\", sha3_uncles: \"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\", size: 505, state_root: \"0xcbba7b0124e996555b4f315d2d38878fd3321e3a2321ff2d4a14972d00dc67ee\", timestamp: ~U[2024-02-06 18:55:00Z], total_difficulty: nil, transactions_root: \"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\", uncles: [], withdrawals_root: \"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\"}) in Indexer.Transform.AddressCoinBalances.reducer/2\n    (elixir 1.14.5) lib/enum.ex:1580: anonymous fn/4 in Enum.reduce_into_protocol/4\n    (elixir 1.14.5) lib/enum.ex:1580: Enum.\"-reduce_into_protocol/4-lists^foldl/2-0-\"/3\n    (elixir 1.14.5) lib/enum.ex:1569: Enum.into_protocol/3\n    (stdlib 3.17) maps.erl:410: :maps.fold_1/3\n    (indexer 6.1.0) lib/indexer/block/fetcher.ex:182: Indexer.Block.Fetcher.fetch_and_import_range/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 6.1.0) lib/indexer/block/catchup/fetcher.ex:195: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","first_block_number":0,"last_block_number":0}}
```

**Comment by Kb00711** [comment]
I have created over 70 NFTs and have been first to mint but haven't received first minter Rewards or any Rewards at all since the 3rd NFT creation
