### ISSUE TITLE
Indexer.Fetcher.PendingTransaction: no function clause matching in EthereumJSONRPC.Transaction.do_elixir_to_params/1

### ISSUE THREAD

**Issue by nikitosing** [blockscout/blockscout#9436]
```
2024-02-20T22:15:57.466 fetcher=pending_transaction [error] Task #PID<0.12507.1> started from Indexer.Fetcher.PendingTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.do_elixir_to_params/1
    (ethereum_jsonrpc 6.1.0) lib/ethereum_jsonrpc/transaction.ex:206: EthereumJSONRPC.Transaction.do_elixir_to_params(%{"blockHash" => nil, "blockNumber" => nil, "from" => "0x0000000000000000000000000000000000000000", "gas" => 21000, "hash" => "0x9a4c9f5ce4ec71e2029a22db64fab34be663258a5e4116a1123f35734f1096e3", "input" => "0x", "nonce" => 26318, "r" => 0, "s" => 0, "to" => "0x56272f6932e6ae0116d270a2e919d20d3052f206", "transactionIndex" => nil, "type" => 3, "v" => 0, "value" => 0})
    (ethereum_jsonrpc 6.1.0) lib/ethereum_jsonrpc/transaction.ex:202: EthereumJSONRPC.Transaction.elixir_to_params/1
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 6.1.0) lib/ethereum_jsonrpc/pending_transaction.ex:27: EthereumJSONRPC.PendingTransaction.fetch_pending_transactions_geth/1
    (indexer 6.1.0) lib/indexer/fetcher/pending_transaction.ex:120: Indexer.Fetcher.PendingTransaction.task/1
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<2.81718007/0 in Indexer.Fetcher.PendingTransaction.handle_info/2>
    Args: []
2024-02-20T22:15:57.467 application=indexer fetcher=pending_transaction [error] pending transaction fetcher task exited due to {:function_clause, [{EthereumJSONRPC.Transaction, :do_elixir_to_params, [%{"blockHash" => nil, "blockNumber" => nil, "from" => "0x0000000000000000000000000000000000000000", "gas" => 21000, "hash" => "0x9a4c9f5ce4ec71e2029a22db64fab34be663258a5e4116a1123f35734f1096e3", "input" => "0x", "nonce" => 26318, "r" => 0, "s" => 0, "to" => "0x56272f6932e6ae0116d270a2e919d20d3052f206", "transactionIndex" => nil, "type" => 3, "v" => 0, "value" => 0}], [file: 'lib/ethereum_jsonrpc/transaction.ex', line: 206]}, {EthereumJSONRPC.Transaction, :elixir_to_params, 1, [file: 'lib/ethereum_jsonrpc/transaction.ex', line: 202]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1658]}, {EthereumJSONRPC.PendingTransaction, :fetch_pending_transactions_geth, 1, [file: 'lib/ethereum_jsonrpc/pending_transaction.ex', line: 27]}, {Indexer.Fetcher.PendingTransaction, :task, 1, [file: 'lib/indexer/fetcher/pending_transaction.ex', line: 120]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}.  Rescheduling.
```

**Comment by askiiRobotics** [comment]
Hey! We've faced a similar problem recently. Apparently it was due to non-strict following a schema-agreement on RPC-side. 
So, in the error you'd provided: 
```elixir
%{"blockHash" => nil, 
    "blockNumber" => nil, 
     "from" => "0x0000000000000000000000000000000000000000", 
     "gas" => 21000, 
     "hash" => "0x9a4c9f5ce4ec71e2029a22db64fab34be663258a5e4116a1123f35734f1096e3", 
     "input" => "0x", 
     "nonce" => 26318, 
     "r" => 0, 
     "s" => 0, 
     "to" => "0x56272f6932e6ae0116d270a2e919d20d3052f206", 
     "transactionIndex" => nil, 
     "type" => 3, 
     "v" => 0, 
     "value" => 0})
```

And on a code side we have:
```elixir
  def do_elixir_to_params(
        %{
          "blockHash" => block_hash,
          "blockNumber" => block_number,
          "from" => from_address_hash,
          "gas" => gas,
          "gasPrice" => gas_price,
          "hash" => hash,
          "input" => input,
          "nonce" => nonce,
          "to" => to_address_hash,
          "transactionIndex" => index,
          "value" => value,
          "type" => type,
          "maxPriorityFeePerGas" => max_priority_fee_per_gas,
          "maxFeePerGas" => max_fee_per_gas
        } = transaction
      ) do
    result = %{
      block_hash: block_hash,
      block_number: block_number,
      from_address_hash: from_address_hash,
      gas: gas,
      gas_price: gas_price,
      hash: hash,
      index: index,
      input: input,
      nonce: nonce,
      to_address_hash: to_address_hash,
      value: value,
      transaction_index: index,
      type: type,
      max_priority_fee_per_gas: max_priority_fee_per_gas,
      max_fee_per_gas: max_fee_per_gas
    }

    put_if_present(transaction, result, [
      {"creates", :created_contract_address_hash},
      {"block_timestamp", :block_timestamp},
      {"r", :r},
      {"s", :s},
      {"v", :v}
    ])
  end
```

So if we are going to compare expectations and what was provided, we'll see that r, s, v sig components are presented, but they are optional. Other optional fields "creates" and "block_timestamp" aren't presented, but since they are optional, it is alright.
But what about mandatory fields?
"gasPrice" and "to" are not presented and that may be a problem. Also please pay attention to "maxPriorityFeePerGas" and "maxFeePerGas" since these fields are a part of pending transaction schema.

**Comment by vbaranov** [comment]
The error is unreproducible with the code in the master branch.
