### ISSUE TITLE
Http 500 - 1st argument: not a bitstring for contract method input

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#9503]
### Description

```
Request: GET /smart-contracts/0xb9657EDCf84BCA4DE60b0f849f397C093459D0f8?function_name=getRegisteredNodeIds&method_id=987a4500&type=regular&is_custom_abi=false&args_count=1&arg_0=2345&from=0x782534071b6c94374ec4eff2e084dadadbd58c94
** (exit) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a bitstring

        :erlang.byte_size([])
        (explorer 6.1.0) lib/explorer/smart_contract/reader.ex:851: Explorer.SmartContract.Reader.bytes_to_string/1
        (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (explorer 6.1.0) lib/explorer/smart_contract/reader.ex:731: Explorer.SmartContract.Reader.new_value/3
        (explorer 6.1.0) lib/explorer/smart_contract/reader.ex:700: anonymous fn/3 in Explorer.SmartContract.Reader.link_outputs_and_values/3
        (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (explorer 6.1.0) lib/explorer/smart_contract/reader.ex:699: Explorer.SmartContract.Reader.link_outputs_and_values/3
        (explorer 6.1.0) lib/explorer/smart_contract/reader.ex:395: Explorer.SmartContract.Reader.query_function_with_names/7
```

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Steps to reproduce

go to https://coston-explorer.flare.network/address/0xb9657EDCf84BCA4DE60b0f849f397C093459D0f8/read-contract#address-tabs

`9. getRegisteredNodeIds` input `2345`

For some inputs it works (e.g. 2343).

### Backend version

v6.1.0-beta

### Elixir & Erlang/OTP versions

v1.14.5 (erlang 25)

### Operating system

Linux

**Comment by sl1depengwyn** [comment]
Closed in favour of https://github.com/blockscout/frontend/issues/2001
