### ISSUE TITLE
Every transaction stuck in "pending" except the first one

### ISSUE THREAD

**Issue by wighawag** [blockscout/blockscout#9736]
### Description

I am running blockscout locally with docker compose (geth clique) against a geth dev node

It see each block / transaction going through but consider all of them pending forever, except the first transaction

I see some errors in the log like the following

```
 {"time":"2024-03-27T11:52:12.759Z","severity":"error","message":"Task #PID<0.5426.0> started from Indexer.Block.Realtime.Fetcher terminating\n** (MatchError) no match of right hand side value: <<216, 131, 1, 13, 4, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 50, 49, 46, 51, 133, 108, 105, 110, 117, 120>>\n    (indexer 6.3.0) lib/indexer/transform/blocks.ex:92: Indexer.Transform.Blocks.recover_pub_key/2\n    (indexer 6.3.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 6.3.0) lib/indexer/block/fetcher.ex:148: Indexer.Block.Fetcher.fetch_and_import_range/3\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 6.3.0) lib/indexer/block/realtime/fetcher.ex:338: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3\n    (indexer 6.3.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2\n    (indexer 6.3.0) lib/indexer/block/realtime/fetcher.ex:280: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4\nFunction: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3\n    Args: [708, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://host.docker.internal:8545/\", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: \"http://host.docker.internal:8545/\", debug_traceTransaction: \"http://host.docker.internal:8545/\", debug_traceBlockByNumber: \"http://host.docker.internal:8545/\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]","metadata":{"error":{"initial_call":null,"reason":"** (MatchError) no match of right hand side value: <<216, 131, 1, 13, 4, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 50, 49, 46, 51, 133, 108, 105, 110, 117, 120>>\n    (indexer 6.3.0) lib/indexer/transform/blocks.ex:92: Indexer.Transform.Blocks.recover_pub_key/2\n    (indexer 6.3.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (indexer 6.3.0) lib/indexer/block/fetcher.ex:148: Indexer.Block.Fetcher.fetch_and_import_range/3\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 6.3.0) lib/indexer/block/realtime/fetcher.ex:338: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3\n    (indexer 6.3.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2\n    (indexer 6.3.0) lib/indexer/block/realtime/fetcher.ex:280: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4\n"}}}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

Local (--dev)

### Steps to reproduce

run geth in dev mode

```
geth --dev --nousb --ws --ws.addr "0.0.0.0" --ws.origins "*" --http --http.vhosts "*" --http.addr "0.0.0.0" --http.corsdomain "*" --miner.gasprice $GETH_GASPRICE --dev.period $GETH_BLOCK_TIME --rpc.allow-unprotected-txs --datadir $HOME/.geth-dev --password $HOME/.geth-dev/password --http.api eth,web3,net,admin,db,debug,txpool
```

then: 
```
docker compose -f geth-clique-consensus.yml  up
```

navigate to the explorer

send eth across accoint

### Backend version

https://github.com/blockscout/blockscout/commit/ffa12234c4f1b9971aa5be1e78c5d6a9a6167ad1

### Frontend version

https://github.com/blockscout/blockscout/commit/ffa12234c4f1b9971aa5be1e78c5d6a9a6167ad1

### Elixir & Erlang/OTP versions

https://github.com/blockscout/blockscout/commit/ffa12234c4f1b9971aa5be1e78c5d6a9a6167ad1

### Operating system

Linux

**Comment by wighawag** [comment]
Looks like I was using the wrong docker-compose file (was using clique instead of normal, and I probably use geth.yml first for the first tx, hence why it got valided. closing
