### ISSUE TITLE
Rework `log_index` usage for zkEVM chain type

### ISSUE THREAD

**Issue by k1rill-fedoseev** [blockscout/blockscout#9827]
The Polygon zkEVM has an unconventional `log_index` when comparing with the rest of JSON RPC implementations.

This causes problems in Blockscout during indexing of logs and token transfers, as the code assumes that `log_index` is unique on a per-block basis.

Context: https://github.com/0xPolygonHermez/zkevm-node/issues/3446 , https://github.com/0xPolygonHermez/zkevm-node/pull/3476

Error example:
```
{"time":"2024-03-28T15:23:27.972Z","severity":"warn","message":"Consensus removed from partially imported block because of error: [10052122]","metadata":{"fetcher":"block_catchup","first_block_number":10052122,"last_block_number":10052122}}
{"time":"2024-03-28T15:23:27.973Z","severity":"error","message":"** (FunctionClauseError) no function clause matching in List.first/2\n    (elixir 1.14.5) List.first(nil, nil)\n    (explorer 6.3.0) lib/explorer/chain/import/runner/blocks.ex:668: anonymous fn/2 in Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.3.0) lib/explorer/chain/import/runner/blocks.ex:667: Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (explorer 6.3.0) lib/explorer/prometheus/instrumenter.ex:17: Explorer.Prometheus.Instrumenter.block_import_stage_runner/4\n    (ecto 3.11.2) lib/ecto/multi.ex:883: Ecto.Multi.apply_operation/5\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","first_block_number":10052122,"last_block_number":10052122}}
{"time":"2024-03-28T15:23:27.973Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":10052122,"last_block_number":10052122,"missing_block_count":1,"shrunk":false}}
{"time":"2024-03-28T15:23:27.973Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
```

**Comment by fedor-ivn** [comment]
I see the same errors for Filecoin mainnet.

```
{"time":"2024-09-26T13:06:38.185Z","severity":"error","message":"** (FunctionClauseError) no function clause matching in List.first/2\n    (elixir 1.16.3) List.first(nil, nil)\n    (explorer 6.8.1) lib/explorer/chain/import/runner/blocks.ex:672: anonymous fn/2 in Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.8.1) lib/explorer/chain/import/runner/blocks.ex:671: Explorer.Chain.Import.Runner.Blocks.process_forked_token_transfers/3\n    (stdlib 5.2.3) timer.erl:270: :timer.tc/2\n    (explorer 6.8.1) lib/explorer/prometheus/instrumenter.ex:60: Explorer.Prometheus.Instrumenter.block_import_stage_runner/4\n    (ecto 3.12.3) lib/ecto/multi.ex:897: Ecto.Multi.apply_operation/5\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n\n\nRetrying.","metadata":{"fetcher":"block_catchup","last_block_number":3854161,"first_block_number":3854161}}
```

**Comment by nikitosing** [comment]
Should be fixed with https://github.com/blockscout/blockscout/pull/10880
