### ISSUE TITLE
/api/v2/blocks/208759/transactions\n** (exit) an exception was raised:\n    ** (Jason.EncodeError) invalid byte

### ISSUE THREAD

**Issue by oxf71** [blockscout/blockscout#9837]
### Description

```
2024-04-07T17:36:51.235903006+08:00 stdout F {"time":"2024-04-07T17:36:51.233Z","severity":"error","message":"#PID<0.6267.1416> 
running BlockScoutWeb.Endpoint (connection #PID<0.21316.1415>, stream id 3) terminated\nServer: habitat-backend.bsquared.network:80 (http)\nRequest: GET /api/v2/blocks/208759/transactions\n** (exit) an exception was raised:\n    ** (Jason.EncodeError) invalid byte 0x81 in <<129, 23, 21, 130, 119, 101, 101, 137, 120, 48, 19, 96, 116, 0, 135, 88, 150, 32, 85, 70, 41, 85, 56, 16, 22, 100, 81, 2, 34, 98, 85, 117, 105, 64, 18, 64, 100, 145, 97, 22, 52, 150, 146, 120, 66, 117, 80, 32, 34, 34, ...>>\n        
(jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2\n
(phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n
(block_scout_web 6.4.0) lib/block_scout_web/controllers/api/v2/block_controller.ex:1: BlockScoutWeb.API.V2.BlockController.action/2\n
(block_scout_web 6.4.0) lib/block_scout_web/controllers/api/v2/block_controller.ex:1: BlockScoutWeb.API.V2.BlockController.phoenix_controller_pipeline/2\n
(phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n
(phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n
(phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n
(block_scout_web 6.4.0) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2","metadata":{"error":{"initial_call":null,"reason":"** (Jason.EncodeError) invalid byte 0x81 in <<129, 23, 21, 130, 119, 101, 101, 137, 120, 48, 19, 96, 116, 0, 135, 88, 150, 32, 85, 70, 41, 85, 56, 16, 22, 100, 81, 2, 34, 98, 85, 117, 105, 64, 18, 64, 100, 145, 97, 22, 52, 150, 146, 120, 66, 117, 80, 32, 34, 34, ...>>\n
(jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2\n
(phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n
(block_scout_web 6.4.0) lib/block_scout_web/controllers/api/v2/block_controller.ex:1: BlockScoutWeb.API.V2.BlockController.action/2\n
(block_scout_web 6.4.0) lib/block_scout_web/controllers/api/v2/block_controller.ex:1: BlockScoutWeb.API.V2.BlockController.phoenix_controller_pipeline/2\n
(phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n
(phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n
(phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n
(block_scout_web 6.4.0) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2\n"}}}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

zkevm

### Type of the chain

L2

### Link to the page

https://habitat-explorer.bsquared.network/block/208759?tab=txs

### Backend version

v6.4.0

### Frontend version

v1.27.0

### Elixir & Erlang/OTP versions

exlixir

### Operating system

linux

**Comment by GimluCom** [comment]
Please try to force blockscout to refetch the block
```sh
docker compose exec db psql -U blockscout -d blockscout -c 'UPDATE blocks SET consensus=false WHERE number=208759;'
```

**Comment by oxf71** [comment]
switched to optimism
