### ISSUE TITLE
Terminating Postgrex Geth - Clique PoA

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#9873]
### Description

```
{
    "time": "2024-04-12T15:35:22.525Z",
    "severity": "error",
    "message": "GenServer #PID<0.8323.0> terminating\n** (Postgrex.Error) ERROR 42703 (undefined_column) column t0.token_id does not exist\n\n    query: SELECT t0.\"amount\", t0.\"block_number\", t0.\"log_index\", t0.\"token_id\", t0.\"amounts\", t0.\"token_ids\", t0.\"from_address_hash\", t0.\"to_address_hash\", t0.\"token_contract_address_hash\", t0.\"transaction_hash\", t0.\"block_hash\", t0.\"inserted_at\", t0.\"updated_at\" FROM \"token_transfers\" AS t0 WHERE (t0.\"block_number\" >= $1) AND (t0.\"block_number\" <= $2)\n\n    hint: Perhaps you meant to reference the column \"t0.token_ids\".\n    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6\n    (ecto 3.11.0) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4\n    (ecto 3.11.0) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\n    (explorer 5.3.3) lib/explorer/token_transfer_token_id_migration/worker.ex:71: Explorer.TokenTransferTokenIdMigration.Worker.do_update/2\n    (explorer 5.3.3) lib/explorer/token_transfer_token_id_migration/worker.ex:38: Explorer.TokenTransferTokenIdMigration.Worker.handle_info/2\n    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4\n    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6\nLast message: :update\nState: %{batch_size: 500, bottom_block: 0, current_range: {0, 0}, step: 0}",
    "metadata": {
        "error": {
            "initial_call": null,
            "reason": "** (Postgrex.Error) ERROR 42703 (undefined_column) column t0.token_id does not exist\n\n    query: SELECT t0.\"amount\", t0.\"block_number\", t0.\"log_index\", t0.\"token_id\", t0.\"amounts\", t0.\"token_ids\", t0.\"from_address_hash\", t0.\"to_address_hash\", t0.\"token_contract_address_hash\", t0.\"transaction_hash\", t0.\"block_hash\", t0.\"inserted_at\", t0.\"updated_at\" FROM \"token_transfers\" AS t0 WHERE (t0.\"block_number\" >= $1) AND (t0.\"block_number\" <= $2)\n\n    hint: Perhaps you meant to reference the column \"t0.token_ids\".\n    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6\n    (ecto 3.11.0) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4\n    (ecto 3.11.0) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3\n    (explorer 5.3.3) lib/explorer/token_transfer_token_id_migration/worker.ex:71: Explorer.TokenTransferTokenIdMigration.Worker.do_update/2\n    (explorer 5.3.3) lib/explorer/token_transfer_token_id_migration/worker.ex:38: Explorer.TokenTransferTokenIdMigration.Worker.handle_info/2\n    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4\n    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6\n"
        }
    }
}
```

using geth clique poa, but deploy blockscout explorer get the error like this. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

none

### Operating system

Linux

**Comment by sl1depengwyn** [comment]
It seems that you run an old version of the application (from the logs I suggest it is 5.3.3) on the database that has migrations from a newer one version of the Blockscout
