### ISSUE TITLE
Filecoin address transactions 500

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#9878]
https://filecoin.blockscout.com/address/0x7B90337f65fAA2B2B8ed583ba1Ba6EB0C9D7eA44

```
{"time":"2024-04-15T06:01:42.497Z","severity":"error","message":"#PID<0.16329.427> running BlockScoutWeb.Endpoint (connection #PID<0.16433.427>, stream id 2) terminated\nServer: filecoin.blockscout.com:80 (http)\nRequest: GET /api/v2/addresses/0x7B90337f65fAA2B2B8ed583ba1Ba6EB0C9D7eA44/transactions\n** (exit) an exception was raised:\n    ** (FunctionClauseError) no function clause matching in Explorer.Chain.Wei.hex_format/1\n        (explorer 6.4.0) lib/explorer/chain/wei.ex:122: Explorer.Chain.Wei.hex_format(nil)\n        (explorer 6.4.0) lib/explorer/chain.ex:2891: Explorer.Chain.fetch_tx_revert_reason/1\n        (block_scout_web 6.4.0) lib/block_scout_web/views/transaction_view.ex:354: BlockScoutWeb.TransactionView.transaction_revert_reason/2\n        (block_scout_web 6.4.0) lib/block_scout_web/views/api/v2/transaction_view.ex:508: BlockScoutWeb.API.V2.TransactionView.revert_reason/2\n        (block_scout_web 6.4.0) lib/block_scout_web/views/api/v2/transaction_view.ex:403: BlockScoutWeb.API.V2.TransactionView.prepare_transaction/6\n        (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n        (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n        (block_scout_web 6.4.0) lib/block_scout_web/views/api/v2/transaction_view.ex:72: BlockScoutWeb.API.V2.TransactionView.render/2","metadata":{"error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in Explorer.Chain.Wei.hex_format/1\n    (explorer 6.4.0) lib/explorer/chain/wei.ex:122: Explorer.Chain.Wei.hex_format(nil)\n    (explorer 6.4.0) lib/explorer/chain.ex:2891: Explorer.Chain.fetch_tx_revert_reason/1\n    (block_scout_web 6.4.0) lib/block_scout_web/views/transaction_view.ex:354: BlockScoutWeb.TransactionView.transaction_revert_reason/2\n    (block_scout_web 6.4.0) lib/block_scout_web/views/api/v2/transaction_view.ex:508: BlockScoutWeb.API.V2.TransactionView.revert_reason/2\n    (block_scout_web 6.4.0) lib/block_scout_web/views/api/v2/transaction_view.ex:403: BlockScoutWeb.API.V2.TransactionView.prepare_transaction/6\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (block_scout_web 6.4.0) lib/block_scout_web/views/api/v2/transaction_view.ex:72: BlockScoutWeb.API.V2.TransactionView.render/2\n"}}}
```

**Comment by fedor-ivn** [comment]
Seems that https://github.com/blockscout/blockscout/pull/9647 fixes the same issue.
