### ISSUE TITLE
Support Optimism Fault Proofs in L2->L1 indexing modules

### ISSUE THREAD

**Issue by varasev** [blockscout/blockscout#9893]
To be read: https://oplabs.notion.site/Fault-Proof-Mainnet-Partner-Upgrade-Mission-Control-1ebc8767955044a9a3c31d11647ddd0d

**Comment by avenbreaks** [comment]
still progress sir? i got error on L2 Optimism based chain

```
2024-04-17T13:13:43.907 [error] GenServer Explorer.Counters.LastOutputRootSizeCounter terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "op_output_roots" does not exist

    query: SELECT o0."l2_block_number" FROM "op_output_roots" AS o0 ORDER BY o0."l2_output_index" DESC LIMIT 2
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (explorer 6.4.0) lib/explorer/counters/last_output_root_size_counter.ex:75: Explorer.Counters.LastOutputRootSizeCounter.consolidate/0
    (explorer 6.4.0) lib/explorer/counters/last_output_root_size_counter.ex:37: Explorer.Counters.LastOutputRootSizeCounter.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
Last message: {:continue, :ok}
State: %{consolidate?: true}
```

**Comment by varasev** [comment]
@avenbreaks Looks like you didn't define `CHAIN_TYPE=optimism` env variable when building
