### ISSUE TITLE
L2 Optimism Based

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#9903]
### Description

It looks like there's an error related to a missing table in database. The error message relation "op_output_roots" does not exist. i use v6.4.0-beta

```
INDEXER_OPTIMISM_L1_RPC=https://blissful-ultra-firefly.ethereum-sepolia.quiknode.pro/xxxxxxxxxxxxxxxxxxxx/
INDEXER_OPTIMISM_L1_BATCH_START_BLOCK='5171324'
INDEXER_OPTIMISM_L1_BATCH_INBOX=0xff00000000000000000000000000000000042069
INDEXER_OPTIMISM_L1_BATCH_SUBMITTER=0x3335b12ff0adf80cc0793561956e4d0b9d161508
INDEXER_OPTIMISM_L1_BATCH_BLOCKSCOUT_BLOBS_API_URL=https://eth-sepolia.blockscout.com/api/v2/blobs
INDEXER_OPTIMISM_L1_BATCH_BLOCKS_CHUNK_SIZE=4
# INDEXER_OPTIMISM_L2_BATCH_GENESIS_BLOCK_NUMBER='1'
INDEXER_OPTIMISM_L1_PORTAL_CONTRACT=0x5d59Ea9e3197B5Dd34EE8D279c55205D7D5f8671
INDEXER_OPTIMISM_L1_OUTPUT_ROOTS_START_BLOCK='5171324'
INDEXER_OPTIMISM_L1_OUTPUT_ORACLE_CONTRACT=0x03eF051Bf8BAc9646744aBf0612D8Cd139740aCa
INDEXER_OPTIMISM_L1_WITHDRAWALS_START_BLOCK='5171324'
INDEXER_OPTIMISM_L2_WITHDRAWALS_START_BLOCK='1'
INDEXER_OPTIMISM_L2_MESSAGE_PASSER_CONTRACT=0x4200000000000000000000000000000000000016
INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK='5171324'
INDEXER_OPTIMISM_L1_DEPOSITS_BATCH_SIZE=500
```

```
2024-04-17T09:55:00.592 [error] GenServer Explorer.Counters.LastOutputRootSizeCounter terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "op_output_roots" does not exist

    query: SELECT o0."l2_block_number" FROM "op_output_roots" AS o0 ORDER BY o0."l2_output_index" DESC LIMIT 2
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (explorer 6.4.0) lib/explorer/counters/last_output_root_size_counter.ex:75: Explorer.Counters.LastOutputRootSizeCounter.consolidate/0
    (explorer 6.4.0) lib/explorer/counters/last_output_root_size_counter.ex:37: Explorer.Counters.LastOutputRootSizeCounter.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
Last message: {:continue, :ok}
State: %{consolidate?: true}
2024-04-17T09:55:00.599 [error] GenServer Indexer.Block.Catchup.MissingRangesCollector terminating
** (RuntimeError) could not lookup Ecto repo Explorer.Repo because it was not started or it does not exist
    (ecto 3.11.2) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1
    (ecto 3.11.2) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2
    (explorer 6.4.0) lib/explorer/repo.ex:2: Explorer.Repo.all/2
    (explorer 6.4.0) lib/explorer/chain.ex:2295: Explorer.Chain.missing_block_number_ranges/1
    (indexer 6.4.0) lib/indexer/block/catchup/missing_ranges_collector.ex:157: Indexer.Block.Catchup.MissingRangesCollector.fetch_missing_ranges_batch/2
    (indexer 6.4.0) lib/indexer/block/catchup/missing_ranges_collector.ex:142: Indexer.Block.Catchup.MissingRangesCollector.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
Last message: :update_past
State: %{max_fetched_block_number: 2745451, min_fetched_block_number: 1945451}
2024-04-17T09:55:00.601 [error] GenServer Indexer.Block.Catchup.MissingRangesCollector terminating
** (RuntimeError) could not lookup Ecto repo Explorer.Repo because it was not started or it does not exist
    (ecto 3.11.2) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1
    (ecto 3.11.2) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2
    (explorer 6.4.0) lib/explorer/repo.ex:2: Explorer.Repo.one/2
    (indexer 6.4.0) lib/indexer/block/catchup/missing_ranges_collector.ex:116: Indexer.Block.Catchup.MissingRangesCollector.get_initial_min_max/0
    (indexer 6.4.0) lib/indexer/block/catchup/missing_ranges_collector.ex:47: Indexer.Block.Catchup.MissingRangesCollector.default_init/0
    (indexer 6.4.0) lib/indexer/block/catchup/missing_ranges_collector.ex:29: Indexer.Block.Catchup.MissingRangesCollector.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
Last message: {:continue, :ok}
State: %{max_fetched_block_number: nil, min_fetched_block_number: nil}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth-OP

### Type of the chain

L2

### Link to the page

https://onlyscan.info

### Backend version

v6.4.0-beta

### Frontend version

latest

### Elixir & Erlang/OTP versions

none

### Operating system

Linux

**Comment by avenbreaks** [comment]
solved, but after re-synchronizing, some transactions in hundreds of data contracts were not correct, many holders were missing.

**Comment by zlhwdsz** [comment]
@avenbreaks can you share the solution?
