### ISSUE TITLE
Arbitrum: Internal transactions not handled

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout#9951]
### Description

```
{:error,
 [
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 1,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 7,
       input: %Explorer.Chain.Data{
         bytes: <<237, 161, 18, 44, 58, 210, 23, 84, 91, 149, 129, 241, 132, 35,
           84, 157, 164, 34, 169, 51, 113, 75, 32, 102, 0, 145, 112, 58, 248,
           50, 172, 39, 194, 60, 12, 60>>
       },
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 110>>
       },
       trace_address: [6],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<58, 210, 23, 84, 91, 149, 129, 241, 132, 35, 84, 157, 164, 34,
           169, 51, 113, 75, 32, 102, 0, 145, 112, 58, 248, 50, 172, 39, 194,
           60, 12, 60>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<0>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 1,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 6,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<11, 240, 80, 134, 78, 24, 198, 192, 85, 8, 104, 223, 202, 105,
           25, 161, 15, 96, 53, 128>>
       },
       trace_address: [5],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<58, 210, 23, 84, 91, 149, 129, 241, 132, 35, 84, 157, 164, 34,
           169, 51, 113, 75, 32, 102, 0, 145, 112, 58, 248, 50, 172, 39, 194,
           60, 12, 60>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<0>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 1,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 5,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<157, 221, 222, 213, 130, 219, 159, 84, 43, 247, 150, 18, 251,
           8, 30, 147, 97, 187, 33, 49>>
       },
       trace_address: [4],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<58, 210, 23, 84, 91, 149, 129, 241, 132, 35, 84, 157, 164, 34,
           169, 51, 113, 75, 32, 102, 0, 145, 112, 58, 248, 50, 172, 39, 194,
           60, 12, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<2100000000000>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 1,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 4,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<59, 35, 159, 195, 185, 36, 199, 34, 176, 116, 7, 244, 73, 203,
           33, 238, 186, 41, 56, 38>>
       },
       trace_address: [3],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<58, 210, 23, 84, 91, 149, 129, 241, 132, 35, 84, 157, 164, 34,
           169, 51, 113, 75, 32, 102, 0, 145, 112, 58, 248, 50, 172, 39, 194,
           60, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<10000000000000000>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 1,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 3,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<11, 240, 80, 134, 78, 24, 198, 192, 85, 8, 104, 223, 202, 105,
           25, 161, 15, 96, 53, 128>>
       },
       trace_address: [2],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<58, 210, 23, 84, 91, 149, 129, 241, 132, 35, 84, 157, 164, 34,
           169, 51, 113, 75, 32, 102, 0, 145, 112, 58, 248, 50, 172, 39, 194,
           ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<0>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 1,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 2,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<157, 221, 222, 213, 130, 219, 159, 84, 43, 247, 150, 18, 251,
           8, 30, 147, 97, 187, 33, 49>>
       },
       trace_address: [1],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<58, 210, 23, 84, 91, 149, 129, 241, 132, 35, 84, 157, 164, 34,
           169, 51, 113, 75, 32, 102, 0, 145, 112, 58, 248, 50, 172, 39, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<2596020000000>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 1,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 1,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       trace_address: [0],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<58, 210, 23, 84, 91, 149, 129, 241, 132, 35, 84, 157, 164, 34,
           169, 51, 113, 75, 32, 102, 0, 145, 112, 58, 248, 50, 172, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<10004696020000000>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 3,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 7,
       input: %Explorer.Chain.Data{
         bytes: <<237, 161, 18, 44, 127, 247, 177, 42, 133, 116, 13, 113, 158,
           36, 220, 194, 149, 215, 169, 40, 10, 46, 155, 89, 11, 216, 207, 193,
           220, 56, 162, ...>>
       },
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 110>>
       },
       trace_address: [6],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<127, 247, 177, 42, 133, 116, 13, 113, 158, 36, 220, 194, 149,
           215, 169, 40, 10, 46, 155, 89, 11, 216, 207, 193, 220, 56, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<0>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 3,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 6,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<11, 240, 80, 134, 78, 24, 198, 192, 85, 8, 104, 223, 202, 105,
           25, 161, 15, 96, 53, 128>>
       },
       trace_address: [5],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<127, 247, 177, 42, 133, 116, 13, 113, 158, 36, 220, 194, 149,
           215, 169, 40, 10, 46, 155, 89, 11, 216, 207, 193, 220, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<0>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 3,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 5,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<157, 221, 222, 213, 130, 219, 159, 84, 43, 247, 150, 18, 251,
           8, 30, 147, 97, 187, 33, 49>>
       },
       trace_address: [4],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<127, 247, 177, 42, 133, 116, 13, 113, 158, 36, 220, 194, 149,
           215, 169, 40, 10, 46, 155, 89, 11, 216, 207, 193, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<2100000000000>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 3,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 4,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<106, 30, 30, 67, 186, 105, 4, 0, 196, 140, 54, 28, 18, 67,
           136, 138, 192, 228, 140, 98>>
       },
       trace_address: [3],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<127, 247, 177, 42, 133, 116, 13, 113, 158, 36, 220, 194, 149,
           215, 169, 40, 10, 46, 155, 89, 11, 216, 207, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<24700000000000000>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 3,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 3,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<11, 240, 80, 134, 78, 24, 198, 192, 85, 8, 104, 223, 202, 105,
           25, 161, 15, 96, 53, 128>>
       },
       trace_address: [2],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<127, 247, 177, 42, 133, 116, 13, 113, 158, 36, 220, 194, 149,
           215, 169, 40, 10, 46, 155, 89, 11, 216, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<0>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 3,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 2,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<157, 221, 222, 213, 130, 219, 159, 84, 43, 247, 150, 18, 251,
           8, 30, 147, 97, 187, 33, 49>>
       },
       trace_address: [1],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<127, 247, 177, 42, 133, 116, 13, 113, 158, 36, 220, 194, 149,
           215, 169, 40, 10, 46, 155, 89, 11, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<2596020000000>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >,
   #Ecto.Changeset<
     action: nil,
     changes: %{
       block_number: 3,
       from_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>
       },
       gas: Decimal.new("0"),
       gas_used: Decimal.new("0"),
       index: 1,
       input: %Explorer.Chain.Data{bytes: ""},
       output: %Explorer.Chain.Data{bytes: ""},
       to_address_hash: %Explorer.Chain.Hash{
         byte_count: 20,
         bytes: <<82, 19, 167, 69, 54, 40, 172, 150, 145, 72, 143, 146, 25, 103,
           188, 130, 194, 83, 172, 154>>
       },
       trace_address: [0],
       transaction_hash: %Explorer.Chain.Hash{
         byte_count: 32,
         bytes: <<127, 247, 177, 42, 133, 116, 13, 113, 158, 36, 220, 194, 149,
           215, 169, 40, 10, 46, 155, 89, ...>>
       },
       transaction_index: 1,
       type: :call,
       value: #Explorer.Chain.Wei<24704696020000000>
     },
     errors: [
       call_type: {"is invalid",
        [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}
     ],
     data: #Explorer.Chain.InternalTransaction<>,
     valid?: false
   >
 ]}
```

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Arbitrum Node (geth)

### Type of the chain

L3

### Steps to reproduce

Arbitrum Orbit with Anytrust deployed on Arb Sepolia

### Backend version

4b272cf61dc14da76416be63f1f1df044b03a4b9

### Frontend version

e3b8c8c9d9f5f1f7e3ec02c60f9ba37a1b2366fb

### Elixir & Erlang/OTP versions

1.14.5 Erlang/OTP 24 [erts-12.2.1]

### Operating system

Linux

### Additional information

Function clause

**Comment by InoMurko** [comment]
```
 errors: [call_type: {\"is invalid\", [type: Explorer.Chain.InternalTransaction.CallType, validation: :cast]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>]}\n    (indexer 6.5.0) lib/indexer/fetcher/internal_transaction.ex:284: Indexer.Fetcher.InternalTransaction.import_internal_transaction/2\n    (indexer 6.5.0) lib/indexer/fetcher/internal_transaction.ex:249: Indexer.Fetcher.InternalTransaction.safe_import_internal_transaction/2\n    (indexer 6.5.0) lib/indexer/fetcher/internal_transaction.ex:116: Indexer.Fetcher.InternalTransaction.run/2\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nFunction: &Indexer.BufferedTask.log_run/1\n    Args: [%{batch: [4, 2, 1, 0], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://rollup-proxy-service:8545\", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url:  (truncated)","metadata":{"count":3,"error":{"initial_call":null,"reason":"** (CaseClauseError) no case clause matching:
```

**Comment by vbaranov** [comment]
@InoMurko for Arbitrum stack you have to set compile-time/runtime environment variable `CHAIN_TYPE: "arbitrum"` or in case of Docker setup please choose `blockscout/blockscout-arbitrum` image and set `CHAIN_TYPE=arbitrum` in runtime.
